### ISSUE TITLE
graph is too sparse and far away when using forceatlas2 with few nodes

### ISSUE THREAD

**Issue by dudilugasi** [jacomyal/sigma.js#1008]
when i am using forceatlas2 with few nodes the graph is too sparse and zoomed away. is there a way to set boundaries for the graph so it will be cetered in the screen and zoomed in? 
![untitled](https://user-images.githubusercontent.com/10431969/51826685-52504b00-22f0-11e9-841b-448cc7dc6adf.jpg)
this is a full screen view of my graph

**Comment by traut** [comment]
I'm having the same issue. One possible solution (which requires coding) is to set a threshold (say, 10 nodes) and if graph is smaller than that:
- render nodes with random (x, y) coordinates in a small area in the center of the screen
- use no-overlap layout

**Comment by Yomguithereal** [comment]
Alternatively you can use a margin (in sigma's settings).
