### ISSUE TITLE
Finding the Lenght of edges

### ISSUE THREAD

**Issue by Axeln78** [jacomyal/sigma.js#1022]
Hi! Thank you very much for all the great work! 

I'd like to filter the edges by length (hairy ball problem), though after importing from a gexf file there is one size attribute which is always equal to 1 and one "label" attribute which looks like it could be the length of an edge at some point in time. 

Is there a propriety for the length of the edges? Or should it be calculated in an internal method?

Best!

**Comment by Yomguithereal** [comment]
There isn't an internal property describing edge's length. However, a simple euclidean distance between the position of the source & target node should suffice.

**Comment by Axeln78** [comment]
Thank you for your answer, here is a Code snipped that does the trick for me:

`sigma.classes.graph.addMethod("storeEdgeLenght", function() {
  for (let i = 0; i < this.edgesArray.length; i++) {
    let e = this.edgesArray[i];
    let x1 = this.nodes(e.source).x;
    let y1 = this.nodes(e.source).y;
    let x2 = this.nodes(e.target).x;
    let y2 = this.nodes(e.target).y;
    e.length = Math.hypot(x2 - x1, y2 - y1);
  }
});`
