### ISSUE TITLE
Documentation for version 2 alpha20

### ISSUE THREAD

**Issue by i18rajats** [jacomyal/sigma.js#1028]
please provide a documentation for version v2 as i am unable to run examples also.

**Comment by Yomguithereal** [comment]
Unfortunately I don't have much time nor the means to do so right now. Could you explain what's preventing you from running the examples though? And what's your version of node?

**Comment by i18rajats** [comment]
actually, I am unable to run any of the examples as I don't know the method as in v1 you had given the HTML files and I could run them directly but there are js files now and template folder contains ejs files and I don't know how to run them, and I am using node v10.15.3.

**Comment by Yomguithereal** [comment]
Install the deps using ´npm run install’ the. ´npm run examples’ to build/spawn a dev server hosting the examples on localhost:8000

**Comment by i18rajats** [comment]
Thank you so much for the support as now I can work further.
