### ISSUE TITLE
importing data

### ISSUE THREAD

**Issue by rajatsadh24** [jacomyal/sigma.js#1029]
from where are you importing the data for examples as there are no source files for the data.

**Comment by Yomguithereal** [comment]
It depends on the example. Sometimes the data is amgorithmically generated and sometimes I load it from a gexf or json file for instance. I use webpack loaders to « import » the data file as a string but you could also use fetch or xhr to retrieve the file. I use loaders as a convenience here but I would not vouch for it in a prod context.

**Comment by i18rajats** [comment]
Thanks a lot for this quick reply, I will try this and will revert back if there is any issue.

**Comment by i18rajats** [comment]
I am going to use MongoDB to import data and i want to make an app which renders graph from the data given in MongoDB and the graph should refresh whenever I update the database, what should be the process.

**Comment by i18rajats** [comment]
please! reply as I need assistance, I am unable  to process anything

**Comment by i18rajats** [comment]
I was working with sigma.js v1 and i made application which used MongoDB database data to render the graphs and i want to migrate my application  from v1 to v2 in order to render large number of edges.

**Comment by i18rajats** [comment]
please, help me regarding the above issue.

**Comment by Yomguithereal** [comment]
@i18rajats what you need to achieve is unclear to me but I guess that the only thing you need to know is that whenever you update the rendered graph (by adding/removing nodes/edges or editing any kind of attributes), you will trigger a re-render next frame.

**Comment by i18rajats** [comment]
@Yomguithereal I need to render data stored in MongoDB database so that the renderer gets the data from the database and renders it when I run a js file.

**Comment by Yomguithereal** [comment]
Then what you did before using sigma v1 should still work the same, no?

**Comment by i18rajats** [comment]
I am unable to render a JSON file that's a problem.

**Comment by Yomguithereal** [comment]
You need to load the JSON file using ajax (or fetch) and iterate over it to create your graph.

**Comment by i18rajats** [comment]
Please can you give me an example

**Comment by Yomguithereal** [comment]
```js
fetch('data.json')
  .then(response => response.json())
  .then(data => {
     let graph = new Graph();

     data.nodes.forEach(({key, attributes}) => graph.addNode(key, attributes));
 
     // Same for edges or else
  });
```

**Comment by i18rajats** [comment]
in Sigma.js v2 we are completely rendering the data on the client side itself so in order to fetch the data these codes must be put in server side right?

**Comment by Yomguithereal** [comment]
The code I wrote above should be run client side. But you could chose to better format your json data server side to make parsing code that instantiate the graphology graph simpler in the client.

**Comment by i18rajats** [comment]
but the specific format of JSON data is not given anywhere.

**Comment by Yomguithereal** [comment]
That's because you can define it however you like. If you want to stick to graphology's serialization format it's described here though: https://graphology.github.io/serialization.html#format

**Comment by i18rajats** [comment]
actually, there is no example given so that I can easily render my JSON data and I am facing trouble in rendering my JSON data as you are using faker for random data generation.

**Comment by i18rajats** [comment]
it will be very helpful if I could see my data and tell me how to render that.
