### ISSUE TITLE
Opacity 

### ISSUE THREAD

**Issue by Faydaen** [jacomyal/sigma.js#103]
Is it possible to change opacity of the edges and nodes?
And how to do it?

**Comment by bornakke** [comment]
Is it posible that this error has returned. When I manually set the alpha edge value (e.g. "rgb(190,190,190,0.5)") the graph simply turn all edges completly black. This only happens in canvas mode.

Example code below:

$(document).ready(function() {
	window.s = new sigma({ 
		renderers: [
   	 		{
      		container: 'sigma-container',
      		type: 'canvas' // force it to canvas... if it were not already?
      		}
  		],
  		settings: {}
  	});
  	
	//Parse data
    sigma.parsers.gexf( 'data/november_med_partier.gexf', 
    function(graph) { 
    	  s.graph.read(graph);
          s.refresh();
      	
        var i = 0;
    	s.graph.edges().forEach(function(e) {
            	e.color = "rgb(190,190,190,0.5)";
        });
       s.refresh(); 
      
    });
});   

![Uploading localhost_anNA_basic_sigma_html.png…]()

**Comment by Yomguithereal** [comment]
Hello @bornakke, you wrote `rgb` in your example while you should write `rgba`. Could you tell me whether this fixes the problem?

**Comment by bornakke** [comment]
Arch - that is the reason why you should never program late in the evening :)
