### ISSUE TITLE
Not able to import sigma in vue.js project

### ISSUE THREAD

**Issue by havardl** [jacomyal/sigma.js#1042]
Hi,

I've installed the 1.2.1 version of Sigma.js with npm and I'm currently trying to import and use it in a vue.js component, but I get the following error:

`"TypeError: sigma__WEBPACK_IMPORTED_MODULE_0___default.a is not a constructor"`

I import it in the following way:
`import sigma from 'sigma';`
`this.s = new sigma({})`

Any ideas, or other ways of importing Sigma.js in a vue.js component?

**Comment by Yomguithereal** [comment]
That's because this library is quite old and used to import itself the old way. Try the following:

```js
import 'sigma';
//...
this.s = new sigma({});
```

And if you feel adventurous, check out the undocumented v2 which uses modern require schemes (check out the examples folder in the v2 branch).

**Comment by havardl** [comment]
With that import statement, I get the following error:
`[Vue warn]: Error in mounted hook: "ReferenceError: sigma is not defined"`

Do I need to register it somewhere else beyond the component?

**Comment by Yomguithereal** [comment]
I don't know Vue very well. Normally, importing sigma is meant to assign it to window. Can you check if `window.sigma` exists after you import it? If so, you'll need to find a way to silence that warning (I surmise Vue has a way to be told if some variable exists in the global scope).

**Comment by havardl** [comment]
After checking `windows.sigma` (which was undefined), this was needed to make it work:
```javascript
const sigma = require('sigma'); (window).sigma = sigma; 
```
Thanks for the pointers! Looking forward to use v2 in the near future :)

**Comment by ing200086** [comment]
Does anyone have a simple vue project on github with this working? I have been trying in vain to get this working for a starting vue-cli project. I would very much appreciate a working example to compare.

**Comment by SOVLOOKUP** [comment]
I made a minimum example with sigma and vue3, maybe this can help you.

https://github.com/SOVLOOKUP/sigma-vue3

> Does anyone have a simple vue project on github with this working? I have been trying in vain to get this working for a starting vue-cli project. I would very much appreciate a working example to compare.
