### ISSUE TITLE
goTo api not changing anything on screen

### ISSUE THREAD

**Issue by Kayjim** [jacomyal/sigma.js#1059]
I am trying to perform a simple search for a node and then zoom in on said node to display information about that node. After setting break points and checking all the data, the script runs without errors, and I can see that the camera x, y, and ratio settings are updated. However, on screen there is no zoom affect or repositioning happening...

The flow goes: Search for node by ID, find matching ID, return x, and y coordinates, and then pass these coordinates into the camera API goTo(x, y, ratio) function.

`if(data.nodes[i] == searchQuery){ 
var node = data.nodes[i];
s.cameras.cam1.goTo({x: node.x, y: node.y, ratio: s.cameras.cam1.ratio / s.cameras.cam1.settings('zoomingratio')});
}
`

What am I missing?

**Comment by maxcorbeau** [comment]
Maybe `s.cameras.cam1.ratio / s.cameras.cam1.settings('zoomingratio')});` evaluates to `1` and thus the zoom doesn't change? Try putting a fixed value for debugging such as `.5`

**Comment by Kayjim** [comment]
I was able to fix this by changing some of the context.

**Comment by maxcorbeau** [comment]
@Kayjim : sharing a code snippet back might help others who are facing similar issues
