### ISSUE TITLE
The node size is too big when compare to edge length

### ISSUE THREAD

**Issue by heziiop** [jacomyal/sigma.js#1074]
I hava a graph with 453 nodes and 2025 edges, and I use a plugin layout [sigma.layout.paragraphl.js](https://github.com/nblintao/ParaGraphL), all the node's size are the same, when I set each node's size to 1(or any other positive number), the node seems too big when compare to the length of edges (so the display graph is occupied by many nodes, and I'm nearly unable to see the edges),
![image](https://user-images.githubusercontent.com/25722077/76677766-1b7ce780-660d-11ea-9ae4-00f9bf018618.png)

 but when I set the node size to 0, it looks much better though the nodes looks a little small.
![image](https://user-images.githubusercontent.com/25722077/76677746-e5d7fe80-660c-11ea-8a76-efe5c72ce3fb.png)

So my question is: is there a way to display the nodes in a proper size?

**Comment by Yomguithereal** [comment]
Hello @heziiop, you should try to tweak the `autoRescale` settings related to node size. Check out the docs [here](https://github.com/jacomyal/sigma.js/wiki/Settings#rescale-settings).

**Comment by heziiop** [comment]
Hi @Yomguithereal, I set the maxNodeSize and it works, thanks.  I found I have set the maxNodeSize in the wrong place, so it didn't work, it should be set in the sigma's settings but I set it in renderer's settings.
