### ISSUE TITLE
Camera usage ?

### ISSUE THREAD

**Issue by jb2b38** [jacomyal/sigma.js#1077]
I created a graph with nodes having fixed positions (ie : {id: 'node1', label: 'Node 1', x: 12, y: 34}).
My nodes and edges are declared in two separate arrays.

```
const network = new Sigma()

network.addRenderer({
    container: document.getElementById('container'),
    type: 'webgl',
})

network.settings({
    minArrowSize: 100,
    labelThreshold: 1,
    zoomMin: 0.1,
    zoomMax: 10,
    defaultNodeColor: '#00f',
    sideMargin: 3,
})

nodes.forEach(node => {
    node.size = 1
    network.graph.addNode(node)
})

edges.forEach(edge => {
     network.graph.addEdge(edge)
})

network.refresh()
```

Now, the network.refresh call centers my graph nicely in the container. But I want to trigger actions that would focus on specific nodes, and I struggle to understand how I'm supposed to do that.

I read the camera API documentation, and noticed the goTo, graphPosition and cameraPosition methods, but was unable to find my way with these.

What I tried: 
- logged network.cameras[0], and confirmed that its x and y coordinates (displaying 0, 0) were not related in any way to the coordinates of my nodes, which range from 0 to 30 (I have a node placed at coordinates 0,0, which is placed on the central vertical axis, somewhere between the center of the container and its top, so 0,0 from the node does not match 0,0 from the camera, be it the center of the camera or one of its corners). My conclusion was that I needed to use the graphPosition and cameraPosition methods to convert the coordinates between the node's and camera's.
- network.cameras[0].goTo({x: node.x, y:node.y}), I noticed that the camera moved very slightly, but did not center on my node
- const newCoords = network.cameras[0].cameraCoordinates(node.x, node.y), followed by network.cameras[0].goTo({x:newCoords.x, y: newCoords.y, ratio:1}). I noticed that the newCoords object had the exact same coordinates as the node's, and so the camera moved slightly as well, but not centered on my node (camera was placed at x:0,y:0, the node was placed at x:3,y:9, then camera position displayed x:3,y:9).
- same as previous, but with a ratio of 0.5. I could only confirm that the zoom level increased, but the camera was still centered on the same spot.
- disabled autoRescale (and augmented the distance between my nodes). The results looks way better when I network.cameras[0].goTo({x: node.x, y:node.y}) right after the first render. But if I drag the view and trigger it once again, the camera is applied the same vectorial movement from my current view. Which means the camera was probably not following the view being dragged.

So, my question is about clarifying the way I am supposed to interact with the camera API.
Where can I find examples for this usage, guidance, or any advice ?
I searched the issue tracker for examples of graphPosition and cameraPosition usage, but could not find relevant information.
How is the camera linked to the container? How can I make it follow the mouse dragging my network? And can I center it on multiple nodes at once ?

Precision : now that autoRescale is disabled, my full network is not centered beautifully on first render, and I don't know how to achieve this.

**Comment by LiamKenneth** [comment]
Hi @jb2b38 did you ever solve this? I have the same issue and also searched through other issues with no luck and facing the same problems you have described here.

**Comment by Christian-Nja** [comment]
Same here

**Comment by sim51** [comment]
Hi,

This is a working example : https://plnkr.co/plunk/tmGBNZSQ88LpGeoF
If you click on a node, the camera go to the node's position.

What you missed is that sigma create its own graph structure (see `sigma.graph`). 
So in this example, I search a node into the sigma graph structure bu the node's id : 

```
s.graph.nodes().find(function (node) {
   return node.id === nodeId;
});
```

The second important point is that Sigmajs can have many cameras, and the coordinates are tracked under the attributes `read_${CAM_PREFIX}:x` (same for `y`, `size`, `color`) .

So to retrieve the position of a node for a specifc camera you need to do : 

```
var sigmaNode = s.graph.nodes().find(function (node) {
  return node.id === nodeId;
});
s.cameras[0].goTo({
  x: sigmaNode["read_" + s.cameras[0].prefix + 'x'],
  y: sigmaNode["read_" + s.cameras[0].prefix + 'y'],
});
```

NOTE: The example is a stupid  because in the event, we already have the corresponding sigma node in  `e.data.node`.It's just to show you how to navigate into the sigma graph structure

**Comment by sim51** [comment]
Let me know if this answer respond to your need, so I can close the issue.
