### ISSUE TITLE
Typescript and index import issue

### ISSUE THREAD

**Issue by sim51** [jacomyal/sigma.js#1090]
With the current TS configuration, we have to define the path to a file, even if its name is `index`.
The wanted behaviour is to allow to not have the `index`.

Example, to be able to do 
```
import WebGLRenderer from "./renderers/webgl";
```

instead of this

```
import WebGLRenderer from "./renderers/webgl/index";
```

See discussions in  #1089 & #1085

**Comment by Yomguithereal** [comment]
Note we can also create a `./renderers/webgl.ts` file rather than relying on the index and keep the `webgl` subfolder and the result would be the same, if this is simpler.

**Comment by sim51** [comment]
It works now with our latest typescript improvement, see https://github.com/jacomyal/sigma.js/blob/v2/src/endpoint.ts#L11
