### ISSUE TITLE
sigma js - display nodes depending on node.size

### ISSUE THREAD

**Issue by benl96** [jacomyal/sigma.js#1091]
i'm trying to display the data of my graph based on the node.size.

I have a slider that has a range from 1 to 500 and I want to only show the nodes based on their size

    .html
     <input type="range" min="1" max="500" step="1.0" id="nodeSizeRange" />

    .js
     var arr = []
     $('#nodeSizeRange').change(function () {
      s.graph.nodes().forEach(function(n){
      if (n.size < slider.value) {
        s.graph.dropNode(n.id);
        arr.push(n)
      }
        s.refresh();
      })
    })

The code above is working right now, however it's only working in one direction, once a node is dropped it's obviously gone and I simply just can't display the full graph anymore

I want to be able to cover both ways, that's why I created that array. I keep the dropped Nodes in there so that I can add them later.

The dropNode function also deletes all edges and that is kind of my problem right now, I am able to readd the nodes eg `s.graph.addNode(n);` but the referenced edges are missing.

What would be the best way to solve this in the most efficient way?

Best regards in advance!

**Comment by Yomguithereal** [comment]
Hello @benl96. Know that you can set the `hidden` key on your nodes to `true` to hide them if you need to. This should make this use case simpler as you only need to toggle the `hidden` key when iterating on your nodes, based upon their sizes. Also you should probably move the `refresh` call outside of the `forEach` to avoid redrawing the graph for each node as I don't remember if the function is debounced or not.

**Comment by benl96** [comment]
Thanks @Yomguithereal - that did the thing for me!
I already moved the `refresh` call outside of the loop.
Didn't find anything about the `hidden` key in the wiki though...

**Comment by Yomguithereal** [comment]
> Didn't find anything about the hidden key in the wiki though...

Yes the doc is lacking at best :). Don't hesitate to edit relevant parts of the wiki where you feel this could be of use to others in the future.
