### ISSUE TITLE
Hosting pages which load json or gexf files on github pages

### ISSUE THREAD

**Issue by logicatcore** [jacomyal/sigma.js#1095]
I am very new to javascript and hosting websites, bear with me if my questions are very vague and basic in nature.

I did try and get sigma partially working on my github pages repository which seem to work for examples which do not deal with parsing json and gexf data files. 

So, my question is, is it possible to do get the __load-external-json.html__ working on github pages?

**Comment by Yomguithereal** [comment]
I don’t see why not. I’d wager it is a relative path issue you are having.

**Comment by logicatcore** [comment]
I thought so too and have double checked everything.

Could you have a look at it? Maybe you can notice something

https://logicatcore.github.io/

https://github.com/logicatcore/logicatcore.github.io/blob/sigma-js-testing/_posts/2020-08-14-load-external-json_copy.html

**Comment by logicatcore** [comment]
I found a workaround for this by creating a local variable with the JSON contents assigned directly. Thanks for the help!
