### ISSUE TITLE
Node border

### ISSUE THREAD

**Issue by AlexNoodl** [jacomyal/sigma.js#1099]
Hi. I`m junior frontend developmer from Russia. In my work I use your cool library. I need to add border to all node on graph, but don`t now how to do this. In another issue i found answers about renderers methods, but don`t see examples how to do. http://yomguithereal.github.io/articles/node-border-renderer/ this link to tutorial doesn`t work anymore and it`s not good(((

Can you help me with this question???

**Comment by Yomguithereal** [comment]
Hello @AlexNoodl. A degraded version of the article can still be found [here](https://github.com/Yomguithereal/yomguithereal.github.io/blob/f8f0696d3170c1c57adf47dfb4ea1de806e1c19a/_posts/2014-11-20-node-border-renderer.md). And the js code of the custom renderer can be found [here](https://github.com/Yomguithereal/yomguithereal.github.io/blob/f8f0696d3170c1c57adf47dfb4ea1de806e1c19a/assets/js/articles/node_renderer/index.js).

**Comment by AlexNoodl** [comment]
@Yomguithereal Awesome! Thank you!
