### ISSUE TITLE
Sigma.js@v"2.0.0-alpha40" steps to get started

### ISSUE THREAD

**Issue by ccolonna** [jacomyal/sigma.js#1101]
Hi, i'd like to use `sigma.js` in a project. Which are current steps to follows to go up with this. 
Currently i installed it with
`npm install sigma`

I'm following this [examples](https://github.com/jacomyal/sigma.js/tree/v2/examples) as a base to start. Are they ok to create working code?

Am i supposed to install all the packages used by the examples? For example `graphology`

As this are only dependencies i got installing sigma:

```
     "sigma": {
      "version": "2.0.0-alpha40",
      "resolved": "https://registry.npmjs.org/sigma/-/sigma-2.0.0-alpha40.tgz",
      "integrity": "sha512-E64G8UE/jNzzdUBJln9pjKiY7ZS2eRiRqcjwPgSIGXqDK+I7r9oHaNcYkTgttH2Re5e2b4FvJvoAJ3fTEASD0w==",
      "requires": {
        "@yomguithereal/helpers": "^1.0.0",
        "events": "^3.0.0",
        "graphology-metrics": "1.13.0",
        "graphology-utils": "^1.4.0"
      }
    }
```

**Comment by Yomguithereal** [comment]
Hello @Christian-Nja 

Yes those examples are a good starting point. And yes you will need to install `graphology` as sigma v2 now uses it. You may also need to install some other graphology [libraries](https://graphology.github.io/standard-library.html) depending on what you are trying to achieve (loading a gexf file for instance).

**Comment by Christian-Nja** [comment]
Great, thank you @Yomguithereal  for fast reply!

**Comment by jasondamour** [comment]
@Yomguithereal Sorry for the dumb question. But how do I import `WebGLRenderer`, using npm/webpack? 

My `src/index.js` looks like this: 
```
import Graph from "graphology";
import gexf from "graphology-gexf/browser";
// import WebGLRenderer from "src/renderers/webgl/index";
// import Sigma from 'sigma';

const graph = new Graph();

// const container = document.getElementById("container");
// const renderer = new WebGLRenderer(graph, container);
// window.renderer = renderer;
// window.camera = renderer.getCamera();
```

I have tried referencing the `../node_modules/sigma/src/renderers/webgl/index.ts` directly from node_modules/, but I get an error due to the file being typescript. I think I should be using a webpacked version, but I don't know how to do so. I think I'm misunderstanding something obvious :)

**Comment by Yomguithereal** [comment]
You should import the renderer likewise:

```js
import {WebGLRenderer} from 'sigma';
```

**Comment by sim51** [comment]
This is an example on codesandbox that should helps you : https://codesandbox.io/s/sigmajs-issue-xx-00nll
