### ISSUE TITLE
v2 label color hard-coded?

### ISSUE THREAD

**Issue by jakekara** [jacomyal/sigma.js#1102]
I wasn't able to figure out how to change label text color in v2 using the WebGLRenderer. Peeking at the code, it appeared to be hard-coded. Is that correct?

I wrote a little patch to make it configurable (https://github.com/jakekara/sigma.js/commit/c768bdee2c85cf2974434ef9cf4ce3363a6348bc). However, I wasn't totally sure what the best approach was to make this configurable and keep it in line with the current code base. This worked for my immediate need.

**Comment by connor4312** [comment]
I ran into this as well. Would love to get it fixed -- can you put your changes in a PR to make it easy for maintainers?
