### ISSUE TITLE
Mouse captor uses setImmediate which does not exist in FF

### ISSUE THREAD

**Issue by Yomguithereal** [jacomyal/sigma.js#1103]
This explains the jagged camera movements.

**Comment by havardl** [comment]
@Yomguithereal - will this fix be released anytime soon?

**Comment by Yomguithereal** [comment]
@havardl this fix is related to sigma v2 so I am not sure it will fix what you think it will fix?

**Comment by havardl** [comment]
Ah, sorry. I'm currently using version 2.0.0-alpha40 in a test project, where I'm getting this error in Firefox and Chrome. It's not breaking anything, but just wanted to check if there would be a new release.

**Comment by Yomguithereal** [comment]
I see. Let me check if I can draft a quick alpha41 to help you then.

**Comment by Yomguithereal** [comment]
Hm... could be done but it might change some things on your end since we are in the process of refactoring many things right now. This could mess up the thickness of your edges (which means you would need them to be < 1 size to have the same crisp lines as what 1 meant before).

**Comment by havardl** [comment]
Ok, I understand. It seems unnecessary to create a new release for this then, as I'm just trying to port a project from v1.2.1 to v.2. Thanks for looking into it for me.

**Comment by Yomguithereal** [comment]
Note that the message is not printed in the console anymore with last commit, but it is the only thing actually fixed by this :)
