### ISSUE TITLE
How do I move camera to specific node in sigma.js version 2?

### ISSUE THREAD

**Issue by suhdonghwi** [jacomyal/sigma.js#1112]
I want to know how I can convert node x, y position to camera position.

**Comment by sim51** [comment]
Hi, this is what you can do, where `id` is your node key : 

```
const x = renderer.nodeDataCache[id].x;
const y = renderer.nodeDataCache[id].y;
renderer.camera.animate({ x, y }, { easing: "linear", duration: 500 });
```

I just push a commit that will help users to do that, without using the internal cache system.
The example is available here : https://github.com/jacomyal/sigma.js/blob/v2/examples/pan-to-node.ts#L26-L30

**Comment by suhdonghwi** [comment]
Thank you very much for your contribution!
