### ISSUE TITLE
neo4j cypher query error

### ISSUE THREAD

**Issue by LilithElina** [jacomyal/sigma.js#1116]
I'm trying to get the example "load-neo4j-cypher-query.html" to work, but only get three "Uncaught SyntaxError: Unexpected end of JSON input" errors back. This is the error message:
"xhr.onreadystatechange @ c:\Users\Sarah\Documents\Work\tools\sigma.js\plugins\sigma.neo4j.cypher\sigma.neo4j.cypher.js:50:31"

I'm a beginner with all of this and can't figure out what the problem is. Can someone please help?

**Comment by sim51** [comment]
This plugin is only compatible with neo4j 3.X (not 4.X)

**Comment by LilithElina** [comment]
Thank you!
