### ISSUE TITLE
doc and samples for v2

### ISSUE THREAD

**Issue by knowledgeplaces** [jacomyal/sigma.js#1127]
Hi folks,
I have installed Sigma under a MyEclipse environment which I use for both Java and Angular developments.
I used the command "npm install sigma" and got version 2.0.0 installed.
I have followed the instructions to make it work with Angular, and so far so good, I can create a Sigma object in an Angular component.
But I cannot find any documentation, is there some doc avalaible and where?
The [doc  ](https://www.npmjs.com/package/sigma) says:
A development server can be spawned locally to view the examples. Visit localhost:8000 after executing the following commands: 
npm install
npm run examples
You can play around with the files in directory examples, the web pages are live-reloaded whenever the code gets changed.
I cannot run these samples either. Please advise.

**Comment by sim51** [comment]
Those npm commands are related to the sigma folder.
If you call `npm run examples` in your project folder, you ask NPM to run the task 'examples' of your project.

**Comment by knowledgeplaces** [comment]
Bonjour Benoît (l’accent sur le i me fait penser qu’on peut parler français), et merci du retour rapide.

Désolé je ne suis pas très à l’aide avec npm…

Je me suis mis dans le dossier sigma.

Quand je rentre la commande « npm install », j’ai l’erreur  en rouge ci-dessous, et en effet je n’ai pas le fichier webpack.programs.config.js, une idée ?

/c/metaLMS/console/metalms-admin/node_modules/sigma
$ npm install
> ***@***.******@***.***> prepare
> npm run clean && npm run transpile && npm run build
> ***@***.******@***.***> clean
> rimraf $npm_package_config_clean
> ***@***.******@***.***> transpile
> tsc -p ./tsconfig.transpile.json -d && replace '\.glsl' '.glsl.js' rendering -r && webpack --config ./webpack.programs.config.js
rendering\webgl\programs\edge.arrowHead.js
22: var edge_arrowHead_vert_glsl_1 = __importDefault(require("../shaders/edge.arrowHead.vert.glsl.js"));
23: var edge_arrowHead_frag_glsl_1 = __importDefault(require("../shaders/edge.arrowHead.frag.glsl.js"));
rendering\webgl\programs\edge.clamped.js
23: var edge_clamped_vert_glsl_1 = __importDefault(require("../shaders/edge.clamped.vert.glsl.js"));
24: var edge_frag_glsl_1 = __importDefault(require("../shaders/edge.frag.glsl.js"));
rendering\webgl\programs\edge.fast.js
22: var edge_fast_vert_glsl_1 = __importDefault(require("../shaders/edge.fast.vert.glsl.js"));
23: var edge_fast_frag_glsl_1 = __importDefault(require("../shaders/edge.fast.frag.glsl.js"));
rendering\webgl\programs\edge.js
39: var edge_vert_glsl_1 = __importDefault(require("../shaders/edge.vert.glsl.js"));
40: var edge_frag_glsl_1 = __importDefault(require("../shaders/edge.frag.glsl.js"));
rendering\webgl\programs\edge.quadraticBezier.js
22: var edge_quadraticBezier_vert_glsl_1 = __importDefault(require("../shaders/edge.quadraticBezier.vert.glsl.js"));
23: var edge_quadraticBezier_frag_glsl_1 = __importDefault(require("../shaders/edge.quadraticBezier.frag.glsl.js"));
rendering\webgl\programs\edge.triangle.js
22: var edge_triangle_vert_glsl_1 = __importDefault(require("../shaders/edge.triangle.vert.glsl.js"));
23: var edge_triangle_frag_glsl_1 = __importDefault(require("../shaders/edge.triangle.frag.glsl.js"));
rendering\webgl\programs\node.fast.js
22: var node_fast_vert_glsl_1 = __importDefault(require("../shaders/node.fast.vert.glsl.js"));
23: var node_fast_frag_glsl_1 = __importDefault(require("../shaders/node.fast.frag.glsl.js"));
rendering\webgl\programs\node.js
22: var node_vert_glsl_1 = __importDefault(require("../shaders/node.vert.glsl.js"));
23: var node_frag_glsl_1 = __importDefault(require("../shaders/node.frag.glsl.js"));
[webpack-cli] Failed to load 'C:\metaLMS\console\metalms-admin\node_modules\sigma\webpack.programs.config.js' config
[webpack-cli] Error: Cannot find module 'C:\metaLMS\console\metalms-admin\node_modules\sigma\webpack.programs.config.js'
Require stack:
- C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\webpack-cli.js
- C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\bootstrap.js
- C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\bin\cli.js
- C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WebpackCLI.tryRequireThenImport (C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\webpack-cli.js:32:22)
    at loadConfig (C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\webpack-cli.js:1536:38)
    at C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\webpack-cli.js:1589:42
    at Array.map (<anonymous>)
    at WebpackCLI.resolveConfig (C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\webpack-cli.js:1588:32)
    at WebpackCLI.createCompiler (C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\webpack-cli.js:2045:33) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\metaLMS\\console\\metalms-admin\\node_modules\\sigma\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'C:\\metaLMS\\console\\metalms-admin\\node_modules\\sigma\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'C:\\metaLMS\\console\\metalms-admin\\node_modules\\sigma\\node_modules\\webpack-cli\\bin\\cli.js',
    'C:\\metaLMS\\console\\metalms-admin\\node_modules\\sigma\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
npm ERR! code 2
npm ERR! path C:\metaLMS\console\metalms-admin\node_modules\sigma
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c npm run clean && npm run transpile && npm run build
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ericm\AppData\Local\npm-cache\_logs\2021-07-09T16_20_03_094Z-debug.log

Sinon j’ai commencé à coder par tâtonnement, a priori j’ai un graphe de données qui compile en Angular 12
             const graph = new Graph();
             graph.addNode(1, { label: 'A first node', x: 1, y: 3, size: 1 });
             graph.addNode(2, { label: 'And another one', x: 3, y: 3, size: 1 });
             graph.addEdge(1, 2);
             const sampleGraph = new Sigma(graph, this.sigmaSchema.nativeElement, null);

Mais à l’exécution j’ai l’erreur :
core.js:6456 ERROR Error: Uncaught (in promise): Error: Sigma: container has no height.
Une idée ?

Merci d’avance !

Cordialement.

Eric Malalel
Directeur
01 42 42 78 35 - 06 11 62 17 60
***@***.******@***.***> | www.knowledgeplaces.com<https://www.knowledgeplaces.com/>
2 rue du Centre
93160 Noisy le Grand
***@***.***D774EF.A2FD1620]<https://www.knowledgeplaces.com/>
Portails et formations sur mesure pour utilisateurs exigeants

De : Benoît Simard ***@***.***>
Envoyé : vendredi 9 juillet 2021 17:07
À : jacomyal/sigma.js ***@***.***>
Cc : Eric Malalel ***@***.***>; Author ***@***.***>
Objet : Re: [jacomyal/sigma.js] doc and samples for v2 (#1127)


Those npm commands are related to the sigma folder.
If you call npm run examples in your project folder, you ask NPM to run the task 'examples' of your project.

**Comment by sim51** [comment]
Hi,

Yes I'm a french guy :)

But I will continue in english because this issue is public and perhaps one day it will save time to someone else that will have the same problem as you.

If you want to run the sigmav2 examples, you must clone the repository to have the whole source code of sigma, and not only what is published in NPM. 

When we publish on NPM, we don't send the entire repository (like tests, examples, ...) to reduce the footprint of the package.

So what you need to do is :
* cloning the repository locally
* checkout the v2 branch
* type npm install and then npm run examples

We are working on the sigma v2  website with  working version of  examples, and we also hope to find a way to publish them on codesandbox (ex: https://codesandbox.io/s/sigmajs-issue-xx-00nll?file=/src/index.ts)

**Comment by knowledgeplaces** [comment]
Bonsoir Benoît.

J’ai réglé la 2ème erreur, « container has no height », et j’ai maintenant mon graphe de test qui s’affiche.

***@***.***D7750F.9BA79790]

Il me reste donc à connaître toutes les possibilités de la librairie via une doc ou les exemples.

Merci d’avance si vous pouvez me dépanner sur les exemples.

Cordialement.

Eric Malalel
Directeur
01 42 42 78 35 - 06 11 62 17 60
***@***.******@***.***> | www.knowledgeplaces.com<https://www.knowledgeplaces.com/>
2 rue du Centre
93160 Noisy le Grand
***@***.***D7750F.36792FF0]<https://www.knowledgeplaces.com/>
Portails et formations sur mesure pour utilisateurs exigeants

De : Eric Malalel
Envoyé : vendredi 9 juillet 2021 18:39
À : jacomyal/sigma.js ***@***.***>; jacomyal/sigma.js ***@***.***>
Cc : Author ***@***.***>
Objet : RE: [jacomyal/sigma.js] doc and samples for v2 (#1127)

Bonjour Benoît (l’accent sur le i me fait penser qu’on peut parler français), et merci du retour rapide.

Désolé je ne suis pas très à l’aide avec npm…

Je me suis mis dans le dossier sigma.

Quand je rentre la commande « npm install », j’ai l’erreur  en rouge ci-dessous, et en effet je n’ai pas le fichier webpack.programs.config.js, une idée ?

/c/metaLMS/console/metalms-admin/node_modules/sigma
$ npm install
> ***@***.******@***.***> prepare
> npm run clean && npm run transpile && npm run build
> ***@***.******@***.***> clean
> rimraf $npm_package_config_clean
> ***@***.******@***.***> transpile
> tsc -p ./tsconfig.transpile.json -d && replace '\.glsl' '.glsl.js' rendering -r && webpack --config ./webpack.programs.config.js
rendering\webgl\programs\edge.arrowHead.js
22: var edge_arrowHead_vert_glsl_1 = __importDefault(require("../shaders/edge.arrowHead.vert.glsl.js"));
23: var edge_arrowHead_frag_glsl_1 = __importDefault(require("../shaders/edge.arrowHead.frag.glsl.js"));
rendering\webgl\programs\edge.clamped.js
23: var edge_clamped_vert_glsl_1 = __importDefault(require("../shaders/edge.clamped.vert.glsl.js"));
24: var edge_frag_glsl_1 = __importDefault(require("../shaders/edge.frag.glsl.js"));
rendering\webgl\programs\edge.fast.js
22: var edge_fast_vert_glsl_1 = __importDefault(require("../shaders/edge.fast.vert.glsl.js"));
23: var edge_fast_frag_glsl_1 = __importDefault(require("../shaders/edge.fast.frag.glsl.js"));
rendering\webgl\programs\edge.js
39: var edge_vert_glsl_1 = __importDefault(require("../shaders/edge.vert.glsl.js"));
40: var edge_frag_glsl_1 = __importDefault(require("../shaders/edge.frag.glsl.js"));
rendering\webgl\programs\edge.quadraticBezier.js
22: var edge_quadraticBezier_vert_glsl_1 = __importDefault(require("../shaders/edge.quadraticBezier.vert.glsl.js"));
23: var edge_quadraticBezier_frag_glsl_1 = __importDefault(require("../shaders/edge.quadraticBezier.frag.glsl.js"));
rendering\webgl\programs\edge.triangle.js
22: var edge_triangle_vert_glsl_1 = __importDefault(require("../shaders/edge.triangle.vert.glsl.js"));
23: var edge_triangle_frag_glsl_1 = __importDefault(require("../shaders/edge.triangle.frag.glsl.js"));
rendering\webgl\programs\node.fast.js
22: var node_fast_vert_glsl_1 = __importDefault(require("../shaders/node.fast.vert.glsl.js"));
23: var node_fast_frag_glsl_1 = __importDefault(require("../shaders/node.fast.frag.glsl.js"));
rendering\webgl\programs\node.js
22: var node_vert_glsl_1 = __importDefault(require("../shaders/node.vert.glsl.js"));
23: var node_frag_glsl_1 = __importDefault(require("../shaders/node.frag.glsl.js"));
[webpack-cli] Failed to load 'C:\metaLMS\console\metalms-admin\node_modules\sigma\webpack.programs.config.js' config
[webpack-cli] Error: Cannot find module 'C:\metaLMS\console\metalms-admin\node_modules\sigma\webpack.programs.config.js'
Require stack:
- C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\webpack-cli.js
- C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\bootstrap.js
- C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\bin\cli.js
- C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WebpackCLI.tryRequireThenImport (C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\webpack-cli.js:32:22)
    at loadConfig (C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\webpack-cli.js:1536:38)
    at C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\webpack-cli.js:1589:42
    at Array.map (<anonymous>)
    at WebpackCLI.resolveConfig (C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\webpack-cli.js:1588:32)
    at WebpackCLI.createCompiler (C:\metaLMS\console\metalms-admin\node_modules\sigma\node_modules\webpack-cli\lib\webpack-cli.js:2045:33) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\metaLMS\\console\\metalms-admin\\node_modules\\sigma\\node_modules\\webpack-cli\\lib\\webpack-cli.js',
    'C:\\metaLMS\\console\\metalms-admin\\node_modules\\sigma\\node_modules\\webpack-cli\\lib\\bootstrap.js',
    'C:\\metaLMS\\console\\metalms-admin\\node_modules\\sigma\\node_modules\\webpack-cli\\bin\\cli.js',
    'C:\\metaLMS\\console\\metalms-admin\\node_modules\\sigma\\node_modules\\webpack\\bin\\webpack.js'
  ]
}
npm ERR! code 2
npm ERR! path C:\metaLMS\console\metalms-admin\node_modules\sigma
npm ERR! command failed
npm ERR! command C:\windows\system32\cmd.exe /d /s /c npm run clean && npm run transpile && npm run build
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ericm\AppData\Local\npm-cache\_logs\2021-07-09T16_20_03_094Z-debug.log

Sinon j’ai commencé à coder par tâtonnement, a priori j’ai un graphe de données qui compile en Angular 12
             const graph = new Graph();
             graph.addNode(1, { label: 'A first node', x: 1, y: 3, size: 1 });
             graph.addNode(2, { label: 'And another one', x: 3, y: 3, size: 1 });
             graph.addEdge(1, 2);
             const sampleGraph = new Sigma(graph, this.sigmaSchema.nativeElement, null);

Mais à l’exécution j’ai l’erreur :
core.js:6456 ERROR Error: Uncaught (in promise): Error: Sigma: container has no height.
Une idée ?

Merci d’avance !

Cordialement.

Eric Malalel
Directeur
01 42 42 78 35 - 06 11 62 17 60
***@***.******@***.***> | www.knowledgeplaces.com<https://www.knowledgeplaces.com/>
2 rue du Centre
93160 Noisy le Grand
***@***.***D7750F.36792FF0]<https://www.knowledgeplaces.com/>
Portails et formations sur mesure pour utilisateurs exigeants

De : Benoît Simard ***@***.******@***.***>>
Envoyé : vendredi 9 juillet 2021 17:07
À : jacomyal/sigma.js ***@***.******@***.***>>
Cc : Eric Malalel ***@***.******@***.***>>; Author ***@***.******@***.***>>
Objet : Re: [jacomyal/sigma.js] doc and samples for v2 (#1127)


Those npm commands are related to the sigma folder.
If you call npm run examples in your project folder, you ask NPM to run the task 'examples' of your project.

**Comment by knowledgeplaces** [comment]
Thanks for feedback.
Where can I find the v2 repo?
https://github.com/jacomyal/sigma.js is for v1.2.1.
Also, which tool do I need to checkout the v2 branch? I am really not familiar with npm, sorry.

**Comment by sim51** [comment]
For question about how to use sigma, use stackoverflow instead (https://stackoverflow.com/questions/tagged/sigma.js).
Github issues are for issues :)
