### ISSUE TITLE
planned sigma v2 features

### ISSUE THREAD

**Issue by bogklug** [jacomyal/sigma.js#1129]
Hi, I'm considering switching from sigma v1 to sigma v2. Judging from the README file it seems almost finalized and I wanted to ask if you're still planning to add any new features in the near future. In particular are you planning to add an svg renderer perhaps (would be useful for exporting to vector graphics formats)?

**Comment by sim51** [comment]
SigmaV2 is based on graphology for the graph data storage, and Sigmav2 is a webgl renderer for Graphology.
If you want to export your graph in SVG, I recommend you to take a look at https://github.com/graphology/graphology-svg

**Comment by sim51** [comment]
SigmaV2 is still in beta mode, even if we use it in many projects that are already in production. 
But before to do a release we have to redo the website, and also to do some tweaks in the code that can eventually lead to some (tiny) breaking changes, mainly in the internal API.

**Comment by bogklug** [comment]
Thanks. To dig deeper :) - will graphology-svg try to replicate the looks of the network from the webgl renderer? E.g. at first glance it seems that in the webgl renderer there is some code for curved edges or edges with arrow heads and in graphology-svg there is not?

**Comment by sim51** [comment]
It's two separated project, and so yes the renders are not the same. 
But in SVG it's really easy to create a new shape for nodes and/or edges, and it's already configurable via `components` in `graphology-svg`.
