### ISSUE TITLE
Using hideEdgesOnMove does not work with defaultEdgeType set to "arrow" in v2

### ISSUE THREAD

**Issue by apitts** [jacomyal/sigma.js#1132]
With the below set: 
hideEdgesOnMove: true,
defaultEdgeType: "arrow",

It looks like edges will not "unhide" after moving the graph if I hover a node just after moving the graph but before edges have unhidden.

**Comment by apitts** [comment]
Actually, it looks like I get the same behaviour without setting defaultEdgeType to arrow.

**Comment by apitts** [comment]
I have verified that this happens for me in the settings.ts example in the examples folder (after adding hideEdgesOnMove: true and moving the graph around a lot).

**Comment by sim51** [comment]
Thanks @apitts for the bug, I can reproduce it, and I corrected it. 
The code will be reviewed before to merge it in the v2 branch.

**Comment by apitts** [comment]
Terrific - thanks @sim51!
