### ISSUE TITLE
enterNode event on the extremes for v2 doesn't seem to fire

### ISSUE THREAD

**Issue by apitts** [jacomyal/sigma.js#1135]
If I approach say the left most node from the left then the enterNode event doesn't seem to fire until I'm over the centre of the node, i.e. for the nodes on the left and right of the graph it doesn't appear to take into account their size beyond the centre of the node. Perhaps the bounding box ignores node size? This can be tested via the events example.

**Comment by sim51** [comment]
I can reproduce it. 

 `sigma.getQuadNodes(x,y)` returns an empty array, don't know why.  I need the help of @jacomyal  on this one :)

**Comment by sim51** [comment]
If I remove this line, it works : https://github.com/jacomyal/sigma.js/blob/v2/src/core/quadtree.ts#L504-L505

**Comment by jacomyal** [comment]
After discussing this issue with @Yomguithereal, it looks like removing this early exit is the best solution indeed. We will just always add nodes from the `OUTSIDE_BLOCK` to the candidates, to handle some rare edge cases. I'm pushing the fix.
