### ISSUE TITLE
Better TS typing for event

### ISSUE THREAD

**Issue by sim51** [jacomyal/sigma.js#1142]
Adding TS types for Sigma, Captor & Camera.

**Comment by jacomyal** [comment]
I consider this feature done now that PR #1167 has been merged. It will be shipped with v2.2.

**Comment by sim51** [comment]
Events are typed internally, but they are not exported.
So I can't used the type SigmaEvent for example, I have to redefine it in my code and then TS do a duck typing check, which is not optimal

**Comment by Yomguithereal** [comment]
I guess we can export the relevant types then. One thing though is that they are defined in the class file themselves. Should we move them to `type.ts` so that importing types always come from the same file?

**Comment by sim51** [comment]
Yep exporting them is enough.
To centralize them into `type.ts` is OK for me, but to let them in the file where events are implemented make sense also.
