### ISSUE TITLE
Graphology upgrade report

### ISSUE THREAD

**Issue by Yomguithereal** [jacomyal/sigma.js#1149]
@jacomyal @sim51 I just upgraded `graphology` to 0.22.1 in the repo. It does not affect anything apart from `package.json` files as it seems. The upgrade is only mostly breaking if you used the `#.forEach*Until` methods and advanced `#.degree` trickery so most projects should be fine.

Some remarks:

1. I did not upgrade the `demo` because `react-sigma-v2` has a peer dep which does not allow  `0.22.1`.
2. `better-edge-measures` seem to be mergeable without issues at this point.

Check f46a5670c25e94241f15fd61fe0c53f35dd6b290 for reference.

It would be good if someone other than me could peruse the v0.22 changelog and assert whether I missed something obvious: https://github.com/graphology/graphology/blob/master/CHANGELOG.md#0220

**Comment by sim51** [comment]
FYI, I updated today the react lib, mainly for the peer dependencies mapping

**Comment by sim51** [comment]
Demo updated, see PR #1151
