### ISSUE TITLE
V2 double click event

### ISSUE THREAD

**Issue by avenzi** [jacomyal/sigma.js#1153]
Hello,

I may be mistaken, but it doesn't appear that doubleClick events are available yet in V2. In the source it looks like the mouse captor handleDoubleClick() method does not emit any events, and no double click events exist for the sigma class itself, like 'doubleClickNode' or 'doubleClickStage'.

What I've ended up doing in my project to change the default double click behavior is just redefine the captor handler, like so:

`
sigma.getMouseCaptor().handleDoubleClick = function(event) {
    console.log("Double Click!")
    }
` 

Is this the intended way to handle double click events, or will this emitted event be added at some point?

Thanks!

**Comment by jacomyal** [comment]
Hi @aeviox,

You are right, the double click events [are missing](https://github.com/jacomyal/sigma.js/blob/9d4e33cd73d4ee9ec1b00b34697e30cdc327c47d/src/core/captors/mouse.ts#L112-L129), and it shouldn't be too hard to add.

We will try to add that soon, probably at the same time we tackle issue #1142. Thanks for the report, I'll keep you updated here as soon as we have something.

**Comment by Aeviox** [comment]
Worth nothing that the [wheel events](https://github.com/jacomyal/sigma.js/blob/504f7eeb9fbf7bdf78683a6c97e8495cef2bd50d/src/core/captors/mouse.ts#L247-L289) don't look like they are there either, but again correct me if I'm wrong.

Thanks again!

**Comment by jacomyal** [comment]
Indeed, I never thought of it, but it's easy to add and I can imagine this feature being useful sometime.

**Comment by gajicdev** [comment]
Would love the doubleclick and wheel events aswell 😄

**Comment by jacomyal** [comment]
I just pushed a commit implementing the wheel and double-click events.

However, there are two things to note:
1. At the moment, the events are just emitted, and there is no way to use that to cancel the default event behavior. For instance, there's no way right now to cancel normal sigma zoom when the user uses the mouse-wheel on a node.
2. The double-click events are dispatched **in addition** the the click events. If you need to catch a double-click that would cancel the single-click, you will need to implement this the application side.

This should be deployed within the upcoming v2.1.0 release.

**Comment by avenzi** [comment]
I just submitted a pull request that I believe fixes the first of your concerns, allowing wheel and doubleClick event handlers to prevent the default behavior defined in the MouseCaptor. The usage looks like this (where renderer is a reference to the Sigma renderer):
```
renderer.getMouseCaptor().on("doubleClick", (event) => {
    console.log("double click", event)
})

renderer.on("doubleClickNode", (event) => {
    event.event.preventDefault()
    console.log("double clicked a node", event.event)
})

renderer.getMouseCaptor().on('wheel', (event) => {
    console.log("wheel")
})

renderer.on('wheelNode', (event) => {
    event.event.preventDefault()
    console.log("wheeled on a node")
})
```

Another option could be to make the preventDefault() method available to the Node and Stage events by simply adding it as a property to the returned object [here](https://github.com/jacomyal/sigma.js/blob/443ee9f1f4485370d1e56b31878a6800b3399a9e/src/sigma.ts#L435-L441). This would have the benefit of avoiding the "event.event...".
