### ISSUE TITLE
border and image at node

### ISSUE THREAD

**Issue by N1neTa1ls** [jacomyal/sigma.js#1154]
I decided to switch from sigma 1.2.1 to v2
there are a few questions
1. I need to display the image and the border at the same time so that I can select the nodes I need and color the border in the color I need around the image
In the example given, there is either one or the other
2. I can't find documentation about which events, nodes, and boundary parameters the new sigma takes into account
(in the wiki of the old sigma it was)
3. maybe there is a document on the implementation of the old functionality in the new sigma?
I am clearly missing many plugins that were implemented in 1.2.1

**Comment by Yomguithereal** [comment]
Hello @N1neTa1ls,

> 1. I need to display the image and the border at the same time so that I can select the nodes I need and color the border in the color I need around the image
In the example given, there is either one or the other

To do so you will need to combine both programs and the related shaders into a single one basically. The one able to display borders here: https://github.com/jacomyal/sigma.js/blob/main/examples/custom-rendering/node.border.ts and the one for images there: https://github.com/jacomyal/sigma.js/blob/main/src/rendering/webgl/programs/node.image.ts There is no easier way to do so unfortunately since this lib is all about benefitting from webgl performance and there is not really a way to make this easier to do without sacrificing said performance.

This said, if you only need borders when a node is "selected" there might be a way to do so by using the `labelRenderer` or `hoverRenderer` setting for which you can find a customization example here: https://github.com/jacomyal/sigma.js/blob/main/examples/custom-rendering/node.border.ts

> 2. I can't find documentation about which events, nodes, and boundary parameters the new sigma takes into account
(in the wiki of the old sigma it was)

This documentation will be written at some point, we just need some time to do so. In the meantimes the [examples](https://github.com/jacomyal/sigma.js/tree/main/examples) should give you most of them as well as the expected payloads and parameters.

> 3. maybe there is a document on the implementation of the old functionality in the new sigma?
I am clearly missing many plugins that were implemented in 1.2.1

Which one are you referring to? Most of them are now completely obsolete because they can be replicated using v2 features out-of-the-box or are implemented in [graphology](https://graphology.github.io/) or its [standard library](https://graphology.github.io/standard-library/).

**Comment by N1neTa1ls** [comment]
> Hello @N1neTa1ls,
> 
> > 1. I need to display the image and the border at the same time so that I can select the nodes I need and color the border in the color I need around the image
> >    In the example given, there is either one or the other
> 
> To do so you will need to combine both programs and the related shaders into a single one basically. The one able to display borders here: https://github.com/jacomyal/sigma.js/blob/main/examples/custom-rendering/node.border.ts and the one for images there: https://github.com/jacomyal/sigma.js/blob/main/src/rendering/webgl/programs/node.image.ts There is no easier way to do so unfortunately since this lib is all about benefitting from webgl performance and there is not really a way to make this easier to do without sacrificing said performance.
> 
> This said, if you only need borders when a node is "selected" there might be a way to do so by using the `labelRenderer` or `hoverRenderer` setting for which you can find a customization example here: https://github.com/jacomyal/sigma.js/blob/main/demo/src/canvas-utils.ts
> 
> > 1. I can't find documentation about which events, nodes, and boundary parameters the new sigma takes into account
> >    (in the wiki of the old sigma it was)
> 
> This documentation will be written at some point, we just need some time to do so. In the meantimes the [examples](https://github.com/jacomyal/sigma.js/tree/main/examples) should give you most of them as well as the expected payloads and parameters.
> 
> > 1. maybe there is a document on the implementation of the old functionality in the new sigma?
> >    I am clearly missing many plugins that were implemented in 1.2.1
> 
> Which one are you referring to? Most of them are now completely obsolete because they can be replicated using v2 features out-of-the-box or are implemented in [graphology](https://graphology.github.io/) or its [standard library](https://graphology.github.io/standard-library/).

thanks for the quick response!

1. Tomorrow, afternoon I'll look, it's, already night in Russia)
Unfortunately, I am not a professional specialist yet, If with the help of the links that you gave me it will be possible to implement the allocation of the nodes I need, it will be great

3. the first thing I remembered is
tooltips with mustache
A* algorythm

**Comment by N1neTa1ls** [comment]
> To do so you will need to combine both programs and the related shaders into a single one basically. The one able to display borders here: https://github.com/jacomyal/sigma.js/blob/main/examples/custom-rendering/node.border.ts and the one for images there: https://github.com/jacomyal/sigma.js/blob/main/src/rendering/webgl/programs/node.image.ts There is no easier way to do so unfortunately since this lib is all about benefitting from webgl performance and there is not really a way to make this easier to do without sacrificing said performance.

I was trying to figure out how to connect these two files, but I didn't understand how to do it
Are there any plans to refine such functionality?

**Comment by Yomguithereal** [comment]
> the first thing I remembered plugin is
tooltips with mustache

I don't understand which plugins you are speaking of.

> A* algorythm

A* is on the roadmap yes. But do you specifically need A*? Which heurstic do you intend to use in your case? Isn't Dijsktra enough?

> I was trying to figure out how to connect these two files, but I didn't understand how to do it
Are there any plans to refine such functionality?

Probably not, except if someone or even us at one point contribute a very specific image + border node program. But without solid knowledge of webgl it might be difficult indeed.

**Comment by N1neTa1ls** [comment]
> I don't understand which plugins you are speaking of.

  <script src="js/SigmaJS/plugins/sigma.plugins.tooltips.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/0.8.1/mustache.min.js"></script>
  
  

> A* is on the roadmap yes. But do you specifically need A*? Which heurstic do you intend to use in your case? Isn't Dijsktra enough?

A* preferably, but we will be content with what we have

**Comment by Yomguithereal** [comment]
> another question, is edge allocation now also impossible?

I am not sure to understand what you mean.

**Comment by N1neTa1ls** [comment]
> > another question, is edge allocation now also impossible?
> 
> I am not sure to understand what you mean.

I can hang an event on the node
for example
      this.renderer.on('rightClickNode', (e) => {
        e.event.preventDefault();
        console.log(e);
      });
and perform any actions with it

previously I could do the same with edge, in v2 I don't see this functionality(

**Comment by sim51** [comment]
The edge click is not present yet.
It's on the roadmap, and the work has been already started in the branch `better-edge-measures`.

**Comment by ontologymerging** [comment]
[Yomguithereal](https://github.com/Yomguithereal)
Can I give me contact to you by email to ask some questions related to sigmajs v2?.
If possible, please send an email to my address: mtthanh.stcc@gmail.com

**Comment by Yomguithereal** [comment]
Why don't you ask your question here?

**Comment by taducanh1605** [comment]
Hi @Yomguithereal,
I try to show the border of nodes (at all times), but I only use javascript with sigma.min.js file, i don't understand too well how you set border for nodes. Can you give me a simple example using js?

**Comment by jacomyal** [comment]
This thread is starting to get really confusing, and far away from the original question.

- @N1neTa1ls: About the original question, to display both the border and an image an in node, you need to have a custom renderer. There is one in progress by @kaij in PR #1206 for instance. Also, at the moment, [the examples](https://github.com/jacomyal/sigma.js/tree/main/examples) are the best source both for documentation and for how to do things with sigma.
- @taducanh1605: Same answer for borders, it is not integrated in sigma's core. Also, unfortunately, custom rendering is probably too advanced of a usecase to solve without a proper building tool. I would suggest you start with existing example to see how to build an app using sigma.

**Comment by ontologymerging** [comment]
Hello [Jacomyal] and [Yomguithereal]

My question is the same to taducanh1605. I built an application using sigmajs to show all databases in the form of a graph.
However, I would like to draw a border for each node. So, I come this forum to ask you for them.
As you suggested, I should use this link to conduct it.
https://github.com/jacomyal/sigma.js/blob/main/examples/custom-rendering/node.border.ts
In fact, I try to use this existing example, however it does not work. If possible, please give me an explicit example (how to use) of this work. Many thanks in advance!

**Comment by ontologymerging** [comment]
Hello [Jacomyal]

Many thanks for your prompt answer.
Maybe, my question is not very clear to you. Your example is very nice and flexible!.  My problem is that I would like to always show  a border for each node when running the application without using "hovermouse". From my observation they will appear border when we hover on node. I hope that this description is more clear to you. Thank you so much!
