### ISSUE TITLE
(V2) Unexpected node interaction with zIndex

### ISSUE THREAD

**Issue by avenzi** [jacomyal/sigma.js#1157]
### Description: 
 When overlapping nodes have different zIndex values, the visual overlap as well as click and hover events all exhibit different behavior, leading to unexpected results.

### Versions:
- Sigma.js: 2.0.0
- Graphology: 0.21.1 and 0.22.0
- OS: macOS Big Sur
- Browsers: Firefox (94.0.1), Edge (95.0.1020.44), Chrome (95.0.4638.69)

### To Reproduce:
- See CodeSandbox example: https://codesandbox.io/s/v2lle
  - Two nodes have been added to the graph, one at zIndex=0 (grey) and one at zIndex=1 (blue)
  - A "clickNode" event has been bound to output the node clicked to the console.
- open the console, then move the mouse from left to right on the canvas, incrementally clicking the overlapping nodes at different horizontal locations and observe the behavior of the hover and click events.

Note: Because of the inconsistencies, I cannot tell whether zIndex is intended to go up or down with respect to node "depth", but this issue remains either way (see observed behavior).

Observed Behavior:
- The visual overlap of the nodes show nodes with _higher_ zIndex on _top._
- Click events hit the node with the _lowest_ zIndex.
- Hover events completely ignore zIndex, instead prioritizing the _closest_ node (distance to center)

Expected Behavior:
- The hover and click events target the same node.
- zIndex direction is consistent across all interactions.

### Possible Solution?
It looks like the intent was to allow hovering of any node regardless of zIndex, which is why it seems like hovering is [only dependent on distance](https://github.com/jacomyal/sigma.js/blob/8242328505357bfa3dd5530e241556030408ee8f/src/sigma.ts#L400-L403), with a TODO for possible targeting based on size. This makes sense, but the problem is that the click event is not bound by the same rules, so the result is that you can be hovering one node but click another node that might not even be visible. This is shown in the CodeSandbox example where you can be hovering near the center of the blue node, but click events hit the grey node behind it.

Please share your thoughts on the following proposed solutions:

1) Match click and hover event targets.
   - I believe all that is necessary is to emit the hoveredNode in the [click listener](https://github.com/jacomyal/sigma.js/blob/8242328505357bfa3dd5530e241556030408ee8f/src/sigma.ts#L436). This would match the click and hover event targets, which is the expected behavior. 
   - The problem with this proposed solution is that the zIndex would no longer affect node interaction; the click and hover events would both be dependent only on distance to the closest node, ignoring zIndex (as the hover event currently does). This justifies my second proposal.
   
    
2) Match hover/click events to visual overlap, respecting the same zIndex ordering. 
   - This means making the hover event target the node that is visually on top (according to zIndex), rather than the closest node. Because of my first solution, the click event does the same.
   - This means that now all three characteristics have matching behaviors: visual overlap, hover, and click.
   - This also means that one can explicitly control all these characteristics using only zIndex, and that information is translated directly and clearly to the user. (i.e., if you see a node visually on top of the others, that is one which will be clicked.)

### Notes
I came across this problem because I was having trouble with hidden nodes overlapping visible nodes and preventing click events. I was originally going to submit a bug report for that, but I thought I might be able to get around it using zIndex, which is when I came across the interactions outlined above. This is another reason for my suggestions: If hover and click events respect zIndex, then the special case of hidden nodes is simple - all I need to do is put a line in my nodeReducer that changes the zIndex of hidden nodes.

**Comment by jacomyal** [comment]
Hi @avenzi,

Thanks a lot for this very clear and detailed report!

The fact that the hovered node and the clicked node are not the same is clearly an issue to solve, good catch.

About expecting syncronized zIndex and node interactions though, I'm not so sure. I personally like that all nodes are available for interactions, and I can imagine being frustrated trying to click a small node that is partially behind a bigger node otherwise.

So I would vote for solution one.

@Yomguithereal @sim51 what's your opinion on this issue?

**Comment by avenzi** [comment]
I agree that being able to click/hover every node regardless of position is a desirable feature - I can definitely see your example being a frustrating situation. 

I think my specific use case boils down to disabling interaction with certain nodes (hidden nodes), and my proposed solution 2 was an attempt to generalize that behavior: being able to specify which nodes are prioritized for interaction in _any_ situation. 

Maybe whether zIndex affects interaction could simply be another optional argument when defining the renderer?

Or, If it isn't optimal to tie that to zIndex at all, would it be possible to add a separate attribute to control this behavior? Maybe a boolean node attribute that determines whether it can be interacted with, which would then be easy to modify in a nodeReducer.
