### ISSUE TITLE
Maybe unnecessary context clearing in edge label rendering

### ISSUE THREAD

**Issue by Yomguithereal** [jacomyal/sigma.js#1171]
Is this necessary since we clear it in `#.clear`? https://github.com/jacomyal/sigma.js/blob/main/src/sigma.ts#L927

**Comment by jacomyal** [comment]
I just checked, and it actually is useful for some cases. For instance, when the mouse leaves a node, `scheduleHighlightedNodesRender` is called, which will call `renderEdgeLabels`, which redraws the edge labels, without ever calling the `#.call` method.
