### ISSUE TITLE
clearEdges won't delete the edges in the graph

### ISSUE THREAD

**Issue by leonard97** [jacomyal/sigma.js#1173]
## Example bug report

Modification of the node default color in the settings has no effect

- Sigma.js version : 2.1.1
- Graphology version : 0.21.1
- Operating system: Win 10
- Web browser: Chrome 96.0.4664.45

### Expected behavior

Sigma.getGraph().clearEdges() should remove edges like clear() removes everything

### Actual behavior

clearEdges() does not remove the edges from the graph

### Example

https://codesandbox.io/s/clever-mcclintock-z1u0w

**Comment by Yomguithereal** [comment]
Good catch @leonard97. I have opened a PR fixing the issue. We will review this and probably release a fix next week.
