### ISSUE TITLE
Mouse position on zoom / wheel is wrong when window scrolled

### ISSUE THREAD

**Issue by kaij** [jacomyal/sigma.js#1175]
## Zooming with mouse wheel uses wrong mouse position when scrolled down

**Sigma.js version:** 2.1.0 - 2.1.1 (works fine in 2.0.0)
**Graphology version:** 0.23.1
**Operating System:** macOS 12.0.1
**Web browser:** Chrome 95.0.4638.69 (arm64)

### Steps to reproduce
Unfortunately don't have a reproduction ready and am not enough into sigma.js yet to debug this issue. My fallback at the moment is using Sigma 2.0.0. But I'm sure it can be pretty well reproduced with Sigma 2.1.1 and the examples.

1. Use a sigma container further down the page (so you need to scroll down the page bit to reach the container)
2. Use mousewheel or double-click to zoom into the graph

### Expected behavior
Should zoom in/out at mouse position

### Actual behavior
Zoom position is dependent on scroll position. It works when scrolled at the top of the page. If scrolled further down, the graph "fades" away to top when scrolling in. 

## Note
Note: zoom controls work fine. The behaviour start with 2.1.0, so it's somewhere in the changes between 2.0.0 and 2.1.0.

**Comment by jacomyal** [comment]
Good catch. I must have screwed up somehow when trying to improve events mouse positions in a recent commit. I'll work on it ASAP and let you know when it's fixed. Thanks for the report!

**Comment by jacomyal** [comment]
The fix has been deployed in version 2.1.2, FYI.

**Comment by kaij** [comment]
Very cool, thanks for this ultrafast fix!
