### ISSUE TITLE
Uncaught Error: Sigma: Coordinates of node 1 are invalid. A node must have a numeric 'x' and 'y' attribute

### ISSUE THREAD

**Issue by veqryn** [jacomyal/sigma.js#1179]
- Sigma.js version : 2.1.2
- Graphology version : 0.23.1
- Operating system: docker node 17
- Web browser: chrome

**Steps to reproduce**
My json data:
```json
{
  "nodes": [{
      "key": 1,
      "attributes": {
        "label": "foo"
      }
    },
    {
      "key": 2,
      "attributes": {
        "label": "bar"
      }
    }
  ],
  "edges": [{
    "source": 1,
    "target": 2
  }]
}
```

I throw this data into the "layouts" example that you all have.
I have also tried having it start in the 'force atlas' and 'circular' positions.

- Expected behavior
A nice network graph with decent initial positions, where I can click on a node and drag it to a new position.
Something similar to https://observablehq.com/@d3/force-directed-graph

- Actual behavior
```
index.js:325 Uncaught Error: Sigma: Coordinates of node 1 are invalid. A node must have a numeric 'x' and 'y' attribute.
    at index.js:325
    at r6.i5.forEachNode (graph.js:2181)
    at $61a1e5f614e32376$var$validateGraph (index.js:323)
    at new Sigma (sigma.js:148)
    at index.ts:115
(anonymous) @ index.js:325
i5.forEachNode @ graph.js:2181
$61a1e5f614e32376$var$validateGraph @ index.js:323
Sigma @ sigma.js:148
(anonymous) @ index.ts:115
```

I of course do not know the positions of my nodes ahead of time. That is why I am using this library to draw the graph for me.

**Comment by jacomyal** [comment]
Hi @veqryn,

This is not a bug, and the error seems quite clear to me: Indeed sigma needs valid `x` and `y` positions for each node, to be able to render them. Also, for similar reasons, most force-directed layouts (including the ones in various other libs and applications, such as d3.js or Gephi...) need initial nodes positions to be able to properly iterate.

The good news is that there are simple ways to get initial positions:

1. You can use [`graphology-layout/random`](https://graphology.github.io/standard-library/layout#random) to get random initial positions, or [`graphology-layour/circular`](https://graphology.github.io/standard-library/layout.html#circular)to put your nodes on a circle. This is exactly what we do [in the `csv-to-network-map` example](https://github.com/jacomyal/sigma.js/blob/c5a907ae188c3ba3fbc006ff70f3e9220603248a/examples/csv-to-network-map/index.ts#L76-L80), for instance.

2. You can iterate on nodes and give them the initial positions you wan. For instance, the following code will put all your nodes on a line:

```javascript
let i = 0;
graph.forEachNode(node => {
  graph.setNodeAttribute(node, 'x', 0);
  graph.setNodeAttribute(node, 'y', i);
  i++;
});
```

I hope this helps!
