### ISSUE TITLE
Node default color cannot be set

### ISSUE THREAD

**Issue by leonard97** [jacomyal/sigma.js#1184]
## Bug report

Modification of the node default color in the settings has no effect

**Sigma.js version:** 2.1.2
**Graphology version:** 0.21.1
**Operating System:** Windows 10
**Web browser:** Chrome Version 96.0.4664.45

### Steps to reproduce

Check the live example https://codesandbox.io/s/clever-mcclintock-z1u0w 

### Expected behavior

Nodes and label should be displayed in green

### Actual behavior

Nodes and labels are displayed in grey

**Comment by sim51** [comment]
In the example you provided,  you are not configuring the Sigma settings, but you are setting node's attributes.
The good way is the following :

```
import Graph from "graphology";
import Sigma from "sigma";

const container = document.getElementById("sigma-container") as HTMLElement;

const graph = new Graph();

graph.addNode("John", {
  x: 0,
  y: 10,
  size: 5,
  label: "John"
});
graph.addNode("Mary", {
  x: 10,
  y: 0,
  size: 3,
  label: "Mary"
});

graph.addEdge("John", "Mary");
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const renderer = new Sigma(graph, container, {
  labelWeight: "normal",
  defaultNodeColor: "#39ff14",
  labelColor: { color: "#39ff14" }
});

```

**Comment by leonard97** [comment]
Thank you very much. This worked like a charm!
