### ISSUE TITLE
Multigraph doesnt seem to work

### ISSUE THREAD

**Issue by gajicdev** [jacomyal/sigma.js#1189]
Hi

It seems like the multigraph of graphology is not working with sigma v2:
https://codesandbox.io/s/sharp-elbakyan-5ly15?file=/index.ts

This throws an error
```
graph.addEdge("John", "Mary", { multi: true, multi: true });
graph.addEdge("John", "Mary", { multi: true, multi: true });
```

This not
```
graph.addEdge("John", "Mary", { multi: true, multi: true });
graph.addEdge("Mary", "John", { multi: true, multi: true });
```

Best

**Comment by Yomguithereal** [comment]
Hello @gajicdev, in your example you imported the MultiGraph wrongly. It should be:

```js
import {MultiGraph} from "graphology";
```

and not:

```js
import MultiGraph from "graphology";
```

else you just import the default graph while renaming it.

Now, this said, sigma does not really support multi graphs in that all your edges from A to B will be drawn the same way, i.e. will be drawn on one another, yielding no real usefulness. It might be supported in the future in a way or another but currently it does not.
