### ISSUE TITLE
deleting an instance

### ISSUE THREAD

**Issue by ehnuje** [jacomyal/sigma.js#119]
what i'm trying to do is make a query to DB with ajax and draw a graph with that data on the same div, without refreshing. So I use the method emptyGraph, but it seems that the instance of disappeared graph still alive. 

Is there any way that I can remove not only nodes and edges, but also the whole instance? Thank you :)

below this code is what i wrote
 document.getElementById('delete_button').addEventListener('click',function(){
    sigInst.emptyGraph(); //remove node and edges from graph instance
    sigInst.draw(); //re-draw the (empty) graph
  },true);

**Comment by ekkis** [comment]
I have a similar situation where I want to refresh the contents of a div with a new query (from Neo)  so I do something like `if (sigInst) sigInst.kill(); sigma.neo4j.cypher({...}, myQuery, { container: 'myContainer', type: 'canvas' }, function(s) { signets = s; ... })` but it doesn't seem to work.  my old graph doesn't get cleared up and replaced with the new query

**Comment by Yomguithereal** [comment]
Hello @ekkis. It is a bit complicated to debug with so little code. Do you have a link somewhere pointing to it more thoroughly?

**Comment by ekkis** [comment]
yes, most reasonable.  I spent a bunch of time trying to create a small demo to demonstrate but it works as expected, so it must be some kind of issue with the functionality I stripped out.  thanks for responding, I appreciate your support

**Comment by ekkis** [comment]
so after such futsing, I figured it out... I'm using the dragNodes plugin and as per the documentation, I had included the call `sigma.plugins.killActiveState()` right after the initialization of the active state.  that messed things up and after removing it, it seems I don't really need it.  so now it all works.

**Comment by Yomguithereal** [comment]
Cool. Happy to hear it's now working.
