### ISSUE TITLE
Typo in mousemove event example

### ISSUE THREAD

**Issue by michaelaltmann** [jacomyal/sigma.js#1190]
## Guidelines
In the example, the "mousemovebody" event should be called "mousemove"
https://github.com/jacomyal/sigma.js/blob/main/examples/mouse-manipulations/index.ts#L50

**Comment by Yomguithereal** [comment]
Hello @michaelaltmann, this is not a typo. This event specifically exists to make some dnd scenario easy to implement.

**Comment by michaelaltmann** [comment]
Hmmm.  The CodeSandbox doesn't work for me.  In my own app, based on your example, I had to change mousemovebody to mousemove.

**Comment by Yomguithereal** [comment]
Can you make sure you have v2.1.3 installed?

**Comment by michaelaltmann** [comment]
Your CodeSandbox has
graphology 0.23.2
graphology-layout-force 0.2.2
sigma 2.1.3

**Comment by michaelaltmann** [comment]
![Screen Shot 2021-12-13 at 9 34 25 AM](https://user-images.githubusercontent.com/2830939/145841623-dd667df9-3e99-4e9d-aa47-8c02873f7b4e.png)

**Comment by michaelaltmann** [comment]
I thought the intention of this example sandbox was that I could drag a single node in the graph.

**Comment by michaelaltmann** [comment]
Strange.  No console messages or browser "Problems".
Mouse over a node correctly shows a halo.  Mouse click correctly creates a new node.
Mouse drag that starts away from a node moves the whole graph.  I think this is expected behavior.
Mouse drag that starts on a node does nothing. Unexpected.

**Comment by michaelaltmann** [comment]
I am on a Mac and was having the issue with Chrome.  I just tried Safari and dragging a node works as expected.

**Comment by Yomguithereal** [comment]
I am trying to reproduce the issue on Chrome on a mac but to no avail. Can you maybe try in private mode or disabling any extension you might have?

**Comment by michaelaltmann** [comment]
Restarting Chrome did not help.
New Incognito window in Chrome does solve the problem.  I'll have to dig into this and figure out what is interfering.

**Comment by Yomguithereal** [comment]
> New Incognito window in Chrome does solve the problem. I'll have to dig into this and figure out what is interfering.

If incognito mode "fixes" the issue I would bet on a browser extension, or configuration.

**Comment by michaelaltmann** [comment]
I disabled all extensions, but the problem persists.  I need to do some other work, but will let you know if I pinpoint the root cause.
