### ISSUE TITLE
Property does not exist

### ISSUE THREAD

**Issue by dontbanmeplz** [jacomyal/sigma.js#1191]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests.
If you have questions on how to use Sigma.js, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/sigma.js) instead of creating an issue here.

To help us understand your issue, please specify important details, primarily:

- Sigma.js version : latest
- Graphology version : latest
- Operating system: Ubuntu
- Web browser: Chrome
- **Steps to reproduce**
- Set up the main example 
Run `npm start`
- Expected behavior
- Graph to be displayed
- Actual behavior
White screen and error:
```
ERROR in /root/graph/index.ts
./index.ts 14:6-13
[tsl] ERROR in /root/graph/index.ts(14,7)
      TS2339: Property 'addNode' does not exist on type 'Graph<any, any, any>'.

ERROR in /root/graph/index.ts
./index.ts 15:6-13
[tsl] ERROR in /root/graph/index.ts(15,7)
      TS2339: Property 'addNode' does not exist on type 'Graph<any, any, any>'.

ERROR in /root/graph/index.ts
./index.ts 17:6-13
[tsl] ERROR in /root/graph/index.ts(17,7)
      TS2339: Property 'addEdge' does not exist on type 'Graph<any, any, any>'.
```
Additionally, include (as appropriate) console logs, stacktraces, and other debug info.

**Comment by jacomyal** [comment]
Hi @dontbanmeplz,
Your instructions are not enough for me to reproduce this bug.
What does `Just a run` mean?

**Comment by dontbanmeplz** [comment]
> Hi @dontbanmeplz,
> 
> Your instructions are not enough for me to reproduce this bug.
> 
> What does `Just a run` mean?
> 
> 
> 
> 

Im sorry I meant to say that I set up the example and ran it with `nvm start`

**Comment by dontbanmeplz** [comment]
I didn't install graphology right
