### ISSUE TITLE
White square on highlighted nodes that overlaps

### ISSUE THREAD

**Issue by sim51** [jacomyal/sigma.js#1192]
When two nodes that overlaps are highlighted, there a render  issue

![image](https://user-images.githubusercontent.com/231657/146757566-f811668a-31cf-480c-b6dd-c4ab233feb4a.png)

- CodeSandbox : https://codesandbox.io/s/gracious-mahavira-74jj7?file=/src/index.ts:213-342
- Sigma.js version : 2.1.3

**Comment by jacomyal** [comment]
OK, it's "solved" :)

![image](https://user-images.githubusercontent.com/144846/146966114-4b2a9af2-9c4a-43bc-bfb3-430a78a7833d.png)

More precisely, there is still one layer with all the white discs and shadows (canvas), then on layer with all nodes (WebGL).
Thanks for the report!

**Comment by sim51** [comment]
For those who read this ticket :

As described, the white square appears when you have multiple highlighted nodes that overlap.
In general, I have multiple highlighted nodes when I want to force some labels to display, like for example to display the neighbors of a node on the hover event. 

This situation can now be avoid by using the props `forceLabel` in the reducers @see #1187
