### ISSUE TITLE
Lifecycle of instance when it is killed

### ISSUE THREAD

**Issue by sim51** [jacomyal/sigma.js#1196]
When sigma instance has been killed, if I change a setting with `setSettings` an error is thrown ("container has no width...").
There is no way to see if an instance is killed or not, so it's not possible to put this code in an if statement.

**Sigma.js version:** 2.1.3

### Steps to reproduce

Check the live example https://codesandbox.io/s/restless-dawn-n9bvt?file=/src/index.ts

### Expected behavior

Having an error is OK, but the message should be something like "The sigma instance has been killed".
Moreover users should be allowed to know if the instance is killed or not.

### Actual behavior

The error "Sigma: container has no width." is thrown.

## Note

The setSetting method triggers a new render, that's why the error is thrown.

**Comment by jacomyal** [comment]
Hi @sim51,
Weirdly enough, I can't reproduce it now, either locally (with all the commits that have been done since v2.1.3), or on your CodeSandbox... Can you still reproduce it?

**Comment by sim51** [comment]
Nop, so closing the issue.
