### ISSUE TITLE
💡 Feature Idea: Support combo style grouping of nodes & links for the data visualization

### ISSUE THREAD

**Issue by cliffordfajardo** [jacomyal/sigma.js#1201]
## Is your feature request related to a problem? Please describe.
As a user rendering lots of data on a graph, specifically related data, a combo feature would help visually simplify the complexity of  of the graph by :
- hiding large sets of related nodes initially
- allow the user to click (drilldown) into the node combo to reveal the information, this can happen for any number of levels
- offering a way for users to explore the graph following the principle of progressive disclosure (_give details when I need it, hide it when i dont_)

## Describe the solution you'd like
- An addition of a "combo" API into the library, offering user's another way of visualizing data

## Describe alternatives you've considered
The only 2 libraries that I am aware of that offer this functionality are:
- [Open Source] - Ant Visualization group's [G6 Typescript](https://g6.antv.vision/en/docs/manual/middle/elements/combos/defaultCombo) library ([Graphin](https://graphin.antv.vision/en-US), a react wrapper around G6) 
- [PAID license] - Cambridge Intelligence's [Keylines](https://cambridge-intelligence.com/keylines/) JS library & [Regraph](https://cambridge-intelligence.com/regraph/) (React wrapper around Keylines library)
- [Unmaintained since 2017-ish] -- [Cisco NextUI Node sets](https://youtu.be/gBsUDu8aucs?t=52)
   - [example](https://github.com/NeXt-UI/next-tutorials/blob/master/tutorials/tutorial-003-01.md)

## Question(s)
- Is this combo feature something that's worth including into Sigma.js itself, or is it better to talk with the [graphology ](https://github.com/graphology/graphology)? 
- Seems like this would be a great base feature to have in Graphology so that any library (including this or other) can take advantage of the benefits

## Demo Idea (references from other libraries)
![CleanShot 2022-01-10 at 19 20 40](https://user-images.githubusercontent.com/6743796/148875745-3030527a-5309-42b1-bf64-f470f031893c.gif)

https://user-images.githubusercontent.com/6743796/148876265-8cda468d-0d67-4afc-857e-667673b8676e.mp4

https://user-images.githubusercontent.com/6743796/148875939-d1ca9d20-7fcd-42e5-bf37-3a0a9f85fcc6.mp4

![image](https://user-images.githubusercontent.com/6743796/148875546-3ae5049e-39f3-4fb7-b9a8-5783560d7fd1.png)

## References
- [G6 Overview of combos](https://g6.antv.vision/en/docs/manual/middle/elements/combos/defaultCombo)
- [Combo article by Cambridge intelligence 1](https://cambridge-intelligence.com/combos/)
- [Combo article by Cambridge intelligence 2](https://cambridge-intelligence.com/graph-visualization-rectangular-combos/)
- [Combo article by Cambridge Intelligence 3](https://cambridge-intelligence.com/category/keylines/combos/)

@jacomyal @Yomguithereal

**Comment by avenzi** [comment]
I think this is a great idea and it has a lot of use cases. In my own project, I've implemented a version of this by selectively hiding and revealing nodes according to an underlying tree structure, but it's not quite as fancy as the examples given. If this were a native feature, it would certainly make this task a lot simpler.

**Comment by cliffordfajardo** [comment]
> _In my own project, I've implemented an approximate version of this by selectively hiding and revealing nodes according to an underlying tree structure, but it's not quite as fancy as the examples given_

> _though this certainly won't be a simple feature to implement._
I figured

@avenzi -  seeing some examples would be awesome. I'd be curious to learn how different people have approached this problem. Is there a github repo or codesanbox.io you could share? 🙏

**Comment by avenzi** [comment]
Unfortunately I don't have anything simple that isn't part of a much larger project, but I can share how I've been trying to do it. Essentially I've created a separate tree structure that holds all the information about nodes and their parents/children. A parent node can be expanded through some user trigger (I chose double-clicking), which immediately hides that parent node and un-hides the children. Then you can add some things like animating the children nodes expanding outwards and visual stuff like that. That's pretty much the gist of it, and it doesn't look as nice as the examples given because it doesn't really implement that nice "grouping" behavior. 

Ultimately, I would assume that if this were to be implemented in Sigma, it would require much more than just my hacky method of using existing features to emulate it. Things like displaying edges between groups and determining node placement within groups would need to be figured out.

**Comment by Yomguithereal** [comment]
Hello @avenzi and @cliffordfajardo,

this idea is clearly a legitimate UX concern but, as demonstrated by @avenzi, this feature can very well be implemented from userland. I think, and @jacomyal will chime in to infirm what I am telling you if necessary, that sigma.js' scope is a bit less high-level. What I mean is that we think sigma.js, as a library, should enable you to realize this UX feature, but we also think this idea is too complex and too opinionated (also you need to make plenty of design choice to adapt this kind of feature to your own needs, and we could not be able to make those choice for you or remain generic enough) to be part of sigma.js' core. This said, this would be a very good use case for some kind of external sigma plugin/module/library/package that anyone could maintain.

So I will currently close this issue but feel free to reopen it if you feel sigma's current state does not allow you to develop this feature on your end. Don't hesitate to still discuss on the closed issue if you want some advice if you endeavor to implement this and have a hard time grasping some details.

In the same spirit, feel free to reopen the graphology issue if you feel some clever generic indexation scheme could help you achieve your goal from `graphology-indices` or `graphology-utils` for instance.

**Comment by cliffordfajardo** [comment]
Thanks for adding context - thanks!

**Comment by cliffordfajardo** [comment]
Update G6 now supports the combos I illustrated above
- https://github.com/antvis/G6/discussions/3435

**Comment by gdnwr** [comment]
For the refactored sigma v3, is there any consideration to implement a combo?

**Comment by gdnwr** [comment]
> ## Guidelines
> ## Is your feature request related to a problem? Please describe.
> As a user rendering lots of data on a graph, specifically related data, a combo feature would help visually simplify the complexity of of the graph by :
> 
> * hiding large sets of related nodes initially
> * allow the user to click (drilldown) into the node combo to reveal the information, this can happen for any number of levels
> * offering a way for users to explore the graph following the principle of progressive disclosure (_give details when I need it, hide it when i dont_)
> 
> ## Describe the solution you'd like
> * An addition of a "combo" API into the library, offering user's another way of visualizing data
> 
> ## Describe alternatives you've considered
> The only 2 libraries that I am aware of that offer this functionality are:
> 
> * [Open Source] - Ant Visualization group's [G6 Typescript](https://g6.antv.vision/en/docs/manual/middle/elements/combos/defaultCombo) library ([Graphin](https://graphin.antv.vision/en-US), a react wrapper around G6)
> * [PAID license] - Cambridge Intelligence's [Keylines](https://cambridge-intelligence.com/keylines/) JS library & [Regraph](https://cambridge-intelligence.com/regraph/) (React wrapper around Keylines library)
> * [Unmaintained since 2017-ish] -- [Cisco NextUI Node sets](https://youtu.be/gBsUDu8aucs?t=52)
>   
>   * [example](https://github.com/NeXt-UI/next-tutorials/blob/master/tutorials/tutorial-003-01.md)
> 
> ## Question(s)
> * Is this combo feature something that's worth including into Sigma.js itself, or is it better to talk with the [graphology ](https://github.com/graphology/graphology)?
> * Seems like this would be a great base feature to have in Graphology so that any library (including this or other) can take advantage of the benefits
> 
> ## Demo Idea (references from other libraries)
> ![CleanShot 2022-01-10 at 19 20 40](https://user-images.githubusercontent.com/6743796/148875745-3030527a-5309-42b1-bf64-f470f031893c.gif) [ ![CleanShot 2022-01-10 at 19 20 40](https://user-images.githubusercontent.com/6743796/148875745-3030527a-5309-42b1-bf64-f470f031893c.gif) ](https://user-images.githubusercontent.com/6743796/148875745-3030527a-5309-42b1-bf64-f470f031893c.gif) [ ](https://user-images.githubusercontent.com/6743796/148875745-3030527a-5309-42b1-bf64-f470f031893c.gif)
> 
>  rectangular-combos-beta.mp4 
>  CleanShot.2022-01-10.at.19.22.30.mp4 
> ![image](https://user-images.githubusercontent.com/6743796/148875546-3ae5049e-39f3-4fb7-b9a8-5783560d7fd1.png)
> 
> ## References
> * [G6 Overview of combos](https://g6.antv.vision/en/docs/manual/middle/elements/combos/defaultCombo)
> * [Combo article by Cambridge intelligence 1](https://cambridge-intelligence.com/combos/)
> * [Combo article by Cambridge intelligence 2](https://cambridge-intelligence.com/graph-visualization-rectangular-combos/)
> * [Combo article by Cambridge Intelligence 3](https://cambridge-intelligence.com/category/keylines/combos/)
> 
> [@jacomyal](https://github.com/jacomyal) [@Yomguithereal](https://github.com/Yomguithereal)

For the refactored sigma v3, is there any consideration to implement a combo?
