### ISSUE TITLE
Is there a way to force labels to show all the time?

### ISSUE THREAD

**Issue by jwscot** [jacomyal/sigma.js#1202]
Is there a way with the current sigma to force node labels to render regardless of node size?

I know there were the 'forceLabel' and 'labelThreshold' with the old release but these don't seem to work for me with the new updates (I am using the most recent version incl. Graphology).

Thanks!

**Comment by jwscot** [comment]
Ok great, thanks @jacomyal. Is there a minimum node size for label rendering (preferably a mutable one)?

I've changed my node sizes drastically to test if labels render when nodes are larger but they don't - they only disappear when I make my nodes very small. I've also changed the distance between nodes to see if that affects it but no luck. 

It's very strange - all of my nodes are equal in size yet a seemingly stochastic pattern of labels seems to render.

**Comment by Yomguithereal** [comment]
@jwscot I think you need to tweak the `labelRenderedSizeThreshold` setting defined [here](https://github.com/jacomyal/sigma.js/blob/main/src/settings.ts#L110). You can pass it as an instantiation option and edit it using the `#.setSetting` method.

**Comment by Yomguithereal** [comment]
> It's very strange - all of my nodes are equal in size yet a seemingly stochastic pattern of labels seems to render.

This said, if all your nodes have the same size you might want to tweak those other two settings [here](https://github.com/jacomyal/sigma.js/blob/main/src/settings.ts#L108-L109) because we use a grid in order to limit the number of labels shown on screen for UX and performance reasons, but you might want to alter the selection's behavior.

**Comment by jacomyal** [comment]
There are basically three mechanisms to determine which labels to display:

1. The `labelRenderedSizeThreshold` setting says that any node with an actual on-screen radius under the given value won't have its label displayed (it might be diameter and not radius, I'm not sure right now)
2. The `labelDensity` and `labelGridCellSize` settings say that in each `[labelGridCellSize}px x {labelGridCellSize}px` cell, there shouldn't be more than `[labelGridCellSize}px x {labelGridCellSize}px x {labelDensity}` labels displayed. This is quite obfuscated, and @Yomguithereal already submitted PR #1172 to improve readability. But basically, increase `labelDensity` (to like 1, right now), and this rule will probably no more be effective.
3. A node with `forceLabel` has its label displayed all the time.
