### ISSUE TITLE
Error while building demo project

### ISSUE THREAD

**Issue by jimixxperez** [jacomyal/sigma.js#1204]
- Sigma.js version : v2.1.3
- Graphology version : ^0.23.2
- Operating system: 
    Distributor ID:	Pop
    Description:	Pop!_OS 20.04 LTS
    Release:	20.04
    Codename:	focal

- Expected behavior
  building demo project

- Actual behavior
yarn run build
yarn run v1.22.4
$ react-scripts build
Creating an optimized production build...
Failed to compile.

Module not found: Error: Can't resolve 'sigma/rendering/webgl/programs/node.image' in '/home/local/HQ/jeremy.perez/Projects/sigma.js/demo/src/views'

-> node.image seems to be really missing

cheers

**Comment by jacomyal** [comment]
Hi @jimixxperez,

I tried reproducing your issue using a fresh new clone and your version of yarn, but it works fine for me (Ubuntu, node v16.8.0).
What do you get when you run `cat node_modules/sigma/rendering/webgl/programs/node.image.js` from the `demo` folder ?

**Comment by jimixxperez** [comment]
@jacomyal  Thank you for the quick reply.
Getting a new error with a fresh clone. 
I m quiet new to the nodejs world. Maybe I unintentionally did something wrong.

nodejs v14.18.3

My steps:
10153  git clone https://github.com/jacomyal/sigma.js.git
10154  cd sigma.js
10155  git checkout tags/v2.1.3
10156  cd demo
10157  yarn add react-scripts
10158  yarn run build

yarn run v1.22.4
$ react-scripts build
Creating an optimized production build...
Failed to compile.

The requested module './io5' contains conflicting star exports for the names 'IoLogoAndroid', 'IoLogoAngular', 'IoLogoApple', 'IoLogoBitbucket', 'IoLogoBitcoin', 'IoLogoBuffer', 'IoLogoChrome', 'IoLogoClosedCaptioning', 'IoLogoCodepen', 'IoLogoCss3', 'IoLogoDesignernews', 'IoLogoDribbble', 'IoLogoDropbox', 'IoLogoEuro', 'IoLogoFacebook', 'IoLogoFlickr', 'IoLogoFoursquare', 'IoLogoGithub', 'IoLogoGoogle', 'IoLogoHackernews', 'IoLogoHtml5', 'IoLogoInstagram', 'IoLogoIonic', 'IoLogoIonitron', 'IoLogoJavascript', 'IoLogoLinkedin', 'IoLogoMarkdown', 'IoLogoNoSmoking', 'IoLogoNodejs', 'IoLogoNpm', 'IoLogoOctocat', 'IoLogoPinterest', 'IoLogoPlaystation', 'IoLogoPython', 'IoLogoReddit', 'IoLogoRss', 'IoLogoSass', 'IoLogoSkype', 'IoLogoSlack', 'IoLogoSnapchat', 'IoLogoSteam', 'IoLogoTumblr', 'IoLogoTux', 'IoLogoTwitch', 'IoLogoTwitter', 'IoLogoUsd', 'IoLogoVimeo', 'IoLogoVk', 'IoLogoWhatsapp', 'IoLogoWindows', 'IoLogoWordpress', 'IoLogoXbox', 'IoLogoXing', 'IoLogoYahoo', 'IoLogoYen', 'IoLogoYoutube' with the previous requested module './io'

**Comment by jacomyal** [comment]
So the good news is that now, when I follow your exact steps, I have the same error indeed.

When you run `yarn add react-scripts`, you update the required version of react-scripts from v4.0.3 to v5.0.0. If you run `yarn` instead, it will just install the required dependencies, and everything will work fine.

By the way, you can probably also skip the `git checkout tags/v2.1.3` step: There have been a lot of commits since this release, including one that updates all dependencies (and especially the demo's react-scripts version).
