### ISSUE TITLE
Node image texture grows beyond canvas limits

### ISSUE THREAD

**Issue by kaij** [jacomyal/sigma.js#1207]
Canvas size is limited by platform and browser (e.g. 32768x32768px on modern platforms). When having a lot (hundreds) of different node images, the current implementation of the atlas texture may run into the width limit. Once it hits the limit, no node image in the graph is displayed correctly anymore.

Reason: the atlas texture in the node.image program grows only in horizontal direction. If using retina (x2) display, the limit is 16384 pixels, divided by 100 (max node texture size) results in 163 images that are possible. 

I've implemented a full fix in #1198 (node.combined) which fills up the atlas texture in rows, with a defined maximum row size (e.g. 16384px).

### Steps to reproduce

Use a lot of different node image textures (each at least 100x100px).

### Expected behavior

Each node circle shows the correct image.

### Actual behavior

Texture processing is aborted and all nodes show distored images (see example image):
![image](https://user-images.githubusercontent.com/1143418/152388126-89bbdbfe-d2ef-46b8-9801-677f2ac7aaa7.png)

## Note
There is a quick fix that can be implemented for the node.image program (see pull request). A full version which supports up to thousands of images is implemented in #1198 and could be merged also in the node.image program.

**Comment by jacomyal** [comment]
Wow, great catch! I'll probably backport indeed your fix to the `node.image` program once I find time to merge your pull request. Thanks a lot!

**Comment by kaij** [comment]
@jacomyal You're welcome. Thanks for publishing sigma.js! Our project (a dynamic co-reference network visualization on a corpus of 20 millions of people and 9 mio. text pages) is using it heavily as main visualization, it will hopefully go live soon. Keep you updated :-)
