### ISSUE TITLE
How to use sigma.js with django backend server. 

### ISSUE THREAD

**Issue by Obad94** [jacomyal/sigma.js#1211]
Hello.

I have a project built on django and want to integrate sigma.js in it. How to avoid node.js server to use sigma.js with django?

**Comment by Yomguithereal** [comment]
Hello @Obad94, sigma.js is a browser library. It does not require node.js. I don't know about Django but if your question is about how to integrate sigma as an old-school script, you can find the library bundled here: https://github.com/jacomyal/sigma.js/releases and graphology here: https://github.com/graphology/graphology/releases

**Comment by Obad94** [comment]
Hi @Yomguithereal ,

Thanks for the quick response. Basically, I'm new to javascript and I was wondering how to use bundle.js in production. now I'm successfully able to integrate Sigma v.2 bundle.js in Django. Graphs are working perfectly fine. but in Django, it's giving the error `Firefox can’t establish a connection to the server at http://localhost:10000/__webpack_hmr.`  I don't want hot module replacement in production to refresh the server code. How to avoid this error in production in bundle.js file.

**Comment by Yomguithereal** [comment]
@Obad94 your issue has nothing to see with sigma as it is most likely an error related to your django/webpack packaging.
