### ISSUE TITLE
At least 5 nodes are outside the global quadtree zone.

### ISSUE THREAD

**Issue by tom-osint** [jacomyal/sigma.js#1213]
What causes `sigma/quadtree.insertNode: At least 5 nodes are outside the global quadtree zone. You might have a problem with the normalization function or the custom bounding box.` to happen internally?

Is it due to too many nodes in the same location? I am loading anywhere between 3k to 20k nodes.
I am using circular (in graphology) to initially layout the graph before handing it off to fa2 to reduce the occurrence of this error.

How can this be mitigated, so that I can guarantee it to work every time.

This warning completely breaks the graph.

**Sigma.js version:** Latest
**Graphology version:** Latest
**Operating System:** Windows 11
**Web browser:** Chrome Latest

If needed a reproducible example can be supplied.

Cheers.

**Comment by Yomguithereal** [comment]
Hello @tom-osint, this usually happens when you use custom bbox for drag n drop. Can you provide a reproducible example so we can try and find what's wrong?

**Comment by OrkhanAlikhanov** [comment]
In my case, what @Yomguithereal said was correct. DnD was causing this by setting custom bbox value. The fix is that before applying the new layout just disable the custom bbox: `sigma.setCustomBBox(null)`
