### ISSUE TITLE
Dropping node from graph isn't reflected until further rendered interface interaction

### ISSUE THREAD

**Issue by jasonford** [jacomyal/sigma.js#1214]
Thanks for the great library! This might be a basic misunderstanding of which methods to call in what order, but I have come up dry after a pretty extensive search for an example/demo/documentation.

If this is not a "bug" in the code sense, then some easier to find documentation about how to properly drop nodes from a rendered graph might be in order.

I'm happy to write the documentation if I'm pointed in the proper code direction! Also, happy to make a PR to support dropping nodes in the way I'm doing so below if it turns out this can be considered a bug/very desired feature.

# Info
- versions: indicated in imports in code below
- Operating system: any
- Web browser: chrome (but unlikely browser related)

# Steps to reproduce

run the following code that is adapted from the example on the homepage (I would have made a codesandbox, but codesandbox was crashing my browser on the example...)

The only substantive change I made to the hompage example (https://codesandbox.io/s/github/jacomyal/sigma.js/tree/main/examples/mouse-manipulations) is the "clickNode" handler at the end

```js
import Graph from "npm/unscoped/graphology/0.23.0";
import Sigma from "npm/unscoped/sigma/2.2.0";
import chroma from "npm/unscoped/chroma-js/2.1.2";
import { v4 as uuid } from "npm/unscoped/uuid/8.3.2";
//import ForceSupervisor from "npm/unscoped/graphology-layout-force/0.2.2/worker";

// Retrieve the html document for sigma container
const container = document.getElementById("sigma-container");

// Create a sample graph
const graph = new Graph();
graph.addNode("n1", { x: 0, y: 0, size: 10, color: chroma.random().hex() });
graph.addNode("n2", { x: -5, y: 5, size: 10, color: chroma.random().hex() });
graph.addNode("n3", { x: 5, y: 5, size: 10, color: chroma.random().hex() });
graph.addNode("n4", { x: 0, y: 10, size: 10, color: chroma.random().hex() });
graph.addEdge("n1", "n2");
graph.addEdge("n2", "n4");
graph.addEdge("n4", "n3");
graph.addEdge("n3", "n1");
  
// Create the spring layout and start it
//const layout = new ForceSupervisor(graph, { isNodeFixed: (_, attr) => attr.highlighted });
//layout.start();

// Create the sigma
const renderer = new Sigma.Sigma(graph, container);

//
// Drag'n'drop feature
// ~~~~~~~~~~~~~~~~~~~
//

// State for drag'n'drop
let draggedNode = null;
let isDragging = false;

// On mouse down on a node
//  - we enable the drag mode
//  - save in the dragged node in the state
//  - highlight the node
//  - disable the camera so its state is not updated
renderer.on("downNode", (e) => {
  isDragging = true;
  draggedNode = e.node;
  graph.setNodeAttribute(draggedNode, "highlighted", true);
  renderer.getCamera().disable();
});

// On mouse move, if the drag mode is enabled, we change the position of the draggedNode
renderer.getMouseCaptor().on("mousemovebody", (e) => {
  if (!isDragging || !draggedNode) return;

  // Get new position of node
  const pos = renderer.viewportToGraph(e);

  graph.setNodeAttribute(draggedNode, "x", pos.x);
  graph.setNodeAttribute(draggedNode, "y", pos.y);
});

// On mouse up, we reset the autoscale and the dragging mode
renderer.getMouseCaptor().on("mouseup", () => {
  if (draggedNode) {
    graph.removeNodeAttribute(draggedNode, "highlighted");
  }
  isDragging = false;
  draggedNode = null;
  renderer.getCamera().enable();
});

// Disable the autoscale at the first down interaction
renderer.getMouseCaptor().on("mousedown", () => {
  if (!renderer.getCustomBBox()) renderer.setCustomBBox(renderer.getBBox());
});

//
// Create node (and edge) by click
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
//

// When clicking on the stage, we add a new node and connect it to the closest node
renderer.on("clickStage", ({ event }) => {
  // Sigma (ie. graph) and screen (viewport) coordinates are not the same.
  // So we need to translate the screen x & y coordinates to the graph one by calling the sigma helper `viewportToGraph`
  const coordForGraph = renderer.viewportToGraph({ x: event.x, y: event.y });

  // We create a new node
  const node = {
    ...coordForGraph,
    size: 10,
    color: chroma.random().hex(),
  };

  // Searching the two closest nodes to auto-create an edge to it
  const closestNodes = graph
    .nodes()
    .map((nodeId) => {
      const attrs = graph.getNodeAttributes(nodeId);
      const distance = Math.pow(node.x - attrs.x, 2) + Math.pow(node.y - attrs.y, 2);
      return { nodeId, distance };
    })
    .sort((a, b) => a.distance - b.distance)
    .slice(0, 2);

  // We register the new node into graphology instance
  const id = uuid();
  graph.addNode(id, node);

  // We create the edges
  closestNodes.forEach((e) => graph.addEdge(id, e.nodeId));
});
  
    
renderer.on('clickNode', ({ event, node }) => {
  graph.dropNode(node)
})
```

- Expected behavior: after calling "dropNode" I would expect the node and connected edges to be removed from the rendering of the graph.
- Actual behavior: the node is dropped from the graph state, but the rendered graph does not update until something else causes the display to be refreshed. The edges attached to the node are indeed removed from the display, which leads me to think that the node still hanging around is truly a bug. I have tried all sorts of combinations of refreshing with various methods on the Sigma instance, camera, graph, and such, but to no satisfactory avail

**Comment by jasonford** [comment]
Just bumping to keep from getting stale. Pretty easily reproducible with that couple line change from the example on the homepage

**Comment by Yomguithereal** [comment]
@jasonford I think the issue lies with the hover mechanism since the node and its edges are indeed dropped from the graph and the renderer immediately when clicking the node. The hover remains rendered though until you move your mouse this is true indeed. Let me see if we can find some easy solution.
