### ISSUE TITLE
Get color from node

### ISSUE THREAD

**Issue by matta1596** [jacomyal/sigma.js#1228]
Hi there,

I'm quite a rookie with javascript and sigma js in general and have therefore used the Oxford Gephi exporter to set up a project even though I can understand it's not really up to date with the current standards. 
Despite my poor skills I've managed to create a product fitting my needs in most aspects - you can see it here: [https://uservoices.dk/graf/]

Nevertheless I have a few issues that are still haunting me that I hoped to get some advice on - maybe it would also be helpful for some of the many other not so technically skilled users that wish to visualize their data this way.

1. I wish to add colored dots next to search results and related nodes in my attribute panel to show their category, but I have a hard time pulling the correct variable. I was able to use for example ' + c.colour + ' for color of the given edge, but not really able to tell how these values are defined.

2. I'd like to change the nodeActive() function so that it wouldn't clear the nodes currently being showed, but just add the next ones "on top". So that one could add on and on until one manually clears the canvas. I hoped I'd be able to just remove the _clearing the canvas_ part from the function, but I was not able to figure out how.

3. I have three attributes/properties giving the values 'TYPE', 'url' and 'url2' in the panel on the right for the selected node. I would like to treat the differently, so that the urls are linking buttons while the 'TYPE' values are just spelled out. I tried to separate them through if/else but I'm not able to grab them.
Could see this method being used in the original template like this `if (image_attribute)` but I was never able to figure out how this variable was defined in the first place and therefore not sucessful defining my own to target my attributes.

I know these questions are probably stupid and it's maybe even foolish to rip up in this old exporter, but I really hope that someone could point me in the right direction.

Thanks a lot,

**Comment by jacomyal** [comment]
Hi @matta1596,

Your questions are not stupid, but I am not sure you will find a place to ask them unfortunately.
We do not maintain this old sigma version anymore, and your questions are actually related to the sigma exporter code itself, which we did not write nor maintain at any time. And to be fair, I am not sure anyone at the OII is still maintaining it either.
