### ISSUE TITLE
May I customize the shape of the points

### ISSUE THREAD

**Issue by akitaSummer** [jacomyal/sigma.js#1234]
hi~
I‘m using sigma v2, I found that all the points are circular, even using image rendering.
may I customize the shape of the points, such as SVG

**Comment by sim51** [comment]
Hi,

Node shape are created by a Node program.
For now we only have a circle program (normal, fast and with image, check https://github.com/jacomyal/sigma.js/tree/main/src/rendering/webgl/programs)

What type of shape do you want ?

**Comment by akitaSummer** [comment]
@sim51 
sorry i just saw it, i want to show only my svg/image instead of a circle wrapping the svg/image😘

**Comment by sim51** [comment]
Like I said it's not possible, without to create a new node program.
A hack can be to put the node color with the same value as your background color

But  IMHO ,it's important to have a shape (even with images) on all nodes, so their bounds are visible and also all node are "identical"

**Comment by akitaSummer** [comment]
I understand what you mean, thank you very much for your patient answer, this is a very nice library
