### ISSUE TITLE
Dotted Lines

### ISSUE THREAD

**Issue by elfedez** [jacomyal/sigma.js#1238]
**Is your feature request related to a problem? Please describe.**
I'm working on a use case where between two nodes there can exist multiple edges. In other libraries the solution is to have curved edges to display all edges, but I read in other issues your response that it's quite expensive to do that.

**Describe the solution you'd like**
The solution that I'm looking for is have dotted lines. 

**Describe alternatives you've considered**
I considered a specific color to highlight that there might exist multiple connection between those two nodes, the issue is that each edge has its own color and the display color should be the one that has more weight. 

The other solution that we though about was to have multiples lines and include an extra point between the two nodes to create like a triangle. see the screenshot below.

![Untitled Diagram drawio](https://user-images.githubusercontent.com/5719393/166112562-43075262-7629-4003-b8be-0906f2409bb4.png)

**Comment by wantnocode** [comment]
Modify based on `edge.clamped.ts`

>const POINTS = 6,
  ATTRIBUTES = 7, 
...
const x_ =(x1 + x2) / 2 ,  // midpoint
              y_ = (y1 + y2) / 2;
// Set different distances of lines
var X,Y;
if(data.index % 2 === 0) {
  if(data.index !== 0){
     X = x_ + k * 0.25 ...;
     Y = y_ + k * 0.25 ...;
  }
}else{
   X = x_ - k * 0.25 ...;
   Y = y_ - k * 0.25 ...;
}
.................
// Add point between the first and second point
  array[i++] = X;
   array[i++] = Y;
   array[i++] = -n1;
   array[i++] = -n2;
   array[i++] = thickness;
   array[i++] = color;
   array[i++] = 0;
 // 
   array[i++] = X;
   array[i++] = Y;
   array[i++] = -n1;
   array[i++] = -n2;
   array[i++] = thickness;
   array[i++] = color;
   array[i++] = 0;


![image](https://user-images.githubusercontent.com/32726183/182518735-167fa50c-21b2-4be1-b1fd-2f52e30d6f0b.png)
