### ISSUE TITLE
`clickNode` not triggered on touch devices

### ISSUE THREAD

**Issue by jacomyal** [jacomyal/sigma.js#1240]
Apparently, at least using the [`events` example](https://www.sigmajs.org/examples/events/), the `clickNode` event is not triggered when "touching" a node on a touch device (but `clickEdge` seems ok).

**Comment by kaij** [comment]
🥳  I was waiting for this... this will free time on my side so I can merge the node.combined program.

**Comment by jacomyal** [comment]
Nice :)
