### ISSUE TITLE
disabled camera but cant scroll past graph

### ISSUE THREAD

**Issue by matthewlkaplan** [jacomyal/sigma.js#1247]
I've disabled the camera because I couldn't find a better way to disable zoom/movement of the graph, and now I am unable to scroll past the graph.

**Comment by jacomyal** [comment]
Hi @matthewlkaplan,

I understand your problem, and at the same time, I have already met cases where I want the camera to be disabled **and** the DOM events defaults to be prevented:
- In an app I worked on, I want to be able to drag and drop nodes, without dragging the graph **nor the page** on touch device
- In another app, I want to be able to use the mouse wheel on a node to increase / decrease a numeric attribute, without zooming **nor** scrolling

We've been discussing with @Yomguithereal about it, and we think there are three different things that users should be able to toggle:
1. Camera interactions
2. Custom interactions
3. DOM events defaults

Right now, `camera.disable()` deals with 1., we can remove sigma listeners to handle 2., but we have no way to deal with 3. We need to find the best design for it and it should solve your issue.
