### ISSUE TITLE
Label and Highlight colors 

### ISSUE THREAD

**Issue by jacksbox** [jacomyal/sigma.js#1254]
It would be a useful feature to make label color's and highlight color's (node, box, label) configureable by node without having to implement an own node renderer

**Comment by Yomguithereal** [comment]
Hello @jacksbox, I think this is typically something we would want to keep in userland for now. This said it does not mean we won't provide it ourselves at some points in a separate package. I will soon need something akin to what you propose for [medialab/ipysigma](https://github.com/medialab/ipysigma/). I'll be able to point you the code then.
