### ISSUE TITLE
Transition effect for node/edge reducers?

### ISSUE THREAD

**Issue by phuongduyphan** [jacomyal/sigma.js#1255]
Does sigma support transition effect between states when using reducers? For example in this [demo](https://codesandbox.io/s/github/jacomyal/sigma.js/tree/main/examples/use-reducers?file=/index.ts), I want to have a transition effect (smoother color change for example) when a node is hovered.

**Comment by sim51** [comment]
There is no native function to do that, you have to do it by yourself.

When a node is hovered, you can create a timer that change the color of nodes.
