### ISSUE TITLE
How to transfer my app to react app?

### ISSUE THREAD

**Issue by jackfrost1411** [jacomyal/sigma.js#1265]
I have my app running. I used the example source codes from this repository. I want to deploy it and wish to do so by converting it into a react app. How should I do it? Also, the link to the react source code ([sourcecode](https://github.com/jacomyal/sigma.js/tree/main/examples/website-showcase)) on the homepage of sigma.js is not working.

**Comment by sim51** [comment]
Good catch for the broken link, the good one is https://github.com/jacomyal/sigma.js/tree/main/demo
I will fix it.

Otherwise you can take a look at https://sim51.github.io/react-sigma/ and its examples code https://github.com/sim51/react-sigma/tree/main/packages/examples
