### ISSUE TITLE
Prevent Viewport from panning v2

### ISSUE THREAD

**Issue by glauni** [jacomyal/sigma.js#1267]
Hi there,

i'd like to limit how far one can pan the camera with sigma.

```
    Sigma.js version : 2.2.0
    Graphology version : 0.24.1
    Operating system: MacOS (Monterey 12.4)
    Web browser: Firefox 102.0.1 (64-Bit)
```

Ive used [this](https://github.com/jacomyal/sigma.js/issues/574) before, but it doesnt work with sigma v2 anymore.

Looking forward to do this myself if i find the time.

**Comment by ping40** [comment]
#metoo

**Comment by jacomyal** [comment]
I finally pushed a fix for this ticket:
The new `cameraPanBoundaries`, if truthy, will prevent users from:
- panning the graph outside the viewport when the graph is smaller than the viewport
- panning the graph in a way that makes the viewport go "outside the graph", when the viewport is smaller
Also, (Ox) and (Oy) axis are handled separately for that matter.

Finally, it is possible to specify custom boundaries (expressed in the graph coordinates system), or add a tolerance margin in pixels.

Except for the custom boundaries, this new setting is showcased in this new story:
https://www.sigmajs.org/storybook/?path=/story/camera-control--story
