### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by jackfrost1411** [jacomyal/sigma.js#1268]
What is the max number of edges that Sigma JS can render? I am trying to render 1 million edges and go for 6 million in the future! Is it even feasible?

**Comment by sim51** [comment]
There is no hard-coded limitation in Sigma.
But Sigma runs on Web browser on which there are limitations, specially on the JS heap size, and we don't have the hand on the memory allocation.

So I'm not sure that displaying 1 million of edges in a web browser is possible ... (will be the same with other web libs).   

There is a Sigma performance showcase at this address if you want to test : https://www.sigmajs.org/examples/large-graphs

I don't know your use-case, but I suggest you to generate a SVG on the server side and display it in your browser.
With SVG you can still have some interactions in the browser, but it will not be possible to run graph layouts.
You need to try ...
The generated SVG can be heavy, so it can takes also a lot of time to your browser to interpret it.
