### ISSUE TITLE
Rendering multiple graphs

### ISSUE THREAD

**Issue by jackfrost1411** [jacomyal/sigma.js#1269]
I want to render multiple graphs according to specific user inputs. I am trying to show graphs varying with years. For example, look at this source - https://www.gapminder.org/tools/#$model$markers$bubble$encoding$frame$value=1857;&trail$data$filter$markers$alb=1800;;;;;;;;&chart-type=bubbles&url=v1

So I have multiple data files (for years from 2012 to 2022) and I want to create a setting in which a user can select a year and a graph from that data file will be rendered. Is there anything you can help me with?

**Comment by sim51** [comment]
For this, I recommend to create one graph with a date property on nodes & edges,  and then use the sigma reducers to hide nodes/edges that doesn't fit my filter.

You can take a look here to see how reducers work : https://github.com/jacomyal/sigma.js/blob/main/examples/use-reducers/index.ts#L117-L152

Please, use stackoverflow if you have question on how to use sigma.
Github's issue are mainly for bugs and missing feature
