### ISSUE TITLE
Can I have a background image zoom in and zoom out with nodes?

### ISSUE THREAD

**Issue by wmspectre** [jacomyal/sigma.js#127]
I want to add a background image rather than solid colour as background, 
but the image can not zoom in and zoom out.

**Comment by PlanCZero** [comment]
@wmspectre, did you fix it? If you did. Please provide me how to fix it. Thank you.

**Comment by PlanCZero** [comment]
Any solution or idea?

**Comment by Compynerd255** [comment]
I do know that Sigma, by default, does not normally manage your background - the display elements are transparent and the container element is the background. You could, however, rescale such a background image by hooking into a camera's `coordinatesUpdated` event:

```
sigInst.cameras[0].bind('coordinatesUpdated', function() {
  // read sigInst.cameras[0] and change your background coordinates
});
```

Note that you have to use the camera's `goTo` function for this event to work. The captors are careful to do this, even when they hook into the events themselves, but if you set the view properties yourself, the event will not fire.

**Comment by PlanCZero** [comment]
@Compynerd255 Thank you for your advice.

**Comment by Compynerd255** [comment]
@Wittipat Thank you for asking the question! I won't have time tonight, but
I will see if I can do anything to get the camera API documented in the
wiki.

**Comment by Yomguithereal** [comment]
Thanks @Compynerd255.

**Comment by PlanCZero** [comment]
Hi, Please check this #698. It might be helpful.
