### ISSUE TITLE
Make WebGLContext public or a function to clear the array

### ISSUE THREAD

**Issue by AlexanderFalk** [jacomyal/sigma.js#1271]
## Feature request

I have an issue with WebGL contexts (canvases) filling up the browser. We have a tab system where we switch between instances. Each time we switch to a new tab, 7 canvases are added to the context and at some point we hit: 
`WARNING: Too many active WebGL contexts. Oldest context will be lost.`

We have integrated Sigma.js into an Angular application and when we swap tabs, we have added the following the to `ngOnDestroy` lifecycle:

```
this.renderer.clear();
this.graph.clear();
this.renderer.kill();
```

But the contexts are still alive and the garbage collector has a hard time cleaning fast enough. I have added a workaround to refresh the application automatically after switching between 5 instances, but this is not a good solution.

**Describe the solution you'd like**
Is it possible to make some sort of functionality to remove the contexts when calling the `kill()` method? Or try to set `this.webGLContexts = []` at the end of the `kill()` method? I have a theory this could help the garbage collector kick in faster. 

I may experiment with the solution myself - when I have the time - but I wanted to raise our problem here to see if others are experiencing the same and may have found a solution.

**Describe alternatives you've considered**

**Additional context**
Here is a snippet of 35 canvases after 5 clicks.
![image](https://user-images.githubusercontent.com/8970495/186336977-bbadef7b-c26a-4545-8e88-9d9dfb1187b4.png)

**Comment by Yomguithereal** [comment]
Hello @AlexanderFalk. I am starting to investigate the issue. Some useful references for later:

- https://developer.mozilla.org/en-US/docs/Web/API/WEBGL_lose_context/loseContext
- https://github.com/mapbox/mapbox-gl-js/issues/2656

I am not sure whether there is a perfect solution here. You might want to keep a pool of Sigma renderers but it might be tricky if you need to change their containers on the fly. A pool of webgl context might be a solution also but this is not trivial. I will experiment with the `WEBGL_lose_context` first.

**Comment by Yomguithereal** [comment]
I just made some attempts using the `WEBGL_lose_context` extension and 1. it does not free the resources and 2. it outputs warning in the console. I am not sure whether this is a good solution frankly. #1280 was merged and will be part of the next release though. So if you manage a pool of sigma along with their containers (you can hide them to avoid destroying/creating them), I guess it could help you manage your use case?

**Comment by AlexanderFalk** [comment]
@Yomguithereal thanks for answering. I will differently check out #1280 . This may be helping us out 👍.

**Comment by Yomguithereal** [comment]
@AlexanderFalk can you report whether the `#.setGraph` method of v2.4.0 addresses your issue?
