### ISSUE TITLE
Turn off zoom on double click on the container

### ISSUE THREAD

**Issue by imrefazekas** [jacomyal/sigma.js#1274]
## Guidelines

I would love to remove the zoom on double click. In some cases, simple wheel is enough.
No API / settings has been found for it. 

## Feature request template

**Describe the solution you'd like**
A settings option to turn off that behaviour of sigma

**Comment by sim51** [comment]
Hi,

Yes there is no settings to avoid this default behavior, and I'm not sure that we want to add it.
But you can catch all the double click events, and prevent the sigma default behavior.

I created a code sandbox here to show/test it : https://codesandbox.io/s/1274-turn-off-zoom-on-double-click-fu8lwt

The code is the following : 

```
sigma.on("doubleClickStage", (e) => {
  e.preventSigmaDefault();
});
sigma.on("doubleClickNode", (e) => {
  e.preventSigmaDefault();
});
sigma.on("doubleClickEdge", (e) => {
  e.preventSigmaDefault();
});
```
