### ISSUE TITLE
Pass both border and node color as a parameter

### ISSUE THREAD

**Issue by tankBug** [jacomyal/sigma.js#1276]
**Problem:** 

The node border has a color parameter, but the node center doesn't. Only a hardcoded option in the frag shader, which is white by default.  I would like to have the option to pass both node color and border color parameter to it.

Attempted workaround by me:

I have no experience with webgl programming, which makes it quite difficult for me to change how this works. I've read up a bit on how the parameters is passed in an array and how you define the location for each parameter for the shaders to extract them, and if I started from scratch with a simple program, it would be ok, but all of this appears to handled inside sigma.js ("a_color") and I don't want to mess with the source. The shaders seem easy enough to customize, but I don't know how to override the node file to accommodate for the extra border color parameter passed to the vertex shader. 

**Suggested solution:** 

Add the possibility to pass both node color and node border color.

**Comment by yren** [comment]
yeah, I also need this feature.

**Comment by Yomguithereal** [comment]
@yren this article was for the v1 version of sigma and is not relevant anymore. However, if you feel adventurous you will find some sigma v2 renderers here: https://github.com/Yomguithereal/sigma-experiments/tree/master/renderers with some supporting borders and even three dots for nodes. The border relative sizes must be constant but the color can vary per node. Check the example here for usage info: https://github.com/Yomguithereal/sigma-experiments/blob/master/renderers/ftest/ftest.ts

**Comment by yren** [comment]
ok, thanks
