### ISSUE TITLE
Add geographic layout

### ISSUE THREAD

**Issue by reyman** [jacomyal/sigma.js#13]
Use the X,Y coordinate attribute of node to project graph into openlayer, or other geographic vizualisation library

**Comment by doganyazar** [comment]
Hello @Yomguithereal, I am trying to understand what you mean here. The question is about fixing graph nodes on specific geographic points on openlayers (or any other map) so we need a way to override layout algorithms and set the viewport coordinates. So how do we do that in afterRender hook? Is it not already to late doing it when the render is complete? 
Is there a way to set the nodes fixed for this use case? I have tried "graphology-layout-forceatlas2" and set fixed: true param but that did not seem to do the trick either.

**Comment by sim51** [comment]
FYI, I created some times ago an example of this : https://codesandbox.io/s/priceless-wildflower-lepn9?file=/index.ts

It's not finalized, but it works and it's a good start

**Comment by doganyazar** [comment]
Hi @sim51 ,
Thank you very much for the example. It seems to work indeed but I cannot figure out what you did differently than mine. My approach is:
* Calculate the XY coordinates of the graph nodes using their latitude and longitude and set these coordinates on "x" and "y" attributes on the graph nodes. (In your example it is latlngToGraph() function)
* render the graph

I confirm that these values are calculated correctly but still sigma draws them further apart from each other using some layout algorithm. I noticed that in older version (sigma v1) there was an "autoRescale" [flag](https://github.com/jacomyal/sigma.js/issues/548) to disable this behaviour but could not find a related param for the current version. 

I would appreciate any pointers
