### ISSUE TITLE
Cleanup quadtree space

### ISSUE THREAD

**Issue by Yomguithereal** [jacomyal/sigma.js#1310]
Currently, the quadtree indexes the `framedGraph` space, normalizing the sizes by the container width. This works but is conceptually weird and might cause issues with screens having a vertical aspect ratio.

We could use the nullCamera `viewport` space to index but there are two issues with this:

1. Handling rotations
2. We would be wasting some part of the x or y dimension (we already are actually), since we rescale the graph aspect ratio wrt viewport aspect ratio.

**Comment by jacomyal** [comment]
Once #1382 is dealt with, this issue will be solved.
