### ISSUE TITLE
Concerns regarding node hitbox and item collision genericization

### ISSUE THREAD

**Issue by Yomguithereal** [jacomyal/sigma.js#1312]
The idea was to add a way to specify alongside a webgl program a way to:

1. declare the hitbox (that must be a rectangle) for a rendered node (the default being a square inscribing the node circle, basically)
2. declare a way to check for collision (typically in viewport coordinates, against mouse position)

There are some issues there:

1. the quadtree has no method to take an arbitrary rectangle to index (internally it can, it is more of an API problem) but we still have an issue about the sizes, wrt the `framedGraph` space. And the fact that this space has some blank space on the outskirts of the largest dimension (see #1310).
2. regarding collisions, if we take the node case, we need the viewport positions, and the camera-scaled size. The fact is we might need arbitrary supplementary data from NodeDisplayData here to make a decision and maybe scale some other sizes (edge thickness etc.)

**Comment by jacomyal** [comment]
Related to #1371

**Comment by jacomyal** [comment]
#1382 could completely solve this issue definitely.

**Comment by jacomyal** [comment]
I close this as we have a working version of picking in the `v3` branch.
