### ISSUE TITLE
set click event for enable & disable label

### ISSUE THREAD

**Issue by mohammad-hormati** [jacomyal/sigma.js#1314]
hi.
i'm use react sigma v2 and i set a event for click each node but i don't know how to set setting for enable and disable label.
can anyone help me ??
thanks

**Comment by sim51** [comment]
what do you mean by `enable and disable label` ?

**Comment by mohammad-hormati** [comment]
i mean that i want set click event for display label instead of hover event

**Comment by sim51** [comment]
When you hover a node, it has the status `highlighted` which display the node and its label inside a "box".
You can highlight any node on the graph, just by settings it's graph attribut `highlighted` to `true` : 

`sigma.getGraph().setNodeAttribute(id, "highlighted", true);`

**Comment by mohammad-hormati** [comment]
it not worked.
i have enter node event like this : 

      enterNode({ node }) {
        sigma.setSetting('hoverRenderer', (context, data, settings) =>
          drawLabel(context, { ...sigma.getNodeDisplayData(data.key), ...data }, settings)
        );
      },

and i want set click node event like this : 

   clickNode({ node }) {
        graph.setNodeAttribute(node, 'highlighted', true);
      },

but i don't know how to access to label for showing it

**Comment by sim51** [comment]
This example should put you on the good xay : https://codesandbox.io/s/react-sigma-highlighted-61yf1u?file=/src/App.tsx
