### ISSUE TITLE
Are there docs for sigma.js?

### ISSUE THREAD

**Issue by TGOlson** [jacomyal/sigma.js#1324]
Scanning the website and github, all I see are examples. But it's kind of hard to know where to start from just examples, are there any pages that document available methods to call, interactions w/ graphology, etc?

**Comment by youyinnn** [comment]
Yeah, me too. I feel so bad that there are no API docs for this 10k stars library. It's confusing me.

**Comment by TGOlson** [comment]
By the way, this library is super powerful and thanks to everyone for all the hard work! I've just found it to be slightly confusing digging around examples and code to wire things together, instead of docs. Thanks : )

**Comment by jacomyal** [comment]
For the record, we have difficulties shipping that damn v3.0.0 version, but it will come with TSDoc and a Docusaurus-built documentation website (it's already done, we just need to fix some other things before releasing v3).

**Comment by jacomyal** [comment]
The documentation is out! I just updated the website to the new v3 version, and the documentation is available here: https://www.sigmajs.org/docs/

Don't hesitate to report issues or the ask for new pages. Now that it's out, it'll be way easier to improve it and add new topics.
