### ISSUE TITLE
Label size proportional

### ISSUE THREAD

**Issue by KostaPag** [jacomyal/sigma.js#1334]
Hello,
is there a possibility in v2 to make the labels size proportional, like the first Sigma version ?
Has anyone an idea ?

**Comment by Yomguithereal** [comment]
@KostaPag you can do it by defining a custom label renderer for instance. Here is how `ipysigma` does it for instance: https://github.com/medialab/ipysigma/blob/master/src/custom-label.ts

**Comment by KostaPag** [comment]
It worked, thanks

**Comment by StockerGaming** [comment]
Hm, when using this custom renderer the size of the labels are still fixed, what could be the issue here?

**Comment by StockerGaming** [comment]
@KostaPag Did the exact code provided in the link work for you? Unfortunately, it didn't work for me
