### ISSUE TITLE
Custom shape

### ISSUE THREAD

**Issue by mohammad-hormati** [jacomyal/sigma.js#1335]
hi,
i am using react sigma and i want change shape of node from circle to square and display image for each node.
how can i do this ?

**Comment by Yomguithereal** [comment]
For instance [`ipysigma`](https://github.com/medialab/ipysigma) does it by using a pictogram webgl program used to render svg icons as nodes that can be found [here](https://github.com/Yomguithereal/sigma-experiments/tree/master/renderers).

**Comment by mohammad-hormati** [comment]
there is a type property for each node
but when change it to square or diamond graph not work
i can show image by image property but it is circle 
I want it to be square

**Comment by sim51** [comment]
There is no square node program in native sigma.js

So you need to develop a new node program (with its shader) like this one https://github.com/jacomyal/sigma.js/blob/main/src/rendering/webgl/programs/node.ts , but for square

**Comment by mohammad-hormati** [comment]
thanks so much
