### ISSUE TITLE
Is there a way to render image sprites?

### ISSUE THREAD

**Issue by TGOlson** [jacomyal/sigma.js#1336]
Hey all. First, thanks for all the hard work to make a great library. I actually am building a pretty large graph, and tried a bunch of different graphing libraries, and none were as fast as smooth as sigma. Super cool stuff!

My question, could anyone share a pointer on how I would go about rendering [image sprites](https://www.w3schools.com/css/css_image_sprites.asp)? For example, I know I can use `getNodeImageProgram()` to render an image for my node backgrounds. However, I have a very large graph (5k+ nodes), each with a distinct background image. So what I'd like to do is compile all these images in a large sprite file (or two, or three), and use offsets to reference the sub-portion of the image I want (thereby saving thousands of network requests). My problem is I'm not sure how to do that in webgl land. 

I was actually able to follow a tutorial on how to render multiple images at different offsets using webgl (https://webglfundamentals.org/webgl/lessons/webgl-2d-drawimage.html), but I got stumped when trying to integrate it into the Sigma node program framework. I suspect it's not a huge change from the current node image program, but I'm not much of a webgl expert!

Thanks in advance for any help.

**Comment by jacomyal** [comment]
Actually, the current node image program deals with images with its own sprite (it's named a "texture atlas" in WebGL but it's basically the same thing).

I guess you could rewrite the image program where you give it directly a sprite, and each node would carry it's image coordinates. It would actually be easier to write than the current program, since it has to handle each image load, and the update of the texture atlas.

**Comment by TGOlson** [comment]
Hey! Thanks for the response : )

I was actually able to get the sprite rendering working (a few months ago, I forgot I still had this question open). It worked basically as you said -- for the most part I just ripped out a lot of the extra image loading logic, and iirc tracked the image coords a little differently. But overall a success! Thanks
