### ISSUE TITLE
Set number of iteration for ForceAtlas2

### ISSUE THREAD

**Issue by CGenie** [jacomyal/sigma.js#1337]
Hello,

Before the big refactor into typescript we had this

https://github.com/jacomyal/sigma.js/tree/v1.2.1/plugins/sigma.layout.forceAtlas2

In particular there were 2 parameters: `startingIterations` and `iterationsPerRender`. Now when I look at the docs:

https://graphology.github.io/standard-library/layout-forceatlas2.html

I see only `iteration` . It seems to be available only for the synchronous layout. Is it possible to add this to the webworker as well?

**Comment by sim51** [comment]
Please, open this issue on the graphology repository, it's not a sigma feature.
