### ISSUE TITLE
Cannot load images from url

### ISSUE THREAD

**Issue by hk-centaari** [jacomyal/sigma.js#1340]
The image attribute is working fine with the local image path but not with the url.

**Comment by Yomguithereal** [comment]
Hello @hk-centaari, without an image url example of your issue I cannot answer for sure but I guess you are having a CORS issue here. Indeed to be able to read an image using canvas and transform it into a texture you nees to have CORS access to said image, which only the server hosting the image can enable, in which case sigma cannot do anything about it. You might want to use a proxy in this case or host the images yourself.

**Comment by hk-centaari** [comment]
Yeah looks like CORS issue. Thanks
