### ISSUE TITLE
Is it possible to integrate custom dash components in sigma js 

### ISSUE THREAD

**Issue by vermyas** [jacomyal/sigma.js#1344]
## Guidelines

Please note that GitHub issues are only meant for bug reports/feature requests.
If you have questions on how to use Sigma.js, please ask on [StackOverflow](https://stackoverflow.com/questions/tagged/sigma.js) instead of creating an issue here.

## Feature request template

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Yomguithereal** [comment]
If we are speaking about plotly dash component, which is not clear at all: I don't see why not. If those custom component accept custom JavaScript you can probably do it yes.
