### ISSUE TITLE
More Documentation Please

### ISSUE THREAD

**Issue by rahmannurhidayat022** [jacomyal/sigma.js#1346]
Thank you for making this open source, very helpful. I hope It would be more helpful if there was more complete documentation.

**Comment by jacomyal** [comment]
I just pushed a first documentation (based on Docusaurus) for the V3 on the `v3` branch. It will be deployed as soon as we release the v3 (hopefully later this year).

I close this issue and the related ones, to keep track on the [v3 milestone](https://github.com/jacomyal/sigma.js/milestone/9).
