### ISSUE TITLE
Please upload some official documentation for Sigma.js

### ISSUE THREAD

**Issue by wthrajat** [jacomyal/sigma.js#1351]
Hi.
Please upload some official documentation for Sigma.js
I am aware of the code-sandbox examples present in www.sigmajs.org but it'd be nice if the library could have some official docs which could mention all the methods and functionality of the library.

For example we have the official docs of the popular D3.js [here](https://github.com/d3/d3/blob/main/API.md)

Thanks a lot :))

**Comment by anpari** [comment]
You can find some documentation [here](https://www.sigmajs.org/docs/classes/sigma.default.html). It helped me a lot, but there is still a bit to be desired when comparing to other frameworks.

**Comment by jacomyal** [comment]
When the v3 will be released (hopefully later this year), both a new Docusaurus-based documentation and the existing TypeDoc will be accessible on the website (it's already implemented). I close this issue, to better keep track on what's left to do.
