### ISSUE TITLE
How to use animateNodes in pure javascript

### ISSUE THREAD

**Issue by vinaysb** [jacomyal/sigma.js#1358]
Hello, is it possible to import animateNodes function in pure javascript?

I have tried using `Sigma.animateNodes`, but I keep running into the error, `Sigma.animateNodes is not a function`.

**Comment by sim51** [comment]
`animateNodes` is pure function, it's not a function that is part of the Sigma object.
SO you just have to import it : `import { animateNodes } from "sigma/utils/animate";`

You can take a look at this code : https://github.com/jacomyal/sigma.js/blob/main/examples/layouts/index.ts#L95

**Comment by vinaysb** [comment]
I am unable to import that in a pure javascript file. I am not using a framework like react, but just javascript. Is is possible to import `animateNodes` using ES6 syntax?

**Comment by sim51** [comment]
`import { animateNodes } from "sigma/utils/animate";` is an ES6 syntax, so I don't understand your question.
Please provide some code (or better a code sandbox) to see what you have tried so far.

**Comment by vinaysb** [comment]
Here is a code sandbox link for the issue I am having. https://codesandbox.io/s/black-pond-4qrdfx

I tried the ES6 import method but I get the error `Uncaught TypeError: Failed to resolve module specifier "sigma/utils/animate". Relative references must start with either "/", "./", or "../".
` 

Adding a `"./"` also does not fix the error. I get CORS error on codesandbox but on VSCode I just get 404 error.  

Furthermore I have tried using the function as is, and using `Sigma.utils.animate.animateNodes` & `Sigma.utils.animateNodes`

**Comment by sim51** [comment]
Where did you find the sigma.js file ?
Why are you not using npm for dependencies in your example ? (same question for graphology)

**Comment by vinaysb** [comment]
What do you mean where did I find it, its literally in the releases of this github repo. 

And I have been saying that this is for pure javascript and not node or react.

**Comment by sim51** [comment]
This is a **pure JS** example which use **npm** for dependencies, and that feets your needs : https://codesandbox.io/s/competent-leaf-6triuf

**Comment by AndreaCirina** [comment]
Hi @vinaysb, did you solve the problem? I'm trying too but I'm not having success

**Comment by vinaysb** [comment]
Hey @AndreaCirina No I did not, I ended up switching to d3.js due to better documentation. 

Sadly even the "**pure js**" example presented here is still using a package.json file which my usecase (in python django) would not work.

**Comment by AndreaCirina** [comment]
thanks for the reply, i am also creating a web application with python, in case i will change too. Thanks again and have a nice evening!
