### ISSUE TITLE
Typescript definition for node/edge data

### ISSUE THREAD

**Issue by sim51** [jacomyal/sigma.js#1359]
## Program process function 

Sigma allows developer to create node's program, but the definition of the `NodeDisplayData` can't be extended.

For example, if I want to write a program that do a circle and a border with their color and size managed by the data, it's not possible. I can't add the attributs `borderSize` and `borderColor` for example.

For now, TS allows to extend the `NodeDisplayData` in   program's process function.

```
export default class NodeProgramBorder extends AbstractNodeProgram {
  ...
  process(
      data: NodeDisplayData & { borderSize?: number; borderColor?: string },
      hidden: boolean,
      offset: number
    ): void {
   ...
  }
...
}
```

TS compile, even if in pure object conception, it should not. 

## Propagation of the graph type

The graph types are not propagated deeply in the code base of sigma, like in the node/edge reducer for example

**Comment by jacomyal** [comment]
@sim51 has recently worked on that for v3, there is a branch [`v3-graph-typing`](https://github.com/jacomyal/sigma.js/commits/v3-graph-typing) with an implementation, that should be shipped with next v3 alpha or beta release.
