### ISSUE TITLE
viewRectangle y2 same as y1 which makes no sence for abstact rectangle

### ISSUE THREAD

**Issue by DenchPokepon** [jacomyal/sigma.js#1364]
- Sigma.js version : 3.0.0-alpha3

https://github.com/jacomyal/sigma.js/blob/7b3a5ead355f7c54449002e6909a9af2eecae6db/src/sigma.ts#L1627-L1649

y1 and y2 data in the abstarct rectangle of a node are basically the same, is it intended? If yes, what's the difference between y1 and y2?

### Expected behavior

I think it makes more sense to define y2 as `y: 0 - marginY + this.height`
And then height becomes `p1.y - h.y`

### Actual behavior

y2 = y1 which makes no sence

**Comment by Yomguithereal** [comment]
@DenchPokepon I don't remember the specifics but the rectangle does not have to be axis-aligned, typically when rotating the camera, hence this specification of the rectangle.
