### ISSUE TITLE
Codesandbox Example for Custom Render Broken

### ISSUE THREAD

**Issue by ericdong79** [jacomyal/sigma.js#1367]
The example for custom rendering failed: https://codesandbox.io/s/github/jacomyal/sigma.js/tree/main/examples/custom-rendering

**Sigma.js version:** latest(3.0)
**Graphology version:** 0.2.4
**Operating System:** CodeSandbox
**Web browser:** Edge 

### Steps to reproduce

Open the custom node example in [sandbox](https://codesandbox.io/s/github/jacomyal/sigma.js/tree/main/examples/custom-rendering) it throws `this.bind is not a function`

### Expected behavior

Works without error

### Actual behavior

Page cannot render

**Comment by luka-papez** [comment]
Same things happens for me with:
* Sigma.js version: latest(3.0)
* Graphology version: 0.2.4
* Operating System: CodeSandbox
* Web browser: Firefox (116.0.3)

However, I was able to workaround the error by pinning the dependencies in Sandbox's `package.json` to the following versions:
```json
  "dependencies": {
    "graphology": "0.23.0",
    "graphology-layout-force": "0.2.2",
    "sigma": "2.4.0"
  }
```

My best bet is that there is some incompatibility between `sigma` 3.0 and previous versions like `2.4.0`.

Thanks for this great project btw!

**Comment by jacomyal** [comment]
I updated the website, so now the link opens the new [Storybook](https://www.sigmajs.org/storybook/?path=/story/custom-rendering--story) local link, which works. The Codesandbox were breaking too often, I removed all links. Thanks for the report!
