### ISSUE TITLE
Rotating the view with a mouse

### ISSUE THREAD

**Issue by bblanchon** [jacomyal/sigma.js#1374]
Hi,

Thanks a lot for this incredible library!

I noticed I could rotate the view with a touch screen.
Is there any way to do so with a mouse?

Best regards,
Benoit

**Comment by wthrajat** [comment]
Following this

**Comment by sim51** [comment]
I created a sandbox to illustrate how to do that : https://codesandbox.io/s/sigmajs-issue-1374-8qc4gs

To rotate the graph, you only need to set the state of the camera : `renderer.getCamera().setState({ angle: deltaAngle });`
The rest of the code is pretty much which gesture you w&nt to use and how to listen it.

Hope it helps.

**Comment by bblanchon** [comment]
Excellent! Thanks a lot, Benoît.
