### ISSUE TITLE
Scaling Issue when Exporting Chart with a higher Resolution

### ISSUE THREAD

**Issue by Gykonik** [jacomyal/sigma.js#1375]
#### Summary
When attempting to export a Sigma.js chart at a higher resolution than the original, the scaling doesn't work as expected. Specifically, parts of the chart are cut off at the edges when it is moved around. For instance, when the chart is moved to the top-right corner, the exported image misses a small section and I couldn't figure out why.

My exporter is based on [saveAsPNG](https://github.com/jacomyal/sigma.js/blob/main/examples/png-snapshot/saveAsPNG.ts) modified only by an additional `scale` parameter.

#### Steps to Reproduce
Go to the [codesandbox example](https://codesandbox.io/s/black-smoke-q2lf7x?file=/index.ts)
1. Create a Sigma.js chart instance.
2. Zoom out a bit and move the chart to the bottom left.
3. Click `Save as PNG` to export the chart.

#### Expected Results
The exported PNG should be a scaled-up version of the current view, without any parts being cut off.
The expected PNG should look as follows: (only 2x the resolution, thus maybe a bit smaller in font size or something)
![image](https://github.com/jacomyal/sigma.js/assets/17333876/a5a6ac3b-88a0-4d28-a235-4791e9848441)

#### Actual Results
The exported PNG has its edges cut off, not fully capturing the current chart view.
The PNG that actually gets exported is the following. As you can clearly see, the edges are cut-off in a strange way:
![graph (9)](https://github.com/jacomyal/sigma.js/assets/17333876/3b4e2b21-e1fa-4f51-8b23-69c646f7c62e)

#### Additional Context
I also tried to experiment with the scale factors, doing things like scaling the `cameraState` and stuff, but nothing worked.

#### Environment
- Sigma.js version: 3.0.0-alpha-3
- Browser: doesn't matter
- Operating system: Windows 11

I would love to get guidance on how to resolve this issue. I'm not sure whether I'm missing anything, or the rendering logic is weird in this case. Thank you!

**Comment by boogheta** [comment]
I think the problem comes from the stagePadding setting that is set to 30 by default within Sigma
The problem seems to be fixed when setting it to 0 line 56
```
const renderer = new Sigma(graph, container, {
  renderEdgeLabels: true,
  allowInvalidContainer: true,
  stagePadding: 0
});
```

**Comment by Gykonik** [comment]
Thanks for the quick reply, that definitely is the issue! However, when setting `stagePadding` to zero, the nodes overflow to some amount (looks like the amount is roughly the node thickness). You can also view this in the updated codesandbox.

I also thought about whether it would be sufficient to just set `stagePadding: 0` for the "high-resolution" graph as this one is the one that we're going to export, but that didn't work either.

**Comment by boogheta** [comment]
Indeed that makes sense, this is the role of the stagePadding as I understand it.

Well actually then the solution is to adjust the stagePadding of the scaled image to build: within saveAsPNG.ts, when you instantiate the tmpRenderer, you should adjust the settings to also scale the stagePadding like this for instance:
```
  const scaledSettings = renderer.getSettings()
  scaledSettings.stagePadding = scaledSettings.stagePadding * scale;

  // Instantiate sigma:
  const tmpRenderer = new Sigma(
    renderer.getGraph(),
    tmpRoot,
    scaledSettings
  );
```

**Comment by boogheta** [comment]
btw, if you intend to play also with diverse node/labels/edges sizes settings, you should also adjust those with scale for the tmpRenderer's settings, I do this for instance here with a settings generator function taking a scale as input:
https://github.com/medialab/communautes-libres-graph/blob/main/index.ts#L108-L143

**Comment by Gykonik** [comment]
God, that took me ages... I use `zoomToSizeRatioFunction` which made it way harder for me to figure out what to scale and what not. But now I finally got it working. Thanks for your support!

If anyone's curious, here's my solution:

```
const temporaryRenderer: Sigma = new Sigma(graph.getGraph(), temporaryRoot, {
    ...originalSettings,
    zoomToSizeRatioFunction: (ratio: number) => originalSettings.zoomToSizeRatioFunction(ratio) / scale,
    labelSize: originalSettings.labelSize * scale,
    edgeLabelSize: originalSettings.edgeLabelSize * scale,
    labelRenderedSizeThreshold: originalSettings.labelRenderedSizeThreshold * scale,
    labelGridCellSize: originalSettings.labelGridCellSize * scale,
    stagePadding: originalSettings.stagePadding * scale,
  });
```
