### ISSUE TITLE
Html in hover and timeout

### ISSUE THREAD

**Issue by Manubi** [jacomyal/sigma.js#1376]
Hi everyone,
I have two questions. 

- Is it possible to render a link in my drawHover function and if how?
- If it's possible how can i add an eventlistener that keeps displaying the hover until the cursor leaves the drawed hover?

![CleanShot 2023-09-11 at 09 59 47](https://github.com/jacomyal/sigma.js/assets/20935138/96d2f038-b2ae-4bca-ab35-310224d7a199)
I've seen the https://github.com/jacomyal/sigma.js/blob/7b3a5ead355f7c54449002e6909a9af2eecae6db/src/rendering/canvas/label.ts
and https://github.com/jacomyal/sigma.js/blob/7b3a5ead355f7c54449002e6909a9af2eecae6db/src/rendering/canvas/hover.ts but can't really make it work. 

Thanks!

**Comment by jacomyal** [comment]
Sigma only supports drawing labels and hovered nodes in canvas, so there are no way to render HTML. If you want to display more data, in a user-friendly way, I'd advise you to draw node-related information in a modal or a side panel, as we do [in Retina](https://ouestware.gitlab.io/retina/beta/#/graph/?url=https%3A%2F%2Fouestware.gitlab.io%2Fretina%2Fbeta%2Fdataset.gexf&c=c&s=s&n=data%20mining&sa[]=s&sa[]=r&ca[]=t&ca[]=c&st[]=t&st[]=c&ds=1&dc=1) for instance.

About the timeout issue, sigma draws the hovered node as long as its hovered, and I cannot think of a way to tune that at the moment.

And unfortunately, none of these two features can be easily done in sigma yet, and they would add too much debt right now to be considered.
