### ISSUE TITLE
nodeReducer optimization

### ISSUE THREAD

**Issue by TGOlson** [jacomyal/sigma.js#1388]
Hey all -- first I just want to say thanks for this amazing library. I'm just about wrapping up a super fun project that would definitely not be possible without the amazing work you all have done.

Quick question/comment. I'm taking a look at some later stage optimizations for my project, and noticing that my `nodeReducer` is taking up a decent amount of scripting time each render cycle. I dug in deeper and realized a lot of the time on each reducer call was due to copying the data passed into the reducer.

This is something you show to do in your [reducer examples](https://github.com/jacomyal/sigma.js/blob/7b3a5ead355f7c54449002e6909a9af2eecae6db/examples/use-reducers/index.ts#L117-L118). (eg. `const res: Partial<NodeDisplayData> = { ...data };`)

However, I noticed you already make a copy of the attributes before passing them to the reducer: https://github.com/jacomyal/sigma.js/blob/7b3a5ead355f7c54449002e6909a9af2eecae6db/src/sigma.ts#L776-L779

So, this leads me to two suggestions:

1. Could you perhaps update the documentation to show that reducers receive a copy of the data and are safe to mutate the object? I think this is a completely fine pattern (eg. I believe redux also does this), it would just be nice to know that upfront.
2. I think using a spread operator may be a good bit more efficient than `Object.assign`. I did some quick jsperf tests, and at least for my data structure it was up to 2x faster.

**Comment by jacomyal** [comment]
1. Good point. I actually just realized that the first thing I do in most my reducers is cloning... I will document this in the new v3's doc.
2. Interesting - are you sure it's faster on all most used browsers? If we're sure it's always faster, we can update it.

**Comment by TGOlson** [comment]
Sweet! re: #2, I am pretty sure it's faster in most cases (it seems like in general just avoiding the overhead of a function call is pretty performant), but tbh I'm seeing some conflicting info about exactly how much of a performance improvement it is in a real world scenario.

It sounds like node/some browsers do a lot of aggressive caching with the spread operator which might impact the results of something like a jsperf test in an unrealistic way.

Anyways, I suspect it would make things faster but don't feel quite informed enough to push super hard either way! For v3 you could even provide an option while creating the reducer to skip cloning if people don't want/need it. 

But either way I'm happy with it how it all worked out for me and will leave you all to decide what works best for Sigma : )
