### ISSUE TITLE
Export Graph with `ImageRenderer`

### ISSUE THREAD

**Issue by Gykonik** [jacomyal/sigma.js#1389]
Hey there, I am utilizing the [png-snapshot](https://github.com/jacomyal/sigma.js/tree/main/examples/png-snapshot) utility to export SigmaJS graphs. It functions well for standard nodes but fails to include images from nodes rendered with ImageRenderer during export.

The issue persists despite creating a new instance of the ImageRenderer prior to export to prevent interference with the existing renderer. Any insights or solutions would be greatly appreciated.
 Thanks in advance!

**Comment by jacomyal** [comment]
Hum, I would use the same instance actually, because it already has the texture generated and loaded, so you should have the images displayed properly. Can you try and validate that it still doesn't work?

**Comment by Gykonik** [comment]
I tried it by just inferring the graph and settings from the existing graph like this:
`const temporaryRenderer: Sigma = new Sigma(graph.getGraph(), temporaryRoot, graph.getSettings());`

However it doesn't change anything - the graph gets exported as it is (as expected), but the images are missing.
