### ISSUE TITLE
Sample program in sigmajs.org website not working

### ISSUE THREAD

**Issue by mk48** [jacomyal/sigma.js#1392]
### Steps to reproduce
Go to https://www.sigmajs.org/
scroll to Customize section
click "Launch live codesandbox"
https://codesandbox.io/s/github/jacomyal/sigma.js/tree/main/examples/custom-rendering
![image](https://github.com/jacomyal/sigma.js/assets/3082469/b62a83d1-7354-47da-898f-2fa1c6afcecc)

### Expected behavior
It should run

### Actual behavior
showing error
![image](https://github.com/jacomyal/sigma.js/assets/3082469/0d70d1e1-0508-4c74-b3ad-4a8b5df0a64c)

**Comment by mk48** [comment]
Just keep the bug alive :)

**Comment by mk48** [comment]
Just keep the bug alive :)

**Comment by mk48** [comment]
Just keep the bug alive :)

**Comment by jacomyal** [comment]
I updated the website, so now the link opens the new [Storybook](https://www.sigmajs.org/storybook/?path=/story/custom-rendering--story) local link, which works. The Codesandbox were breaking too often, I removed all links. Thanks for the report!

**Comment by mk48** [comment]
Thanks for fixing the link 🌷
