### ISSUE TITLE
ALways show edge label

### ISSUE THREAD

**Issue by ss2342** [jacomyal/sigma.js#1395]
Right now, when I set `renderEdgeLabel` to be true, I see my edge labels only when i hover over a node. How do I modify this logic such that the edge labels are always visible?

**Comment by Gykonik** [comment]
That's the desired behavior as specified in `edgeLabelsToDisplayFromNodes` [here](https://github.com/jacomyal/sigma.js/blob/7b3a5ead355f7c54449002e6909a9af2eecae6db/src/core/labels.ts#L128). However, if you want to enforce the edge labels to always be visible, you can use the `forceLabel` key. Something like the following should work:

```
graph.forEachEdge((edgeKey: string): void => {
    graph.setEdgeAttribute(edgeKey, "forceLabel", true);
});```

(Alternatively, you can also directly set the attribute `forceLabel` inside your data source, if that's an option).
