### ISSUE TITLE
Multi-monitor Setup cause Hitbox Misdetection

### ISSUE THREAD

**Issue by cardin** [jacomyal/sigma.js#1398]
- Sigma.js version : 3.0.0-beta4
- Graphology version : 0.23.0
- Operating system: Windows 10
- Web browser: Chrome 120.0.6099.200, Edge 120.0.2210.121

- **Steps to reproduce**
   - Have a dual monitor setup (e.g. left-right configuration)
   - Run the demo on the Secondary Display
- Expected behavior
   - Hovering over the node should highlight the node
- Actual behavior
   - Hovering ~1 inch to the right and bottom of the node will highlight the node
  
https://github.com/jacomyal/sigma.js/assets/553816/89ca108f-dd77-4f54-aed9-f2b450f419fe

- Code Sandbox reproduction

https://codesandbox.io/s/github/jacomyal/sigma.js/tree/sigma@3.0.0-beta.4/packages/examples/use-reducers

**Comment by jacomyal** [comment]
Hello @cardin,

Thanks a lot for your report. I can't reproduce your issue. I wonder if the cause wasn't #1399, which has been solved for version [3.0.0-beta.5](https://www.npmjs.com/package/sigma/v/3.0.0-beta.5). Is it still occurring for you?

**Comment by cardin** [comment]
Hi Jacomyal, I'm not able to reproduce the issue with 3.0.0-beta.5, it should be fixed now. Thank you!
