### ISSUE TITLE
Incorrect Hover Behavior on Nodes and a Potential Solution

### ISSUE THREAD

**Issue by foxton9** [jacomyal/sigma.js#1399]
- Sigma.js version : 3.0.0-beta.4
- Graphology version : 0.23.0
- Operating system: Windows 10
- Web browser: Firefox 121.0.1
 &nbsp; 
- **Steps to reproduce**
  - Run the [Code Sandbox example](https://codesandbox.io/s/github/jacomyal/sigma.js/tree/sigma@3.0.0-beta.4/packages/examples/use-reducers)
  - Move the cursor towards any hoverable node, and then move around it.
  - Observe the point at which the node becomes hovered.
 &nbsp; 
- Expected behavior
The node should become hovered as the cursor enters the node.
- Actual behavior
Only when the cusor positioned at the buttom-right side of the node with some offset, the intended node will become hovered.

https://github.com/jacomyal/sigma.js/issues/1398 reported similar issues.
 &nbsp; 
- Possible cause and solution
 
The issue might be due to DPI scaling not being accounted for in the coordinate calculation in the `getNodeAtPosition` function.

https://github.com/jacomyal/sigma.js/blob/a4a68930be9319e032a17af157c18393b01f1ec5/packages/sigma/src/sigma.ts#L450-L451

Updating the coordinate calculation to consider the device's pixel ratio could solve this this issue, however, it's worth considering that there may be other potential problems that have been missed.

The code change could be as follows:
```JavaScript
const { x, y } = position;
const canvasX = x * this.pixelRatio
const canvasY = y * this.pixelRatio

const color = getPixelColor(this.webGLContexts.nodes, this.frameBuffers.nodes, canvasX, canvasY, this.pickingDownSizingRatio);
```
 &nbsp; 

Pixel ratio should also be the considered when binding  `pickingTexture`.

https://github.com/jacomyal/sigma.js/blob/a4a68930be9319e032a17af157c18393b01f1ec5/packages/sigma/src/sigma.ts#L407-L408

by multiplying the ratio

```JavaScript
this.width * this.pixelRatio / this.pickingDownSizingRatio,
this.height * this.pixelRatio / this.pickingDownSizingRatio,
```

This method appears to resolve an error that was reported in the browser console.
> WebGL warning: drawArraysInstanced: Drawing to a destination rect smaller than the viewport rect. (This warning will only be given once)

**Comment by temuera** [comment]
+1

**Comment by jacomyal** [comment]
Thanks a lot for this very detailed report. I just pushed the fix (based on your inquiry, thanks again), and I hope to release a new beta tomorrow, with fixes on the other issues you linked.
