### ISSUE TITLE
Export graph to sigma.js template using gephi toolkit?

### ISSUE THREAD

**Issue by baau** [jacomyal/sigma.js#140]
Hi,
I am new to gephi and sigma.js, I used Gephi toolkit to generate a community detection graph and am having problem in exporting it as Sigma.js template. Could anyone please provide me with an example or the procedure?

**Comment by kercos** [comment]
@baau could you please explained how you managed to export a sigmajs file programmatically? (without the GUI). Thanks.

**Comment by ishai-smadja** [comment]
@kercos 
@baau 
I know I'm late for the party, but if anybody has a walkthrough as to how to do it I'll be happy to learn!
