### ISSUE TITLE
Build fails with "Missing './rendering/node-labels' specifier" after updating to 3.0.0-beta.8

### ISSUE THREAD

**Issue by someaka** [jacomyal/sigma.js#1406]
## Description

After updating the `sigma` package from version `3.0.0-beta.6` to `3.0.0-beta.8`, the build process fails with the following error:

**Error: [commonjs--resolver] Missing "./rendering/node-labels" specifier in "sigma" package**

This issue occurs during the build step using Vite (`vite build`). Reverting back to version `3.0.0-beta.6` resolves the issue, suggesting that the problem is specific to the `3.0.0-beta.8` release.

## Steps to Reproduce

1. Update the `sigma` package from version `3.0.0-beta.6` to `3.0.0-beta.8` in a project using Vite for building.
2. Run the build command (`vite build`).
3. Observe the build failure with the mentioned error.

## Expected Behavior

The build process should complete successfully without errors, as it does with version `3.0.0-beta.6`.

## Actual Behavior

The build process fails with an error related to a missing specifier in the `sigma` package.

## Environment

- Sigma version: 3.0.0-beta.8
- Vite version: 5.1.5
- Node.js version: v21.6.2
- Operating System: windows 11

## Additional Context

- This issue was not present in version `3.0.0-beta.6` of the `sigma` package.
- The project setup and configuration have not changed between updates, only the version of the `sigma` package.

Reverting to `3.0.0-beta.6` temporarily solves the problem, indicating that the issue might be related to changes introduced in `3.0.0-beta.8`.

Any assistance or guidance on resolving this issue would be greatly appreciated.

**Comment by jacomyal** [comment]
Hi @someaka,

We rewrote the whole build system recently, and reorganized the things exported from sigma.js.
Now, everything rendering related is exported from `sigma/rendering`. So you can now use:

```typescript
import { drawDiscNodeLabel, NodeLabelDrawingFunction } from "sigma/rendering";
```

Sorry for the mess, I'm finishing various remaining tasks for the v3 release, and it breaks too much things. It should stabilize in the coming days, hopefully. Also, I'll release the documentation online soon as well, and it will help with those kind of issues as well.

Thanks for the report !

**Comment by someaka** [comment]
Hi @jacomyal,

Just wanted to say thank you for the detailed explanation and solution! Really appreciate you taking the time to clarify the changes in sigma.js and provide guidance on updating the import statements.

Looking forward to the upcoming v3 release and improved documentation. Thanks again for your help!

**Comment by jacomyal** [comment]
Thanks, I appreciate that :)
