### ISSUE TITLE
 v3.0.0-beta.10: Package.json module (esm) export "./rendering" incomplete

### ISSUE THREAD

**Issue by josundt** [jacomyal/sigma.js#1408]
- Sigma.js version :  v3.0.0-beta.10
- Graphology version : 0.25.4

In v3.0.0-beta.10, I found various issues inthe package.json export fields.

For each of the export fields there are 3 conditional exports: `module`, `import` and `default` (fallback).

_Question: Not sure why there's a `module` (non-standard/custom)  export condition and a separate `import` (standard) export condition. It looks a bit to me as if the the non-standard one may be redundant - that they both are meant to handle ESM module import conditions?  (Ref. [NodeJS Documentation](https://nodejs.org/api/packages.html#conditional-exports))_

**Issues**

1. While the conditional `module` export field points to existing files (`.esm.js` files), the conditional `import` export field points to files not included in the package (`.cjs.mjs` files). These files, like f.ex. `./rendering/dist/sigma-rendering.cjs.mjs` do not exist in the package.

2. The `./rendering` export field:  

    - The conditional `default` export module (`./rendering/dist/sigma-rendering.cjs[.dev|.prod].js`) has the following **20** exports:   
    
        `AbstractEdgeProgram`, `AbstractNodeProgram`, `AbstractProgram`, `EdgeArrowHeadProgram`, `EdgeArrowProgram`, 
        `EdgeClampedProgram`, `EdgeProgram`, `EdgeRectangleProgram`, `NodePointProgram`, `NodeProgram`, `Program`,
        `drawDiscNodeHover`, `drawDiscNodeLabel`, `drawStraightEdgeLabel`, `loadFragmentShader`, `loadProgram`, `loadVertexShader`,
        `EdgeLineProgram`, `EdgeTriangleProgram`, `NodeCircleProgram`.
    
    - The corresponding conditional `module` export module (`./rendering/dist/sigma-rendering.esm.js`) only **3** exports:   
    
         `EdgeLineProgram`, `EdgeTriangleProgram`, `NodeCircleProgram`.
     
     I'm missing 17 exports in the esm.js file compared to the cjs[.dev|.prod].js files.
     For this reason I can currently not upgrade from 3.0.0-beta.6 to 3.0.0-beta.10.
     
     _PS! I have not checked if there are similar export differences between cjs/esm files in other export fields than "./render"._

3. TypeScript types should be listed under each package.json export field. If the commonjs and esm transpiled code has the same content/exports (which probably is desirable), you only need a single "types" reference per export field.

This is how I believe the export fields in package.json should have been:
```jsonc
{
  //...
  "exports": {
      ".": {
      "types": "./dist/sigma.cjs.d.ts"
      "import": "./dist/sigma.esm.js",
      "default": "./dist/sigma.cjs.js"
    },
    "./types": {
      "types": "./types/dist/sigma-types.cjs.d.ts"
      "import": "./types/dist/sigma-types.esm.js",
      "default": "./types/dist/sigma-types.cjs.js"
    },
    "./settings": {
      "types": "./settings/dist/sigma-settings.cjs.d.ts"
      "import": "./settings/dist/sigma-settings.esm.js",
      "default": "./settings/dist/sigma-settings.cjs.js"
    },
    "./rendering": {
      "types": "./rendering/dist/sigma-rendering.cjs.d.ts"
      "import": "./rendering/dist/sigma-rendering.esm.js",
      "default": "./rendering/dist/sigma-rendering.cjs.js"
    },
    "./utils": {
      "types": "./utils/dist/sigma-utils.d.ts"
      "import": "./utils/dist/sigma-utils.esm.js",
      "default": "./utils/dist/sigma-utils.cjs.js"
    },

  },
  //...
}
```

**Comment by jacomyal** [comment]
Hi,

Thanks a lot for that report. I reproduce this issue locally.

When we wanted to modernize how sigma is built, we looked at projects that have the features we want (monorepo with as less configuration and ad-hoc code as possible, types export, and multiple endpoints possible). We finally mimicked what [react-select](https://github.com/JedWatson/react-select) is doing, which is basically just using [Preconstruct](https://preconstruct.tools/).

It works very well, but I somehow screwed up the configuration apparently. I just pushed a new version that hopefully fixes this issue. I'll let you test and confirm that.

Thanks again for that report!

**Comment by josundt** [comment]
@jacomyal I can verify that it works now.  

I encourage you to add `types` (.d.ts file) to each of the export fields since this is recommended (like in my sample above).

When TypeScript is configured to use NodeNext/Node16 module resolution, the TS compiler uses package.json to resolve types for each of the export fields. [Read more](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing).

**Comment by jacomyal** [comment]
My problem here is that those `"exports"` entries are directly handled by Preconstruct, so that we don't have to. So, if I manually edit the `package.json` to add those `"types"` entries in the `"exports"` definition, and then I run `npx preconstruct fix`, they disappear. Which makes simply editing those entries manually not an option...

I'll investigate to see if there are some ways to make Preconstruct better handle those `"types"` fields.

**Comment by arreumb** [comment]
Is there **any** way to make the following code work again ? 

https://www.sigmajs.org/storybook/?path=/story/sigma-edge-curve--labels  

It seems that EdgeCurveProgram and EdgeCurveProgram are missing. 
I spent a lot of time searching for a solution  to have curved edges with curved labels but I didn't find any.
