### ISSUE TITLE
How do I do custom shapes?

### ISSUE THREAD

**Issue by ReyRodriguez** [jacomyal/sigma.js#1413]
Hi, I'm working on migrating a project that uses an old version of Sigma to v3?

in that project they have a plugin for custom shapes, how do I achieve those custom shapes for nodes?

They're basically just white rectangles.

**Comment by jacomyal** [comment]
There are various resources now to help you migrate custom programs from v2 to v3:
- You can start with the [dedicated documentation](https://www.sigmajs.org/docs/advanced/migration-v2-v3), that describes precisely the breaking changes and how to migrate
- You can also read the [Customizing appearance](https://www.sigmajs.org/docs/advanced/customization) and [Renderers](https://www.sigmajs.org/docs/advanced/renderers)
- Finally you can check the [Custom rendering](https://github.com/jacomyal/sigma.js/blob/main/packages/storybook/stories/custom-rendering/index.ts) example, that shows how to write a custom program for sigma

If it's not enough to help you, please provide more detailed information as a comment (the version of sigma you are migrating from, the original code you were using to display those white rectangles, ...).
