### ISSUE TITLE
Create a snapshot of "sigma-containter"

### ISSUE THREAD

**Issue by Diegoxlus** [jacomyal/sigma.js#1414]
The problem with taking a screenshot is that the canvas is divided into several sections:
![image](https://github.com/jacomyal/sigma.js/assets/34036453/a0f68764-0e09-4f03-8b69-c2ba3c161cbe)

I am using Angular and I don't see a way to capture it, I have tried to create a single canvan combining the existing ones but the styles are not maintained in the new one.

**Comment by jacomyal** [comment]
Until we release a proper `@sigma/snapshot` package, fully featured and with the proper options, there is an example on how to snapshot a sigma instance [here](http://localhost:6006/?path=/story/png-snapshot--story).

The code is [there](https://github.com/jacomyal/sigma.js/blob/main/packages/storybook/stories/png-snapshot/saveAsPNG.ts). Don't hesitate to come back to this ticket if you have trouble making it work.
