### ISSUE TITLE
Questions about the use of the sigma

### ISSUE THREAD

**Issue by Arelina** [jacomyal/sigma.js#1416]
I am a user of this sigma, now I am upgrading the version of the sigma used in the project to v3, and I have some problems 
Because the amount of data used is huge，So I had to use this method for performance
```js
// import EdgesDefaultProgram from "sigma/rendering/webgl/programs/edge";
// import EdgesFastProgram from "sigma/rendering/webgl/programs/edge.fast";
 renderer = new Sigma(graph, container, {
    defaultEdgeType: "edges-fast",
    // allowInvalidContainer: true,
    renderEdgeLabels: true,
     edgeProgramClasses: {
       "edges-default": EdgesDefaultProgram,
      "edges-fast": EdgesFastProgram,
    },
  });
```
But in the new version this feature does not seem to work, is there a solution or is there any documentation I can check.
Thanks to the authors for providing such a powerful graph framework

**Comment by jacomyal** [comment]
Hello,

In the v3, the endpoints [have changed](https://www.sigmajs.org/docs/advanced/migration-v2-v3/#exports-endpoints) and the existing programs [have been renamed](https://www.sigmajs.org/docs/advanced/migration-v2-v3/#existing-programs).

So, to fix your case, you probably have to write something like:

```javascript
import { EdgeLineProgram, EdgeRectangleProgram } from "sigma/rendering";

// [...]

renderer = new Sigma(graph, container, {
  // allowInvalidContainer: true,
  defaultEdgeType: "edges-fast",
  renderEdgeLabels: true,
  edgeProgramClasses: {
    "edges-default": EdgeRectangleProgram,
    "edges-fast": EdgeLineProgram,
  },
});
```

I hope this helps!
