### ISSUE TITLE
The error of edge reduce 

### ISSUE THREAD

**Issue by Arelina** [jacomyal/sigma.js#1417]
I am very sorry to ask you some questions again.
I have another question，I need to show some of the lines and points on demand，so I used the Node reduce And edge reduce setting,but when I use this refresh function more than 4 times. console show this warning .
<img width="871" alt="image" src="https://github.com/jacomyal/sigma.js/assets/42526528/2b2e1548-9c09-4248-a96f-ec3ce2c9956f">
Then all the edges in the graph are gone.
when I zoom  this graph 
<img width="814" alt="image" src="https://github.com/jacomyal/sigma.js/assets/42526528/ce934943-b796-442c-b9e5-c755c6cadbab">
my Code is this
```js
// ... set circleDatas = [xxxpoint,xxxpoint,xxxpoint....]
  renderer?.refresh();

// reduce function
const edgeReducerFunc = (edge: string, data: any) => {
  const res: Partial<EdgeDisplayData> = { ...data };
  if (circlesData.value && circlesData.value.length > 0) {
    const sourceNode = graph.getSourceAttribute(edge, 'label').replace(/\(.*\)/, "").trim()
    const targetNode = graph.getTargetAttribute(edge, 'label').replace(/\(.*\)/, "").trim()
    if (isCircle.value) {
      if (circleDatas.includes(sourceNode) && circleDatas.includes(targetNode) && ((Math.abs(circleDatas.indexOf(sourceNode) - circleDatas.indexOf(targetNode)) === 1) || (Math.abs(circleDatas.indexOf(sourceNode) - circleDatas.indexOf(targetNode)) === circleDatas.length - 1))) {
        res.color = "#ff0000";
        res.size = 1;
        res.type = "edges-default";
      }
    } else {
      if (circleDatas.includes(sourceNode) && circleDatas.includes(targetNode) && ((Math.abs(circleDatas.indexOf(sourceNode) - circleDatas.indexOf(targetNode)) === 1))) {
        res.color = "#ff0000";
        res.size = 1;
        res.type = "edges-default";
      }
    }
  }
  return res;
}
```

**Comment by Arelina** [comment]
Correct presentation
![image](https://github.com/jacomyal/sigma.js/assets/42526528/2b5709b3-7967-40db-9f39-523308a0dd68)

**Comment by jacomyal** [comment]
The warnings you see are there because sigma is remounted too often in your application. This shouldn't happen, and is probably due to some code elsewhere in your application.

Are you using a frontend framework such as React or Angular? Can you add some logs where you instantiate Sigma, to see if it does or does not occur often?

**Comment by Arelina** [comment]
Thanks for the warning. It really was a problem when I re-mounted the instance somewhere
