### ISSUE TITLE
Optimizing Zoom Functionality for Scalable Graphics

### ISSUE THREAD

**Issue by Arelina** [jacomyal/sigma.js#1418]
I am very sorry to disturb you again☹️. I have one final question for you, and it pertains to a rather demanding requirement. I do not expect a straightforward solution but would greatly appreciate any advice or suggestions you might have.

My requirement is as follows: When zooming in on a graph, I wish for the nodes to stop increasing in size beyond a certain zoom level, while the distance between any two nodes continues to expand. Naturally, this means the lines connecting the nodes would not thicken further. I attempted a solution by dynamically adjusting the node sizes based on the zoom factor during the scaling process. However, this method resulted in significant performance degradation, causing the zooming action to become extremely sluggish.

I understand this is a challenging issue, but any insights or alternative approaches you could offer would be immensely helpful.

Thank you for your time and consideration.

**Comment by Arelina** [comment]
I will manually close this issue when I get your answer

**Comment by jacomyal** [comment]
I've never seen that usecase, but luckily there actually is a way to do exactly this: The [`zoomToSizeRatioFunction`](https://github.com/jacomyal/sigma.js/blob/8d4bd70e9d7cc36e59e0856c8b18355c5bbda7b6/packages/sigma/src/settings.ts#L55) does quite exactly this, even if it has not been designed for this usecase.

The default value is `Math.sqrt`, but you can do exactly what you want by using something like `x => Math.max(0.8, Math.sqrt(x))`.

You can see an example here:
https://codesandbox.io/p/sandbox/issue-1418-example-2464cs?file=%2Findex.ts

**Comment by Arelina** [comment]
Thank you very much for your answer. This question has been bothering me for a long time and it is very useful for me
