### ISSUE TITLE
CDN release for latest version

### ISSUE THREAD

**Issue by longmtran** [jacomyal/sigma.js#1419]
Hi,

Is there a plan to release CDN asset for newer version? The latest one in https://cdnjs.com/libraries/sigma.js stopped at 3.0.0-beta.6. All version above this are blank there.

Thanks.

**Comment by jacomyal** [comment]
Hi,
I'll investigate, thanks for that report.

**Comment by jacomyal** [comment]
I created a ticket on the proper CDNjs GitHub repository:
https://github.com/cdnjs/packages/issues/1789

**Comment by longmtran** [comment]
@jacomyal great, thanks for the prompt action.

**Comment by jacomyal** [comment]
Quick update: I finally sent [a PR](https://github.com/cdnjs/packages/pull/1871) about this to the related repo.

**Comment by jacomyal** [comment]
Quick update: My PR has been merged, but there is something wrong with CDN.js deployment. I opened [a ticket](https://github.com/cdnjs/cdnjs/issues/14261) on the related repo.
