### ISSUE TITLE
Utility functions not available when loading sigma statically via cdn

### ISSUE THREAD

**Issue by longmtran** [jacomyal/sigma.js#1421]
Hi,

I'm attempting to load the library via cdn (https://cdnjs.com/libraries/sigma.js/3.0.0-beta.6) statically in the html page and can render the graph successfully in a non-TS approach. Similar to the example in your documentation https://www.sigmajs.org/docs/quickstart#quick-example but I had to use `const renderer = new Sigma.Sigma(graph, container);`

However, when I attempt to replicate the layout example from your storybook (Random, Circular, etc) in a pure js script, I notice that all the utility functions such as the one used in this example `animateNodes()` dont seem to be added to any scope, hence getting error `Uncaught ReferenceError: animateNodes is not defined`

Here is the console out put of the global Sigma object. 

![Screenshot 2024-04-04 at 03 21 14](https://github.com/jacomyal/sigma.js/assets/1169545/f26041f3-111b-46cd-97a9-be25cada6aaa)

Does anyone know how I can access these utility functions when loading the lib statically via CDN? Or is it not possible in this way?

Thanks.

**Comment by jacomyal** [comment]
Hi,
When the CDN issue (#1419) will be fixed, the list of things exported to the bundle will be this:
https://github.com/jacomyal/sigma.js/blob/89a1be9953dd3488546fabc880dac262d5019c67/packages/sigma/src/index-bundle.ts#L20-L26

So, all programs and all utilities will become available. I close this ticket to make it easier to track.
