### ISSUE TITLE
Changing programs with `setSetting` has no effect

### ISSUE THREAD

**Issue by sim51** [jacomyal/sigma.js#1423]
I'm using the node-border program in an application with light & dark mode. 
So when the theme changed, I change the `nodeProgramClasses` by using the `setSetting` function.
But nothing changed in my displayed graph...

To reproduce it, check : https://codesandbox.io/p/sandbox/funny-lamport-vz4r9j

**Comment by jacomyal** [comment]
I confirm that the programs are initialized when sigma is instantiated, and that no programs settings update is handled later.

**Comment by sim51** [comment]
What I purpose is to throw an error if in the function  we set a program. 
For now, just it doesn't work, without any notice.

**Comment by jacomyal** [comment]
I don't like it, I'd rather forbid setting some settings that allowing it and throwing errors. I'll think about it.
