### ISSUE TITLE
Angular: update from 2.4 to sigma 3.0 beta, cannot find type declarations error during compile

### ISSUE THREAD

**Issue by holo05** [jacomyal/sigma.js#1425]
Hello,
I have updated my Angular 16 app from sigma 2.4.0 to sigma 3.0.0 beta and now I get the following error when compiling:

![image](https://github.com/jacomyal/sigma.js/assets/41048494/e9c85193-2782-4184-a9b5-31e7fce250a8)

Thank you for any hints!

**Comment by togishi** [comment]
Same with Angular 17.3, any hints would be wondertastic!

**Comment by SMxJrz** [comment]
+1

**Comment by jacomyal** [comment]
I can reproduce it, and I see the problem: the current stack screws up when generating types for a class built with `createEdgeCompoundProgram`.

I think it shouldn't be too hard to solve, I'll let you know as soon as I publish a version with a fix. I don't know why it breaks with Angular specifically though.

Thanks for the report!

**Comment by jacomyal** [comment]
I just published [sigma v3.0.0-beta.19](https://www.npmjs.com/package/sigma/v/3.0.0-beta.19) that solves this issue. Thanks again for the report!
