### ISSUE TITLE
Issue with atlas generation in @sigma/node-image

### ISSUE THREAD

**Issue by jacomyal** [jacomyal/sigma.js#1430]
I tried to visualize the dataset from [MARVEL graphs](https://www.marvel-graphs.net/#/characters/). The atlas texture generation is broken, and it is observable in two different ways:

1. Some node images change over time (without any user input

![issue-images-marvel](https://github.com/jacomyal/sigma.js/assets/144846/483dd7e3-bbf1-4354-be7f-daea9da814e0)

2. Most nodes (all nodes?) have display broken images (distorted and/or multiple images)

![image](https://github.com/jacomyal/sigma.js/assets/144846/eb5a33e8-31a9-446c-a3e9-bf70156b4bc7)

This issue initially comes from this [Gephi Lite ticket](https://github.com/gephi/gephi-lite/issues/149).

**Comment by TheBigRoomXXL** [comment]
Hello, 

I work on a project where i want to display lots of image and I have the same behavior. 

In my case this is caused by the texture being bigger than `gl.MAX_TEXTURE_SIZE`. I already use a custom version of `NodeImageRenderer` for my specific needs so  I am in the process of fixing this by paginating the atlas. Basically the `textureManager` and `NodeImageProgram` now have a list of texture instead of just one. This is apparently a common solution in video games. 

The only issue that I have is that I need to update `uniform sampler2D u_atlas` in the fragment shader so that each node use the correct texture and have I have not yet found where to do that in the rendering workflow. If can't do it that way, I will add a texture index in the node data array and load all textures in the shader. 

Once I have figure out that last detail the solution  should be applicable to `@sigma/node-image` whiteout too much difficulty.

You can checkout my solution here: 
[texture.ts](https://gist.github.com/TheBigRoomXXL/482464038b510b0a33f05f2a8a00aaab)
[factory.ts](https://gist.github.com/TheBigRoomXXL/cbf68a5cafd298f54743fb7b10dd35ae)

**Comment by jacomyal** [comment]
Wow, great, thanks!
I am right now exactly looking for ways to handle multiple atlases, thanks a lot for the sharing!

**Comment by TheBigRoomXXL** [comment]
It's pleasure if I can Help! Sigma is an amazing library 😉.

I just finished my fix to have multiple atlas. Here is a picture with 6973 images, all 128x128 in size, rendered across 2 8192x192 textures. Not much visible at that distance ^^. 

![image](https://github.com/jacomyal/sigma.js/assets/80152117/008d5cbc-6adf-40dd-a50d-f501ed441546)

 The way I did it was to add a new float attribute `v_texture_index` and replace the atlas by and array of atlas (`uniform sampler2D u_atlas[10];`). Then I just use an if statement to determine the correct altas in the shader : 

```glsl
    int index = int(v_texture_index + 0.5); // +0.5 avoid rounding errors
    vec4 texel;
    if (index == 0) texel = texture2D(u_atlas[0], (v_texture.xy + coordinateInTexture * v_texture.zw), -1.0);
    else if (index == 1) texel = texture2D(u_atlas[1], (v_texture.xy + coordinateInTexture * v_texture.zw), -1.0);
    else if (index == 2) texel = texture2D(u_atlas[2], (v_texture.xy + coordinateInTexture * v_texture.zw), -1.0);
    else if (index == 3) texel = texture2D(u_atlas[3], (v_texture.xy + coordinateInTexture * v_texture.zw), -1.0);
    else if (index == 4) texel = texture2D(u_atlas[4], (v_texture.xy + coordinateInTexture * v_texture.zw), -1.0);
    else if (index == 5) texel = texture2D(u_atlas[5], (v_texture.xy + coordinateInTexture * v_texture.zw), -1.0);
    else if (index == 6) texel = texture2D(u_atlas[6], (v_texture.xy + coordinateInTexture * v_texture.zw), -1.0);
    else if (index == 7) texel = texture2D(u_atlas[7], (v_texture.xy + coordinateInTexture * v_texture.zw), -1.0);
    else if (index == 8) texel = texture2D(u_atlas[8], (v_texture.xy + coordinateInTexture * v_texture.zw), -1.0);
    else if (index == 9) texel = texture2D(u_atlas[9], (v_texture.xy + coordinateInTexture * v_texture.zw), -1.0);
    else texel = texture2D(u_atlas[1], (v_texture.xy + coordinateInTexture * v_texture.zw), -1.0);
```

That's not clean but I could not find a better way to do it so it's good-enough™ for now.

 It *mostly* work but I often have a flaky bug where some images use the wrong texture or the webgl context is lost. Those error mostly appear when  I have lot's of images and  `DEBOUNCE_TEXTURE_UPDATE_MS` in the texture manager is low. I think there might be some conflict  when  `textureManagerCallback` and the rendering happen at the same time? Or maybe the gpu run out of memory when `this.ctx.getImageData` and the rendering is called at the same time. I don't realy know but I am going to do some profilling tomorrow.  

## Nicely render images:
![image](https://github.com/jacomyal/sigma.js/assets/80152117/d8c02743-4396-4372-826f-a348c7f24756)

## Buggy render
![image](https://github.com/jacomyal/sigma.js/assets/80152117/282ef16b-fad3-41ae-a655-2de0aac7dab9)



Here is the updated version of my code:

[factory.ts](https://gist.github.com/TheBigRoomXXL/cbf68a5cafd298f54743fb7b10dd35ae)
[texture.ts](https://gist.github.com/TheBigRoomXXL/482464038b510b0a33f05f2a8a00aaab)
[shader-vert.ts](https://gist.github.com/TheBigRoomXXL/5ae4b414aaf6e36779ded2c73f8cafb1)
[shader-frag.ts](https://gist.github.com/TheBigRoomXXL/c03a1c6b582b89936ea3b36a697d2ae5)

**Comment by jacomyal** [comment]
Thanks a lot @TheBigRoomXXL!
I first tried to write another solution (that would maintain a pool of sub-programs), but I failed...
So I started from your version, and updated it so that it respawns its program when a new texture is required.

https://github.com/jacomyal/sigma.js/commit/81bd3dc8ea3cf449d14094f39806e38a03bbd92d

Anyway, your comments helped a lot, thanks again :pray:
