### ISSUE TITLE
SigmaJS using NodeJS Server-Side Layout

### ISSUE THREAD

**Issue by RackweLLizm** [jacomyal/sigma.js#1431]
I'm trying to use SigmaJS. Thank you for this beautiful project. Currently, even if the number of nodes with certain X and Y values ​​in Canvas is 100,000, there will be no problems with visualization. But if the X and Y values ​​are not clear, even 5000 nodes will slow down.
What I want to do is to create the x and y values ​​of these nodes on the server side nodeJS with the layout I choose (FA2 etc.) and quickly display the data with X, Y values ​​on the client.

Can I run Layout on NodeJS with SigmaJS?

**Comment by jacomyal** [comment]
Sigma.js doesn't compute layouts by itself, but instead is based on [Graphology](https://github.com/graphology/graphology) - which supports NodeJS.

So, you could imaging the following workflow:
- Load your data in a Graphology instance back-end side
- Compute your layout (still back-end side)
- Serialize your graph back-end size (using [Graph#export](https://graphology.github.io/serialization.html#export)), and send the string to the front-end
- Load the graph from Graphology front-end side (using [Graph#import](https://graphology.github.io/serialization.html#import)), and give this graph (with proper x,y values) to sigma.js

I hope this helps.

**Comment by RackweLLizm** [comment]
Thank you for your quick reply. I will try it immediately and get back to you

**Comment by RackweLLizm** [comment]
@jacomyal 
I ran it as you said and it was successful, but the problem is that the X and Y values ​​of the nodes are unknown and they need to be created meaningfully by the system. When I look at the layouts in graphology that will create meaningful layouts, they all ask for X and Y values ​​at the beginning. But in my scenario the values ​​of X and Y are unknown. If I do Circular and Random, a meaningless image appears with 5000+ data. What do you think I should do in this situation? Is there a solution for this? For example: Graphology is a layout option that will create the ForceAtlas2 layout by calculating it on its own, without x and y values. Antv G6 has similar options but they work slowly

**Comment by jacomyal** [comment]
You necessarily have to get initial nodes positions. One trick I often use is (which is some kind of theoretical nonsense, but it works enough for me):
- Group the nodes by communities using [graphology-communities-louvain](https://graphology.github.io/standard-library/communities-louvain)
- Use [graphology-layout/circlepack](https://graphology.github.io/standard-library/layout#circlepack), using the `community` node attribute previously computed to pack the nodes (using the `hierarchyAttributes` option)
- Then, start ForceAtlas2
