### ISSUE TITLE
sigma/node-image not working on Angular

### ISSUE THREAD

**Issue by Nekoraru22** [jacomyal/sigma.js#1433]
## Info

**Sigma.js version:** ^3.0.0-beta.19
**Angular version:** 16
**Graphology version:** ^0.25.4
**Operating System:** Windows 11 64-bit
**Web browser:** OperaGX - LVL5 (core: 109.0.5097.130)

### Steps to reproduce

`npm install` on Angular project and start it with `ng serve`

### Error
![image](https://github.com/jacomyal/sigma.js/assets/57575090/ca41e890-cee3-4885-85e2-90e9eea383a3)

By doing this on `node_modules/@sigma/node-image/dist/declarations/src/index.d.ts` I get everything to work correctly:
```ts
export { default as createNodeImageProgram } from "./factory.js";
import { NodeProgramType } from "sigma/rendering";
interface N {
    [key: string]: unknown;
}
interface E {
    [key: string]: unknown;
}
interface G {
    [key: string]: unknown;
}
export declare const NodeImageProgram: NodeProgramType<N, E, G>;
export declare const NodePictogramProgram: NodeProgramType<N, E, G>;
```
I have only imported and declared interfaces

In the previous version the same file was like this:
```ts
export { default as createNodeImageProgram } from "./factory.js";
export declare const NodeImageProgram: import("sigma/rendering").NodeProgramType<import("graphology-types").Attributes, import("graphology-types").Attributes, import("graphology-types").Attributes>;
export declare const NodePictogramProgram: import("sigma/rendering").NodeProgramType<import("graphology-types").Attributes, import("graphology-types").Attributes, import("graphology-types").Attributes>;
```

**Comment by jacomyal** [comment]
Hi @Nekoraru22,

Thanks for that report. I can reproduce this issue.
When I build locally, I get the "good" version (with the inline `import("graphology-types").Attributes`).

I have 3 issues now I need to address:
1. Why can the current stack build different versions of the d.ts files, including an invalid version
2. How can I detect that the generated d.ts files are broken, before publishing
3. Why are Angular users the only people to detect that these d.ts files are broken

I'll investigate, and I'll come back to you as soon as I can.

**Comment by jacomyal** [comment]
@Nekoraru22 I just republished all packages with cleaner typings, and there is now [some safeguard](https://github.com/jacomyal/sigma.js/commit/5a1e2d822a0774f9095a0e4b3a0fb538ad18eefc) that lints the generated *.d.ts files before publishing. So this kind of problem should hopefully not occur anymore in the future.

Thanks again for the report, and sorry for the inconvenience.
