### ISSUE TITLE
MouseMove event does not fire from within a Web-Component (ShadowDom)

### ISSUE THREAD

**Issue by benny-noumena** [jacomyal/sigma.js#1441]
Hey there

First of all, sorry for not following protocol with Bug-Reporting but I have little time right now and would like to get a feedback so I can proceed with a PR if needed.
I spent some time to figure out why the `mousemove` event was not working for me when I was using sigma.js within a lit web-component.

I did some debugging and narrowed it down to the `mousemove` and `mouseup` events being registered directly on the document, rather than on the container element.

What is the reason behind this?

If I change it to the container element everything works as expected for me.

Would it be safe to do so? Because then I would proceed and make a PR.

Many thanks for all the hard work!

Best Ben

**Comment by benekeil** [comment]
it would be great if all events were also supported for the shadow dom

**Comment by jacomyal** [comment]
Hi,

@sim51 just pushed a fix implementing [suggestion from @foxton9](https://github.com/jacomyal/sigma.js/issues/1400#issuecomment-1902169951) on issue #1400.
