### ISSUE TITLE
How to download Graph image?

### ISSUE THREAD

**Issue by ubaidxmughal** [jacomyal/sigma.js#1442]
I am using sigma.js v3 and i dont found anything about how to download image of graph.

**Comment by jacomyal** [comment]
There is an story that shows how to do that. At the moment, it requires quite some code, but it might become an easier to use new module later.

The story is here: https://www.sigmajs.org/storybook/?path=/story/png-snapshot--story
The code is there: https://github.com/jacomyal/sigma.js/tree/main/packages/storybook/stories/png-snapshot
