### ISSUE TITLE
Inconsistent behavior with screen pixel ratio

### ISSUE THREAD

**Issue by Picorims** [jacomyal/sigma.js#1446]
The CSS size, the canvas size and the output of graphToViewport() does not consistently handle pixel ratio, leading to weird behaviors in some contexts.

# Device info

**Sigma.js version:** 3.0.0-beta.23
**Graphology version:** 0.25.4
**Operating System:** Windows 10
**Web browser:** Firefox 128.0

# Steps to reproduce

- Open Sigma on a screen with a screen pixel ratio of 100%
- Observe consistency between canvas CSS and context sizes, as well as the output of graphToViewport().
- Apply a different screen ratio, for instance 125%, and restart Sigma (by reloading the page for example, or restarting the browser if needed).
- Observe inconsistency between the canvas CSS and context sizes, as well as inconsistency between what Sigma draws and the output of graphToViewport() (if used for example to draw on a canvas with no transform and no pixel ratio computation and with identical CSS and canvas dimensions as Sigma canvases).

The following behavior is observable on Sigma examples on Storybook in devtools when it comes to CSS versus canvas resolution, such as here: https://www.sigmajs.org/storybook/?path=/story/nodes-edges-opacity--story

# Expected behavior

Ideally, having a different pixel ratio should not generate inconsistencies.

# Actual behavior

In some selected API methods or computations, pixel ratio is not taken into account, leading to confusing behavior when using such APIs or adding a canvas underneath Sigma canvases. It is hard to distinguish bugs from intended behavior in this case.

# Additional info

The following screenshot show the CSS inconsistency:
![image](https://github.com/user-attachments/assets/61d51d8a-d79f-43a1-b303-aee5b31c63d6)

In some cases, such as the graphToViewport() method, it is possible to compensate this behavior by applying or cancelling the pixel ratio scaling of coordinates, either through computation or canvas transformations, once you are aware of this limitation.

In the case of the CSS, it is hardly visually noticeable, and only important to be aware of from a developer perspective.

**Comment by jacomyal** [comment]
Hi @Picorims,

I am not sure I understand your issue, for me it's a feature (and one that took some time to properly implement):
- The CSS dimensions are the "HTML-world pixels" dimensions, which are in what the browser considers as pixels
- The `width` and `height` attributes are the "screen-world pixels" dimensions, which are in the actual pixels of your screen

It is weird, but by default, if we don't do this, the graphs appear aliased and rough on devices with `devicePixelRatio > 1` (such as Retina displays for instance). You can search for "canvas retina display" online, and you'll find [this kind of resources](https://stackoverflow.com/questions/4720262/canvas-drawing-and-retina-display-doable).

**Comment by Picorims** [comment]
Thanks for the resource, I will take a look. If it is intended behavior then it is alright, it was just a bit confusing. I know browsers manipulate the px unit especially on mobile but I am not fully familiar with the details or what's the behavior on desktop.
