### ISSUE TITLE
Node Renderers Missing From .js Binaries

### ISSUE THREAD

**Issue by efwb001** [jacomyal/sigma.js#1450]
Hello,

I'm trying to use sigma from javascript/html. The quick-start guide, github releases, and CDNs that I can find only serve sigma.js and sigma.min.js, which don't have the optional node renderers (@sigma/node-image etc.). Is there any JavaScript version of these node renderers?

(Why is this a bug? Because these features are much talked about on the site but currently seem unusable via HTML/JS).

**Comment by jacomyal** [comment]
Hi @efwb001,

There is a specific bundle `sigma.min.js` that is built from the [`sigma/src/index-bundle.ts`](https://github.com/jacomyal/sigma.js/blob/751a1abcdced8c4b00e58990683a5953f50b36a8/packages/sigma/src/index-bundle.ts#L25) file. It exposes the other renderers under the `Sigma.renderers` key.

This bundle should soon (#1419) be the file available on CDNjs. Also, I just fixed the release process so that this bundle is in the upcoming GitHub releases.

Thanks for this report!

**Comment by jacomyal** [comment]
OK, I confirm, the [new releases](https://github.com/jacomyal/sigma.js/releases/tag/sigma%403.0.0-beta.28) do only contain the bundle now.

**Comment by jacomyal** [comment]
If you have `Sigma` in the global scope, you should be able to write something like:

```javascript
const graph = new Graph();

graph.addNode("a", {
  x: 0,
  y: 0,
  size: 20,
  label: "Jim",
  image: "https://upload.wikimedia.org/wikipedia/commons/7/7f/Jim_Morrison_1969.JPG",
});
graph.addNode("b", {
  x: 1,
  y: -1,
  size: 40,
  label: "Johnny",
  image: "https://upload.wikimedia.org/wikipedia/commons/a/a8/Johnny_Hallyday_%E2%80%94_Milan%2C_1973.jpg",
});
graph.addNode("c", {
  x: 3,
  y: -2,
  size: 20,
  label: "Jimi",
  image: "https://upload.wikimedia.org/wikipedia/commons/6/6c/Jimi-Hendrix-1967-Helsinki-d.jpg",
});

graph.addEdge("a", "b", { size: 10 });
graph.addEdge("b", "c", { size: 10 });

const NodeImageProgram = Sigma.rendering.createNodeImageProgram()
const sigmaInstance = new Sigma(
  graph,
  document.getElementById("container"),
  {
    nodeProgramClasses: {
      image: NodeImageProgram
    }
  }
);
```

To see exactly what is exported in this `Sigma.rendering` object, please check `sigma/src/index.bundle.ts`:

https://github.com/jacomyal/sigma.js/blob/bda69c95d81689548c8dc7f9533a84d3fb6be725/packages/sigma/src/index-bundle.ts#L26-L32

**Comment by jacomyal** [comment]
Hi, sorry again, you're absolutely right :) At the moment, the object exported to the global scope from `sigma.min.js` is named `sigma` and not `Sigma`. I don't like this, so I'm pushing a patch right now.

Upcoming versions will have the proper global export under the `Sigma` key (there should be a new minor version soon, probably today). Until then, you can add `const Sigma = sigma;` before anything else, and that will do the trick.

Thanks for your report and for your patience :pray:
