### ISSUE TITLE
How to create square shaped nodes?

### ISSUE THREAD

**Issue by charnelclamosa** [jacomyal/sigma.js#1452]
I'm new in sigma.js development, and I've been trying to create a custom shape node which is square, as per [the docs](https://stackoverflow.com/), this is possible by using the "renderer".

Based on the docs, I need to instantiate the renderer with a declared type that uses the NodeCircleProgram and the name of the node type as key, refer to the code snippet below:
```
const renderer = new Sigma(graph, container, {
  allowInvalidContainer: true,
  defaultEdgeType: "straight",
  defaultNodeType: "square",
  nodeProgramClasses: {
    square: NodeCircleProgram,
    circle: NodeCircleProgram
  },
  edgeProgramClasses: {
    straight: EdgeArrowProgram,
    curved: EdgeCurvedArrowProgram
  }
})
```
Then this is how I'm rendering the nodes:
```
myNodes.forEach(value => {
  graph.addNode(value.key, {
    forceLabel: true,
    label: value.label,
    x: value.col,
    y: value.row,
    size: value.size,
    url: value.url,
    type: "square"
  })
})
```
Anyone that can point out what is the problem here? The nodes and edges are working fine with no error in the console logs, but the nodes is still circle.

**Comment by StockerGaming** [comment]
In order to render the nodes as squares, you need to use a NodeProgram which renders then as squares. You are explicitly still using the NodeCircleProgram in your code. Maybe someone has written a shader for square nodes and made it freely available online, maybe you need to write it yourself.

I hope that helps!

**Comment by jacomyal** [comment]
Hi,

@StockerGaming was absolutely correct :)
But there is also some needs for simple nodes rendering example, so I actually just implemented it as [@sigma/node-square](https://www.npmjs.com/package/@sigma/node-square) (the link might not be working right now, but it will soon, as soon as I publish).
