### ISSUE TITLE
TypeScript Documentation gone from sigmajs.org

### ISSUE THREAD

**Issue by StockerGaming** [jacomyal/sigma.js#1462]
There used to be a page for the TypeScript documentation of Sigma on the documentation site on sigmajs.org which I found to be useful. It appears to be completely gone now. I do not know whether this is intended.

**Comment by jacomyal** [comment]
I upgraded the website dependencies and fixed the Docusaurus and Typedoc configurations, and the Typedoc is [back online](https://www.sigmajs.org/docs/category/typedoc-api). It's still quite rough though, I'll try to improve the integration someday.
