### ISSUE TITLE
Sigma: could not find a suitable program for node type "padding"!

### ISSUE THREAD

**Issue by shradha0810** [jacomyal/sigma.js#1463]
I am using sigma.js graph in my react project I want to use image node program with some padding. So I tried implementing according to the storybook examples but I keep on getting this error I tried solving it but I am not able to
![Screenshot 2024-09-13 143706](https://github.com/user-attachments/assets/3ad800f5-56a1-44c5-ade2-2c436d534ebf)

If I am doing anything wrong please recommend changes.This is my initialization for nodeProgram and used imports and I am using dependency  "@react-sigma/core" for rendering graph.

```jsx
import { createNodeImageProgram, NodeImageProgram } from "@sigma/node-image";
import { NodeCircleProgram, createNodeCompoundProgram } from "sigma/rendering";

  const paddingProgram = useMemo(() => {
    return createNodeImageProgram({
      padding: 0.1,
      objectFit: "contain",
      correctCentering: true,
      // drawingMode: "color",
    });
  }, []);
  const NodeProgram = useMemo(() => {
    return createNodeCompoundProgram([NodeCircleProgram, paddingProgram]);
  }, []);
  
  <SigmaContainer
          settings={{
            allowInvalidContainer: true,
            defaultNodeType: "image",
            defaultEdgeType: "arrow",
            nodeProgramClasses: {
              image: NodeImageProgram,
              padding: NodeProgram,
            },
          }}
        >
```

**Comment by sim51** [comment]
Hi,

I tried to reproduce your error, but without success. 
You can take a look at this code sandbox : https://codesandbox.io/p/sandbox/sigma-issues-1464-96vcp9

If you want to continue the discussion, can you create a ticket on react-sigma instead ? (I think it's more related to it than to sigma itself). 

Thanks !
