### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by rahst12** [jacomyal/sigma.js#1468]
Hi all,
Where can I find a key list of improvements made in v3, a summary/changelog of the differences between the beta versions (are there long-term stable versions), and a general roadmap/vision for the future?

Thanks,
Ryan

**Comment by jacomyal** [comment]
Hi @rahst12,

You're right, a clean communication on these points are missing right now.
I just wrote an announcement about all this, you can read it [here](https://github.com/jacomyal/sigma.js/discussions/1469).
