### ISSUE TITLE
Roadmap and Changelog?

### ISSUE THREAD

**Issue by rahst12** [jacomyal/sigma.js#1474]
First, I love SigmaJS.  It renders graphs incredibly fast!

Is there a SigmaJS roadmap to a full 3.0 release, or a vision of what is forthcoming in future releases?  Also, a changelog of features would be very helpful too.  I've been tracking tag comparisons in lieu of that (https://github.com/jacomyal/sigma.js/compare/sigma%403.0.0-beta.18...sigma%403.0.0-beta.32).

Thanks

**Comment by jacomyal** [comment]
Hi @rahst12,

Indeed there is! I wrote a post #1469 in the "discussion" part of this repository, where I explain what's left to do before removing this `beta` flag:
https://github.com/jacomyal/sigma.js/discussions/1469

Don't hesitate to reply to the discussion thread if you have any question.
