### ISSUE TITLE
useMemo leads to nodesCount being undefined

### ISSUE THREAD

**Issue by DanielRuf** [jacomyal/sigma.js#1482]
Check the demo and the generated titles in the panels:

![image](https://github.com/user-attachments/assets/ff5d0888-5d8f-4474-a204-6e4e2b8e665f)

**Comment by jacomyal** [comment]
Hi @DanielRuf,

I need a bit more information here to be able to help you:
- What dependencies does your `useMemo` listen to?
- What exactly does your `useMemo` returns?
- More generally, could you provide some code or even some context, to help us understand what could go be the cause of your issue?

**Comment by DanielRuf** [comment]
You can see it at https://www.sigmajs.org/demo/
