### ISSUE TITLE
Inconsistent hovered nodes neighbors highlighting in example story

### ISSUE THREAD

**Issue by vemonet** [jacomyal/sigma.js#1485]
- Sigma.js version : 3.0.0-beta.33
- Graphology version : 0.25.4
- Operating system: Ubuntu 22.04
- Web browser: Firefox 131.0.3 (64-bit) and Chromium 130.0.6723.69 (Official Build) (64-bit)
- **Steps to reproduce**

Going to the story: https://www.sigmajs.org/storybook/?path=/story/use-reducers--story

- Actual behavior

When you hover a node it shows all edges between all connected nodes, not only the edges between the hovered node and its connected nodes. But when you click multiple times on the hovered node at some point the edges that are between the connected nodes other than the hovered node ends up disappearing. Even if there was nothing in the code that changes the edges displayed based on clicks.

For example if you hover "Javert" you will see the edge between "Thenardier" and "Mme Thenardier". If you click many times at some point these edges will disappear. 

This is because `const edges = graph.filterEdges((e) => graph.extremities(e).some((n) => nodesIndex.has(n)));` in `setHoveredNode` will filter edges to keep all edges between all nodes connected to the hovered node. 

This conflicts with the code defined in the `edgeReducer`:

```ts
    this.renderer.setSetting("edgeReducer", (edge, data) => {
      const res: Partial<EdgeDisplayData> = { ...data };
      if (this.hoveredNode && !this.graph.hasExtremity(edge, this.hoveredNode)) {
        res.hidden = true;
      }
```

- Expected behavior

It all works fine showing only edges connected to the hovered node when I change the code in `setHoveredNode` to

```ts
const edges = this.graph.filterEdges((e) => !this.graph.hasExtremity(e, node));
```

It is not a major bug in the library itself, but the logic to filter out edges is defined twice, which ends up creating potential conflicts and inconsistent behaviors. Not sure if it is possible, but ideally this logic should be defined only in 1 place.

Otherwise it could be nice for newcomers to make this clearer in the story example, it can be a bit confusing at start :) 

Feel free to close if you feel like this is already addressed enough

**Comment by jacomyal** [comment]
Good catch, thanks! For the record, another way to trigger consistently this bug is to "try to drag a node" (i.e. down the mouse on the node, then move the mouse before releasing the mouse).

The code about the `partialGraph` is not the part supposed to be showcased on that example, so I'll simply drop it, and fix  the edges filtering part in the `edgeReducer`.

Thanks again!
