### ISSUE TITLE
throw error when node hover and setGraph

### ISSUE THREAD

**Issue by wszgrcy** [jacomyal/sigma.js#1486]
**Sigma.js version:** 3.0.0-beta.36
**Graphology version:** 0.25.4
**Operating System:** windows 10
**Web browser:** chrome 124

### Steps to reproduce

When I move the mouse over a node, or when the hover state of the node is not cancelled Using setGraph will throw an exception

### Expected behavior

worked

### Actual behavior

throw error

## Note

error position 
https://github.com/jacomyal/sigma.js/blob/126195956b46275ff4b0d5dedd380aa17ab3c9e2/packages/sigma/src/sigma.ts#L1114
![image](https://github.com/user-attachments/assets/4fc970d1-8ce5-4c30-a22c-9b1772cc3e8d)
I think after `setGraph`, we should first clear the value of `hoveredNode`, so that it will work properly
or `this.nodeDataCache[this.hoveredNode]?.hidden` add `?`

**Comment by jacomyal** [comment]
Good catch! I just pushed a fix, it will be released in the next version (should be today). Thanks for the report :+1:
