### ISSUE TITLE
Does the forceAtlas implementation take into account hiding nodes and edges?

### ISSUE THREAD

**Issue by Raibaz** [jacomyal/sigma.js#15]
When a node and/or an edge is hidden (i.e., has `hidden` == 1), does forceAtlas still consider it for attraction and repulsion?

I wrote a small change that seems to avoid considering hidden nodes and edges, but i wanted to be sure before submitting another pull request :)

**Comment by apitts** [comment]
I don't believe the current FA2 excludes hidden nodes, correct? I was wondering if anyone had made any progress on this or was currently working on it? It would be really nice to exclude isolates from the algorithm for example by hiding them.

**Comment by Yomguithereal** [comment]
No, for the time being, FA2 does not exclude hidden nodes. You can try to fix your hidden nodes however if what you want is them not to be affected by the layout by setting a property `fixed` to true on them.

**Comment by apitts** [comment]
Thanks @Yomguithereal!  Just so I make sure I understand 100% - fixing nodes will leave their position unchanged but their fixed positions will still influence the positions of other non-fixed nodes in the current algorithm.  Right?  I may try to implement the exclude hidden nodes setting for the algorithm myself if it's not too hard.  It looks to me that: 
1. The optional setting would need to be set here: https://github.com/jacomyal/sigma.js/blob/master/plugins/sigma.layout.forceAtlas2/worker.js#L40
2. The node and edge matrices would need to be iterated through on initialisation if the setting was true and only non-hidden nodes and edges between two non-hidden nodes would need to be included in those matrices on initialisation. 

Would be great if you could tell me if I'm missing something obvious!

**Comment by Yomguithereal** [comment]
Hello @apitts. This is the case indeed. Fixed nodes won't move but will still have an impact on repulsion/attraction.

The tricky part here is that since node and edges are expressed through a flat matrix, one needs to keep the order of the nodes so that positions might be reapplied to the nodes' data afterwards, so filtering the hidden nodes wouldn't work and you'd have to create conditions within the algorithm to skip the wanted node, rather.

**Comment by apitts** [comment]
Ahh...thanks @Yomguithereal! I had a feeling it wouldn't be that straightforward....
