### ISSUE TITLE
zoom to a node

### ISSUE THREAD

**Issue by saurinshah7** [jacomyal/sigma.js#176]
hi, 

currently, I am trying to write a functionality for zooming to a node. Currently, am doing something like

s.cameras[0].goTo({x:node.x,y:node.y,ratio:0.0625})

but this does not seem to work. It would be great help if someone could help me with this. I am using new version of the library. 

-Saurin

**Comment by JantineD** [comment]
How do i define the nodes?

**Comment by Yomguithereal** [comment]
Hello @JantineD. I am not sure I understand your question. Could you develop a bit more please?

**Comment by dara0418** [comment]
Awesome! Thanks so much for the workaround.
