### ISSUE TITLE
add node at mouse position 

### ISSUE THREAD

**Issue by ammanvedi** [jacomyal/sigma.js#182]
Im having trouble implementing a simple facility to add nodes to the graph at the point of a mouse click, although the examples provided show adding via mouse click, this is with touch and mouse disabled, i would like to be able to get the graph co-ordiante from a mouse click so i can add a node where the users mouse is placed while maintaining the ability to zoom. 

I have investigated the cameraposition and graphposition functions with no luck so far

thanks in advance

**Comment by lasithc** [comment]
Hi,
I am having the issue specified in http://stackoverflow.com/questions/40980357/sigma-js-linkurious-add-a-node-for-the-right-click-mouse-event
Is this related ?

**Comment by tylorbayer** [comment]
Has any progress been made to the autoRescale issue?  I have an existing graph that is not centered around "0,0" that I want to add nodes too, however, with the solution above the nodes get placed super far away from the actual mouse click.

**Comment by kannes** [comment]
@tylorbayer it would be awesome if you could add some minimal, working code example here. It might take you just a minute but for others it might be hard to know where even to start. ;)

**Comment by mahmoudafer** [comment]
> @tylorbayer it would be awesome if you could add some minimal, working code example here. It might take you just a minute but for others it might be hard to know where even to start. ;)

+1

**Comment by AlexNoodl** [comment]
> @tylorbayer it would be awesome if you could add some minimal, working code example here. It might take you just a minute but for others it might be hard to know where even to start. ;)

Hi, you resolve this issue?
