### ISSUE TITLE
Drag and drop for individual nodes

### ISSUE THREAD

**Issue by philipcdavis** [jacomyal/sigma.js#187]
Hi @jacomyal, 
First off -- impressive library. I'm loving the revamp!
I was wondering if you were going to be adding the possibility for individual nodes to be dragged and repositioned using the mouse. I understand that you can move the entire graph around, but it might be nice to put drag and drop individual nodes.

Any thoughts? 

Best,
Philip

**Comment by Erfan-Sahafi** [comment]
Hello, how can I disable drag and move the graph?
I want to use Sigma in React, please help me.
