### ISSUE TITLE
Leap Motion control of Sigma.Js graph

### ISSUE THREAD

**Issue by deemeetree** [jacomyal/sigma.js#195]
You've probably heard of [Leap Motion](http://www.leapmotion.com) – 3D gesture-control interface that is on sale at any Fnac in Paris these days for like 60 eur.

Well, they have that library [Leap.Js](http://developer.leapmotion.com/leapjs/examples), which basically enables you to control any Canvas element using your hand gestures in the air. 

So of course I wanted to try it on Sigma graphs and it's so good! Minority Report embodied.

Just add the following code to any Sigma visualization and see how well it works!

```
// Include the Leap.Js library
<script src="//js.leapmotion.com/leap-0.4.1.js"></script>

// Add this code below to control your Sigma instance using LEAP (s in this case)

var controller = new Leap.Controller({enableGestures: true});
var firstValidFrame = null;

// Avoid visual feedback loop :)
var defaultRatio = s.cameras[0].ratio;

controller.loop(function(frame) {
       if (!firstValidFrame && frame.valid) firstValidFrame = frame;
       var translation = frame.translation(firstValidFrame);

       // Here is the code for controlling Sigma default camera view

       // This will move the graph horizontally with your hand swipe in the air
       s.cameras[0].x = -translation[0];

       // This will move the graph up and down with your hand swipe in the air
       s.cameras[0].y = translation[1];

       // This will zoom in if you move your hand towards the screen and zoom out if you move away
       s.cameras[0].ratio = defaultRatio + (translation[2]/360);

       });
  }
);
```

My only problem was that it only worked when ForceAtlas2 was running. If I use stopForceAtlas2, then none of that works for some reason. Any help would be appreciated. If you want me to demo it and you are in Paris, just let me know :)

**Comment by bastiankhalil** [comment]
@deemeetree can I have your email?

**Comment by deemeetree** [comment]
@bastiankhalil it’s dmitry att noduslabs dott com
