### ISSUE TITLE
HTML rendered node labels

### ISSUE THREAD

**Issue by philipmjohnson** [jacomyal/sigma.js#197]
Greetings,

I am a newcomer to sigma.js and am wondering how difficult it would be to have my node label text rendered as HTML (so, for example, I could have clickable links in the node labels.

Thanks,
Philip

**Comment by delete000** [comment]
Hi deemeetree,

could I perhaps get the help you offered to Philip? Where exactly in the source code do I have to look to introduce hyperlinks in the labels?

Cheers

**Comment by jpmarindiaz** [comment]
@philipmjohnson do you happen to have an example where you update a div with additional info when a node is clicked?
I'd really appreciate it!

**Comment by cfleck** [comment]
s.bind('clickNode', function(e) {
	$('#selector_of_div_to_manipulate').html('fill with anything');
});

or

s.bind('clickNode', function(e) {
	$('#selector_of_div_to_manipulate').append('add anything');
});

**Comment by jpmarindiaz** [comment]
@cfleck Great, thanks!

**Comment by ZhaofengWu** [comment]
Sorry if this is a silly question, but it looks like the graph is only a `canvas` that does not have any HTML elements in it. So how would I add a piece of HTML, say, next to a node? In other words, I do not have a DOM reference to the nodes.

**Comment by AVermeij** [comment]
@ZhaofengWu, you can use the node's rendered coordinates (for example `node['renderer1:x']`) to render any HTML you want next to a focal node. See for example the last comment in https://github.com/jacomyal/sigma.js/issues/413 which implements this.
