### ISSUE TITLE
Curved Edges

### ISSUE THREAD

**Issue by gstub** [jacomyal/sigma.js#207]
Hi,

I was using sigma js before the upgrade, and when I would draw edges they would be curved. I recently learned of the new sigma js and decided to use it. But now when I draw my graphs all of the edges are straight. Is there a way to curve the edges?

Thanks!

**Comment by gitbestsou** [comment]
Any reason I did this and still the edges are coming as straight? What does this do anyway? Curvemmeans just a random curve or follows some specific algorithm?
