### ISSUE TITLE
FishEye in Sigma 2?

### ISSUE THREAD

**Issue by deemeetree** [jacomyal/sigma.js#226]
Hi, I haven't found any implementation of FishEye in the new Sigma. Or have I missed something? Thanks!

**Comment by solipsy** [comment]
Hi, I'd also really like to see this in the new Sigma. I'd be prepared to write it myself for the canvas renderer if I knew how to start ,,, can anyone give me some directions? Thanks!

**Comment by deemeetree** [comment]
anyone knows if this has been implemented?
