### ISSUE TITLE
How to stop the graph from resizing?

### ISSUE THREAD

**Issue by apitts** [jacomyal/sigma.js#256]
I am currently using the recently added dragNodes plugin - which is terrific so thanks very much @jacomyal and @josemazo.  One thing I would like to be able to do is stop the graph from resizing when a user drags a node.  At the moment dragging a node just a little bit can cause all of the other nodes to shrink together, i.e. it causes some fairly dramatic resizing.  I've tried changing a few of the settings but couldn't work out how to turn off this resizing when dragging.   The autoRescale setting had some effect but the initial graph in that case was then very small.  

Any suggestions would be much appreciated.

**Comment by ryan-williams** [comment]
+1!
