### ISSUE TITLE
Labels and Nodes Separate on Large Resolution Displays

### ISSUE THREAD

**Issue by rerobins** [jacomyal/sigma.js#257]
When displaying on large resolution displays (was testing on a 2560x1600) the label and node separate horizontally when the display is maximized.  When the browser is not maximized the labels and the nodes combine back together.   In addition, the nodes can no longer be clicked on (at least events do not fire for highlight or click).  I believe that these two are related.

I was using the WebGL renderer in Google Chrome Version 35.0.1916.69 beta.  This can also be reproduced by zooming out on Google Chrome.  Can start to see the labels slightly move to the left as zooming out.  The labels didn't jump completely off the node till the zoom got to about 50%.

**Comment by oserban** [comment]
I know this might be an old issue that nobody is interested in, but we recently found that we're affected by this as well in the Open Visualisation Environment (see https://github.com/ove/ove-apps/issues/238).

Did anyone find a workaround for this? We are using v1.2.1 and haven't tried v2.0 yet as we're looking for a more stable release.
