### ISSUE TITLE
Can I draw a rectangle in graph?

### ISSUE THREAD

**Issue by SN1979** [jacomyal/sigma.js#271]
I want to draw a rectangle in the graph. 
But It seems only several types are available, circle, diamond, equilateral, pacman, square, and star.

Could you help to do that? 
And where can I see all the attributes of node?

**Comment by vivekdaryani** [comment]
I have indeed extended the custom shapes plugin to include a 'rectangle' shape. 
But it seems the edges still assume that node is still a circle. As a result they end up somewhere outside or disappear inside the rectangle.

**Comment by Yomguithereal** [comment]
In this case, you will probably have to design an edge renderer that will adapt to the shape of its source and target nodes. I can show you how to code a custom renderer if you want.
