### ISSUE TITLE
Problem on edges generating

### ISSUE THREAD

**Issue by ghost** [jacomyal/sigma.js#273]
My code genetates this json:

Object {nodes: Array[4], edges: Array[3]}
edges: Array[3]
0: Object
     color: "#0F260C"
     id: "e1"
     size: 10
     source: "n0"
     taget: "n1"
1: Object
     color: "#0F260C"
     id: "e2"
     size: 10
     source: "n0"
     taget: "n2"
2: Object
     color: "#0F260C"
     id: "e3"
     size: 10
     source: "n0"
     taget: "n3"

nodes: Array[4]
0: Object
     color: "#35FF4C"
     id: "n0"
     label: "Sevilla"
     size: 20
     x: 0
     y: 0
1: Object
     color: "#31CFE8"
     id: "n1"
     label: "Cerro del Hierro"
     size: 10
     x: 1
     y: 0
2: Object
     color: "#31CFE8"
     id: "n2"
     label: "Torrecilla"
     size: 10
     x: 0
     y: 1
3: Object
     color: "#31CFE8"
     id: "n3"
     label: "Mulhacén"
     size: 10
     x: 1
     y: 1

But when i create new sigma, it makes error log lake this:
"Uncaught The edge target must have an existing node id. "

All target "id" is alright, but it still dont work!
Help me please!

Here my full code: http://codepaste.net/3g5wgg

Regards for your atention and sorry for my bad English!

**Comment by gitbestsou** [comment]
https://goo.gl/oJp8AV Do you see any error on this json file? i am getting the same error.
