### ISSUE TITLE
Edge render order

### ISSUE THREAD

**Issue by csweaver** [jacomyal/sigma.js#282]
Is there a way to force the order of edged rendered? I'm having a problem where I would like to highlight some edges, but less important edges are being drawn on top of them. See the screenshot for an example. I'd like the green edges to be on top and the gray edges to be below. I'm using the canvas render if it makes a difference.
![screen shot 2014-05-23 at 2 58 17 pm](https://cloud.githubusercontent.com/assets/1517263/3070669/73780d24-e2ac-11e3-91bb-fecd71bbaf76.png)

**Comment by deanshub** [comment]
also if its possible make the z-index cross elements,
I've made a cluster plugin that enables nodes and edges within nodes but the order of the rendering makes it irrelevant...

**Comment by bencooper222** [comment]
I'd like to leave a second on this issue^. I'm not a skilled web developer so I don't have any great ideas on how to fix this but I'd really *really* appreciate having this feature on my projects.

**Comment by Yomguithereal** [comment]
For this, you would have to design a custom renderer that would render cluster after clusters rather than rendering edges then nodes. The default renderer does not work this way for performance reasons but I can see the appeal of you use case.

**Comment by lapsus63** [comment]
You should see issue [820](https://github.com/jacomyal/sigma.js/issues/820) about node and edges overlap rendering
