### ISSUE TITLE
Animate specific nodes only

### ISSUE THREAD

**Issue by 1tylermitchell** [jacomyal/sigma.js#289]
I'm just starting to dig into the animate code to understand how it works, but I thought I'd ask here in case I'm missing something obvious already. 
I'm building some interaction where I select a node (clickNode event) and then want to animate all the other nodes.  I can get all the logic figured out, except when I run animate plugin, it applies to the whole graph.  
I know as a workaround I can make sure that the properties I'm animat/changing for that selected node is set so it does not change, but that feels like a hack.
Any tips?

**Comment by sheymann** [comment]
@spatialguru now available https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.plugins.animate
