### ISSUE TITLE
right-click events

### ISSUE THREAD

**Issue by sheymann** [jacomyal/sigma.js#296]
Hello,

Do you consider adding the events:
rightClick
rightClickStage
rightClickNode
rightClickNodes

?

It's useful to display a popup or a context menu without impacting the browsing activity in the graph.

**Comment by apitts** [comment]
Wondering if anyone has been able to get righClick events working on Chrome?  They are working fine for me in Firefox but not at all in Chrome.  I suspect it may be the Chrome contextMenu but have disabled that and still no luck.

**Comment by apitts** [comment]
It's very hacky and I would much prefer to use the sigma events but this seems to be working for the moment.

```javascript
    if (document.addEventListener) {
        document.addEventListener('contextmenu', function(e) {
          //my custom functionality on right click
            e.preventDefault();
        }, false);
    } else {
        document.attachEvent('oncontextmenu', function() {
            //my custom functionality on right click
            window.event.returnValue = false;
        });
    };
```

**Comment by sheymann** [comment]
@apitts no issue with it, see how I've done in [sigma.plugins.tooltips](https://github.com/Linkurious/linkurious.js/tree/linkurious-version/plugins/sigma.plugins.tooltips)

**Comment by apitts** [comment]
@sheymann Thanks for that!  Good to know it's just my issue as it narrows it down a lot. I see how you have removed the contextmenu in the tooltips plugin.  The only thing I can think of at the moment is it might be something specific to Chrome on Ubuntu that's giving me the issue...I'll try testing it on Windows once I have access to a Windows machine.  Definitely doesn't look like a sigma issue though.
