### ISSUE TITLE
Drag node division by 0 error when the first two nodes have the same y position 

### ISSUE THREAD

**Issue by markov00** [jacomyal/sigma.js#303]
Hi, I was playing around with sigma and I discovered that if i set to the same y value the first two nodes of my graph and use the dragNodes plugin, when I try to drag one node the graph disappear.
The problem is caused by the algorithm used inside the plugin, on the linear interpolation

```
y = ((y - ref[0].renY) / (ref[1].renY - ref[0].renY)) * (ref[1].y - ref[0].y) + ref[0].y;
```

the `(ref[1].renY - ref[0].renY)` will turn to 0 if the the first two nodes of the graph are at the same y position resulting in a division by 0 error and a NaN value on the x and y positions.

I think it will happen also when you are using the same x value

**Comment by styu** [comment]
Pull request created: https://github.com/jacomyal/sigma.js/pull/664
