### ISSUE TITLE
drag node bug

### ISSUE THREAD

**Issue by antonioaltamura** [jacomyal/sigma.js#315]
hi, i noticed a strange behavior with drag node plugin.
You can try yourself:
In the example drag-nodes.html try to change the nodes X coordinate to 0 (66th row in the for loop)
then try to drag any node: the whole graph totally disappear.

i'm on win7 i tried with chrome, ff, ie

**Comment by styu** [comment]
Pull request created: https://github.com/jacomyal/sigma.js/pull/664
