### ISSUE TITLE
Is it possible to render a graph without providing node positions?

### ISSUE THREAD

**Issue by azeemba** [jacomyal/sigma.js#336]
The way I am creating the graph, the graph can be of varying structure so there is no obvious position I can provide for my nodes. So the only solution I see is to implement a graph layout algorithm, but I imagine this might be a feature that more people might need so it would be nice if it was built into the library. I imagine something like [cytoscape](http://cytoscape.github.io/cytoscape.js/#layouts) provides.

Am I missing some other way of doing this? 
I see the forceAtlas plugin, but it seems that it doesn't work without positions.

**Comment by luke18** [comment]
Hello @Yomguithereal 
Exactly the same need. Is this improvement right now available?
It would be really cool to include a layout algorithm in this project.

**Comment by Yomguithereal** [comment]
Hello @luke18, those improvements are not available yet. We only have an iterative layout [plugin](https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.layout.forceAtlas2), but no deterministic ones to put nodes on a circle, grid etc... It would be nice to have such a plugin however. Let me see what I can see about this in a near future.

**Comment by nachosn89** [comment]
I have done this:

s.graph.nodes().forEach(function(node, i, a) {
node.x = Math.cos(Math.PI * 2 * i / a.length);
  	node.y = Math.sin(Math.PI * 2 * i / a.length);
  	node.size=8;
  	node.color='#f00';
});
s.refresh();
s.startForceAtlas2({worker: true,adjustSizes:true,gravity: 5,outboundAttractionDistribution:true});

First I make a circle and after that I use ForceAtlas2 to realign the nodes.

**Comment by Yomguithereal** [comment]
Hello @nachosn89, this is indeed a sensible way to dispose the nodes around a circle.

**Comment by Federicopvs** [comment]
@Yomguithereal I just started using sigma because I would like to create a force graph including 2000+ nodes without a starting positions in the json file.
Is there an example implementing the **ForceAtlas2** plug-in? I would like to have a look at it to see if it can work for me..

**Comment by Yomguithereal** [comment]
Hello @Federicopvs. You can check out [this](https://github.com/jacomyal/sigma.js/blob/master/examples/force.html) example.

**Comment by Federicopvs** [comment]
let me see if I understand this correct..
My goal is to load an external json file where the nodes do not have a starting position..

Should I just change this part:
`g = {
      nodes: [my nodes],
      edges: [my edges]
    };`

..and leave the rest of the code untouched as it is the one giving the position to the elements?
And how can I refer tothe arrays (nodes and adges) from my json file?

**Comment by leuch3rd** [comment]
Hello, 
I was wondering if there was any movement on implementing native graph lines for a rendered canvas.  Thank you!

**Comment by gitbestsou** [comment]
How many nodes and edges can sigma.js render without starting to lag?  I am not asking a definite number. Any approx will do.

**Comment by Yomguithereal** [comment]
This version, ~50k nodes ~500k edges approximately. The next one, which is under development: ~250k nodes ~1M edges.

**Comment by Yomguithereal** [comment]
If you have edge events it will probably lag with this scale. There is no proper way to make edge events scale very well.

**Comment by Yomguithereal** [comment]
> Actually I have a particular data(not in the form of nodes and edges) and I am writing a script to generate nodes and edges from that data which is running before rendering occurs. Can that program be a reason of the browser slowdown?

If this is done once before rendering there is no reason why it would be so.

**Comment by gitbestsou** [comment]
Yes. I actually have edge events..And node and search events as well.
