### ISSUE TITLE
Drag nodes plugin that is compatible with WEBGL renderer?

### ISSUE THREAD

**Issue by aabhyank** [jacomyal/sigma.js#337]
Is there any available update on the drag nodes plugin which is compatible with the WebGL renderer?

**Comment by jayeshmori** [comment]
@aabhyank, @antonkulaga - Did you guys find any solution to the problem? I am thinking of spending some time on the issue but do not want to re-invent the wheel.

**Comment by lumucheng** [comment]
Dear @aabhyank , @antonkulaga , @jayeshmori - I'm also hoping that you guys have a solution to the webgl drag node issue. any ideas? thank you

**Comment by AVermeij** [comment]
Check out https://github.com/jacomyal/sigma.js/issues/815, works very well here to enable node dragging in WebGL renderers

**Comment by lumucheng** [comment]
@AVermeij Thank you very much! The solution indeed works very well :)
