### ISSUE TITLE
Graph model's memory usage

### ISSUE THREAD

**Issue by mef** [jacomyal/sigma.js#340]
I have noticed that the memory usage of sigma.graph is very high. Processing large graphs leads to `out of memory` errors.

To give an idea, here is how sigma.js compares to node.js' graphjs module for a graph having 1210 nodes and 26409 edges, just to instantiate the graph:

```
# sigma.js when issue was opened
# process.memoryUsage().rss: 141.537.280

# sigma.js after a memory leak fixed in d821d8c
# process.memoryUsage().rss: 135.946.240

# graph.js
# process.memoryUsage().rss:  24.743.936
```

It's worth noting that graph.js also indexes the data for fast access.

I'd rather stick to using sigma.js because its API looks more straightforward to me. I have investigated the graph data and indexing structure in sigma.js

Here is the graph model's data stored for a very simple graph:
- node `n1` with one attribute `attr:nodeAttr`
- node `n2` having no attribute
- edge `e1` from `n1` to `n2` with one attribute `attr:edgeAttr`

``` json
{
  "nodesArray": [{ "attr": "nodeAttr", "id": "n1"},{ "id": "n2"}],
  "edgesArray": [{ "attr": "edgeAttr", "id": "e1", "source": "n1", "target": "n2"}],
  "nodesIndex": {"n1": { "attr": "nodeAttr", "id": "n1"}, "n2": { "id": "n2"}},
  "edgesIndex": {"e1": { "attr": "edgeAttr", "id": "e1", "source": "n1", "target": "n2"}},
  "inNeighborsIndex": {"n1": {}, "n2": { "n1": {"e1": {"id": "e1", "source": "n1", "target": "n2", "attr": "edgeAttr"} }}},
  "outNeighborsIndex": {"n1": { "n2": {"e1": {"id": "e1", "source": "n1", "target": "n2", "attr": "edgeAttr"} }}, "n2": {}},
  "allNeighborsIndex": {"n1": { "n2": {"e1": {"id": "e1", "source": "n1", "target": "n2", "attr": "edgeAttr"} }}, "n2": { "n1": {"e1": {"id": "e1", "source": "n1", "target": "n2", "attr": "edgeAttr"} }}},
  "inNeighborsCount": {"n1": 0, "n2": 1},
  "outNeighborsCount": {"n1": 1, "n2": 0},
  "allNeighborsCount": {"n1": 1, "n2": 1}
}
```

Observations:
1. `nodesArray` and `nodesIndex` are duplicate storage of the entire nodes dataset. Do we really need the array structure when we can iterate on `nodesIndex` object?
2. same remark as previous for `edgesArray` and `edgesIndex`
3. in `nodesIndex`, the objects' keys are the nodes Ids. Then we don't need to store the redundant `id` attribute.
4. same remark as previous for `edgesIndex`
5. `inNeighborsIndex`, `outNeighborsIndex` and `allNeighborsIndex` stores the whole edge data in the nested structure. Significant savings can be done by only storing the reference to the edges' id instead. Neighbors indexes can be used to check whether there is an edge between two nodes, and to lookup the id of the edge between two nodes. then in cases when it's needed a accessing `edgesIndex` by edge key can give the edges attributes.
6. `inNeighborsIndex`, `outNeighborsIndex` and `allNeighborsIndex` do store keys for nodes that have no edge. This is users extra space for nothing.
7. `allNeighborsIndex` is a concatenation of `inNeighborsIndex` and `outNeighborsIndex`. A method looking up both indexes and concatenating the result could do the same.
8. Neighbors count indexes: no redundancy, clean structure.

It seems to me that "fixing" points 1 to 5 above won't require lot of rework of the library, while and won't have affect the API too much, while providing significant gains.

Point 6 may require extra checks when using the indexes, I am not sure if its something suitable.

The effect of change suggested in point 7 should be further investigated.

For the sample graph used above, the graph model implementing the suggestions above would be so:

``` javascript
{
  "nodesIndex": {"n1": { "attr": "nodeAttr"}, "n2": {}},
  "edgesIndex": {"e1": { "attr": "edgeAttr", "source": "n1", "target": "n2"}},
  "inNeighborsIndex": {"n2": { "n1": "e1"}},
  "outNeighborsIndex": {"n1": { "n2": "e1"}},
  "inNeighborsCount": {"n1": 0, "n2": 1},
  "outNeighborsCount": {"n1": 1, "n2": 0},
  "allNeighborsCount": {"n1": 1, "n2": 1}
}
```

301 characters instead of 772 (spaces and line breaks excluded)

Is this something that the maintainers of sigma.js would consider worth being implemented?

Edit: added memory usage measured after memory leak fixed in d821d8c

**Comment by tylorbayer** [comment]
How can I use the sigma.noIndex.js if I wasn't originally using sigma.min.js?
