### ISSUE TITLE
Possible to distinguish between clickStage and stage drag?

### ISSUE THREAD

**Issue by rjbriody** [jacomyal/sigma.js#342]
Is it possible to distinguish between a clickStage and "dragStage' event? 

The "2. BIND CALLBACKS TO EVENTS" example on http://sigmajs.org/ can be used to recreate my issue. 

When a node is clicked the non-neighboring nodes are grey'd out. Cool, good so far. Now if you move the graph by dragging the stage then when the mouse is released the clickStage event is fired and the entire graph is recolored. I would like to prevent this from happening. 

What would be really great is if the clickStage event were not fired at all when the mouse is moved while down (by some appropriate amount). However, I can understand if this behavior is not so great for everyone else.

Thanks!
Bob B

**Comment by yeelan0319** [comment]
Hi @jacomyal,

I really appreciate you fixed this issue, it's great helpful. However, I cannot find the isDragging property both in "clickStage" and "clickNode" event captor property in release 1.0.3. I also dig into the source code  for the latest release, namely, "captor.mouse.js" file, but cannot find the property as well. 

Could you please help me out with it? Thanks!

**Comment by bentwonk** [comment]
Thanks, I found isDragging really useful

**Comment by telam** [comment]
@jacomyal thank you for adding this functionality I was running into the same problem with the drag plugin and the clickNode event.

**Comment by Kuroky360** [comment]
@telam  the isDragging property seems to stay false for me too in the clickNode event while dragging one node .

**Comment by telam** [comment]
For anyone who is having trouble with the clickNode event and the isDragging property, I found a temporary solution, although it is a little hacky. @Kuroky360 I hope this helps you!

```
// let the user drag nodes around
var listener = new sigma.plugins.dragNodes(network, network.renderers[0]);

listener.bind("drag", function (e) {
    network.unbind('clickNode');
});

listener.bind("dragend", function (e) {
    setTimeout(function () {
        network.bind('clickNode', node_click_function);
    }, 250);
});
```

**Comment by Kuroky360** [comment]
@telam well, I will try it.Thanks for your suggestion!
