### ISSUE TITLE
Clickable URLs for each node in information pane?

### ISSUE THREAD

**Issue by rjordan65** [jacomyal/sigma.js#353]
Finally figured out how to attach images for each node using the "image attribute" option in the exporter, but what do I need to do to create clickable URLs for each node? I've made a "profile" column for my nodes sheet with all the URLs, but I'm not sure what I need to modify in the exported sigma code to make these links active and clickable. Help would be much appreciated.

**Comment by malihaz** [comment]
@rjordan65  hii, did you find the solution to what you had been looking for?

**Comment by malihaz** [comment]
@rjordan65  hii, did you find the solution to what you had been looking for?
