### ISSUE TITLE
Displaying very long node labels?

### ISSUE THREAD

**Issue by sheymann** [jacomyal/sigma.js#363]
By long label I mean a string > 30 characters. Currently Sigma displays labels on a single line, and in the case of long labels it clutters the visualization awefully.

Three approaches that may be combined: 
* truncate labels (e.g. "This is a long lab...") (better if it cuts at the end of words)
* filter label characters using a regexp pattern (useful in case of URLs)
* display labels on multiple lines, each line has a max number of characters

Who would like to work on this issue with me?

**Comment by fgerstmayer** [comment]
Hi,

I am running, more or less, into the same issue/desire.
I have a rather long label and I would like to use multiple lines for a better layout.
Is there any solution or a workaround for this problem yet?
 
As of now, I tried control sequences and html tags, but neither worked for me. However, I am rather new into JS, so the problem may also be the operator :)
Kind regards

**Comment by sheymann** [comment]
FYI the feature is available in [linkurious.js](https://github.com/Linkurious/linkurious.js) (sigma fork) with the setting `maxNodeLabelLineLength:20`

**Comment by umdstu** [comment]
@sheymann Can we revisit this? that fork no longer exists and this functionality is really useful.
