### ISSUE TITLE
Collapsible nodes

### ISSUE THREAD

**Issue by mabossert** [jacomyal/sigma.js#366]
I would like to be able to visualize really large networks and would like to be able to collapse nodes as a means to de clutter the view similar to what is seen for D3 here: http://bl.ocks.org/mbostock/1062288

Ideally, this would be both manual (e.g. User click or something) and also tied to zoom level such that at a certain zoom level/ratio, the collapsed nodes in view are "opened".

Would this be a trivial thing to implement?  Would this be best done as a plugin?  If so, I am willing write code...but am not sure where to start.  I am an experienced perl programmer, but relatively novice with javascript...but am a quick learner.

**Comment by AVermeij** [comment]
Perhaps this piece of functionality in vis.js resembles what you're looking for? http://visjs.org/examples/network/18_fully_random_nodes_clustering.html

Would be great to have something similar in sigma.js indeed.

**Comment by altraud** [comment]
Exactly like the zoom out!

**Comment by VarunWachaspati** [comment]
Any update on this issue?. Would be a great feature to have.

**Comment by usara0812** [comment]
Exactly what I wanted to do...could you tell me how you resolved this...I am trying to click on the purple circle and collapse the graphs and uncollapse the other way...D3 example is a tree !

Thanks !

<img width="878" alt="screen shot 2017-04-07 at 5 27 21 pm" src="https://cloud.githubusercontent.com/assets/27035504/24823620/1398163c-1bc6-11e7-8359-6b7e950fe1c1.png">

**Comment by RA-Danny** [comment]
Any update anyone ?
