### ISSUE TITLE
Nodes disappear on canvas if autoRescale: false

### ISSUE THREAD

**Issue by sheymann** [jacomyal/sigma.js#373]
Notice that many edge extremities are missing in this picture.
![image](https://cloud.githubusercontent.com/assets/177962/3935295/05454cb6-2494-11e4-9541-0a7d74e06e66.png)

Edit basic.html with this code:

``` js
sigma.renderers.def = sigma.renderers.canvas;
s = new sigma({
  graph: g,
  container: 'graph-container',
  settings: {
    autoRescale: false,
    zoomMin: 0.0001
  }
});
```

Then zoom enough to see the graph.

This bug doesn't happen with the WebGL renderer.
This bug doesn't happen on `autoRescale: ['nodePosition']`.
Tested against d821d8c8fe77075396634d185e5e0db27d17bcbc

**Comment by Skie-Khelle** [comment]
Another working workaround I found is to work on some big offset and create dummy, transparent node at position [0,0];

        sigma.graph.addNode({
            id:     'ghost',
            size:   0,
            x:      0,
            y:      0,
            dX:     0,
            dY:     0,
            type:   'ghost'
        });
        sigma.camera.goTo({
            x: 1000,
            y: 1000
        });

**Comment by qpwo** [comment]
I encountered this bug today; I would be very happy if someone finds a way to fix it.
