### ISSUE TITLE
Fix to support gjslint on Windows

### ISSUE THREAD

**Issue by sheymann** [jacomyal/sigma.js#374]
Gruntfile.js:42 fails on Windows, and we currently have to edit the file manually each time we want to lint the code. Painful.

Assuming that gjslint is installed through the standard procedure https://developers.google.com/closure/utilities/docs/linter_howto, gjslint.exe is installed into the Python directory called "scripts", like `C:\\Python27\\Scripts`...but we don't know which version of Python is installed.

Hopefully, assuming that the PATH env variable contains the path to python scripts, it is possible to omit the closure linter path and to remove the `command` option as follows:

```
closureLint: {
      app: {
        closureLinterPath: 'gjslint',
        src: coreJsFiles,
        options: {
          stdout: true,
          strict: true,
          opt: '--disable 6,13'
        }
      }
}
```

For cross-platform compatibility, and if you think that setting the path on linux systems is necessary (which I doubt because executables in `/usr/local/bin` are accessible whatever the current dir), we end with:

```
closureLinterPath: (process.platform === "win32") ? 'gjslint' : '/usr/local/bin',
command: 'gjslint'
```

What do you think about it?

EDIT: I've found that the options are not passed to gjslint with this approach. We have to set closureLinterPath with the directory, thus having a way to get/build it.

**Comment by sheymann** [comment]
grunt-closure-linter seems dead https://github.com/wzr1337/grunt-closure-linter/issues/15

**Comment by kriku** [comment]
yep!
[https://developers.google.com/closure/utilities/](https://developers.google.com/closure/utilities/) - depricated

there is way around with [closure-compiler](https://github.com/google/closure-compiler) and `--jscomp_warnings=lintCheck`
