### ISSUE TITLE
Force Atlas 2 is acting really weird now...

### ISSUE THREAD

**Issue by dtracers** [jacomyal/sigma.js#378]
I just updated yesterday and now Force Atlas2 is freaking out on me and is not spreading out like normal.  (Though it appears to be faster)

I am using mac 0SX 10.9 and chrome 36.
FA2 (1.0.2) works fine
FA2 (1.0.3) is acting weird

I will add images as 2 separate comments to this issue (because there are going to be like 6 of them.)
They will be posted in the exact same order

**Comment by Compynerd255** [comment]
I've also been using Sigma, and I can confirm this issue in Microsoft Edge (Windows 10 app development). If I create any graph with a single central node and any number of isolate nodes branched from it, the center node jitters erratically. This happens whether I add the nodes manually or use graph.read(). Rolling back to ForceAtlas from 1.0.2 fixes the problem for me as well.
