### ISSUE TITLE
Only display node labels on hover?

### ISSUE THREAD

**Issue by veronica-red** [jacomyal/sigma.js#387]
I have a large network and I would like to only display the node labels when I hover over the node with my mouse, is this possible?  I'm sure it's something super easy and I am just missing it.

Thanks in advance!

**Comment by developeranirudhprabhu** [comment]
Can this display of label on hover be done for edges?

**Comment by gitbestsou** [comment]
I want the same thing. Has the thing been fixed yet?

**Comment by AesaKamar** [comment]
Any updates on the status of this?

**Comment by zsxking** [comment]
setting `labelThreshold: 100` or some large value works for me. Hover still works.

**Comment by nuric** [comment]
With the version `2.4.0`, adding `{drawLabels: false}` option makes labels render only on hover.
