### ISSUE TITLE
Loading sigma.js and plugins using amd

### ISSUE THREAD

**Issue by ghost** [jacomyal/sigma.js#396]
I am looking through the examples and see that all the examples (even the quick start example on the homepage) load the needed libraries through script tags.

I would need to load sigma and the json parser plugin using amd - specifically - require.js:

like so:

``` javascript
define([
    'jquery',
    'underscore',
    'backbone',
    '../lib/sigma/sigma.min.js',
    '../lib/sigma/plugins/sigma.parsers.json.min.js'
], function($, _, Backbone, sigma, sigmaParser ){
...

render: function(){
          sigma.parsers.json('../conf/sigma_data.json', {
            container: this.el,
            settings: {
              defaultNodeColor: '#ec5148'
            }
          });
        },
...
}
```

but when I try to reference sigma or sigmaParser - I get a null reference.  However, in the debugger I see that the js files were properly fetched.  Is there a naming convention that I am missing here?

Can sigma be loaded via AMD - specifically requirejs?

**Comment by Flo-Schield-Bobby** [comment]
Actually, it is really cleaner to use the "shim" option of requirejs (if you use require) :

    require.config({
        paths: {
            'sigma': '../lib/sigma-1.0.3.require'
        },
        shim: {
            'sigma': {
                exports: 'sigma'
            }
        }
    });

**Comment by orls** [comment]
I'd be really good for sigmajs to support AMD loading better.

For tips on how how achieve AMD support with minimal changes, have a look at [UMD](https://github.com/umdjs/umd) -- specifically their [`returnExports.js` example](https://github.com/umdjs/umd/blob/master/returnExports.js).

**Comment by henryoswald** [comment]
+1
