### ISSUE TITLE
rescale 

### ISSUE THREAD

**Issue by aMockingBird** [jacomyal/sigma.js#416]
Is it possible to rescale the graph after hiding some nodes so that it fits exactly the container (so the rescaling mustn't take into consideration the hidden nodes)? if yes, how? Thanks in advance

**Comment by olingerc** [comment]
Hi, I currently face the same issue. I load new nodes into the graph dynamically and would like to have the graph rescale itself so that all nodes are visible? Thanks.

**Comment by olingerc** [comment]
Sorry, I just realized that this actually works automatically when calling refresh. My issue is more that when a user changes the zooming level, I want to give a reset button that makes whole graph visible again.

**Comment by AVermeij** [comment]
That should be pretty easy to achieve actually. If ``s`` is your sigma instance, try this:

    sigma.misc.animation.camera(
      s.cameras[0],
      { ratio: 1, x: 0, y: 0, angle: 0 },
      { duration: 150 }
    );

**Comment by olingerc** [comment]
Works perfectly!

**Comment by Yomguithereal** [comment]
Thanks @AVermeij.
