### ISSUE TITLE
Missing setting defaultNodeSize

### ISSUE THREAD

**Issue by sheymann** [jacomyal/sigma.js#424]
Currently, all nodes must have the property `size` defined, otherwise they are not rendered. When `node.size` is missing, `settings('defaultNodeSize')` should be used to render the node;

Introducing the sigma setting `defaultNodeSize` would solve this issue.

**Comment by leonn** [comment]
@sheymann  I used

settings: {
      minNodeSize: 
}
 to solve this

**Comment by sheymann** [comment]
@leonn it doesn't solve the issue, as `minNodeSize` is set to 1 by default.

**Comment by leonn** [comment]
Yeah you're right @sheymann  but  if you by default add nodes with size: 0   and use your minNodeSize  it will work like a charm

**Comment by sheymann** [comment]
Ah that's nice indeed, but I need to drop the `size` key.

**Comment by qinfchen** [comment]
Does `size` do anything? I tried adjusting size all nodes, but It did't affect the node sizes in the graph. But if i changed maxSizeNode, all node sizes changed.
