### ISSUE TITLE
How to make labels always visible?

### ISSUE THREAD

**Issue by cbartosiak** [jacomyal/sigma.js#427]
Hi,

I've looked for the answer long but unfortunately haven't found any solution/workaround. The problem is that in the old sigma we could set selected nodes nodes active and see their labels as long as they remain active. In the new version of the library it is not possible since there is no active state. Even Linkurious fork (which contains active state feature) doesn't provide the same functionality.

Is there any way to force labels to be drawn other than attaching own html to each node?

**Comment by bornakke** [comment]
So this easy solution does no longer work?
https://github.com/jacomyal/sigma.js/issues/11
