### ISSUE TITLE
rendering webgl

### ISSUE THREAD

**Issue by swapnil-rapidops** [jacomyal/sigma.js#428]
hey guys i want to know how to use custom node/edge renderer with webgl,
i tried to use it according to the example but not working for me.
here is the code i have tried to use.

sigma.utils.pkg('sigma.webgl.edges');
    sigma.webgl.edges.tt = {
    POINTS: 2,
    ATTRIBUTES: 3,
    addEdge: function(edge, source, target, data, i, prefix, settings) {
      var w = 0.5,
          x1 = source[prefix + 'x'],
          y1 = source[prefix + 'y'],
          x2 = target[prefix + 'x'],
          y2 = target[prefix + 'y'],
          color = '#F00';  //edge.color;

```
  if (!color)
    switch (settings('edgeColor')) {
      case 'source':
        color = source.color || settings('defaultNodeColor');
        break;
      case 'target':
        color = target.color || settings('defaultNodeColor');
        break;
      default:
        color = settings('defaultEdgeColor');
        break;
    }

  // Normalize color:
  color = sigma.utils.floatColor(color);

  data[i++] = x1;
  data[i++] = y1;
  data[i++] = color;

  data[i++] = x2;
  data[i++] = y2;
  data[i++] = color;
}
};
```

may i know where i am wrong.

**Comment by louy2** [comment]
Please edit to include all your code in codeblock.
