### ISSUE TITLE
zoomIn zoomOut events?

### ISSUE THREAD

**Issue by antonioaltamura** [jacomyal/sigma.js#435]
Hi, as in title, there is no event bind on zoom, there is a way I can get it?

**Comment by devgitk** [comment]
@qinfchen  does this work?! @alfredopacino did u try to implement this?

**Comment by alfredopacino** [comment]
i didnt tried but it should work, just note the fact the actions should be fired just if i scroll on graph container div, not the other divs

**Comment by terrymun** [comment]
For me, I am simply listening to the `DOMMouseScroll` or `mouse wheel` events on the `.sigma-mouse` element, and it works fine for me... even though I do appreciate a custom event emitted by the plugin, e.g. `zoomIn`, `zoomOut`, `pan` and etc. Right now they are all lumped under one single camera API :/ 

$('.sigma-mouse')
    // I destroy and create new Sigma instances on the same page on the go, so I unbind events first
    .unbind('mousewheel DOMMouseScroll')

    // Rebind events
    // Note: use jQuery $.throttle plugin to prevent excessing firing
    .bind('mousewheel DOMMouseScroll', $.throttle(500, function(e) {
        // Example callback
        $('#sigma-tooltip').empty().removeClass('active');
    }));
