### ISSUE TITLE
Graph not included in its container

### ISSUE THREAD

**Issue by francesco-ficarola** [jacomyal/sigma.js#436]
I'm trying to draw a graph using sigma.js. I'm already done, but the problem is that the graph is not included in the corresponding container.

See the screenshot below:
![sigmajs](https://cloud.githubusercontent.com/assets/1279595/4953025/87db03b8-667b-11e4-8b59-cd4f39e1dd38.png)

This is my html code:

```
<div id="graph">
    <div id="sigma-container">
    </div>
</div>
```

and this is the CSS:

```
#graph {
    position: relative;
    width: 700px;
    min-height: 400px;
    margin-top: 2%;
    margin-left: auto;
    margin-right: auto;
    border: 10px solid #555;
    padding: 20px;
    text-align: center;
    background-color: #fff;
}

#sigma-container {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
}
```

then, I generate my graph calling:

```
s = new sigma({ graph: g, container: 'sigma-container' });
```

where:

```
g = { nodes: [1, 2, 3, ...], edges: [1, 2, 3, ...] };
```

**Comment by agajdosi** [comment]
I have also faced this issue, took some time to find it is caused by: `text-align: center;` being inherited from some parent. Fix was to set `text-align: left;` on the `#sigma-container`. Would be nice if Sigma could detect it and behave accordingly.
