### ISSUE TITLE
How to filter nodes that are have lost their edge

### ISSUE THREAD

**Issue by dokithonon** [jacomyal/sigma.js#441]
Hello,
I apply a filter on edges. They disappear fine.
Now I have some nodes alone since their edges have been filtered.
How can I apply a second filter to remove theses nodes ?
Thanks a lot.
PS : I have tried to remove the node without degree = 0 but this does not work since their edges are still there but only hidden.

**Comment by anastazie** [comment]
Hello, did you figure out how to solve this problem? I have the same problem.

**Comment by anastazie** [comment]
I solved this problem by using `adjacentEdges` method to retrieve all edges from each node and then count edges excluding hidden ones.
```
filter
                .undo('non-isolates')
                .nodesBy(function (n) {
                    var count = 0;
                    s.graph.adjacentEdges(n.id).forEach(function (item) {
                        !item.hidden && count++;
                    });
                    console.log(count);
                    return count > 0;
                    }, 'non-isolates')
                .apply();
```
