### ISSUE TITLE
configurable object for settings in sigma constructor

### ISSUE THREAD

**Issue by qinfchen** [jacomyal/sigma.js#445]
It is a little odd that all sigma settings are stored in sigma.settings, which is an instance of configurable class,  and sigma constructor doesn't take configurable object for its settings.

The following code works fine.

``` javascript
var sigma = new sigma({
    settings: {
        mouseEnabled: false
    },
    renderers: [{
        type: sigma.renderers.canvas,
        container: graphContainer[0]
    }]
});
```

but it does not work if I instantiate a configurable object and use that in the constructor. 

``` javascript
var defaultSettings = new sigma.class.configurable({mouseEnabled: false});
var sigma = new sigma({
    settings: defaultSettings,
    renderers: [{
        type: sigma.renderers.canvas,
        container: graphContainer[0]
    }]
});
```

Thoughts?

**Comment by saicharanp** [comment]
Can you please tell me if  you found any solution for this?

**Comment by emanodame** [comment]
@saicharanp did you find a solution?
