### ISSUE TITLE
Trigger hover and label

### ISSUE THREAD

**Issue by Yomguithereal** [jacomyal/sigma.js#448]
It would be nice to find a way to programmatically display the label or the hover of a node.

**Comment by cfleck** [comment]
Anyone found a solution for this yet?

**Comment by jasontschool** [comment]
Just came across this thread looking for the same requirements. I'm still new to the library so this is probably not the cleanest solution, but I looked around the source code and after some debugging found a solution that works at least with the canvas renderer. It seems like you need to dispatch the overNode event to 'hover' a node/label, and that event needs to be dispatched specifically to your renderers:

//keeping track of the renderer
var s = new sigma();
var renderer = s.addRenderer({ 
          container: document.getElementById(id),
          type: 'canvas'
}); 

//triggering a node hover
renderer.dispatchEvent('overNode', {node:s.graph.nodes(node_id)});

**Comment by tienvx** [comment]
#294
