### ISSUE TITLE
Edges added with addEdge will not hover

### ISSUE THREAD

**Issue by 21stcaveman** [jacomyal/sigma.js#466]
Hi, I'm trying to add two nodes and an edge between them like this :

s.graph.addNode({id:'nn0', label:'Nnode 0', x:Math.random(), y:Math.random(), size:1, color:'black'});
s.graph.addNode({id:'nn1', label:'Nnode 1', x:Math.random(), y:Math.random(), size:1, color:'black'});
s.graph.addEdge({id:'ee0', source:'nn0', target:'nn1', type:'curve', color:'red', hover_color: '#000'});
s.refresh();
s.bind('overNode outNode clickNode doubleClickNode rightClickNode', function(e) {
  console.log(e.type, e.data.node.label, e.data.captor);
});
s.bind('overEdge outEdge clickEdge doubleClickEdge rightClickEdge', function(e) {
  console.log(e.type, e.data.edge, e.data.captor);
});

I added these in the provided event sample, and the added edge do not hover or fire overEdge event.

Note :
To make it more clear, if edges are added by array ( the way example does it, in events.html fromexamples package) they hover, no problem. If I add them by graph.addEdge method, the hover will not work.

**Comment by v01tech** [comment]
I have the same issue with dynamically added nodes. Is there any workaround for edge hover issue?

By the way, when using 
`s.startForceAtlas2({worker: true, barnesHutOptimize: true});`
node related 'in' and 'out' events are dispatched twice.

**Comment by 21stcaveman** [comment]
@v01tech , There is a new pull request to fix some edge event binding issues : #494
I tried merging the changes with my build but they did not help solve this particular issue. It may help with the issue you mentioned.

**Comment by 21stcaveman** [comment]
Ok, for anyone else experiencing this, adding "size" to my edges fixed the problem. Looking at the code, renderer should look for the size property and if can not find it, assign value 1 to size, but for some reason if you don't set size for edges, it doesn't work.

**Comment by liobouchan** [comment]
This issue continues now at 24 October 2018,  i have to add the Edge size to fix the problem thanks @21stcaveman
