### ISSUE TITLE
Export shim failing in browserify

### ISSUE THREAD

**Issue by Yomguithereal** [jacomyal/sigma.js#484]
There seems to be something fishy here. Time to rewrite sigma browserify style?

**Comment by hugomrdias** [comment]
+1 or just replace all those .call(this) with .call(window)

**Comment by Yomguithereal** [comment]
We soon plan to shift the library to browserify altogether. So I guess I will be able to close the issue then :).

**Comment by hugofqueiros** [comment]
+1

**Comment by deanshub** [comment]
:+1: 
after migrating, please make sure that this works also in webpack
is there any workaround in the meantime?

**Comment by yurynix** [comment]
IMO, it's more convenient to make plugin(s) export install function:
```
module.exports = function (glob, sigma) {
...(replaces call(this) with call(glob)...
}

import { default as sigma } from 'sigma';
import { default as sigmaForce } from 'sigma/build/plugins/sigma.layout.forceAtlas2.min.js';
sigmaForce(window, sigma);
```
(I've actually patched it like that for my project that uses webpack)

or something like that: https://github.com/cytoscape/cytoscape.js-spread/blob/master/src/index.js

**Comment by Compynerd255** [comment]
+1

In fact, I don't see this being very difficult to do at all - the only thing that Sigma appears to expose is the Sigma namespace object itself.

**Comment by ekkis** [comment]
was this ever resolved? is there a recipe for using the library under browserify?

**Comment by chuckgenco** [comment]
Is there any update?
