### ISSUE TITLE
Sigma doesn't render until browser window has been resized.

### ISSUE THREAD

**Issue by tylerdmace** [jacomyal/sigma.js#489]
Not sure what is causing this but most of the time my sigma graphs aren't rendering until the moment I start to resize the window. As you can see from the below examples, I've got a very simple and straight forward setup. Any ideas?

Setup: MEAN stack app -- working with Angular on the front end (perhaps the source of my issue)

Angular Controller where I instantiate the sigma plot:

      $scope.plot = new sigma({
        graph: $scope.sessionsDataObject.convertedData,
        container: 'sigma-ulam-spiral-sessions',
        settings: {
          defaultNodeColor: 'rgb(107, 146, 5)'
        }
      });

HTML:

     <div id="sigma-ulam-spiral-sessions" class="graph-sigma"></div>

CSS: 

     .graph-sigma {
	max-width: 800px;
	height: 500px;
	margin: auto;
	border: 1px solid black;
     }

**Comment by tylerdmace** [comment]
Doing $scope.plot.refresh(); doesn't seem to do anything even when done right after instantiating the graph (new sigma).

**Comment by A----** [comment]
I'm too using it in an AngularJS context. Admittedly in a directive, but it works.

Your issue seemed consistent with a lack of `refresh()` (http://jsfiddle.net/x1myshvx/) but I may be wrong.

**Comment by bmonty** [comment]
I have a directive for sigma that calls `.refresh()` and `window.dispatchEvent(new Event('resize'))` after each time I add/remove something to the graph, and I still have to physically move the window to get the refresh to happen.  

Also, I have the sigma container div inside a bootstrap tab.  Is there anything special for this config?

**Comment by bmonty** [comment]
One other thing I've noticed.  When you switch to the tab with sigma on it, the nodes in the graph all sit on top of each other.  If I trigger a refresh, the plot appears as normal.

**Comment by A----** [comment]
OK, I forked my fiddle to put the sigma container in an hidden div container (similar to a Bootstrap tab): http://jsfiddle.net/6xx29hym/1/ . You're right, `refresh()` isn't enough.

With Bootstrap, can that be solved by hooking said lines on tab events? (http://getbootstrap.com/javascript/#tabs-events)

**Comment by bmonty** [comment]
@A----, yes that does work...sometimes.  I believe the issue is the content div elements in the Bootstrap tab don't have a length or width until the div is first displayed.  In order to make it work, I had to come up with all kinds of hacks to trigger `refresh()` calls on tab changes.  I also had to implement a slight delay between a tab being selected and the hidden div being revealed.

**Comment by A----** [comment]
I dug a little bit deeper and there's something there. When the container is hidden, its offset(Width|Height) are 0. http://jsfiddle.net/6xx29hym/2/

When `refresh()`ing, it calls `render()` on each renderer of each camera, which, in case of a canvas renderer, calls `resize()`. It uses the offset(Width|Height) of the container.

Thing is, there's been quite a few changes regarding this. It might be worth it to check what's what with a fresh master build.
