### ISSUE TITLE
Scene background-color option

### ISSUE THREAD

**Issue by Flo-Schield-Bobby** [jacomyal/sigma.js#491]
A background-color is actually not in option because, according to the settings documentation, as the layers are transparent, adding a background-color to the container is enough -- at least in most cases --.

However, what if I would like to screenshot the graph as a PNG image with HTML5 download-link ?

I would basically do something like this :

HTML5 :

    <div id='graph-container'>
        <a id='download-link' href='#' download='graph.png'>Download</a>
    </div>

JavaScript :

    sigma.renderers.def = sigma.renderers.canvas;
    var sigmaInstance = new sigma('graph-container', {
        sideMargin: 1
    });
    
    // Do whatever you want with the graph...
    // var data = {};
    // sigmaInstance.graph.read(data);
    
    sigmaInstance.refresh();
    
    var downloadLink = document.getElementById('download-link');
    
    downloadLink.addEventListener('click', function (event) {
        downloadLink.setAttribute('href', sigmaInstance.renderers[0].domElements.scene.toDataURL());
    });

So in this case, I would get a nice screenshot of the graph but without the same background...

JSFiddle : http://jsfiddle.net/FloSchieldBobby/45bpbyra/

Of course an option

I'm ready to write a small plugin to support a background ;
Just wondering what would be the best :
- Adding a new canvas layer as background would we the most performant way (so it would only be drawn initially, then at the resize), however for my needs, I do not know if I could mix two canvas.toDataURL() content in a same image just in javascript ;
- Adding an option for a background-color (disabled by default, only drawn if not transparent) for the ".sigma-scene" canvas, a bit less performant, because redrawn more often...

Any advice about it ?

**Comment by Yomguithereal** [comment]
There is a [plugin](https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.renderers.snapshot) doing exactly what you need.

You can supply a color to the the `background` parameter if you need a background color for your png.

**Comment by Flo-Schield-Bobby** [comment]
Ahem, okay, I will watch the repository better next time...
Thanks !

**Comment by Yomguithereal** [comment]
No problem @Flo-Schield-Bobby. Tell me if you find bugs or quirks with the plugin. It hasn't been tested a lot.

**Comment by Flo-Schield-Bobby** [comment]
In fact it doesn't seem to be in the ````build/plugins```` repository after executing ````npm run build````, do I need to build it in any other way ?

**Comment by Yomguithereal** [comment]
It might be because bower pulls from a release tag and the plugin was included in the Gruntfile later than the latest release.

This is the [part](https://github.com/jacomyal/sigma.js/blob/master/Gruntfile.js#L71-L86) in the Gruntfile where things happen. I am not sure whether this is an acceptable workaround for your production workflow here. Maybe telling bower to hit a precise commit of the library should work until further release is made.

**Comment by Flo-Schield-Bobby** [comment]
It is for a student prototype so everything is acceptable for me currently !
Just for my general culture, how do we say something to bower ? With an issue for instance ?

**Comment by Yomguithereal** [comment]
What I meant was to indicate in your bower.json file a precise commit of this repository to hit so you have the latest dev version rather than the latest release.

Like this:

```json
dependencies: {
    'sigma': 'git://github.com/jacomyal/sigma.js.git#70b4166290'
}
```

**Comment by Flo-Schield-Bobby** [comment]
Oh, it makes sense... Thanks again :)
