### ISSUE TITLE
Custom hover plugin hook

### ISSUE THREAD

**Issue by rjbriody** [jacomyal/sigma.js#496]
Is there a hook for injecting a plugin to handle the hover event? I know I can catch the mouseOver event but I'd like to override and/or augment the functionality that currently displays the node label.

I found this random pic that basically highlights the intended outcome: http://i1-scripts.softpedia-static.com/screenshots/sigma-js_2.png

Ideally this plugin hook would:
- provide a way to override or augment the current functionality
- make it easy to handle zooming
- prevent the plugin implementation from having to worry about the underlying renderer type

If such a plugin hook does not exist, then would it be possible to add one?

**Comment by sheymann** [comment]
How about overriding [`sigma.canvas.hovers.def.js`](https://github.com/jacomyal/sigma.js/blob/master/src/renderers/canvas/sigma.canvas.hovers.def.js)?

**Comment by rjbriody** [comment]
Yes how about that! Exactly what I was looking for. Better than some of the other solutions I've seen in the issues because the position is preserved on move and zoom.

I hacked the "hide logic" into my outNode event handler but I'll dig around to see where the label is being cleared and see about overriding that as well.

Thanks a lot for the excellent suggestion.
