### ISSUE TITLE
A* plugin

### ISSUE THREAD

**Issue by A----** [jacomyal/sigma.js#501]
I wrote an A* implementation for sigma.
Repo: https://github.com/A----/sigma-pathfinding-astar

I can make a PR if you want.

**Comment by sheymann** [comment]
@A---- I'm interested in!

**Comment by A----** [comment]
You got a PR here #505. Feel free to pick it on linkurious.
Also, there's an example in the repository which isn't in the pull request.

**Comment by sheymann** [comment]
Awesome @A---- ! I'd prefer a proper PR from you on https://github.com/Linkurious/linkurious.js to preserve the history, and I'll add you as a contributor.

**Comment by A----** [comment]
Done.

**Comment by A----** [comment]
Closing issue. See PR #505.
