### ISSUE TITLE
Lack of edge events

### ISSUE THREAD

**Issue by holographer** [jacomyal/sigma.js#512]
Is there a plan to add edgeClick edgeRightClick edgeHover events or are those provided via plugins or something else?
I can't see that in the events.html example and I don't see how to create those events.
Am I missing something?

**Comment by qinfchen** [comment]
`clickEdge`, `doubleClickEdge`, and `rightClickEdge` are already there.  See
https://github.com/jacomyal/sigma.js/blob/c6fa5ba6bc8fa98ea1ef439454bfe833411482b1/src/misc/sigma.misc.bindEvents.js

**Comment by Yomguithereal** [comment]
@opdb, for another example, you can see [this](https://github.com/jacomyal/sigma.js/blob/master/examples/events.html) example.

**Comment by opdb** [comment]
On 2015-02-02 01:04, Qinfeng Chen wrote:
> `clickEdge`, `doubleClickEdge`, and `rightClickEdge` are already there. 
>  See
> https://github.com/jacomyal/sigma.js/blob/c6fa5ba6bc8fa98ea1ef439454bfe833411482b1/src/misc/sigma.misc.bindEvents.js
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jacomyal/sigma.js/issues/512#issuecomment-72400960

Apologies, I don't know how I missed that. It was puzzling that I 
couldn't find them.

**Comment by opdb** [comment]
On 2015-02-02 07:04, Guillaume Plique wrote:
> @opdb, for another example, you can see
> [this](https://github.com/jacomyal/sigma.js/blob/master/examples/events.html)
> example.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jacomyal/sigma.js/issues/512#issuecomment-72424627

Thank you, I think I must have been using an outdated release that 
didn't yet have those events.
Will update accordingly.

**Comment by bornakke** [comment]
Is it correct that all these events are only available when EdgeHovering has been enabled?

**Comment by Yomguithereal** [comment]
Yes indeed @bornakke.

**Comment by ThorbenQuast** [comment]
Hello,

I have just tried the event "edgeClick" that is provided by the indicated plugin in my setup.
Hereby, I noticed two things:
1) Clicking on edges that are perfectly aligned horizontally especially those close to the borders of the graph is really hard and sometimes even impossible (as if there was no dedicated area to click on).
2) Everytime a new graph is loaded and the functionality is assigned, there is ~100MB added to my RAM which is not deleted until closure of the webpage. I am using Ubuntu 14 with the most recent versions of Firefox and Chromium (I encounter this problem with both browsers).

Can anyone help?

**Comment by Yomguithereal** [comment]
Hello @ThorbenQuast:

1) The edges are indexed by a quadtree which makes some edges which are perfectly horizontal or vertical sometimes hard to index correctly.
2) What is the size of your graph's data?

**Comment by ThorbenQuast** [comment]
![ee_z__ff](https://cloud.githubusercontent.com/assets/6507652/8229202/0cf46664-15b5-11e5-8405-9b04b03a9c55.png)
![b](https://cloud.githubusercontent.com/assets/6507652/8229203/0cf4c460-15b5-11e5-987f-44b1f8f7e4ad.png)

I would claim my graphs have a rather moderate size. By reload, it is meant that the div in which the sigma graph is placed is emptied using jquery's .empty() method. After placing the control bar (top right corner in the pictures), I call "this.s = new sigma({
				graph: this.structure,
				renderer: {
					container: this.Node.children()[0],
					type: 'canvas'
				},
				settings: this.sSettings
			});" as it is done in most of the provided examples.
The graph settings in this.sSettings include "enableEdgeHovering: true" as it must in order for the edges to be clickable. If this option is set to false, besides giving up on the desired functionality, the RAM is not stacked at each reload. In addition, when reloading a similar graph with clickable nodes, the allocated RAM at each reload is just a minor fraction of what is needed here.
Therefore, I assume that something is not completely efficient for the edge events.

The appropriate code ("update()" = relevant function) is available in a non-github repository:
https://forge.physik.rwth-aachen.de/projects/vispa-pxl/repository/revisions/55b2fb5bb175/entry/pxlbrowser/static/js/views/feynman.js

Any help is highly appreciated.

**Comment by Yomguithereal** [comment]
@ThorbenQuast:

1) do you kill your graph through `s.kill` when "reloading"? Else you would probably have memory leaks.
2) The edge quadtree is by no mean efficient and, not being its author, I cannot assess whether something is broken or if some leak is present somewhere (I will try nonetheless, to find the problem). If I sum up what you say: there seems to be something consuming an absurdly high amount of RAM when using the edge events? Is that it?

**Comment by ThorbenQuast** [comment]
@Yomguithereal:

1) No, I had not killed the graph when reloading but have now added it. 
2) Yes, that is what I have meant.

Since the the usage of s.kill() I have noticed that making the graph still requires lots of RAM (~100MB) but unlike before most of the allocated memory is now deallocated after a couple of seconds posterior to the reload. I think this should be something I can live with.

Thank you very much for the help.
