### ISSUE TITLE
how can I drag and select multiple nodes together ? 

### ISSUE THREAD

**Issue by ellavs1** [jacomyal/sigma.js#516]
sigma.js has plugin of dragNodes - but it works for individual node.

in case I have a sigma circle of nodes , I would like to choose the center node of the circle and move all the nodes to another position. 

look at https://marketplace.gephi.org/plugin/concentric-layout/ - this is the layout which I have . I have many circles like these and I would like to be able to move them

thanks

**Comment by sheymann** [comment]
@ellavs1 @qinfchen It's now available in https://github.com/Linkurious/linkurious.js/tree/plugin/dragNodes/plugins/sigma.plugins.dragNodes

**Comment by deanshub** [comment]
you can use the plugin that i wrote for multiple selection
http://stackoverflow.com/questions/26945345/sigma-js-is-there-a-way-to-drag-select-multiple-nodes/28790722

**Comment by sheymann** [comment]
@ellavs1 do the answers solve your issue?
