### ISSUE TITLE
Using sigma.parseGexf.js or sigma.parsers.gexf.min.js

### ISSUE THREAD

**Issue by snassimr** [jacomyal/sigma.js#520]
Hi , 
I am very confused if to use first or second ?

I saw the example where the instance is done with first js . Is the first is somthing old ?

If there is second how can I set all parameters  : drawingProperties , graphProperties or mouseProperties like it can be done with sigma.parseGexf.js

Thanks, Nissim

**Comment by Yomguithereal** [comment]
You should use the second one as I think the first one was relevant to an older version of sigma.

To set parameters, here is what you can do:

```js
sigma.parsers.gexf(
  'myGraph.gexf',
  {
container: 'myContainer' }
);
```

**Comment by zhangqteradata** [comment]
Hi Nissim
     I want to these  parameters : drawingProperties , graphProperties or mouseProperties.How to change it 
Thanks Qiong
