### ISSUE TITLE
Browser Incompatibility and Debugging Failures with No Exceptions

### ISSUE THREAD

**Issue by TwoBitAlchemist** [jacomyal/sigma.js#522]
I have sigma.js working on Chromium 40 (Linux) using an AJAX POST to retrieve JSON then calling

    minimap.graph.clear().read(data);
    minimap.refresh();

The same code simply does not work on Firefox 35 (Linux) and maybe Chrome 40 Windows. No exception is thrown and nothing is logged to the console, but nothing is displayed in the canvas, which is correctly positioned. I am at a loss as to how to even begin debugging this. What should I try? I will be happy to provide additional information upon request; I'm not exactly sure what is relevant that I could post at the moment.

**Comment by Yomguithereal** [comment]
Can you try to:

1) Switch to default `canvas` just to see whether it could be a webl issue:

```js
sigma.renderers.def = sigma.renderers.canvas;
```

2) Print out the contents of your graph into the console to assess whether your data has been correctly loaded:

```js
s.graph.nodes();
s.graph.edges();
```

**Comment by TwoBitAlchemist** [comment]
Interesting. I supposed it was already using the canvas renderer, but adding the first line you suggested fixed the issue at least on Linux Firefox. I won't be able to test Win Chrome until tomorrow but I am satisfied with this. Thanks for the quick feedback!
