### ISSUE TITLE
Adding edge labels to JSON parser

### ISSUE THREAD

**Issue by rscott1992** [jacomyal/sigma.js#533]
I am having trouble building a sigma.js graph with edge labels, with the input for the graph using an external JSON file. Here is the js code:

    <script>
    sigma.parsers.json('/project/data/graph.json', {
      container: 'graph-container',
      renderer: {
        container: document.getElementById('graph-container'),
        type: 'canvas'
      },
      settings: {
        edgeLabelSize: 'proportional'
      }
    }
    </script>
The error generated on chrome comes from the penultimate '}' and says "Uncaught SyntaxError: Unexpected token /". Below is an example of my JSON file:

    "nodes": [
        {
            "id":"1",
            "label":"Station 1",
            "x" : "0",
            "y" : "0",
            "size" : "10"
        },
        {
            "id":"2",
            "label":"Station 2",
            "x" : "6",
            "y" : "3",
            "size" : "10" 
        } ],
    "edges": [
        {
            "id" : "1",
            "source" : "1",
            "target" : "2",
            "label" : "Rail 1"
        } ]
I'm pretty new to js so it's hopefully something simple, still any assistance is much appreciated! :)

**Comment by withforesight** [comment]
did you try valid JSON
check it here http://jsonlint.com/

{
    "container": "graph-container",
    "renderer": {
        "container": "document.getElementById('graph-container')",
        "type": "canvas"
    },
    "settings": {
        "edgeLabelSize": "proportional"
    }
}

**Comment by Yomguithereal** [comment]
Hello @rscott1992, could you give us more informations like which line is throwing the Error. First thing I notice is that you forgot a closing parent when calling the `sigma.parsers.json` function and that the json sample you show is not valid (but I assume it's because you truncated it).

**Comment by rscott1992** [comment]
Hi @Yomguithereal, yes I have truncated some of the code, the full JSON file I am using is valid, checked with JSONLint (Thanks, @withforesight ).There is also some code in function(s), after the settings that I didn't include for this question and thus forgot the closing parent.
Okay, the error is actually being thrown in my html code? I am using a template from Bootstrap. Perhaps, there is an issue with "container-fluid"? Here is the full HTML code:

      <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container-fluid"> //Error is being thrown on this line
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="index.php">Train Route Planner</a>
            </div>
          </div>
        </nav>

        <div class="container-fluid">
          <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
              <ul class="nav nav-sidebar">
                <li><img class='logo' src='img.png' alt='Train Logo'>         </li>
                <li><br></li>
                <li>Location</li>
                <li><input type='text' class="suggest" id='location'></li>
                <li><br></li>
                <li>Destination</li>
                <li><input type='text' class="suggest" id='destination'></li>
                <li><br></li>
                <li><input type='submit' value='Submit'></li>
            </div>
            <div id = "container">
              <div id="graph-container"></div>
            </div>    
          </div>
        </div>

      </body>

**Comment by Yomguithereal** [comment]
The HTML code cannot throw errors, only JavaScript can. So either you have some JavaScript code somewhere in the HTML or the problem is elsewhere. Is your code public somewhere?  I am afraid I won't be able to help you without being able to reproduce your problem in some way.

**Comment by apitts** [comment]
What happens if you add a parenthesis at the end of your script?

```
<script>
sigma.parsers.json('/project/data/graph.json', {
  container: 'graph-container',
  renderer: {
    container: document.getElementById('graph-container'),
    type: 'canvas'
  },
  settings: {
    edgeLabelSize: 'proportional'
  }
});
</script>
```

**Comment by apitts** [comment]
Oh - I see you have discussed that above already...I suspect it may be a similar syntax error elsewhere if note there.

**Comment by rscott1992** [comment]
Okay, I uploaded the code [here](https://github.com/rscott1992/LondonUnderground). Index.php is the main file. js/initial_graph_draw.js contains the above JS code and data/graph.json contains the JSON data.

**Comment by Yomguithereal** [comment]
Okay @rscott1992, I've found the problem: you are using comments in your json file with `//`. Comments are not supported by JSON. Therefore, your file is not valid. Remove the comments and you will be able to continue.

**Comment by rscott1992** [comment]
Thanks @Yomguithereal, I updated the code I am now getting a new error saying:
 if(!(options.container instanceof HTMLElement))
      throw 'Container not found.';
But in index.php I have a container and graph-container?

**Comment by Yomguithereal** [comment]
You are registering a container twice [here](https://github.com/rscott1992/LondonUnderground/blob/master/js/initial_graph_draw.js#L17-L20).

**Comment by rscott1992** [comment]
Thanks @Yomguithereal this works now! Much appreciated!
