### ISSUE TITLE
cannot get dragNodes to work [using parsers.json and forceAtlas2]

### ISSUE THREAD

**Issue by amplify211** [jacomyal/sigma.js#534]
I have been struggling with this for a while now.. the graph works fine returning data from a json file and running forceAtlas2.. but I cannot seem to get the correct combination of magic potion to get the dragNodes plugin to work.

I have imported everything that was in the examples.. here is my current code if someone could please point me in the right direction. I have tried several other locations to put the "dragListener" with no luck. The current error that is returned from the firefox console is "TypeError: invalid 'instanceof' operand sigma.renderers.svg which points to line 64 in sigma.plugins.dragNodes.js  "if (renderer instanceof sigma.renderers.svg) {"

current partial code:

sigma.renderers.def = sigma.renderers.canvas;
        var g = {
            nodes: [],
            edges: []
        };
        s = new sigma({
            graph: g,
            container: 'containerSigma',
            settings: {
                minNodeSize: 1,
                maxNodeSize: 10,
                sideMargin: 1,
                minEdgeSize: 0.01,
                maxEdgeSize: 4,
                defaultLabelSize: 9,
                labelThreshold: 5,
            }
        });

```
    var thepath = "MY_SPECIAL_PATH";
    sigma.parsers.json(thepath, s, function() {
        var i,
                nodes = s.graph.nodes(),
                len = nodes.length,
                edges = s.graph.edges(),
                num_edges = edges.length;
        // Refresh the display:
        s.refresh();

        s.startForceAtlas2({worker:true});

        var sec_proc = 5000;
        //make sec_proc a function of # nodes and edges
        sec_proc = (((len + num_edges) / 1000))*1300 + sec_proc;

        setTimeout(function() {
                s.stopForceAtlas2();
                              //add dragListener after forceAtlas has finished
                var dragListener = sigma.plugins.dragNodes(s, s.renderers[0]);
            }, sec_proc);
    });
```

**Comment by knoxsp** [comment]
Hi amplify211,
I had this issue and after some looking around, it seems that the svg renderer was added since I downloaded my version of sigma.min.js. The plugin is therefore looking for a renderer that doesn't exist in my code. The simplest solution is to rebuild sigma.min.js as per the instructions or download a newer version of sigma.min.js.
Hope this helps.
