### ISSUE TITLE
ForceAtlas has an error after adding/removing nodes

### ISSUE THREAD

**Issue by pabloem** [jacomyal/sigma.js#542]
I am working on a small demo, where users can add and remove nodes to a graph. Each time a node is added, the ForceAtlas layout algorithm is run for a few milliseconds, and then it's stopped.
I'm finding that if we add some nodes, and remove a few of them, when we run ForceAtlas, there will be an exception.
I looked into it and it seems related to the ByteArrays in ForceAtlas not being recomputed when nodes are added/removed. Is this by design?
I can provide a small demo to show this issue.

Thanks
Pablo

**Comment by Yomguithereal** [comment]
Hello @pabloem. This is unfortunately a known issue (#504). We currently lack of a hook informing that the graph's data has been updated. There is a silly workaround presented in the other issue if you need a quick fix before we can do anything about this.

**Comment by pabloem** [comment]
Okay, I'll close this, then, since there's an issue tracking this already.
The workaround helped, by the way. Thanks : )
