### ISSUE TITLE
Edge hovering slows down clickNode event

### ISSUE THREAD

**Issue by bornakke** [jacomyal/sigma.js#543]
Hi All,

Whenever i turn on edgeHovering the triggering of the clickNode event are delayed 2-3 seconds. Would you think this were due to the extended rendering that the hover effect results in or does it sound more like an error? And if this is a naturel rendering problem, is it then possible to make edges clickable without enabling the edgehovering?

Best regards
Tobias

**Comment by Yomguithereal** [comment]
Edge hovering as well as edge clicking enables an edge quad tree so that the operations are possible. Problem is this quad tree is very slow and might indeed introduce hellish latencies on huge graphs. It should be possible to disable edge hovering in some way or another. Let me check that.

**Comment by bornakke** [comment]
Thank you.

**Comment by sheymann** [comment]
`enableEdgeHovering` is used to both hover and activate the spatial indexing of edges. Weird that clickNode is affected by this setting.

@bornakke Do you perform any `sigmaInstance.refresh()` on click?

**Comment by bornakke** [comment]
Yes.

**Comment by sheymann** [comment]
That's it. When calling this method, nodes and edges are spatially indexed. You can skip the re-indexing process here because nodes/edges do not move on click. Call:

`sigmaInstance.refresh({ skipIndexation: true })`

doc: https://github.com/jacomyal/sigma.js/wiki/Public-API

Does it fix the issue?

**Comment by bornakke** [comment]
Yes that solved it :) Thnk you for the help.

So for me to fully understand the problem: Reindexing is only needed when nodes has been moved?

**Comment by sheymann** [comment]
Yes: the goal of spatial indexing is to be able to match nodes or edges at are "near" the location of the pointer. At every tiny move of the pointer, sigma checks if it is "above" a node or an edge. This can happen a hundred times per second. However looping over all nodes and edges to check their position would be too costly, so we "index" nodes and edges in small boxes and loop over the nodes and edges that belongs to the box where the pointer is located. Knowing which nodes or edges are in these boxes is called indexing. It takes time to build, after that it's fast to query.

I've written it with more accuracy [here](https://github.com/Linkurious/linkurious.js/wiki/Performance#spatial-indexing-and-the-use-of-refresh).

**Comment by bornakke** [comment]
Beautifully - thank you :+1:
