### ISSUE TITLE
Document or remove `renderer.resize(false)` usage

### ISSUE THREAD

**Issue by ryan-williams** [jacomyal/sigma.js#547]
There are a [few](https://github.com/jacomyal/sigma.js/blob/d76227e8f8ae68ed577e123bc6450a4e2b970c77/src/renderers/sigma.renderers.canvas.js#L102) [calls](https://github.com/jacomyal/sigma.js/blob/d76227e8f8ae68ed577e123bc6450a4e2b970c77/src/renderers/sigma.renderers.canvas.js#L144) to renderers' `resize` methods that pass a single argument `false`, despite [the method signature specifying a `w` and `h`](https://github.com/jacomyal/sigma.js/blob/d76227e8f8ae68ed577e123bc6450a4e2b970c77/src/renderers/sigma.renderers.canvas.js#L358). Are these vestigial uses? Can we document or update them?

**Comment by louy2** [comment]
From the sourcecode, if any of the parameters are not defined (not passed in) [the following](https://github.com/jacomyal/sigma.js/blob/d76227e8f8ae68ed577e123bc6450a4e2b970c77/src/renderers/sigma.renderers.canvas.js#L374) is executed:

```javascript
      this.width = this.container.offsetWidth;
      this.height = this.container.offsetHeight;

      w = this.width;
      h = this.height;
```
I need explanation to understand it though.
