### ISSUE TITLE
Clarify relationship between nodes' x, y, and size properties, initial zoom level

### ISSUE THREAD

**Issue by ryan-williams** [jacomyal/sigma.js#548]
I am new to SigmaJS and am confused by the semantics around the `x` and `y` properties given to nodes and the `size` property on edges and nodes.

Here is a simple graph I just created:

```
var g = {
  nodes: [
    { id: '1', x: 10, y: 10, size: 10 },
    { id: '2', x: 20, y: 20, size: 20 }
  ],
  edges: [
    { id: '1-2', source: '1', target: '2', size: 10 }
  ]
};

s = new sigma({
  graph: g,
  container: 'sigma-container'
});
```

When I render it on a page, I see:

![](http://f.cl.ly/items/1I3d1S3H1C0T352S2m38/Screen%20Shot%202015-04-23%20at%205.02.08%20PM.png)

Several things are inconsistent with what I expected:
- the distance between the nodes is actually ~100x their sizes, even though the `x`\- and `y`-coordinate differences are 10 and 10 (resp.) and the nodes' `size`s are 10 and 20.
- the thickness of the edge is miniscule compared to the size of each node, despite having been specified as 10 compared to the nodes' 10 and 20.
- the nodes are not 10 and 20 pixels tall; they look to be about 9px and 16px, resp.
- changing the node `size`s to 50 and 100 results in the same rendered graph; the nodes are ~9px and ~16px across.

Clearly there are some assumptions being made about what the `x`, `y`, and `size` properties mean that I don't understand. Can someone explain how the sizing works and why it works that way, and can we document some of these things?

Is there any way to draw a graph where the nodes' sizes in pixels match their `size` properties?

Thanks!

**Comment by Yomguithereal** [comment]
Hello @ryan-williams,
by default, sigma will rescale the graph so it can be shown in a visually appealing way without forcing you to deal with the node's position relative to your camera/container etc.

If you want to disable this behavior, you can set the `autoRescale` setting to false or fiddle with the `minNodeSize`, `maxNodeSize` etc. settings that can alter the rescaling so the result is more adapted to your need.

Under the hood, sigma will store different prefixed versions of your nodes' sizes and positions. Usually, you'll have the node's basic x,y plus the camera's one and the renderer's one.

**Comment by ryan-williams** [comment]
Thanks for the explanation, @Yomguithereal! Here are the things I've learned that were tricky for me:

* `minNodeSize`/`maxNodeSize`: these top-level settings are the values *in pixels* that govern how nodes are rendered.
* `node.size`: this is **not** pixels; nodes' `size` attributes are honored *relative to each other*, but subject to the largest nodes being rendered as `maxNodeSize` pixels (defaults to "just" 8px).
* `edge.size`: basically the same as `node.size` above, this is mostly just an indication of *relative* edge sizes; the pixel sizes are in practice governed by `minEdgeSize`/`maxEdgeSize`, which default to `0.5` and `1`, resp.
* `node.x`/`node.y`: these are **each** scaled independently, of each other and of nodes'/edges' `size`s. The initial view will cause the graph to use 100% of the available space in each dimension, meaning that:
    * slopes may not be as one expects
    * the `size`s of nodes (and edges) will not be comparable in any meaningful way to the `x`/`y` coordinates governing nodes' positions.
* the settings discussed here (and enumerated [on the wiki](https://github.com/jacomyal/sigma.js/wiki/Settings)) should all go in to one object, despite living under different section headers on that wiki page, and that object should live in a top-level `settings` field passed to the `sigma` constructor, e.g.:
```
  s = new sigma({
    graph: g,
    settings: {
      nodesPowRatio: ratio,
      edgesPowRatio: ratio,
      maxNodeSize: maxNodeSize,
      maxEdgeSize: maxEdgeSize,
      autoRescale: false,
    },
    renderer: {
      container: document.getElementById('sigma-container'),
      type: 'canvas'
    }
  });
```
* `nodesPowRatio`/`edgesPowRatio` were important for me to understand, as they glue together the "virtual"/relative sizes that nodes/edges are specified as with the actual pixel-sizes that they're rendered as, at different zoom levels.

Let me know if you think any of this is worth adding to the wiki and I'll take a crack at it, otherwise this issue can hopefully serve as breadcrumbs for anyone that has similar confusion.

I understand why these defaults can be useful in a variety of situations, but they were sufficiently different from what I've come to expect from using other frameworks that I feel it's worth explaining a little more explicitly.

**Comment by jdbevan** [comment]
Thanks @ryan-williams! *Very* helpful!

**Comment by ckald** [comment]
Hi. I tried to follow the ideas of @ryan-williams , but no luck yet. What I'm trying to do is to define the maximum node radius as the half of the minimal distance in the graph (such that they never overlap).

I've set `nodesPowRatio = 1` for normal scaling and would like to pass the nodes sizes in the same units as the coordinates. But when I set `autoRescale = false`, the plot disappears. I suspect it is just too small to see. How do I define the zoom values then?

What should I do?

**Comment by AndreyRomanyukov** [comment]
Hello, @ckald ! 

From documentation
https://github.com/jacomyal/sigma.js/blob/9708a0935c8215c468074dcdc85262fa46d44b57/src/sigma.settings.js
```
// {number} Determine the size of the smallest and the biggest node / edges
//          on the screen. This mapping makes easier to display the graph,
//          avoiding too big nodes that take half of the screen, or too
//          small ones that are not readable. If the two parameters are
//          equals, then the minimal display size will be 0. And if they
//          are both equal to 0, then there is no mapping, and the radius
//          of the nodes will be their size.
minEdgeSize: 0.5,
maxEdgeSize: 1,
minNodeSize: 1,
maxNodeSize: 8,
```


To convert your units u into pixel coordinates px as 1:1 you should use these settings:

```
minNodeSize: 0,
maxNodeSize: 0,
minEdgeSize: 0,
maxEdgeSize: 0,
nodesPowRatio: 1,
edgesPowRatio: 1,
autoRescale: false
```

Then
coordinates will convert as:
`px = u/ratio`
node's radius will convert as
`px = u/(ratio^nodesPowRatio)`

ratio is sigma.camera.ratio, or camera zoom
Default zoom properties are:
zoomMin = 0.0625 (camera is most close)
zoomMax = 2 (camera is most far)
starting zoom = 1

node.size - radius of node
