### ISSUE TITLE
canvas vs svg

### ISSUE THREAD

**Issue by antonioaltamura** [jacomyal/sigma.js#559]
Hi, I remember there are some limitations using svg render, but I can't remember exactly..which are those?

**Comment by Yomguithereal** [comment]
Hello @alfredopacino, apart from SVG being less performant than canvas (I mean the technologies, not because of the library's implementation), I remember than the hover might not be totally identical in SVG and in canvas. If you need to use SVG, you probably want to use the renderer freestyle mode so you can use CSS comfortably to style your elements.

**Comment by alfredopacino** [comment]
yes, I wondering if there is an easy way to make the graph more eye-catching..
https://github.com/Linkurious/linkurious.js/issues/92#issuecomment-93999420

**Comment by Yomguithereal** [comment]
You can do pretty much everything you could do with SVG so yes you could achieve more eye-catching features very quickly. Just know that SVG doesn't scale as well as canvas and webgl. So on big graphs, this won't work very well. There is an example of graph using a "freestyle" SVG renderer [here](https://github.com/jacomyal/sigma.js/blob/master/examples/svg-freestyle-renderer.html#L124-L129) if you want.

**Comment by alfredopacino** [comment]
I used exactly the lines you linked but the render is still canvas.. what am I missing?

**Comment by Yomguithereal** [comment]
You'll have to use an up to date version of sigma (by this I mean the master branch of this repository) if you want the SVG renderer to work as some core files were modified so it was possible to use it. Did you version your modified version of sigma through git? You can maybe attempt to merge master in it and check the conflicts.

**Comment by alfredopacino** [comment]
I've just replaced the src folder and luckly all works fine, should I replace the plugin folder too? just the dragnode plugin is heavly modded.
Istead of addRender, how can I set the default render as svg?

**Comment by Yomguithereal** [comment]
I don't know about the dragnode plugin but I guess you should if you want to use it.

You can type this line if you want to set the default renderer as svg:

```js
sigma.renderers.def = sigma.renderers.svg;
```

However you'll still need to register the renderer through constructor polymorphism or throug addRenderer if you want to enable freestyling.

**Comment by alfredopacino** [comment]
uhm the addRender method causes a js error:
Uncaught TypeError: Cannot read property 'call' of undefined
http://www.awesomescreenshot.com/image/164397/cf20cc454bd5a40e2dca5a6e0d0da700

**Comment by Yomguithereal** [comment]
I think you don't have the `./misc/sigma.misc.bindDOMEvents.js` file.

**Comment by alfredopacino** [comment]
I have it, as I said I downloaded the latest release and replaced all the src folder.
thanks
