### ISSUE TITLE
edge orientation

### ISSUE THREAD

**Issue by alfredopacino** [jacomyal/sigma.js#562]
Hi, can I change the orientation of the edge? I would to render the arrow from the child to the parent.

**Comment by 21stcaveman** [comment]
@Yomguithereal I have this feature in my repo, let me know if this is something that should being added to the core or a plugin, and I'll create a PR.

**Comment by alfredopacino** [comment]
i guess it could be useful..

**Comment by 21stcaveman** [comment]
Please see PR #568

**Comment by alfredopacino** [comment]
so there is no need of sigmajs source code hack, it's just an external plugin, am i right?

**Comment by Yomguithereal** [comment]
Yes you are @alfredopacino.

**Comment by alfredopacino** [comment]
@21stcaveman thanks, your plugin works great.
