### ISSUE TITLE
label inside node

### ISSUE THREAD

**Issue by alfredopacino** [jacomyal/sigma.js#563]
Hi, looking this closed issue
https://github.com/jacomyal/sigma.js/pull/291
I thought the hover issue was solved, but it's still there.
There is a way to solve?

**Comment by sheymann** [comment]
A fix was merged on https://github.com/Linkurious/linkurious.js/pull/68 with a new setting called `labelAlignment`. 

It indicates how to choose the position of node labels. 
Available values: "right", "top", "bottom", "center", "inside" (i.e. label inside node when it's possible).

**Comment by alfredopacino** [comment]
so should I switch from sigma to likurious? should I just replace the scripts? the sintax for initialization, addnode, edge and all the sigma methods are the same, right?

**Comment by sheymann** [comment]
The changes are made in the Canvas node renderers. You can stick to Sigma if you load the modified renderers after loading Sigma.

**Comment by sheymann** [comment]
@alfredopacino does it solve your issue?

**Comment by alfredopacino** [comment]
yes I solved, thanks!

**Comment by doubleyu** [comment]
hi, @sheymann @antonioaltamura ,  i don't quite understand how to use sigma with linkurious. could you please paste some codes about how you have solved this problem? thank you !
