### ISSUE TITLE
Control Points for edges

### ISSUE THREAD

**Issue by felicedeluca** [jacomyal/sigma.js#566]
Hi,
I need to have control point(s) for the arc to a custom routing with Bezier Paths or other curve paths.

let an arc have:

source,
target,
controlPoint {x: y:}

how can I have the projected 'x' and 'y' with 'prefix'  for the control point in the sigma.canvas.edge.path hook?
The controlPoint is not calculated with source and target but passed in the data.

**Comment by sheymann** [comment]
Hello, override the edge renderers as a plugin and you'll be free to code your own path with specified control points.

**Comment by felicedeluca** [comment]
hi sheymann,
the point is that I need the projected coordinate (with 'prefix') of the control point.

I mean: the source and the target point of the edge are in the 'nodes' array and so they can be rendered with source['prefix' + x] source['prefix' + y] but, since the control point is a property of the edge it is referred to the not projected coordinate source[x] and source[y], I need to get controlPoint['prefix' + x] controlPoint['prefix' +y] to render it correctly with the plugin

**Comment by 21stcaveman** [comment]
@felicedeluca , For each edge, you can get the control point by using sigma.utils.getQuadraticControlPoint and sigma.utils.getSelfLoopControlPoints. You can get the camera prefix from s.camera.prefix
looking at sigma.classes.camera.prototype.applyView you can see this is how this functions maps a node :
```javascript
node[write + 'x'] =
        (
          ((node[read + 'x'] || 0) - this.x) * cos +
          ((node[read + 'y'] || 0) - this.y) * sin
        ) / this.ratio + (options.width || 0) / 2;
      node[write + 'y'] =
        (
          ((node[read + 'y'] || 0) - this.y) * cos -
          ((node[read + 'x'] || 0) - this.x) * sin
        ) / this.ratio + (options.height || 0) / 2;
```

based on that, what you want ( if I understood the question correctly ) would be something like this :
```javascript
var p = s.camera.prefix;
var cp = sigma.utils.getQuadraticControlPoint(node.source.x, node.source.y, node.target.x, node.target.y);
controlPoint[p + 'x'] =
        (
          (cp.x - s.camera.x) * Math.cos(s.camera.angle) +
          (cp.y - s.camera.y) * Math.sin(s.camera.angle)
        ) / s.camera.ratio + containerwidth / 2;
controlPoint[p + 'y'] =
        (
          (cp.y - this.y) * Math.cos(s.camera.angle) -
          (cp.x - this.x) * Math.sin(s.camera.angle)
        ) / s.camera.ratio + containerheight / 2;
```

I have not tested the code, this is just to give you an idea.

**Comment by felicedeluca** [comment]
@21stcaveman maybe I explained bad.
For example, I've this graph data (with example coordiantes)

graph:{
nodes[
{id:'source', x:'3', y:'3', type:'def'},
{id:'target', x:'10', y:'10', type:'def'}
],
edges:[
id:'path',
source:'source',
target:'target',
cp1:{x:'4', y:'5'},
cp2:{x:'7', y:'8'},
type:'path'
]
}

the cp1 and cp2 coordinates are not related to the sources and to the target so can't be calculated with them.
Cp1 and Cp2 are not in the nodes array but are calculated server side.

Now, I want to write a custom renderer for the edges with name: sigma.canvas.edges.path where I can get the mapped coordinates for cp1 and cp2 as I can get the source['prefix'+x] source['prefix'+y].
If I use cp1.x and cp1.y I don't take in account the mapped coordinate of source and target that use 'prefix'. Obviously.

My question is: since I want that the relative position from source, target, cp1 and cp2 dosen't change when I draw source and target with their 'prefix' how can I have cp1['prefix'+x] cp1['prefix'+y] and the same for cp2 (and maybe other)?

With cp1, cp2 I can draw bezier path as well as arc with bends without split it

**Comment by 21stcaveman** [comment]
I'm not sure if I understand. are you trying to get the mapped coordinates of source, target, cp1 and cp2 ?
if thats the case, the code above (or something similar to that) should be able to map each of them.

**Comment by felicedeluca** [comment]
@21stcaveman here's an example a custom rendering of the edges with type 'path'

sigma.canvas.edges.path = function(edge, source, target, context, settings){
	
		var prefix = settings('prefix');
		
		
		var cp1 = edge.cp1,
			cp2 = edge.cp2,
			cp3 = edge.cp3;
		
		var cp1MappedX = cp1['prefix'+x],
			cp1MappedY = cp1['prefix'+y],
			cp2MappedX = cp2['prefix'+x],
			cp2MappedY = cp2['prefix'+y],
			cp3MappedX = cp3['prefix'+x],
			cp3MappedY = cp3['prefix'+y];
		
		 context.beginPath();
      context.moveTo(source['prefix'+x], source['prefix'+y]);

      // line 1
      context.lineTo(cp1MappedX, cp1MappedY);

      // quadratic curve
      context.quadraticCurveTo(cp2MappedX, cp2MappedY, cp3MappedX, cp3MappedY);

      // line 2
      context.lineTo(target['prefix'+x], target['prefix'+y]);

      context.lineWidth = 5;
      context.strokeStyle = 'blue';
      context.stroke();


	
	};



I'm missing this part

		var cp1MappedX = cp1['prefix'+x],
			cp1MappedY = cp1['prefix'+y],
			cp2MappedX = cp2['prefix'+x],
			cp2MappedY = cp2['prefix'+y],
			cp3MappedX = cp3['prefix'+x],
			cp3MappedY = cp3['prefix'+y];


I'm new to sigmajs ... and can't understand how to map. with the code above sigma.camera is undefined.

**Comment by 21stcaveman** [comment]
as far as I understand, prefix is added by each camera during the render process for mapping nodes' geographical properties (see issue #530). the code responsible for mapping these properties (x , y and size) is the one above ( see sigma.classes.camera.prototype.applyView ). Control point of an edge is not one of these properties, so it's mapped coordinates with prepended prefix is not something you can find in nodes or edges. You're gonna have to write the code to map them in your plugin.

sigma.camera should be accessible after you instantiate sigma.

**Comment by felicedeluca** [comment]
yes, I got it, thank you.

the code above can map correctly in cam0 i.e. Camera
but if you use the 'canvas' renderer you need to map in canvas camera (renderer)..

when you use

    var prefix = settings('prefix');

in a plugin, prefix = 'renderer1' (in my case) that is different from 'cam0'

As you can see from the image attached, the node 'centroid' has 

renderer1:x
renderer1:y
renderer1:size

other than 

read_cam0:x
read_cam0:y
read_cam0:size

which you got with the code above.

looking at sigma.renderers.canvas here there is the 'renderer' map but the way is mapped is not so straightforward as the camera case.

I think I need the last one to map correctly on 'canvas'

![centroid prop](https://cloud.githubusercontent.com/assets/8150358/7562919/c53b47ce-f7d8-11e4-8d7e-9fdf12959886.png)

**Comment by 21stcaveman** [comment]
Ok, here is a little plugin that draws the control points for each edge in your graph for you :

```javascript
(function() {
  'use strict';

  if (typeof sigma === 'undefined')
    throw 'sigma is not declared';

  sigma.utils.pkg('sigma.plugins');

  sigma.plugins.drawControlPoint = function(s, options) {
    var o = options || {},
	p = s.camera.prefix,
	mappedCPArray = [],
	i = 0;

    s.graph.edges().forEach(function (edge, index, edgeArray) {
	var source = s.graph.nodes(edge.source), target = s.graph.nodes(edge.target),
    	cp = sigma.utils.getQuadraticControlPoint(source.x, source.y, target.x, target.y);

	cp = {
	id: 'cp' + i++,
	size: 1,
	label: 'Control point for ' + edge.id,
	x:
		(
		  (cp.x - s.camera.x) * Math.cos(s.camera.angle) +
		  (cp.y - s.camera.y) * Math.sin(s.camera.angle)
		) / s.camera.ratio + (o.containerwidth || 0) / 2,

	y:
		(
		  (cp.y - s.camera.y) * Math.cos(s.camera.angle) -
		  (cp.x - s.camera.x) * Math.sin(s.camera.angle)
		) / s.camera.ratio + (o.containerheight || 0) / 2
	};

        s.graph.addNode(cp);
    });

    s.refresh();
  }

  sigma.plugins.kill = function(s) { };
}).call(window);
```

And an example on how to use it :
```javascript
var i, s, c = 0, N = 5, E = 4,
    g = {
      nodes: [],
      edges: []
    };

// Generate a random graph:
for (i = 0; i < N; i++)
  g.nodes.push({
    id: 'n' + i,
    label: 'Node ' + i,
    x: Math.random(1, 100),
    y: Math.random(1, 100),
    size: 1,
    color: 'black'
  });

for (i = 0; i < E; i++)
  g.edges.push({
    id: 'e' + i,
    source: 'n' + i,
    target: 'n' + (i + 1),
    size: 1,
    type: 'curvedArrow'
  });

// Instantiate sigma:
s = new sigma({
  graph: g,
  renderer: {
    container: 'graph-container',
    type: 'canvas'
  }
});

c = sigma.plugins.test(
	s, 
	{ 
	   containerWidth: 200 , 
	   containerHeight: 200
	}
);
```


Let me know if you have any questions. And yes, please give me credit if you use the code in your plugin ;) :))

**Comment by felicedeluca** [comment]
ok, your code works perfectly...
but the correct mapping si done when you do:

s.graph.addNode(cp);

The node created with the plug-in has different coordinates from the node rendered.

Your code calculates the first mapping with the 'camera prefix' but ignores the 'canvas prefix' used when you draw the edges or the nodes with a custom canvas renderer.

See these images:

this is the node with the informations that you calculate with the plugin:

![before add](https://cloud.githubusercontent.com/assets/8150358/7634875/fd7ab322-fa5d-11e4-8e71-b8bc376b707e.png)


This is the node rendered. With read_cam0, renderer1:

![after add](https://cloud.githubusercontent.com/assets/8150358/7634874/fd569adc-fa5d-11e4-8908-2d62b168b697.png)

When you add the node to the graph, it's processed before render and so correctly mapped.

If you use your code for the mapping in 

sigma.canvas.edges.path = function(edge, source, target, context,
			settings){

               ... //your mapping code

                context.beginPath();
		context.arc(cp.x, cp.y, 2, 0,
				Math.PI * 2, true);
		context.fillStyle = 'red';
		context.fill();
		context.save();
		
		context.beginPath();
		context.arc(cp.xOriginal, cp.yOriginal, 2, 0,
				Math.PI * 2, true);
		context.fillStyle = 'green';
		context.fill();
		context.save();

}


you get the wrong mapping, since is not referred to 'canvas' (i.e. renderer1 in my image)


Maybe I'm missing something or explained bad: I don't want to draw control points, but I need to map the control points, passed in the edges info and not in nodes array (so not mapped automatically), to route the edges with a custom path.

**Comment by 21stcaveman** [comment]
You are absolutely correct, my bad! that code isn't mapping correctly. I changed it to this :

```javascript
(function() {
  'use strict';

  if (typeof sigma === 'undefined')
    throw 'sigma is not declared';

  sigma.utils.pkg('sigma.plugins');

  sigma.plugins.drawControlPoints = function(s, options) {
    var o = options || {},
    camera = s.cameras[0],
    renderer = s.renderers[0],
    context = s.renderers[0].contexts.nodes;

    s.graph.edges().forEach(function (edge, index, edgeArray) {
	if ((edge.type == 'curved') || (edge.type == 'curvedArrow')) {
		var source = s.graph.nodes(edge.source), target = s.graph.nodes(edge.target),
	    	cpOriginal = sigma.utils.getQuadraticControlPoint(source.x, source.y, target.x, target.y),
		cos = Math.cos(camera.angle),
		sin = Math.sin(camera.angle),
		cp = { x: (cpOriginal.x - (maxX + minX) / 2) * scale, y: (cpOriginal.y - (maxY + minY) / 2) * scale }

		cp = {
		id: edge.id + 'cp',
		size: 0.5,
		label: 'Control point for ' + edge.id,
		xOriginal: cpOriginal.x,
		yOriginal: cpOriginal.y,
		x:
			(
			  (cp.x - camera.x) * cos +
			  (cp.y - camera.y) * sin
			) / camera.ratio + (renderer.width / 2),

		y:
			(
			  (cp.y - camera.y) * cos -
			  (cp.x - camera.x) * sin
			) / camera.ratio + (renderer.height / 2)
		};

		console.log(cp);

		context.fillStyle = 'red';
		context.beginPath();
		context.arc(cp.x, cp.y, 4, 0, Math.PI * 2, true);
		context.fill();
		context.save();
	}
   });
  }

  sigma.plugins.kill = function(s) { };
}).call(window);
```

Thats because I forgot about a key part of drawing process which is rescaling the graph, as defined in sigma.middlewares.rescale.js

Does this work for you?

**Comment by felicedeluca** [comment]
Ooook now works perfectly..

Please add this part to your code

scale = Math.min(renderer.width / Math.max(maxX - minX, 1), 
					renderer.height / Math.max(maxY - minY, 1));

			var margin  ( settings('rescaleIgnoreSize') ? 0 : (settings('maxNodeSize') || sizeMax) / scale ) + (settings('sideMargin') || 0);
			maxX += margin;
			minX -= margin;
			maxY += margin;
			minY -= margin;

			scale = Math.min(renderer.width / Math.max(maxX - minX, 1), 
					renderer.height / Math.max(maxY - minY, 1));


This adjusts the offsets of the nodes accordingly with the maxNodeSize setting. 

Just after you calculate your scale factor, define the margin of the node and then adjust the scale factor again.

you got the credit  :+1: :smile: 
Thank you

**Comment by tylorbayer** [comment]
I am also trying to have multiple control points for an edge but I am still unsure of how to use this extra plugin to achieve this purpose.  Can one of you send a little clip of how you are using to define the control points for an edge? 

Thanks.
