### ISSUE TITLE
Performance optimization 

### ISSUE THREAD

**Issue by bornakke** [jacomyal/sigma.js#567]
We are trying to optimize the performance of a sigma based interface (http://elite.cadm.dk/). The graph is medium size (423 persons) but with a high number of edges connecting them (17.000+). Further, we are applying a number of custom renderes why we for the moment are trapped in canvas mode. 

To make the user experience more fluent we are considering to disable the drawing of edges. However, disabling the edge rendering by setting drawEdges to false or by manually overwriting the default render with a empty function, does not seem to result in any increased performance. 

Firstly, Shouldn't that be the case given the high number of edges in the graph? Or is there maybe a more 'tricky' way to make sure no resources are spent on edge rendering?

Secondly, in the case that there are in fact something to gain from disabling edges: Is it then possible/meaningful to only render selected edges (e.g. edges of a certain type) or will sigma then be forced to render all edges? 

Thirdly, does any body have some suggestions as to how one can monitor sigmas resource usage? I have never before had to optimize javascript and are still struggling to figure out what calculations are the "expensive" once.  

Hope it make sense and sorry for the many questions.

**Comment by Yomguithereal** [comment]
Hello @bornakke,

Normally, disabling edge rendering should provide you with a perf boost (beware, if I remember correctly, you have hooks in your code that was enabling/disabling edge rendering conditionally, so be sure to check them out).

Be sure to disable every edge event related options if you don't need them as those are a real performance hog.

It is possible to render only some specific edges (the ones you deem necessary for your visualization, for instance). To do so, just drop the edges from the data you will pass to sigma or else, if you need to keep said data, give them a flag that your custom renderers will read to skip the render of such edges.

To monitor sigma's resources usage, you can use the devtools of your browser (on firefox or chrome desirably). Then you'll be able to record stacks, heaps and check performance related graphs etc.

I checked your graph and I am not sure to see what preventing it from being performant. It might be good to see whether your custom renderers don't perform unoptimized operations just to be sure.

Is the code open sourced somewhere so I can read it and see whether I see obvious solutions?

**Comment by bornakke** [comment]
Hi @Yomguithereal ,

Thanks for the response. 

It is correct that I have some hooks, however to make sure they were not interfeering I put up a stripped down version of the map (http://elite.cadm.dk/basic_sigma.html) and here I experience the same performance issues - even when edges are disabled. You can investigate the code her: https://github.com/bornakke/ANna

I actually had some edge related events that were no longer being used. They didn't seem to do anything, but to be sure I have now disabled them. 

Regarding the resource monitoring I guess my problem is that I don't know which of the graphs to look at and what to look for. Do you know any tutorials that one could turn toward for an introduction? 

PS: Good and easy solution for only rendering specific edges - I will try to implement that today or tommorow.

**Comment by bornakke** [comment]
@Yomguithereal 

Now I got a chance to take an extra look at it. 

http://elite.cadm.dk/basic_sigma.html is running a completly stripped down version of the file and experiencing what seem to me the exact same performance issues - even when I disable edges and labels - settings: {"drawEdges":false, "drawLabels":false} 

However the same file loading a version of the network where all edges have been deleted in gephi works flawlessly. I'm aware that there should be some improvement in the performance simply due to the fact that the file size is reduced to 1/3 of the original size. I'm however surprised that it should be this dramatically when edges drawing is turned off. 

The simple solution is ofcause to simply remove all edges in gephi before loading it. It would however be nice to keep the edges so it could be shown when a user e.g. click a node.

**Comment by bornakke** [comment]
I close this issue since I have made a new issue more clearly stating the bug that I think I'm encountering.
