### ISSUE TITLE
Edges in canvas mode severally affect navigation even with edge drawing off

### ISSUE THREAD

**Issue by bornakke** [jacomyal/sigma.js#569]
I'm working with a graph based on a gexf file with 500 nodes and 10.000 edges. Edges drawing is disabled most of the time, but when a node is selected, the edges connecting this specific node is rendered.

The rendering of the graph is however much heavier than a graph where the edges have been entirely removed - even though drawEdges is set to false and the edge render therefore never are run. The navigation works as it should if I e.g. move all the edges to another object and delete them from the graph object. However adding them back to the graph object again results in the problems reappear.

I have created two stripped down versions:
http://elite.cadm.dk/basic_sigma.html
http://elite.cadm.dk/basic_sigma2.html

The two file are identical except that all edges are manually removed from basic_sigma2.

I have recorded the cpu usage on the two making a zoom-out. In the version with edges sigma.classes.camera.applyView, sigma.renderers.canvas.render and a few other files all end out taking nearly 10 times as long to render. 

I have however no idea as to how I should figure out what is in fact going on in these files and hope therefore that somebody else have a suggestion as to what is going on in sigma.

Best
Tobias

**Comment by Yomguithereal** [comment]
Hello Tobias. My intuition on the subject is that sigma will still compute the position's changes even if you don't render the edges and this is the thing crippling your performance. However, cutting the position computation might have unexpected side effects and we should discuss this with @jacomyal.

**Comment by sheymann** [comment]
Does `edge.hidden = true` (on all edges) make any difference?

**Comment by bornakke** [comment]
No, I'm afraid not. Same result.

**Comment by 21stcaveman** [comment]
@bornakke, How about setting batchEdgesDrawing in sigma settings to true?

**Comment by bornakke** [comment]
@21stcaveman Good suggestions, but not luck :-/

**Comment by Yomguithereal** [comment]
There is something more deep at work here. There seems to be loops on edges that are unnecessary but I need some time to investigate it.

**Comment by bornakke** [comment]
Yeah that is my feeling too. I have difficulties figuring out where in the sigma code I should look, but if you could point me in the direction of a file or function from where to start then I would also take a "deeper" look.

**Comment by Yomguithereal** [comment]
Try to change something around this [line](https://github.com/jacomyal/sigma.js/blob/master/src/classes/sigma.classes.camera.js#L120) for a starter and tell me whether this improves your perfs.

**Comment by bornakke** [comment]
That is it. Commenting it out makes the experience fluent. Maybe the solution would be to close the part into a if senteces checking if drawEdges is disabled?

**Comment by Yomguithereal** [comment]
This would be a solution but a dangerous one and I need to ponder the consequences and see whether this should be a setting or not before breaking anything.

**Comment by sheymann** [comment]
@Yomguithereal what are the potential troubles here?

**Comment by jacomyal** [comment]
@bornakke I am not sure we can integrate this test in master, since there is a case where it would cause some issue:

  - `instance.settings('drawEdges', false);`
  - `instance.refresh();` (or drag or zoom)
  - `instance.settings('drawEdges', true);`
  - `instance.render();` (**not** refresh)

At this point, the edges are drawn with the last computed sizes, not the sizes you expect, which is kind of problematic...

So, in your situation I would build sigma with the test on `"drawEdges"` before the loop - at least until we find a better solution.

**Comment by bornakke** [comment]
@jacomyal I see you point. I would think that the current bug is worse (and more normal) than the one that you sketch above, but that is for you to decided. For me it will work fine to simply overwrite the function locally.
