### ISSUE TITLE
node ellipsis shaped

### ISSUE THREAD

**Issue by antonioaltamura** [jacomyal/sigma.js#570]
There is a way to render a node with defined width and height instead of a single value radius (size)?

**Comment by Yomguithereal** [comment]
Yes, you can create a custom node renderer that would accept such properties on nodes and act upon it. However, you might want to do it in canvas rather than in webgl.

**Comment by alfredopacino** [comment]
sorry could you provide me a quick example? I've never saw a different dimension than size, even in custom render..

**Comment by Yomguithereal** [comment]
I don't have an example of renderer doing ellipsis but you'll have to set a width/height combo on your node then deal with proportions (probably based on the rendered size) to draw your ellipsis in canvas.

[Here](http://www.html5canvastutorials.com/advanced/html5-canvas-ovals/) is an example of how you might draw an ellipsis in canvas.

**Comment by alfredopacino** [comment]
uhm yes but using sigmajs i'm not dealing straight with canvas objects for each node..
are you talking about a render plugin edit?

**Comment by Yomguithereal** [comment]
Yes you can dealing with canvas for each node thanks to a custom node renderer. [This](http://yomguithereal.github.io/articles/node-border-renderer/) article explains how you might do that.
