### ISSUE TITLE
Zoom-independent node sizes / Google Map-like decorators

### ISSUE THREAD

**Issue by janusz005** [jacomyal/sigma.js#576]
These are potentially unrelated features but could serve similar purpose in some use cases:

First, regarding node sizes: In most cases it is both a natural and desired property that node screen sizes scale with the zoom level (as they do). Sometimes, however, for selected nodes you could imagine that you might want to keep them at a fixed size (e.g. always large enough to be seen). 

Alternatively, these might not be real nodes but rather graphical decorators (like the location pins on Google Maps) which maintain constant screen size when zooming in or out.

I was wondering if anything like this is currently achievable in Sigma.js? If not, any suggestions for how best to approach this (e.g. extending the library) would be great.  

Thanks in advance!

Janusz

**Comment by Yomguithereal** [comment]
Hello @janusz005. I totally understand your point here. I must have code related to this kind of problem somewhere and I think I recall creating a graph where some "graphical" indicators were keeping a constant size indeed. Let me see whether I can find it back.

**Comment by janusz005** [comment]
thanks @Yomguithereal, that would be awesome!

**Comment by janusz005** [comment]
Hi  @Yomguithereal, just following up to see if you might have and be able to share this code?

thanks!
Janusz

**Comment by Yomguithereal** [comment]
You can check [this](https://github.com/medialab/medea_website/blob/master/app/scripts/external/enbgraph.js) file for an example of renderers displaying cluster labels with a constant size.

The file is a bit big and messy. Don't hesitate to ask for precisions.
