### ISSUE TITLE
Curly and wave-like edge types?

### ISSUE THREAD

**Issue by ThorbenQuast** [jacomyal/sigma.js#580]
Hello,

is it possible to draw custom edge types? For "curve" types, I have seen that there is some function called "quadraticCurveTo" to do the job. Yet, I am interested in having 'curly' and wave-like edges as I am using sigmajs to visualize particle reactions with Feynman graphs (http://hyperphysics.phy-astr.gsu.edu/hbase/particles/imgpar/feynm5.gif). I can probably figure out an algorithm for plotting the gluon line by making use of quadratic curves but I am clueless about the wavy photon line. Is there maybe a convenient helper function that I have overseen?

Cheers

**Comment by 21stcaveman** [comment]
You can create custom renderers to draw these edges for you. For example on how to create custom renderers, please see custom-edge-renderer.html in the examples folder.
For ideas on how to create the edges, for the wavy shape you can use Math.sin or Math.cos function, and you can use quadraticCurveTo function to create the other one. See : https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Drawing_shapes

**Comment by ThorbenQuast** [comment]
Thank you very much!!! "path.arcTo(...)" was exactly the function I was looking for.
