### ISSUE TITLE
Grouping nodes

### ISSUE THREAD

**Issue by leesei** [jacomyal/sigma.js#586]
Is it possible to group nodes together like this?
http://cytoscape.github.io/cytoscape.js/demos/5b192c88616af2f75344/

**Comment by Yomguithereal** [comment]
Hello @leesei. Short answer: no. Long answer: this is not currently possible but with some work, it could be achieved but not painlessly. You would have to create a dedicated renderer that would group nodes together etc.

**Comment by leesei** [comment]
Thanks. This is the state as of v1.0.3.

**Comment by lauwers** [comment]
Has anybody attempted to do this?

**Comment by arpitahuddar** [comment]
Does anyone know how to group nodes so network doesn't look cluttered when displayed on screen?

**Comment by carsonbird** [comment]
What about now, 6 years later?
