### ISSUE TITLE
Attempting to use FA2 from a graph imported from JSON

### ISSUE THREAD

**Issue by michaelorr92** [jacomyal/sigma.js#587]
Hi all,

I am attempting to display a graph using the ForceAtlas2 layout from data in a JSON file. I can do these separately (i.e I can use FA2 if I manually specify the nodes and I can load data from a JSON and graph it) but I can't do these together. Could someone perhaps post some code to demonstrate how this is accomplished? I have been tweaking the examples so far but I have no luck.

Thanks.

**Comment by Yomguithereal** [comment]
Hello @michaelorr92,
could you post some of the code you write so I can see what went wrong please?

**Comment by michaelorr92** [comment]
Hi, this is what I have in my script.

sigma.parsers.json('data.json', {
    container: 'container',
    settings: {
      defaultNodeColor: '#551A8B'
   }
});

s = new sigma({
  graph: g,
  container: 'container',
  settings: {
    drawEdges: false
  }
});

s.startForceAtlas2({worker: true, barnesHutOptimize: false});

**Comment by Yomguithereal** [comment]
Ok. Json fetching, as it is using AJAX, is asynchronous. You must therefore wait for the request to complete before being able to start the layout. You can use the `.json` callback to do so:

```js
sigma.parsers.json(
  'data.json',
  {
    container: 'container',
    settings: {
      defaultNodeColor: '#551A8B',
      drawEdges: false
    }
  },

  // Callback
  function(s) {

    // Data has been loaded, starting the layout
    s.startForceAtlas2({worker: true, barnesHutOptimize: false});
  }
});
```

**Comment by michaelorr92** [comment]
Thank you for the swift reply.

However I still cannot get this to work. When I load up the webpage it is blank and I really have no idea where the issue may be. I can't even post some code to highlight where I think I have went wrong. No errors in the console log either.

**Comment by Yomguithereal** [comment]
What does your HTML looks like? Do you correctly have a div with `container` as its id? What are the sizes of this div according to its css/style? If your container is not sized correctly, for instance, you won't see anything on screen since the container has no height/width.

**Comment by michaelorr92** [comment]
![image](https://cloud.githubusercontent.com/assets/12715570/8105156/83cdf2d2-102e-11e5-8663-608c8b46e1d8.png)

**Comment by Yomguithereal** [comment]
Could you try to set a defined width to your container rather than a max-width?

**Comment by michaelorr92** [comment]
Tried a defined width and the issue remains.

**Comment by AVermeij** [comment]
@michaelorr92 Are you testing this locally or on a webserver? If testing locally, Chrome and IE won't show you anything due to security restrictions. Firefox does work for testing.

**Comment by michaelorr92** [comment]
I am testing this locally using Firefox. I have had other examples working. Just for a sanity check I changed my code to do a previous example graph I attempted and it worked so I don't think it is anything to do with my environment.

**Comment by michaelorr92** [comment]
I think I will leave this issue for now and work on another part of my project. If anyone has any working code that they can post for comparison it would be much appreciated.
