### ISSUE TITLE
Create a Gitter channel? (or similar slack/irc/whatever chat system?)

### ISSUE THREAD

**Issue by jbilcke** [jacomyal/sigma.js#590]
Asking questions as new tickets is nice (everything is at the same place, and we can search),
but I think it would be helpful to have a chatroom like Gitter.im (where one can post things, natively link to github issues..) to ask for more trivial questions, eg. asking for help on how to use sigma.js, why a feature is not working with one's personal project, having lengthy discussions that never end etc..

I'm just suggesting that, because I feel like there are more and more tickets open on sigma, and by taking out community-level questions, ie. issues that are not actual "tasks" that can be completed (issues not related to sigma.js core, roadmap, bugs.. but how to use it) it might get possible to finally focus and progress on the core things.

Also, a chat room would help lower the barrier to the reply: no need to wait for an admin to answer and "close" a question, if someone is around the answer could be quite fast, unlike a forum or mailing list (people having it in background would get a notification for each new msg)

**Comment by emergingdzns** [comment]
+1!
