### ISSUE TITLE
position jump to bring graph fully into view

### ISSUE THREAD

**Issue by emergingdzns** [jacomyal/sigma.js#593]
I’ve got a graph dialed in really nice, but I just found an interesting issue. I have a high resolution screen so when I’m developing, my browser window is very large so I didn’t notice this before. We are generating a graph that’s 700px tall. But we have content above it as well, so often the bottom edge of the graph is down to 1000 or more pixels from the top of the browser window. If the browser window height is less than what is needed to show all of the content above the graph and the full height of the graph, when we mouse over the graph on Safari or Chrome, the page suddenly scrolls up to make it so that the bottom edge of the graph is lined up with the bottom of the browser window. I’m completely perplexed by this. Is this an expected behavior in Sigma?

**Comment by Yomguithereal** [comment]
Did you perchance shunt the `autoRescale` setting?

**Comment by emergingdzns** [comment]
I didn't have an autoRescale setting in my code. I've added it and set it to true in the settings but it didn't change the behavior.

**Comment by emergingdzns** [comment]
I've created a jsFiddle for you to view the behavior. Use Chrome or Safari and you'll see what I'm seeing. Please read the alert pop-up that comes up when you load the page below.

http://jsfiddle.net/emergingdzns/8qh6pa10/5/

**Comment by sheymann** [comment]
caused by a plugin: https://github.com/Linkurious/linkurious.js/issues/134
