### ISSUE TITLE
Searching nodes by label?

### ISSUE THREAD

**Issue by networkgraph** [jacomyal/sigma.js#601]
Has anyone built the capability to search nodes by label?  The [JavaScript GEXF Viewer for Gephi](https://marketplace.gephi.org/plugin/gexf-js-web-viewer/) has a really nice search feature.

**Comment by Yomguithereal** [comment]
Hello @networkgraph, do you need to zoom on the found label, for instance?

**Comment by networkgraph** [comment]
Not necessarily.  Currently, I have a couple of functions bound to clickNode.  They (1) make a persistent label appear when you click a node and (2) show information about the clicked node in a side panel.  What I'd like to do is call those functions for the found node when its label is found.

**Comment by Yomguithereal** [comment]
You can do something of the kind:

```js
function showNode(node) {
  // Do your thing...
}

s.bind('clickNode', function(e) {
  showNode(e.data.node);
});

// When searching
function onSearch(query) {
  var nodes = s.graph.nodes();

  // Filter or find the first matching node then apply showNode on it
}
```

**Comment by networkgraph** [comment]
@Yomguithereal , thank you for the suggestion.  I did something of the kind.

**Comment by PavanTejaReddy** [comment]
Hey I can search the node  labels. Is there any way we can search the node columns. Can someone of you help me regarding this. Thanks in Advance

**Comment by hiteshvaidya** [comment]
@Yomguithereal where do you put that code?

**Comment by Yomguithereal** [comment]
Something like zooming on the coordinates of target node.

**Comment by yogi-emorphis** [comment]
> 
> 
> You can do something of the kind:
> 
> ```js
> function showNode(node) {
>   // Do your thing...
> }
> 
> s.bind('clickNode', function(e) {
>   showNode(e.data.node);
> });
> 
> // When searching
> function onSearch(query) {
>   var nodes = s.graph.nodes();
> 
>   // Filter or find the first matching node then apply showNode on it
> }
> ```

@Yomguithereal  : Hello 
I can find node details using s.bind but OnSearch function what will be query?

**Comment by eduOS** [comment]
Please refer to shis answer：  https://stackoverflow.com/a/47740696/3552975
