### ISSUE TITLE
s.refresh() functionality?

### ISSUE THREAD

**Issue by UsmanAyyaz** [jacomyal/sigma.js#603]
Can someone explain the functionality of the refresh() method? Is the source code for refresh() public?

**Comment by Yomguithereal** [comment]
Hello @UsmanAyyaz. The `refresh` method redraws the graph. It is necessarily called when you want to update the graph's visual and is as such used when you move the camera around, for instance.

The source code is of course public. This is open source, after all. The method is defined [here](https://github.com/jacomyal/sigma.js/blob/master/src/sigma.core.js#L479). But you might find difficult to understand everything it does without digging in some other files.

**Comment by UsmanAyyaz** [comment]
Thanks!

I am trying to implement time evolution of a graph and my initial idea was to keep growing the graph within the same sigma instance and refresh it at intervals. But since the refresh method returns the sigma instance when called, I cant update it again. 

Do you have any suggestion on how to tackle this problem?

**Comment by Yomguithereal** [comment]
I don't understand why the fact that `refresh` returns your instance prevents you from calling `refresh` each time you need. The only reason why the method returns the instance is to enable you to chain methods.

Could you show me some of your code here so I can assess what's holding you back?

**Comment by UsmanAyyaz** [comment]
existing_nodes = []

              for(j=0; j<100; j++){
                console.log("j: ", j)
                source = temp_edges[j].source
                target = temp_edges[j].target
                
                var source_node = findNodes(temp_nodes, source)
                var target_node = findNodes(temp_nodes, target)
              
                if(!contains(existing_nodes,source)){
                  s.graph.addNode(source_node) //add node
                  existing_nodes.push(source)
                }
                if(!contains(existing_nodes,target)){
                  s.graph.addNode(target_node) //add node
                  existing_nodes.push(target) 
                }
                s.graph.addEdge(temp_edges[j]) //add edge
              }

              sigma.plugins.relativeSize(s, 10)
              s.refresh();
              s.sleep(2000)
              

I have the above code in a for loop. It keeps adding nodes and edges in batches of 100 to the graph. At the end of each iteration I am putting the thread to sleep (to give the impression of dynamic building). 

After more testing, I realized that s.refresh() is working but it only displays the final graph and not the in between building stages.

**Comment by Yomguithereal** [comment]
How does your `sleep` function work? In JavaScript, you cannot synchronously sleep without dirty tricks involving the `Date` object and, should you do so you might freeze the current frame and then your UI would not render until the last iteration.

You should probably use a `setTimeout` in your case.

**Comment by UsmanAyyaz** [comment]
function sleep(milliseconds) {
              var start = new Date().getTime();
              for (var i = 0; i < 1e7; i++) {
                if ((new Date().getTime() - start) > milliseconds){
                  break;
                }
              }
            }

**Comment by Yomguithereal** [comment]
Yes this is showing the exact trick you should probably never use in JavaScript code. Is there somewhere I can see your code with the `setTimeout`? Or can you copy the code here please?

**Comment by UsmanAyyaz** [comment]
function build(a,b){

                for(j=a; j<b; j++){
                  console.log("j: ", j)
                  source = temp_edges[j].source
                  target = temp_edges[j].target
                  var source_node = findNodes(temp_nodes, source)
                  var target_node = findNodes(temp_nodes, target)
              
                  if(!contains(existing_nodes,source)){
                    s.graph.addNode(source_node) //add node
                    existing_nodes.push(source)
                  }
                  if(!contains(existing_nodes,target)){
                    s.graph.addNode(target_node) //add node
                    existing_nodes.push(target) 
                  }
                  s.graph.addEdge(temp_edges[j]) //add edge
                  }
             
                  sigma.plugins.relativeSize(s, 10) 
                  s.refresh();
                }

                setTimeout(build(0,50),5000)
                console.log("BUILDING")
                setTimeout(build(50,200),5000)

**Comment by Yomguithereal** [comment]
First thing: you are not using setTimeout correctly. The first argument you must provide to setTimeout is a function and here you are actually passing the result of calling `build(0, 50)` and not a function. You should do the following:

```js
setTimeout(function() {
  build(0, 50);
}, 5000);

// or using setTimeout's polymorphism
setTimeout(build, 5000, 0, 50);

// or by currying the build function
setTimeout(build.bind(this, 0, 50));
```

**Comment by UsmanAyyaz** [comment]
Thanks a lot! It worked. The visualization is running fine.

**Comment by Yomguithereal** [comment]
Glad I could help you!

**Comment by ncardozo** [comment]
Hi,

I think I have a similar problem with refresh not working for me when adding edges to my graph.
I mainly have a set of edges and want to dynamically draw edges between them. To do is I am using a single instance of sigma and the graph, and change the edges attributes of the graph at runtime. I can see the edges being properly created but then they are not displayed on the graph. Here is my code, what am I doing wrong?

`
var g = {
  nodes: [],
  edges: []
}
var s;

function clickedButton() {
  UIElements.generateEdges();
  UIElements.displayGraph();
}

function displayGraph() {
    if(s == null) {
      s = new sigma({
        graph: g,
        container: 'graph-container'
      });
      s.settings({
        immutable: false,
        clone: false
      });
    }
    this.animation(s);
    s.refresh();
  }
}

function generateEdges() {
    g.edges = [];//this.proceed();
    console.log("Techniques edges called");
    for(var i=0; i<languages.length; i++) {
      for(var j=i; j<languages.length; j++) {
        if(i != j && languages[i].technique == languages[j].technique) {
          g.edges.push({
            id: 'e' + languages[i].language + "-" + languages[j].language,
            source: languages[i].language,
            target: languages[j].language,
          });
        }
      }
    }
  }
`

**Comment by ncardozo** [comment]
I figured it out, dont worry about it.
The thing to do is to add the edges to the graph directly, so instead of doing `g.edges.push` you should use `s.graph.addEdge`

**Comment by Yomguithereal** [comment]
Yes indeed @ncardozo. Sorry I was not able to help you sooner.

**Comment by ygarciac** [comment]
Hi,

I have a similar problem with refresh method. I have done my code to include the nodes and the edges with a for loop. Each iteration, I push my edge on the graph, and then I used the refresh method over sigma instance.

The problem is that when I run my HTML code, I don't see the refresh, but when I execute my code adding a breakpoint , I can see how the graph draw each edge at each iteration.

My number of nodes is 3669 and my number of edges is 3961.

I don't think that the amount of data damage the execution.

If any can help me... Thank you so much!!

My code is this:

```
var sigInstance = new sigma({
  container: 'graph-container',
});

setTimeout(function() {
		empezar(0,50);
	}, 5000);
	
setTimeout(function() {
	empezar(50,1000);
	}, 5000);

function empezar(a,b)
{
	for(var i=a; i<b;i+=1)
	{
		edgeAhora = edges[i];
		source = edgeAhora.source;
		target = edgeAhora.target;
		var sourceNode = findNodes(nodes,source);
		var targetNode = findNodes(nodes,target);
		build(sourceNode,targetNode);
	}
}

function build(sourceNode,targetNode)
{	
	var esCiertoSource = contains(existingNodes,sourceNode);
	var esCiertoTarget = contains(existingNodes,targetNode);
		if(esCiertoSource == false){
			sigInstance.graph.addNode(sourceNode);
			existingNodes.push(sourceNode);
		}
		if(esCiertoTarget == false){
			sigInstance.graph.addNode(targetNode);
			existingNodes.push(targetNode);
		}
		sigInstance.graph.addEdge(edgeAhora);
		sigInstance.refresh();
}

function contains(existingNodes,nodeCont)
{
	var esCierto;
	if(existingNodes.length == 0)
	{
		esCierto = false;
		existingNodes.push(nodeCont.id);
	}
	else
	{
		for(var h=0;h<existingNodes.length;h+=1)
		{
			if(existingNodes[h].id == nodeCont.id)
			{
				esCierto = true;
				break;
			}
			else
				esCierto = false;
		}
		if(esCierto == true)
		{
		}
		else
		{
			esCierto = false;
		}
	}
	return esCierto;
}

function findNodes(nodes,idNodeAct)
{
	var nodeAct;
	for(var j=0; j<nodes.length;j+=1)
	{
		if(idNodeAct == nodes[j].id)
		{
			nodeAct = nodes[j];
		}
	}
	return nodeAct;
}
```
