### ISSUE TITLE
Is there a way to change edge color using the addEdge method? If so, can someone give an example.

### ISSUE THREAD

**Issue by UsmanAyyaz** [jacomyal/sigma.js#607]

**Comment by Yomguithereal** [comment]
Hello @UsmanAyyaz. Do you want to give a custom color to your edges or do you just need to color them like their source or target or to give them all the same color?

**Comment by UsmanAyyaz** [comment]
I need to give a custom color to the edge. Basically, I am building a graph in time steps, and at each step I want all the edges being added at that particular step to be colored differently from all previous steps.

**Comment by Yomguithereal** [comment]
Ok, just set a color property to you node and it should be displayed:

```js
// Example when adding the node
s.graph.addEdge({source: ..., target: ..., color: '#FF54BA'});
```
