### ISSUE TITLE
“SAH” in code comment, what does it mean?

### ISSUE THREAD

**Issue by glixingxian** [jacomyal/sigma.js#608]
if (a==b.source) outgoing[b.target]=n;		//**SAH**
else if (a==b.target) incoming[b.source]=n;		//**SAH**
.........
if (groupByDirection) {
		//**SAH** - Compute intersection for mutual and remove these from incoming/outgoing
		for (e in outgoing) {
			//name=outgoing[e];
			if (e in incoming) {
				mutual[e]=outgoing[e];
				delete incoming[e];
				delete outgoing[e];
			}
		}
    }
I see this **SAH** in the code of main.js of the js/main.js file https://github.com/oxfordinternetinstitute/InteractiveVis/tree/master/network

Anyone knows what does this abbreviation means? I'm very confused by it and I recommend that every abbr.(abbreviation) is explained by its full notation in the code comment.

**Comment by AVermeij** [comment]
I think those are just the initials of one of the devs behind that plugin (Scott A. Hale). 

By the way, that plugin is based on an old version of sigma.js - I believe 0.1.

**Comment by glixingxian** [comment]
Thanks @AVermeij !, I asked the same question in the issues of the concerned plug-in project and here is the answer link, FYI(for your information), [oxfordinternetinstitute/InteractiveVis](https://github.com/oxfordinternetinstitute/InteractiveVis/issues/59#event-350577808).
