### ISSUE TITLE
Need a simple example

### ISSUE THREAD

**Issue by falconair** [jacomyal/sigma.js#61]
For the past half an hour I've been trying to get an example working. There really should be a simple, but COMPLETE example.

I first tried to play around with jsfiddle.net. When that didn't work, I tried to run a simple example on my local machine, even that doesn't work (I just get an empty page with no errors in the console).

My code is here, you are welcome to use it (just surrounds sample 'snippet' with html tags--note that I only brought jquery into it to make sure my page was ready, before attempting to add a network):

``` html
<html>
<head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://sigmajs.org/js/prettify.js"></script>
    <script type="text/javascript" src="http://sigmajs.org/js/sigma.min.js"></script>
    <script>
        $(document).ready(function() {
            var sigRoot = document.getElementById('sig');
            var sigInst = sigma.init(sigRoot).drawingProperties({
              defaultLabelColor: '#ccc',
              font: 'Arial',
              edgeColor: 'source',
              defaultEdgeType: 'curve'
            }).graphProperties({
              minNodeSize: 1,
              maxNodeSize: 10
            });

            sigInst.addNode('hello',{
              label: 'Hello',
              color: '#ff0000'
            }).addNode('world',{
              label: 'World !',
              color: '#00ff00'
            }).addEdge('hello_world','hello','world').draw();
          });
    </script>

</head>
<body>
    <div id="sig">
        <canvas width="1170px" height="216px">
    </div>

</body>
</html>
```

**Comment by kyyash** [comment]
I do not see arrows when I use this ?
var sigInst = new sigma({ 
      graph: this.sigmaJson,
      container: 'connGraph-sigma',
      settings: {
          defaultNodeColor: '#ec5148',         
      }
    });
    sigInst.drawingProperties({
      defaultLabelColor: '#ccc',
      font: 'Arial',
      edgeColor: 'source',
      defaultEdgeType: 'curve'
    }).graphProperties({
      minNodeSize: 1,
      maxNodeSize: 10
    });
 
    sigInst.graph.nodes().forEach(function(node, i, a) {
      node.x = Math.cos(Math.PI * 2 * i / a.length);
      node.y = Math.sin(Math.PI * 2 * i / a.length);
    });
   // sigInst.drawingProperties({defaultEdgetArrow:'target'});
    sigInst.refresh();

**Comment by azw413** [comment]
Can these examples be updated with the latest version of sigmajs? We need a simple single page HTML example which works with the latest versions. Most web apps are not using Javascript backends and so just having npm examples is not helpful whereas a static HTML page can be implemented in any backend language.

**Comment by sim51** [comment]
I don't really understand what you want, if it is to have a working example on which you can test the library without having `npm` on your computer, or if you want  to push in production an html page (with sigma) without to have a web/js workspace on your pc.

For the first one, you can run all the examples on code sandbox.
- on github, go to the folder of the example you want to run
-  replace in the url `github.com` by `githubbox.com`

For the second point, you can check this example : https://jsfiddle.net/w7uq3h0o/
