### ISSUE TITLE
What is the best way to determine whether or not a node is hidden at any given time?

### ISSUE THREAD

**Issue by networkgraph** [jacomyal/sigma.js#611]
I am trying to have sigma communicate with a Leaflet map that geocodes the nodes.  I have a page that shows a sigma network graph and a corresponding Leaflet map at once.  I am using the sigma filter plugin and I want only those nodes that are shown in the graph to show on the map.

Here is what I am doing to map all nodes:

```js
s.graph.nodes().forEach(function (n) {
  L.marker([n.attributes.Latitude,n.attributes.Longitude]).addTo(map)
});
```

I assume there should probably be some sort of if statement above the L.marker line.  The filter plugin assigns the class "hidden" to all nodes and edges that are filtered out, so I am thinking that is how I can differentiate between nodes that should be mapped and nodes that should not.  I think the answer lies in jQuery but I'm not sure exactly how to approach it.

**Comment by Yomguithereal** [comment]
jQuery has nothing to do with your problem. Just filter your nodes by the hidden property of the node or use a condition:

```js
// Using Array.filter
s.graph.nodes()
  .filter(function(n) {
    return !n.hidden;
  })
  .forEach(function(n) {
    L.marker([n.attributes.Latitude,n.attributes.Longitude]).addTo(map)
  });

// Using a condition
s.graph.nodes().forEach(function(n) {
  if (!n.hidden) {
    L.marker([n.attributes.Latitude,n.attributes.Longitude]).addTo(map)
  }
});
```

**Comment by networkgraph** [comment]
Yep, thank you.  That was a huge help.
