### ISSUE TITLE
logic OR operator in code

### ISSUE THREAD

**Issue by glixingxian** [jacomyal/sigma.js#614]
I saw this in sigma.js, in the `addNode` method ,there is an OR operator `||`:

``` javascript
this.addNode = function (d, b) {
            if (c.nodesIndex[d]) throw Error('Node "' + d + '" already exists.');
            var b = b || {},
            ... ...
```

I would like to know why use OR here? and the comma`,` after the `{}` seems to be an error? Shouldn't it be semicolon`;`?

Any help will be very appreciated!    :)

**Comment by glixingxian** [comment]
It is called short-circuit evaluation of boolean expressions. 
Here an explanation on StackOverflow [JavaScript OR (||) variable assignment explanation](http://stackoverflow.com/questions/2100758/javascript-or-variable-assignment-explanation).

**Comment by glixingxian** [comment]
**BUT**!!!

WHAT IS THE `,` AFTER THE `{}`?

**Comment by Yomguithereal** [comment]
Hello @glixingxian. First of all I cannot find the code you are talking about here. My guess is that it continues likewise:

```js
this.addNode = function (d, b) {
            if (c.nodesIndex[d]) throw Error('Node "' + d + '" already exists.');
            var b = b || {},
                whatever = 'something';
```

In JavaScript you can assign multiple variables likewise:

```js
var a = 1, b = 2;
// Which is the same as:
var a = 1,
    b = 2;
```

Please refrain from using bold and upper case sentences. This is interpreted by readers as screaming or yelling.

**Comment by glixingxian** [comment]
@Yomguithereal  Thanks! 
I've changed the style my previous comment. Thank you for reminding me of that.

For the `,` question, you are right, there is something that continues after the `,`.
So `var b=0, a=0;` means `var b=0; var a=0;`,  that is declaration then assignment?

**Comment by glixingxian** [comment]
[JS variable declaration](http://www.w3schools.com/js/js_variables.asp )

>**One Statement, Many Variables:**
>You can declare *many* variables in *one* statement
>Start the statement with var and separate the variables by comma
>A declaration can span multiple lines

**Comment by Yomguithereal** [comment]
Can you remind me where you found this code in the sigma's codebase please? I cannot find it anywhere.

**Comment by glixingxian** [comment]
A GitHub repository called [InteractiveVis]  (https://github.com/oxfordinternetinstitute/InteractiveVis/tree/master/network/js/sigma) which uses sigma.js 

I'm reading its code and unavoidably, I read the source code of sigma and got some questions.

I don't know if it uses  the latest version of sigma. As of the source code of sigma that I read, there are not many comments and lots of function names are not semantic, like `function h(){} function n(){}`, whether they are constructors or normal functions.

**Comment by Yomguithereal** [comment]
This is indeed a very old and outdated version of sigma there. It's possible that the code present at your link has been partially minified and concatenated also.
