### ISSUE TITLE
drag vs click events

### ISSUE THREAD

**Issue by antonioaltamura** [jacomyal/sigma.js#620]
Hi, I need to differentiate those events: basically I need a real click event, it shouldn't be fired on drag.
There is a way?

**Comment by Yomguithereal** [comment]
I don't remember very clearly but you should try to log the click event and check it. There should be a `dragging` flag somewhere.

**Comment by alfredopacino** [comment]
there is e.data.captop.isDragging flag. But it's always false. Dragging or not.

    s.bind('clickNode', function(e) {
    	 console.log(e)
    })

**Comment by Yomguithereal** [comment]
If I recall correctly the `isDragging` flag concerns camera panning and not nodes' dragging. I have never used the drag nodes plugin so I am afraid I can't really help you on that matter without first reading its code.

**Comment by vivekdaryani** [comment]
`isDragging` flag is working on stage click
If you drag the complete graph then `e.data.captor.isDragging` is true in the `clickStage` event data

**Comment by Kuroky360** [comment]
@Yomguithereal   Hi,  I thought it should also be helpful to add the "isDragging" flag to the clickNode event as well while dragging one node.Thanks.

**Comment by leofle** [comment]
there is a way to do it now?

**Comment by Kuroky360** [comment]
@leofle  you can do it like this:
```
 dragListener.bind('drag',function(){
                $timeout(function () {
                    sigmaInstance.unbind('clickNode');
                });
            });
 dragListener.bind('dragend',function(){
                $timeout(function(){
                    sigmaInstance.bind('clickNode', node_click_function);
                },250)
            });
```
It works for me.

**Comment by leofle** [comment]
ye, that's what i did too, just that it seems a little too "hacky" but it works, thanks.

**Comment by PrathyushaNarayanan** [comment]
@leofle, @Kuroky360 ,

My graph requires the drag functionality to be enabled along with a tooltip to be displayed on clicking one of the nodes present. [clicking on a specific node displays the tooltip whereas the behavior seen on clicking the other nodes in the graph is different].
The tooltip display works fine until the clickNode event is unbound on drag as specified above. On binding it again once drag is complete, the tool tip isn't displayed.
--------------------------------------------
 function intializeToolTip(){
// Instantiate the tooltips plugin with a Mustache renderer for node tooltips:
        toolTip_config = {
            node: {
                show: 'clickNode',
                hide: 'clickStage',
                cssClass: 'sigma-tooltip',
                position: 'css',
                template: '  <div class="arrow"></div>' +
                '  <div class="sigma-tooltip-body">' +
                '    POI for money laundering ' +
                '  </div>',
                renderer: function (node, template) {
                    // Returns a DOM Element:
                    if (node.id === "node_overlap") {
                        var el = document.createElement('div');
                        return el.innerHTML = Mustache.render(template, node);
                    }else{
                        var foundNode = s.graph.nodes(node.id);
                        if (foundNode !== null) {
                            var fakeData = {
                                node: foundNode,
                            };
                        }
                        s.renderers[0].dispatchEvent('clickNode', fakeData);
                    }
                }
            }
        };


        tooltips = sigma.plugins.tooltips(s, s.renderers[0], toolTip_config);


        tooltips.bind('shown', function(event) {
            console.log('tooltip shown', event);
        });

        tooltips.bind('hidden', function(event) {
            console.log('tooltip hidden', event);
        });
    }
    urls.forEach(function(url) {
        sigma.canvas.nodes.image.cache(
            url,
            function() {
                if (++loaded === urls.length) {
                    s = new sigma({
                        container: 'container',
                        graph: g,
                        renderer: {

                            // This works only with the canvas renderer, so the
                            // renderer type set as "canvas" is necessary here.
                            container: document.getElementById('container'),
                            type: 'canvas'
                        },
                        settings: {
                            labelAlignment: 'bottom',
                            minNodeSize: 4,
                            maxNodeSize: 30,
                            minEdgeSize: 0.1,
                            maxEdgeSize: 4,
                            enableHovering: false,
                            maxNodeLabelLineLength: 16
                        }
                    });

                    intializeToolTip();

		            s.bind("clickNode", handleNodeClick);

		            function handleNodeClick(e) {
		                if(e.data.node.id === 'node_overlap'){
                            return;
		                }else {
                            (e.data.node).color = '#29abe2';
                            (e.data.node).url = node_image_map[e.data.node.id].select;
                            clicked_nodes.push(e.data.node);
                        }
                        s.refresh();
                    };

                    s.bind("clickStage", function(e) {
                       for (var i=0;i<clicked_nodes.length;i++){
                            (clicked_nodes[i]).color = '#216489';
                            (clicked_nodes[i]).url = node_image_map[clicked_nodes[i].id].deselect;
                            s.refresh();
                            if (i == clicked_nodes.length){
                                console.log("PRAT : index to clear the clicked node array "+i+" length: "+clicked_nodes.length );
                                clicked_nodes = [];
                                console.log("PRAT : after clearing the clicked node array "+clicked_nodes.length );
                            }
                        }
                    });

                    intializeToolTip();

                    // Initialize the dragNodes plugin:
                    var dragListener = sigma.plugins.dragNodes(s, s.renderers[0]);

                    dragListener.bind('startdrag', function(event) {
                       console.log("startdrag- "+event);
                    });
                    dragListener.bind('drag', function(event) {
                       console.log("drag-"+event);
                        setTimeout(function () {
                            s.unbind('clickNode');
                        });
                    });
                    dragListener.bind('drop', function(event) {
                        console.log("drop- "+event)
                    });

                    dragListener.bind('dragend', function(event) {
                        setTimeout(function () {
                            s.bind('clickNode',handleNodeClick);
                        });
                        console.log("dragend-"+event);
                    });

                    

                    s.refresh();
                }
--------------------------------------------
Any ideas on how the tooltip display can be handled?

**Comment by nitin7dc** [comment]
@Kuroky360 : thanks

**Comment by bryandandan** [comment]
Works like a charm
