### ISSUE TITLE
Enable edge events

### ISSUE THREAD

**Issue by sonph** [jacomyal/sigma.js#623]
Hey there,
I'm having trouble with the edge events (`overEdge`, `outEdge`, `clickEdge`, etc.) not invoking the callbacks in my code. Other events on nodes, the click events and double click events are working.

I'm wondering if there is documentation somewhere on how to set up edge events?

Thanks for the great library!

**Comment by Yomguithereal** [comment]
Hello @sonph. Can you try to set the `enableEdgeHovering` to true and see whether this fixes your issue?

**Comment by sonph** [comment]
It still doesn't work with `enableEdgeHovering: true`. I modified `events.html` in the examples and replaced all sigma imports with a single file `sigma.min.js` version `1.0.3` straight from npm. Same results. All events work except for edge events.

**Comment by Yomguithereal** [comment]
I think the lastest `1.0.3` version on npm is vastly outdated. You should probably try to clone the repo and build the files and see whether this changes something.

**Comment by sonph** [comment]
Thanks @Yomguithereal using the newest build solves the problem. Apparently this feature is added after the `1.0.3` release.

**Comment by Yomguithereal** [comment]
We really need to cut a release :).

**Comment by sonph** [comment]
True haha
<img width="473" alt="screen shot 2015-07-20 at 12 47 13 pm" src="https://cloud.githubusercontent.com/assets/2466660/8782817/7e395bb8-2edd-11e5-9494-1d2e789a2657.png">
