### ISSUE TITLE
Edge Settings not Respected Until Resize when Parsing from Gexf

### ISSUE THREAD

**Issue by ELind77** [jacomyal/sigma.js#626]
When loading a graph from a .gexf file the initial rendering of the graph does not respect the settings applied to the edges.  The easiest way to observe this is by simply setting `drawEdges` to `false`.  The resulting rendering has edges, but if you resize the browser window the edges go away.  This is also the case for min/maxEdgeSize.  The easiest way to repeat this is to load any gexf file with the following code (here I'm using the java_dependencies graph distributed with gephi and exported to gexf using gephi):

```
<!DOCTYPE html>
<html>
<head>
    <title>Sigma JS Graph Test</title>

    <style>
        body {
            background-color: black;
        }
        #sigma-container {
            width: 800px;
            height: 800px;
        }
    </style>

</head>
<body>
    <div id="sigma-container"></div>

    <script type="text/javascript" src="sigma.min.js"></script>
    <script type="text/javascript" src="sigma.parsers.gexf.min.js"></script>

    <script>
        sigma.parsers.gexf(
            'java_dependencies.gexf',
            //'les_mis.gexf',
            {container: 'sigma-container'},
            function(s) {
                // Styling
                s.settings({
                    // minEdgeSize: 0.1,
                    // maxEdgeSize: 0.1
                    drawEdges: false
                });
            }
        );
    </script>

</body>
</html>
```

I've tested this with the most recent build: e393fa2835a2ae1b0a1de973ae517e689da552d3

Tested on Chrome:
- Linux (Ubuntu 14.04)
- OS X Yosemite
- Win 8.1

Firefox:
- Linux

Opera:
- Linux

It is possible that this issue is related to [Issue 662](https://github.com/jacomyal/sigma.js/issues/622) and/or [Issue 583](https://github.com/jacomyal/sigma.js/issues/583) but I am not familear enough with the code to know if they are actually related.  

Is this a bug, or am I just doing something wrong?

-- Eric

**Comment by Yomguithereal** [comment]
Hello @ELind77. I think you forgot to call `s.refresh()` after updating the settings. If you want to do it quicker, you should instantiate sigma before calling the parser then passing the instance to the parser.

**Comment by ELind77** [comment]
@Yomguithereal Thanks for responding.  I was unable to find any other examples of using the gexf parser.  Is there documentation or an example of using the parser in the way you're describing?  I suppose I could also just call s.refresh() in the callback, but what you're describing sounds preferable.

**Comment by Yomguithereal** [comment]
Here is what you could do for the second option:

```html
<!DOCTYPE html>
<html>
<head>
    <title>Sigma JS Graph Test</title>

    <style>
        body {
            background-color: black;
        }
        #sigma-container {
            width: 800px;
            height: 800px;
        }
    </style>

</head>
<body>
    <div id="sigma-container"></div>

    <script type="text/javascript" src="sigma.min.js"></script>
    <script type="text/javascript" src="sigma.parsers.gexf.min.js"></script>

    <script>
        var s = new sigma({
            container: 'sigma-container',
            settings: {
                drawEdges: false
            }
        });

        sigma.parsers.gexf(
            'java_dependencies.gexf',
            //'les_mis.gexf',
            s,
            function() {
                s.refresh();
            }
        );
    </script>

</body>
</html>
```

**Comment by ELind77** [comment]
Thank you!  

The fault is mine, I clearly didn't look into the source readme enough: https://github.com/jacomyal/sigma.js/blob/master/plugins/sigma.parsers.gexf/README.md

Confirmed, works like a charm.  You can mark this as closed or I can delete it.  Thank you again for being so responsive. 

-- Eric
