### ISSUE TITLE
Cannot render curvedarrow edge.

### ISSUE THREAD

**Issue by hungdluit** [jacomyal/sigma.js#629]
Hi, I'm quite new with this.

I'm trying create a direct graph but fail when trying to render the arrows.

The following is my error. Can someone help me in finding what wrong I'm doing?

Uncaught TypeError: Cannot read property 'def' of undefinedsigma.canvas.edges.arrow @ sigma.canvas.edges.arrow.js:67
sigma.renderers.canvas.render @ sigma.renderers.canvas.js:247
sigma.render @ sigma.core.js:527
sigma.refresh @ sigma.core.js:498
sigma @ sigma.core.js:199
render_wordnet @ home-scripts.js:77
jQuery.Callbacks.fire @ jquery-2.1.4.js:3099
jQuery.Callbacks.self.fireWith @ jquery-2.1.4.js:3211
done @ jquery-2.1.4.js:8264
jQuery.ajaxTransport.send.callback @ jquery-2.1.4.js:8605

and source code

	var i,
    s,
    N = 10,
    E = 50,
    g = {
    	nodes: [],
    	edges: []
    };

    	// Generate a random graph:
    	for (i = 0; i < N; i++)
    		g.nodes.push({
    			id: 'n' + i,
    			label: 'Node ' + i,
    			x: Math.random(),
    			y: Math.random(),
    			size: Math.random(),
    			color: '#666'
    		});

    	for (i = 0; i < E; i++)
    		g.edges.push({
    			id: 'e' + i,
    			label: 'Edge ' + i,
    			source: 'n' + (Math.random() * N | 0),
    			target: 'n' + (Math.random() * N | 0),
    			size: Math.random(),
    			color: '#ccc',
    			type: ['line', 'curve', 'arrow', 'curvedArrow'][Math.random() * 4 | 0]
    		});

    	// Instantiate sigma:
    	s = new sigma({
    		graph: g,
    		renderer: {
    			container: document.getElementById('graph-container'),
    			type: 'canvas'
    		},
    		settings: sigma.setting
    	});

    });

**Comment by hungdluit** [comment]
Sorry, I close this issues. I think I missed some files when copied to my project

**Comment by davidemiceli** [comment]
Sorry could I ask you what file missing? I have the same problem...

**Comment by hungdluit** [comment]
I think I missed CSS files.

**Comment by jsmrcaga** [comment]
DO you know which files are missing? It does not render curvedArrow, and blocks rendering of nodes
