### ISSUE TITLE
Mouse coordinates on clickEdge

### ISSUE THREAD

**Issue by devgitk** [jacomyal/sigma.js#636]
Hi ,

Like we get the coordinates on clickNode,  is there any other function / code to get the coordinates of the clickEdge event?

Thanks

**Comment by Yomguithereal** [comment]
Hello @devgitk. You should normally be able to access the captor's information (in your case the mouse) in the relevant event:

```js
s.bind('clickEdge', function(e) {

  // Check captor for coordinates
  console.log(e.data.captor);
});
```

**Comment by devgitk** [comment]
@Yomguithereal  Able to get the coordinates, thanks!
