### ISSUE TITLE
Get the source and target on edge click.

### ISSUE THREAD

**Issue by devgitk** [jacomyal/sigma.js#638]
Hi ,
How do you get the source and the target of an edge on click event?
Thanks

s.bind('clickEdge', function(e) {
// get the source and target
}

**Comment by Yomguithereal** [comment]
Hello @devgitk. The events gives you the edge's data. You can then retrieve the source & target nodes likewise:

```js
s.bind('clickEdge', function(e) {
  var edge = e.data.edge;

  var sourceNode = s.graph.nodes(edge.source);
});
```

**Comment by devgitk** [comment]
@Yomguithereal  Thanks , it works :)
