### ISSUE TITLE
Some troubles with webpack

### ISSUE THREAD

**Issue by fobdy** [jacomyal/sigma.js#643]
I have `Container not found.` error when using webpack environment with sigma npm package.
This error occurs because `instanceof HTMLElement` evaluates to `false`.

So i had to comment these fragment in `sigma.require.js`:

``` javascript
// Dirty polyfills to permit sigma usage in node
if (HTMLElement === undefined)
    var HTMLElement = function() {};
```

**Comment by sftrabbit** [comment]
Just also had this issue. Managed to get around it by using imports-loader to import `HTMLElement` into Sigma (also needed to do the same for `window` too). Ended up with the following additional loader:

    {
      loader: 'imports?window,HTMLElement',
      test: require.resolve('sigma')
    }

And also added the following externals to the webpack config:

    externals: {
      window: 'window',
      HTMLElement: 'HTMLElement'
    }

**Comment by Wilfred** [comment]
Should be fixed in 31cc1ee3baf321d355f5597ba4d7e9fc8e2c6ff2, not yet released.

**Comment by Yomguithereal** [comment]
@Wilfred can you confirm that my fix on master works so that I can release a new version of the lib please?

**Comment by Wilfred** [comment]
I've just tested it now, I can confirm the fix works :)

**Comment by Yomguithereal** [comment]
Cool. Will soon release a version.
