### ISSUE TITLE
Does sigma.js provide layout algorithms?

### ISSUE THREAD

**Issue by interdrift** [jacomyal/sigma.js#650]
I couldn't find any information in the tutorial about that?

Thanks.

**Comment by Yomguithereal** [comment]
Hello @interdrift,
yes it does implement the ForceAltas2 algorithm that you can find [here](https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.layout.forceAtlas2).

**Comment by interdrift** [comment]
Thanks :+1:
