### ISSUE TITLE
Possible to get the steps in the forceAtlas ?

### ISSUE THREAD

**Issue by avermeir** [jacomyal/sigma.js#661]
Hi all, 

I would like to perform some transformations and/or checks at each step in the forceAtlas algorithm. Or maybe every 5 - 10 steps. Is there a way to retrieve it and register an event ?

(Typically, i would like to slow it down and stop it automatically when nodes arent moving that much anymore, so a kind of convergence check)

Many thanks,
Auré

**Comment by Yomguithereal** [comment]
Hello @avermeir. You should check out the [forceatlas2-namespace](https://github.com/jacomyal/sigma.js/tree/forceatlas2-namespace/plugins/sigma.layout.forceAtlas2) branch and see how the cooldown function works. Tweak it a little and you should get wha you need.

**Comment by avermeir** [comment]
Crystal cleat thanks!
