### ISSUE TITLE
Setting a fixed node border color from JSON graph

### ISSUE THREAD

**Issue by silverandrew** [jacomyal/sigma.js#662]
Hi. I used the JSON exporter for Gephi and imported the JSON block into Sigma. It mostly displays okay, but there is no border around the nodes. A border appears on hover (which is the default setting) I was looking at https://github.com/jacomyal/sigma.js/issues/49 - which is closed - and the suggestion is to always display hovering settings. But I tried "
defaultBorderView: "always"//apply the default color to all nodes always (normal+hover) 
"
and it doesn't appear to be a valid setting currently (I checked in the docs).

Ideally what I want: a black border around all of my nodes. Does this functionality exist in the code somewhere?

Thanks for any help/suggestions.

**Comment by AVermeij** [comment]
You need a custom renderer for that. @Yomguithereal wrote a great post on the topic, see here: yomguithereal.github.io/articles/node-border-renderer/

**Comment by silverandrew** [comment]
Awesome thanks. Closing.
