### ISSUE TITLE
Forceatlas on a subset

### ISSUE THREAD

**Issue by avermeir** [jacomyal/sigma.js#671]
Hi all,

Is it possible to execute forceatlas on. Subset of the graph?

Best,
Auré

**Comment by apitts** [comment]
Related to: 
https://github.com/jacomyal/sigma.js/issues/15

@avermeir Please see the linked issue. To my knowledge it is not currently possible to do so.

**Comment by avermeir** [comment]
Indeed... Maybe i will try a homebrew FA, ty for the followup

**Comment by Yomguithereal** [comment]
I you need the other nodes not to affect the layout then yes, #15 is the correct issue. Else, you can "fix" the other nodes.
