### ISSUE TITLE
Undocumented settings in wiki

### ISSUE THREAD

**Issue by Compynerd255** [jacomyal/sigma.js#673]
I was reading the Settings documentation in the wiki and am finding that it needs a lot of work. Not only could it use some formatting and clarification (which I have already begun to do and anyone is welcome to finish), but I am also finding that there are some settings that are not documented at all and are only discoverable by browsing the source code. For instance, the `prefix` setting, which is really awesome to know about and even more important to support, is not found on the page at all, probably because it is not assigned to anything in `sigma.settings.js`.

Are there any other settings like this? Can we be sure to add them to the wiki and perhaps to the default settings file?

**Comment by JorgensenHans** [comment]
Well, I've been using Sigma a little more and I found out the use of the `prefix` setting - it's for the rendering system, specifically. This does seem like an abuse of the settings object, but still - that's not part of the problem.

However, like I've already started doing, could we put all of the settings in tables?

**Comment by Yomguithereal** [comment]
Sure. Go ahead @JorgensenHans. The table layout might result strange however, due to the amount of text present in some of the description.

Do come back here if you need precision about some settings and I'll find some time for you.

**Comment by Compynerd255** [comment]
I finished tabling out the settings and have also made a few more Wiki pages. I think that everything in settings is covered sufficiently - I'll just continue documenting if I stumble into using another feature that isn't documented clearly.

**Comment by Yomguithereal** [comment]
Thanks @Compynerd255 :-) !
