### ISSUE TITLE
Connect the node to itself

### ISSUE THREAD

**Issue by IonicaBizau** [jacomyal/sigma.js#681]
Is it possible to connect a node to itself?

**Comment by Yomguithereal** [comment]
I guess so. But you would need a specific renderer to display it.

**Comment by AVermeij** [comment]
When you set your edge type to ``curve``, the canvas renderer will render a Bezier curve in case the source id equals the target id. This then shows in your network as a self-loop. See here (lines 50 and 51):

https://github.com/jacomyal/sigma.js/blob/master/src/renderers/canvas/sigma.canvas.edges.curve.js

**Comment by IonicaBizau** [comment]
@AVermeij Thanks! `curve` and `curveArrow` worked fine and multiple ones work as well (#682). :cake:

**Comment by Gustutu** [comment]
Hello could you give me please more precision on how to set the default edge type to curve thanks ;).

**Comment by AVermeij** [comment]
@Gustutu, assuming ``s`` is your sigma instance, you can set the default edge type using ``s.settings('defaultEdgeType', 'curve')``. 

Or you could pass it as a key in the settings object when initializing sigma:

````
s = new sigma({
  graph: g,
  container: 'graph-container',
  settings: {
    defaultEdgeType: 'curve'
  }
});
````
