### ISSUE TITLE
Multiple edges

### ISSUE THREAD

**Issue by IonicaBizau** [jacomyal/sigma.js#682]
I tried to display multiple edges, but just one is displayed.

Isn't this supported already?

**Comment by AVermeij** [comment]
If you mean displaying multiple edges between the same two nodes, you can use the parallel edges plugin to accomplish this: https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.renderers.parallelEdges

You need to set a ``count`` attribute on each of the edges to make sure the plugin renders the edges separarely from each other. If you don't do this, it will just render them on top of each other.

**Comment by IonicaBizau** [comment]
@AVermeij Oh, I see! Thanks! :+1:
