### ISSUE TITLE
Displaying axis data?

### ISSUE THREAD

**Issue by hybr1dz** [jacomyal/sigma.js#685]
Hi, is there a simple way to display axis data with Sigma? I mean something like this https://support.office.com/en-us/article/Add-axis-titles-to-a-chart-e5680ea2-f75a-4234-b140-2b9650792491
or is Sigma only suitable for network graphs? Basically i'm looking for a library that would help implementing a realtime stock market graph with WebGL.

**Comment by Yomguithereal** [comment]
You could do that with sigma but I feel it would be slightly overkill. You should probably rather use something like [d3](http://d3js.org/) or [highcharts](http://www.highcharts.com/) to meet your needs. Sigma is indeed really focused on network graphs rendering.

**Comment by hybr1dz** [comment]
Ok thanks for clearing that up.

**Comment by Yomguithereal** [comment]
No problem @hybr1dz.
