### ISSUE TITLE
[difficult start] Error: WebGL: Error during ANGLE OpenGL init

### ISSUE THREAD

**Issue by glorieux-f** [jacomyal/sigma.js#689]
I would like to produce graphs like the picture attached on dramas https://github.com/dramacode
This one shot graph is done with Gephi, it is of course more interesting to produce the same automatically online on multiple dramas to compare their plot. I got a non running sample code on a gist. https://gist.github.com/glorieux-f/2b9c028c610144266955
What’s wrong ?
In the console the only messages I have are things like :
Error: WebGL: Error during ANGLE OpenGL init.
	...ument.createElement("canvas");try{c=!(!b.getContext("webgl")&&!b.getContext("exp...

Thanks for any tip. When it will works, this code will be of course free for your collection of examples (to change from Les Misérables).

![moliere_tartuffe_graph](https://cloud.githubusercontent.com/assets/5686231/12031436/3913fb66-ae0c-11e5-88c0-22abb6bf521e.png)

**Comment by Yomguithereal** [comment]
Hello @glorieux-f. There seems to be an error with your WebGL runtime that JavaScript code fails to detect beforehand. You should try to force sigma's rendering to use canvas. I can show you how to do so if you want.

**Comment by glorieux-f** [comment]
It could be nice of you. I’m digging on my WebGL issue.
Is my sample code in the Gist runing for you ?
https://gist.github.com/glorieux-f/2b9c028c610144266955
Is there enough data ? For example I have no (x,y) for nodes, I would like to see the brute force (Atlas) result.

**Comment by Yomguithereal** [comment]
So, to force the canvas renderer, you can try the following:

```js
var s = new sigma({
  graph: g,
  renderer: {
    type: 'canvas',
    container: document.getElementById('container')
  }
});
```

**Comment by Yomguithereal** [comment]
You should give a (x,y) to your nodes (albeit random), or else I guess the library won't display anything.

**Comment by Yomguithereal** [comment]
What do you mean by "brute force"?

**Comment by glorieux-f** [comment]
IT WORKS  ! (at least, for a first start)
(x,y) is required. It could be a nice feature to provide random coordinates as default, same for auto id for edges. Shall I open an issue for that ?
Sorry for this "brute force" expression, I mean without human interaction (like usually in Gephi).
Forcing the renderer as canvas is not required for me, even if I have still those weird WebGL messages in the console.

**Comment by Yomguithereal** [comment]
> (x,y) is required. It could be a nice feature to provide random coordinates as default, same for auto id for edges. Shall I open an issue for that ?

It has been in discussion for a long time but people haven't agreed yet on what to do in this case. But a heads up to the developer should really be in place.

> Forcing the renderer as canvas is not required and do not avoid those weird WebGL messages in the console. Maybe this issue should be kept opened ?

Yes indeed.

**Comment by glorieux-f** [comment]
Fresh clone of now Sigma, /examples/basic.html, 
error reproduced with Firefox 43.0.2 Windows 10
BUT
gone after update with Firefox 43.0.3
ISSUE could be considered closed
