### ISSUE TITLE
Detecting the event of a converging graph that is animated by forceAtlas2

### ISSUE THREAD

**Issue by hammady** [jacomyal/sigma.js#69]
I would like to set a convergence threshold for a graph that is being animated using forceAtlas2 plugin. Upon converging to that threshold I would like to handle this event by stopping the animation and draw()ing the graph to display edges.
Is this possible?

**Comment by stuartpb** [comment]
This should be part of the plugin.

**Comment by Yomguithereal** [comment]
Auto stopping an interative graph layout is a difficult task
