### ISSUE TITLE
Remix nodes ? (and tips welcome on theatre graphs)

### ISSUE THREAD

**Issue by glorieux-f** [jacomyal/sigma.js#693]
I’m working on theatre plays to show text interaction between roles. (Sorry, mainly French theatre, no Shakespeare). Already thanks for Sigma, it works very well.
http://fictif.org/resultats/pamphlet6/net.php?play=racine_1677_phedre

I would like to propose a button to remix nodes.
My code is not yet working, where am i wrong ?

```javascript
  // s is a sigma instance
  s.killForceAtlas2();
  for (var i; i < s.graph.nodes().length; i++) {
    s.graph.nodes()[i].x = Math.random();
    s.graph.nodes()[i].y = Math.random();
  }
  s.refresh();
```
Tanks for any tips and critics to improve the view.

**Comment by AVermeij** [comment]
You almost got it - there's a slight error in your loop. If you set your variable ``i`` to ``0``, you'll be good to go:
``
 s.killForceAtlas2();
  for (var i=0; i < s.graph.nodes().length; i++) {
    s.graph.nodes()[i].x = Math.random();
    s.graph.nodes()[i].y = Math.random();
  }
  s.refresh();
``

**Comment by glorieux-f** [comment]
Thanks ! Sorry for a such idiot bug.
