### ISSUE TITLE
defaultEdgeArrow with sigma.parsers.json

### ISSUE THREAD

**Issue by AlfredSD** [jacomyal/sigma.js#714]
Hi,

I'm trying to render a graph using the data parsed from the JSON parser. However the defaultEdgeType and defaultArrowType settings don't seem to take effect. The following is the code I used:

```
<html>
<head>
<style type="text/css">
  #container {
    max-width: 1024px;
    height: 800px;
    margin: auto;
  }
</style>
</head>
<body>
<div id="container"></div>
<script src="js/sigma.min.js"></script>
<script src="js/plugins/sigma.parsers.json.min.js"></script>
<script src="js/plugins/sigma.layout.forceAtlas2.min.js"></script>
<script>
  sigma.parsers.json('file.json', {
    container: 'container',
	type: 'canvas',
    settings: {
      defaultNodeColor: '#ec5148',
      defaultEdgeType: 'curve'
    }
  },function(s) {
    s.startForceAtlas2();
  }
);
</script>
</body>
</html>
```

Is it a mistake on my part?

**Comment by Yomguithereal** [comment]
Hello @AlfredSD,

You should try the following:

```js
sigma.parsers.json('file.json', {
    container: 'container',
    type: 'canvas',
    settings: {
      defaultNodeColor: '#ec5148',
      defaultEdgeType: 'curvedArrow',
      minArrowSize: 2,
      maxArrowSize: 7
    }
  },function(s) {
    s.startForceAtlas2();
  }
```

**Comment by Yomguithereal** [comment]
Summing it up: you need to use the `curvedArrow` renderer if you want to render both curvy edges and arrows. Plus, you should tweak the min and max arrow size settings to get where you want.

**Comment by AlfredSD** [comment]
Ah, my bad. Lesson learned.

Thanks @Yomguithereal :)

**Comment by Yomguithereal** [comment]
Did it work then?

**Comment by AlfredSD** [comment]
Yes it did. But the size of the arrow head doesn't seem to change despite whatever value I put in minArrowSize.
