### ISSUE TITLE
How to disable all labels 

### ISSUE THREAD

**Issue by emixam150** [jacomyal/sigma.js#716]
Hello,
I use canvas renderer. I want to disable labels which are draw on big nodes and when I hover one node. I change `enableHovering` and `drawLabels` to `false`. But labels still appear when i hover a node. :cry: 
Someone can help me ?

**Comment by Yomguithereal** [comment]
Hello @emixam150. Can you show me some of your code so I can help you better?

**Comment by emixam150** [comment]
Sorry, I try a third time and it seems to work now. Thanks !

**Comment by Yomguithereal** [comment]
No problem @emixam150.
