### ISSUE TITLE
How to 'stop' ForceAtlas2 from rendering?

### ISSUE THREAD

**Issue by hyperized** [jacomyal/sigma.js#72]
I would like to know how I stop ForceAtlas2 from rendering infinitely. I am aware that you can call siginstance.stopForceAtlas2() and that you can put a timer on it it, but this is far from ideal. Will it ever stop rendering by itself?

Maybe more importantly, can I just call the end result or speed it up a lot? This way I can let my software call out the nodes and edges and have sigma + ForceAtlas2 handle the order based on the clusters and egdes and not have the page visitors wait for ever to see the edges. Please let me know!

**Comment by stuartpb** [comment]
Yeah, it'd be nice if there was a configuration option for something like "stop once nodes have not moved significantly for X seconds".

**Comment by hyperized** [comment]
4 years later, I think the answer is no?

**Comment by Yomguithereal** [comment]
No good heuristic was found yet to stop layout by itself. You might think this is a trivial problem because you can perform some kind of `"stop once nodes have not moved significantly for X seconds"` test but you can't really and this hugely depends on your graph and its morphology. So right now, a timeout is as good a solution as another or you need to ask your user to stop the layout himself.

**Comment by hyperized** [comment]
@Yomguithereal Fair enough, i'll close this :).

**Comment by wthrajat** [comment]
@Yomguithereal 
> So right now, a timeout is as good a solution as another or you need to ask your user to stop the layout himself

Have we found a better solution?
If not, can we just set the timeout for say `5` seconds (or do we have to set the timer for more seconds if we have large graphs?)

**Comment by Yomguithereal** [comment]
> Have we found a better solution?

No. Stopping a layout is a very hard optimization problem akin to stochastic gradient descent etc. of a non-obvious, non-linear and chaotic function. Some cases are trivial, some other are devilishly hard, even though they seem very simple.

> If not, can we just set the timeout for say 5 seconds (or do we have to set the timer for more seconds if we have large graphs?)

Yes, or use a limited number of iteration. But don't expect anything else than this to be a very imperfect heuristic.
