### ISSUE TITLE
How to set the edge opacity and thickness to be the same as the one on Gephi?

### ISSUE THREAD

**Issue by dumpsters** [jacomyal/sigma.js#732]
In gephi my graph looks amazing in the "Preview" but when I visualize it in vis it looks terrible without any opacity or edge thickness that I setted. Couldn't find anything related to that in the docs.

**Comment by Federicopvs** [comment]
same issue here.. not using gephi but nevertheless badly need an opacity property that can be set dynamically  (according to node attribute)

**Comment by Foudres** [comment]
hi guys, Increase the memory that's gephi can use fix the problem
