### ISSUE TITLE
Nodes added with read get strange performance in hover event

### ISSUE THREAD

**Issue by llp0574** [jacomyal/sigma.js#737]
Hi,
I am trying to add nodes and edges into graph by using `graph.read()`, but there is a strange performance after refreshing the graph.
Before adding them, the nodes and edges in rendered graph will have normal hover event, I filter some nodes and edges from rendered graph into two arrays (`hideNodes` and `hideEdges`) and then drop them from rendered graph. code below:

```
... // codes

s.graph.nodes().forEach(function (n) {
  if (n.attributes.cat !== 'id') {
      hideNodes.push(n);
      s.graph.edges().forEach(function (e) {
        if (e.source === n.id || e.target === n.id) {
          hideEdges.push(e);
        }
      });
      s.graph.dropNode(n.id);
    }
  n.layout_x = n.x;
  n.layout_y = n.y;
  n.x = 0;
  n.y = 0;
});
sigma.plugins.animate(
  s,
  {
    x: 'layout_x',
    y: 'layout_y'
  },
  {
    duration: 2000
  }
);
s.refresh();
```

After that, there will be a event which is aimed to add `hideNodes` and `hideEdges` into rendered graph, code below:

```
s.graph.read({
  nodes: hideNodes,
  edges: hideEdges
});
sigma.plugins.animate(
  s,
  {
    x: 'layout_x',
    y: 'layout_y'
  },
  {
    duration: 1000
  }
);
s.refresh();
```

And after triggering the event, the hideNodes and hideEdges will be added into graph successfully. But the hover event of nodes will show a strange performance: **some nodes can hover normally but some others can not be hovered(whether the node is new added or not), and the click event will get the same situation**.
In addition, the hover event of edge will behave normally.

I am not sure what is the reason causing this problem.
Looking forward to your help, thank you!

Note:
code below is my graph settings:

```
settings: {
  nodeActiveColor: 'default',
  nodeBorderSize: 2,
  nodeHoverBorderSize: 5,
  nodeActiveBorderSize: 2,
  dragNodeStickiness: 0.01,
  defaultNodeBorderColor: '#fff',
  defaultNodeHoverBorderColor: HIGHLIGHT,
  defaultNodeActiveBorderColor: HIGHLIGHT,
  nodeActiveOuterBorderSize: 3,
  labelAlignment: 'top',
  drawLabels: false,
  edgeColor: 'default',
  defaultEdgeColor: '#ccc',
  enableEdgeHovering: true,
  edgeHoverColor: 'edge',
  defaultEdgeHoverColor: '#ff0000',
  edgeHoverSizeRatio: 1,
  edgeHoverExtremities: true,
  zoomMin: 0.001,
  zoomMax: 3
}
```

**Comment by Yomguithereal** [comment]
Hello @llp0574. You can try to set a `hidden` property on the nodes you want to hide rather than dropping them from the graph (no need to hide the edges because they won't be displayed unless all of their extremities are show). This way you should dramatically increase performance.

**Comment by llp0574** [comment]
Hi @Yomguithereal ,thank for your suggestion! It really increase performance when I use `hidden` instead of `dropNode`, and I also found the reason that causing the problem of node hover event, I should `refresh` the graph in the callback of `animate` function, code below:

```
... // codes
s.graph.nodes().forEach(function (n) {
  if (n.attributes.cat !== 'id') {
      n.x = x;
      n.y = y;
      n.hidden = false;
    }
});
sigma.plugins.animate(
  s,
  {
    x: 'layout_x',
    y: 'layout_y'
  },
  {
    duration: 1000
  },
  function () {
    s.refresh();
  }
);
```
It solved this problem perfectly, thank you again!
