### ISSUE TITLE
creat a build folder on repo

### ISSUE THREAD

**Issue by maruilian11** [jacomyal/sigma.js#740]
recently we want to add your lib to https://cdnjs.com. could you please consider add the built `build` folder on repo so that we can use **git auto-update** to add every released version.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/5789

**Comment by Yomguithereal** [comment]
Sigma.js & its plugins are already on cdnjs [here](https://cdnjs.com/libraries/sigma.js) no?

**Comment by maruilian11** [comment]
sorry for not checking it first this time.
thank you very much.

**Comment by Yomguithereal** [comment]
No problem @maruilian11.
