### ISSUE TITLE
where is the online examples? thanks !

### ISSUE THREAD

**Issue by junneyang** [jacomyal/sigma.js#741]

**Comment by Yomguithereal** [comment]
You can find examples in the [`examples`](https://github.com/jacomyal/sigma.js/tree/master/examples) folder of the repository. But I am afraid you'll have to clone the repo and serve the folder to check them out.

**Comment by Wilfred** [comment]
As mentioned in #450, you can use rawgit, e.g. https://rawgit.com/jacomyal/sigma.js/master/examples/basic.html

@Yomguithereal how do you feel about adding rawgit links to the sigma.js homepage? The examples are hugely helpful and it would be nice to make them more visible.
