### ISSUE TITLE
Prevent graph from panning

### ISSUE THREAD

**Issue by geraldo** [jacomyal/sigma.js#746]
Disable graph zooming can be done by settings - but I can't find no way to turn off panning of the graph. As a workaround I limit the range of panning of the camera as described in [this](https://github.com/jacomyal/sigma.js/issues/574) and [this](https://github.com/jacomyal/sigma.js/issues/251) issue, but in my case it would be better to totally turn off panning. Any hints?

**Comment by Yomguithereal** [comment]
Hum, I am not sure you can turn off panning but if what you want is to disable any way to interact with the graph & just render it statically, you can try the disabling the `mouseEnabled` setting.

**Comment by geraldo** [comment]
I need interaction with the graph but want to avoid that users accidentally pan outside the graph. I could configure it setting `scalingMode: 'outside'` and additionally avoiding zoom with `zoomMin` and `zoomMax` set to `1`.
