### ISSUE TITLE
Plugins with parser gexf files

### ISSUE THREAD

**Issue by developer-f-end** [jacomyal/sigma.js#750]
Hello, have a question.
All plugins connected to sigma object, but not example where is plugin will connect on parse file like .gexf(plugin gexf-parser.js) (if this possible) please explain how

**Comment by norbertFeron** [comment]
In example there is a file 'load-external-gexf'

https://github.com/jacomyal/sigma.js/blob/master/examples/load-external-gexf.html

**Comment by developer-f-end** [comment]
it`s clear, but how connect plugin to this object:
``
sigma.parsers.gexf('data/arctic.gexf', {
  container: 'graph-container'
}); 
``
