### ISSUE TITLE
gephi to HTML

### ISSUE THREAD

**Issue by azadehrasooli** [jacomyal/sigma.js#751]
hi!
completely new to coding. 
I have an owl ontology made with protege. then I built the gephi file. now need a HTML file for my website. what should I do!

**Comment by norbertFeron** [comment]
Hello, 
If you have a gexf file and wanna display in web browser you can use [sigma.parsers.gexf] (https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.parsers.gexf) plugin
An example : [load-external-gexf.html](https://github.com/jacomyal/sigma.js/blob/master/examples/load-external-gexf.html)

**Comment by azadehrasooli** [comment]
Thanx ALOT
