### ISSUE TITLE
sigmajs working on ios

### ISSUE THREAD

**Issue by gdem123** [jacomyal/sigma.js#759]
Hi
the graph does not appear on ios ipad using safari. 
Is this exact?
Best,
gdem

**Comment by sim51** [comment]
Sigma is working on safari on a mak book, so it also should work on an Ipad.
Do you have an example that doesn't work on safari but works on a desktop browser ?

**Comment by gdem123** [comment]
Merci pour votre retour.
Voici le code que j'utilise: le graphe que je produis et qui fonctionne sur macbook n’apparaît tout simplement pas sur iPad.

D’autre part je ne sais pas comment changer la taille des edges. ce code ne fonctionne pas. Ils sont aussi très longs et se baladent très loin de leurs nodes: comment rendre tout ceci plus compact?

Merci bcp.

j’ai mis tous les plugins… 

<script type="text/javascript" src={{url_for('static',filename='js/sigma.min.js')}}></script>


<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.exporters.svg.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.parsers.gexf.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.parsers.json.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.pathfinding.astar.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.plugins.animate.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.plugins.dragNodes.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.plugins.filter.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.plugins.neighborhoods.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.plugins.relativeSize.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.renderers.customEdgeShapes.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.renderers.customShapes.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.renderers.edgeLabels.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.renderers.parallelEdges.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.renderers.snapshot.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.statistics.HITS.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.layout.forceAtlas2.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.neo4j.cypher.min.js')}}></script>
<script type="text/javascript" src={{url_for('static',filename='js/plugins/sigma.parsers.cypher.min.js')}}></script>

<script type="application/javascript">

    

    sigma.neo4j.cypher(
            { url: myurl,user:myuser,password:mypassword },
            "{{query|safe}}",
            { container: 'graph-container' } ,
            function(s) {
                mynodes=s.graph.nodes();
                myedges=s.graph.edges();
                console.log(mynodes);

                console.log('Number of nodes :'+ mynodes.length);
                console.log('Number of edges :'+ mynodes.length);
                for (i=0;i<mynodes.length;i++){
                  console.log(mynodes[i]);
                  mynodes[i]['label']=mynodes[i]['neo4j_data']['name'];
                  mynodes[i]['size']=4;
                  switch(mynodes[i]['neo4j_labels'][0]){
                    case ‘aaaa':
                      mynodes[i]['color']='#A9A9A9' //grey
                      mynodes[i]['size']=15
                      break;
                    case ‘xxx':
                      mynodes[i]['color']='#000000' //black
                      mynodes[i]['size']=15
                      break;
                    case ‘yyyy':
                      mynodes[i]['color']='#9400D3' //darkviolet
                      mynodes[i]['size']=25
                      break;
                    
                    default:
                      mynodes[i]['color']='#00000'
                      break;
                  }

                }
                for (j=0;j<myedges.length;j++){
                  console.log(myedges[j]);
                  switch(myedges[j]['neo4j_type']){
                    case ‘ffff':
                      myedges[j]['color']='#A9A9A9' //grey
                      myedges[j]['size']= 5
                      break;
                    case ‘eeee':
                      myedges[j]['color']='#0000FF'//blue
                      myedges[j]['size']= 5
                      break;
                    
                    default:
                      myedges[j]['color']='#00000' //black
                      break;
                  }
                }


               
                s.bind('doubleClickNode', function(event) {
                  console.log(event.data.node.id);
                  window.location.href="/graph/".concat(event.data.node.id);
                });
               
               

                s.refresh();
                s.startForceAtlas2({linLogMode:true,worker:true,barnesHutOptimize:false,strongGravityMode:true,adjustSizes:false,outboundAttractionDistribution:true,startingIterations:10,iterationsPerRender:10,edgeWeightInfluence:1000});
                // Initialize the dragNodes plugin:
                var dragListener = sigma.plugins.dragNodes(s, s.renderers[0]);
                dragListener.bind('startdrag', function(event) {
                  console.log(event);
                  s.killForceAtlas2();
                });
               
                dragListener.bind('drop', function(event) {
                  console.log(event);
                  s.startForceAtlas2({linLogMode:true,worker:true,barnesHutOptimize:false,strongGravityMode:true,adjustSizes:false,outboundAttractionDistribution:true,startingIterations:10,iterationsPerRender:10,edgeWeightInfluence:1000});
                });
                
                s.refresh();
              }

    );


</script>

Y aurait-il une explication??

Bien à vous,

Guillaume Thibaut
