### ISSUE TITLE
How to set initial zoom level ?

### ISSUE THREAD

**Issue by Kuroky360** [jacomyal/sigma.js#760]
does sigma.js support this? 
thanks very much.

**Comment by AVermeij** [comment]
If ``s`` is your sigma instance, you can do it as below right after initializing sigma. A ratio below 1 will zoom in; a ratio higher than 1 will zoom out:

``s.cameras[0].goTo({ x: 0, y: 0, angle: 0, ratio: 0.5 });``

**Comment by Yomguithereal** [comment]
This is indeed how you should do. Thansk @AVermeij.

**Comment by Kuroky360** [comment]
Thanks for your quick feedback!   :+1:  @AVermeij
