### ISSUE TITLE
Why do edges need an ID

### ISSUE THREAD

**Issue by Federicopvs** [jacomyal/sigma.js#771]
I just started using sigma.js and I was wondering why edges also need to have a unique id..
Can I assign a random id to each (like their index number)?
Or does the id have to be consistent with their position or the nodes they connect?

**Comment by jotunacorn** [comment]
The ID is only used as an identifier, so it has to be unique but you can choose anything you like for it, for instance a counter that you increase for each edge, or Math.random if you use enough digits.

The id is used to uniquely identify the edge when using methods such as dropEdge(id). If you don't need to address an added edge after it's creation you can discard the id.

**Comment by Yomguithereal** [comment]
In future versions, we'll use a system able to generate ids for you so you don't have to handle this problem. But, indeed, for the time being, the data model needs a unique identifier provided by the user.
