### ISSUE TITLE
GraphML parser?

### ISSUE THREAD

**Issue by anderspitman** [jacomyal/sigma.js#780]
I'm a little surprised that there doesn't appear to be a general purpose GraphML parser for javascript. I figured if any library would have one implemented it would be sigma. Is there one that I'm missing somehow?

I would just use gexf but I need to import from C++ boost BGL which only writes to graphviz and graphml.

**Comment by anvaka** [comment]
I'm not a contributor in this repository, but I love graphs in general. I briefly looked at [GraphML specs](http://graphml.graphdrawing.org/specification.html) and thought to myself, that it was too verbose to justify its use. 

There are better formats, like a simple `dot` file that is expressive, readable, and well-supported by many tools (including several javascript packages: [siefkenj/dotgraph](https://github.com/siefkenj/dotgraph), [cpettitt/graphlib-dot](https://github.com/cpettitt/graphlib-dot), [anvaka/ngraph.fromdot](https://github.com/anvaka/ngraph.fromdot) and even low-level [AST generator](https://github.com/anvaka/dotparser))

**Comment by anderspitman** [comment]
Thanks for the reply @anvaka. I've used `dot` in the past, but it doesn't support non-visual attributes, correct? See [here](https://gephi.org/users/supported-graph-formats/)

**Comment by anderspitman** [comment]
I went ahead and implemented a simple graphml parser for javascript. It's nowhere near feature complete but does what I need:

https://github.com/anderspitman/graphml-js
