### ISSUE TITLE
Parser Error Callbacks

### ISSUE THREAD

**Issue by x0xMaximus** [jacomyal/sigma.js#802]
While I understand the design approach of allowing various parser types, it seems like there should be a uniform way to handle server error statuses – whether it's on the parser, or an event I can listen to on the graph instance.

What prompted this realization is a graph origin (server that generates a JSON graph dynamically) would fail for reasons out of our control. It's fine as the graph is part of a page with a lot of other content, but I would like a clear way to use the call back to hide the "show graph" button if I can detect there was a network request, or parsing problem.

If I'm missing something obvious about this feature request, then I'd suggest it's added to the [examples](https://github.com/jacomyal/sigma.js/tree/master/examples) as it's not evident after looking through the project.

Thanks,
M

**Comment by Yomguithereal** [comment]
Hello @x0xMaximus. Our current opinion on the subject is that we should separate parsing from the actual fetching work, which should be done by the user on its own means. However, the current paradigm is the product of a now bygone era where ajax was a drag and when some sugar was useful so that it remains simple to use the library.

**Comment by x0xMaximus** [comment]
@Yomguithereal thanks for the prompt response. So I understand the desire / origins of keeping parsing and fetching separate, but looking at this error:

![](http://i.imgur.com/pocuJ0i.png)

The first line is from the server response, the second is from sigma trying to parse the debug page (or any content that will come up on a failed request).

I only need to identify 1 of them to give a better user experience. Could it be that errors in the library during parsing only are raised and directed to send an error event I could listen to? It would add very little complications for new users to get setup with the library, but if they wanted to read how to handle errors, they'd be able to listen for this specific event and then respond appropriately.

**Comment by Yomguithereal** [comment]
Actually we are working on a new version of the library currently that will fix this kind of things. For now, one easy workaround is to fetch the data by your own means and feed the data to the parsers themselves rather than making them fetch the data for you.

**Comment by x0xMaximus** [comment]
@Yomguithereal great – hope the new version development is going smoothly and looking forward to it. Will make that change in the meantime.

Thanks,
M
