### ISSUE TITLE
toggle drawLabels

### ISSUE THREAD

**Issue by rudolfII** [jacomyal/sigma.js#818]
Hello,

I want to be able to toggle visibility of labels of
an existing graph.
I believe I have to toggle the drawLabels property
of some object, but I am unable to find which one.
If you can help...

I have this in my html <script>

var s = new sigma({
        renderer: {
          container: document.getElementById("graphContainer"),
          type: 'canvas'
        },
        settings: {
         --- quite a few here-irrelevant settings ---
        }
      })

and at some point I have

s.graph.read(someGraph)

to populate the graph part.

All that I tried to toggle the visibility did not do it.

Thanks for any comments!

Ruda

**Comment by AVermeij** [comment]
That should be pretty easy actually. After reading your graph, call this:

``// Set the drawLabels setting to false``
``s.settings({drawLabels: false});``
``// Refresh the graph to see the changes``
``s.refresh();``

**Comment by rudolfII** [comment]
Dear AVermeij,

>> s.settings({drawLabels: false});

works, indeed.
I guess, at some point I tried s.settings.drawLabels = false...

Thanks a lot
Ruda
