### ISSUE TITLE
How to give attribute values and Color to node of graph

### ISSUE THREAD

**Issue by geekyminhaj** [jacomyal/sigma.js#824]
I want to know how to give attribute values to a node of a graph like Bad_value, Good_value etc other than ID and label of the graph.
Also I want to create a graph where I want to give a different color to nodes based on some attribute values of nodes.
 eg. Each node is having attribute values as [x, y] where 0<=x,y<=1 and x+y=1.
I want node color to be:
(i) Red if x>0.5,
(ii) white if x=0.5
(iii) Green if x<0.5

**Comment by Yomguithereal** [comment]
The node is basically just a JavaScript object, so you can give it anything you like as a property:

```js
s.graph.addNode({id: 'nodeid', value: 'good', color: computeTheColor()});
```

**Comment by geekyminhaj** [comment]
Thanks a lot for the quick help.

**Comment by Yomguithereal** [comment]
No problem @geekyminhaj. I'll close this issue but don't hesitate to re-open it if you have further questions.
