### ISSUE TITLE
Using sigmajs for Bipartite graph visualization and highlighting shortest path between two nodes

### ISSUE THREAD

**Issue by geekyminhaj** [jacomyal/sigma.js#826]
I have two use cases and trying to find a solution using sigma.js. I tried to find the solution for these two use cases everywhere on the internet but could not find any help. Any lead will be greatly appreciated:
1) Is it possible to use sigma.js for visualization of the Bipartite graph ?if yes how can we use sigma.js for it?
2) Is it possible to highlight the shortest path to a given node from the list of given nodes in the undirected graph?
e.g. Node A is my target node and Nodes B, C and D are the source nodes from which I want to highlight the shortest path to node A in the visualization. Is this use-case is possible in using sigma.js directly or using any plugin?

Any lead will be greatly appreciated.

**Comment by Yomguithereal** [comment]
1. Sure, you probably want to color both types of nodes differently.
2. There is a A* plugin here: https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.pathfinding.astar

**Comment by geekyminhaj** [comment]
Thanks, @Yomguithereal  for the quick help.
