### ISSUE TITLE
is there any way to display tightly connected nodes of graph closer to each other

### ISSUE THREAD

**Issue by geekyminhaj** [jacomyal/sigma.js#830]
I want to visualize the graph in such a way that tightly connected nodes displays close to each rather than having too many crossing edges in the graph. In another way, I want as less as possible crossing edges in my graph. Is there any way to do this in sigma js?

**Comment by sim51** [comment]
Have you tested the `forceatlas2` layout ?

**Comment by geekyminhaj** [comment]
I am trying forceatlas2 layout but my nodes are not stable at their position but keep jumping in the final output.

**Comment by geekyminhaj** [comment]
thanks @sim51, now I have fixed this jumping issue.
