### ISSUE TITLE
Loading SigmaJS Graph in browser

### ISSUE THREAD

**Issue by SuLy-IG** [jacomyal/sigma.js#857]
Hi, 
I am having terrible trouble getting a sigmajs website to work.  I exported it from gephi and loads perfectly. However when I transfer it to my remote server (which apache and Django), the html is displayed on the browser but not the graph. 
Are there instructions I'm missing that would help here?
Thanks!

**Comment by Yomguithereal** [comment]
Out of the blue like that I am not sure I can help you. Do you see error messages displayed in the JavaScript console?

**Comment by SuLy-IG** [comment]
I know its difficult out of the blue. I've been at this for 2 days - its working perfectly locally so there must be something wrong with my setup on the server. 

When I run Safari, no errors are thrown.
In Chrome on the JavaScript Console it says -

 (index):1 XMLHttpRequest cannot load http://irishmemorystudies.com/index.php/industrial-memories/. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://industrialmemories.ucd.ie' is therefore not allowed access.

That's a strange one because its only a page that my website diverts to if there is an error. 

I don't think you'll be able to help much without some more context - but if there is an online resource or manual that might help, I'd be very grateful if you could send it on. 

Thank you!

**Comment by Yomguithereal** [comment]
It seems the issue is that you are loading something using AJAX on a different domain than from which you serve the application. Hence the Cross Origin issue. The server sending the data file should add some cross-origin related headers to its response else AJAX cannot work.

https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

**Comment by SuLy-IG** [comment]
Thank you so so much. I've temporarily removed that diversion and will add those headers later. Now I'm getting a different error (copied below). Looks like to can't find the json file. I'll work through this error and hopefully that will fix it. Thank you!!

`
GET http:// jquery.min.js:4 GET http://industrialmemories.ucd.ie/admin/netmap/data/config.json 404 (Not Found)

`

**Comment by Yomguithereal** [comment]
Well the JSON file cannot be found at the URL you gave jQuery so I cannot help you there :). Maybe the URL is incorrect, maybe your server rules don't serve the data folder, who knows? Only you can fix this since only you can access your server.

**Comment by SuLy-IG** [comment]
Thank you  - the URL is correct and I've tried moving it and have tried changing the folder specified in the main.js file. 
I never thought of server rules being an issue. I'll take a look at that.
Thanks,

**Comment by SuLy-IG** [comment]
I think I resolved the location issue. But now I'm getting something else. 

I'm reluctant to start changing the data since it is working perfectly locally and is exported from gephi. 

Does this error suggest any setup issues to you?

sigma.parseJson.js:8 Uncaught TypeError: Cannot read property 'length' of undefined
    at Object.success (sigma.parseJson.js:8)
    at o (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at w (jquery.min.js:4)
    at XMLHttpRequest.d (jquery.min.js:4)

**Comment by Yomguithereal** [comment]
Are you sure the JSON file you receive is the same? It seems the thing sigma tries to read is different.

**Comment by SuLy-IG** [comment]
Yes it is the same. I've attached it. Its a pretty simple one. I've attached it in a .txt file here.
[config.txt](https://github.com/jacomyal/sigma.js/files/973643/config.txt)

`

`

**Comment by SuLy-IG** [comment]
Success! - it was the data.json file that it was trying to read, but it was looking at the wrong file. Thank you so so much for your help.

**Comment by SuLy-IG** [comment]
Thank you!!
