### ISSUE TITLE
Ability to handle Duplicate Nodes.

### ISSUE THREAD

**Issue by lordeddard** [jacomyal/sigma.js#865]
When the addNode() gets a Node which already exists, It can just ignore the duplicate one and draw the graph. Any fix for this issue?

Thanks!

**Comment by AVermeij** [comment]
In the ``addNode`` function in ``sigma.classes.graph.js``, sigma indeed currently throws an error when a node already exists, which halts further code execution. 

You could for example change the condition in lines 380-381 [here](https://github.com/jacomyal/sigma.js/blob/31cc1ee3baf321d355f5597ba4d7e9fc8e2c6ff2/src/classes/sigma.classes.graph.js) to not throw an error, but simply stop executing ``addNode`` using a ``return`` statement:

``
    if (this.nodesIndex[node.id])
      return;
``

That would make sure your graph is still drawn, while ignoring the duplicate node.

**Comment by lordeddard** [comment]
Yeah! That works! And also I'm a little curious why this is important? I mean why to throw an error for duplicate nodes?
Thanks!

**Comment by Yomguithereal** [comment]
Usually the reason why we throw an error for duplicate nodes is to warn the developer that there might be some kind of error with their data. Else you are supposed to test whether the node exists before adding it but this is not straightforward to do with sigma's current state.

In graphology, for instance, we have distinct methods for distinct behavior for when you want to add a node and throw or add a node or do nothing if it already exists (https://graphology.github.io/mutation.html#addnode).

**Comment by lordeddard** [comment]
Nice! No Idea about that before! Thanks a Lot!
Shall I close the Issue?

**Comment by Yomguithereal** [comment]
Sure, if you feel your question has been answered :). Else don't hesitate to ask more.
