### ISSUE TITLE
sigma is not declared when importing force atlas 2

### ISSUE THREAD

**Issue by Tyrannas** [jacomyal/sigma.js#868]
I'm building a Vue application using sigma.js. 
Everything is working fight, until I try to import force atlas 2, throws a "sigma is not declared" error. 
I looked at the FA2 code, this error is fired if typeof(sigma) == "undefined", but when I do a console.log(typeof(sigma)), it prints "function". 

Any idea on how to fix this? 

thank you.

**Comment by Yomguithereal** [comment]
It means you must load sigma's code before FA2's one. How to you import your code?

**Comment by Tyrannas** [comment]
I was using 
`import sigma from 'sigma
import 'sigma/build/plugins/sigma.layout.forceAtlas2
`
But i just switched back to importing sigma and FA2 into the html and now it works!

**Comment by Yomguithereal** [comment]
Yes, the thing is the forceatlas2 plugin expects to find `sigma` as a global variable. It's old school but this how things were done in ye olde times. Fortunately next version of the library should address this issue.

**Comment by mtholdefer** [comment]
@Yomguithereal I am experiencing this same issue.  I am trying to incorporate sigma.js into a npm/webpack project of mine and I am trying to stay away from imports in the html.  Do you know when the next version of the library will be available?

**Comment by dogcalas** [comment]
Is 2019 and the same problem persist.

**Comment by hiiwave** [comment]
Please try this solution: https://github.com/jacomyal/sigma.js/issues/871#issuecomment-570036779
