### ISSUE TITLE
Curved edges not curved

### ISSUE THREAD

**Issue by Tyrannas** [jacomyal/sigma.js#869]
I'm using Vue.js to build a sigma application, I wanted to display my edges with a curved style instead of a line but it doesnt seem to work. I'm using this to build my edges: 

```
this.sigmaInstance.graph.addEdge({
                                        id : id,
                                        source: newNode.id,
                                        target: node.id,
                                        label: [t],
                                        size: 0.5,
                                        color: "#3997ff",
                                        weight: 1, 
                                        type: 'curve'
                                    });
```

I tried: type: 'curve', and 'curved' but none of them seems to work. I also tried to set the default type of the edges in the sigma settings with curve but with no better result. Changing from 'line' to 'arrow' works though. 

Thank you.

**Comment by Yomguithereal** [comment]
Like that, I'd say that's because by default sigma will use the webgl renderer and curved edges are not supported by the wegbl renderer. Try forcing it to canvas (expect worse performance though) by doing the following (there are cleaner way to do this but this is the fastest to test the issue):

Before instantiating:

```js
sigma.renderers.def = sigma.renderers.canvas;
```

**Comment by Tyrannas** [comment]
I created my renderer with:
 `instance.addRenderer= { container: 'graph-container', type: 'canvas' } `
already.

**Comment by Yomguithereal** [comment]
```js
instance.addRenderer= { container: 'graph-container', type: 'canvas' }
```

This line is pseudo-code? If this is actual code this will fail.

Is your code available somewhere so I can help you better?

**Comment by Tyrannas** [comment]
Yeah sure: https://github.com/Tyrannas/Recif/blob/master/front/src/components/modules/Sigma.vue, line 316

**Comment by Yomguithereal** [comment]
Can you type `sigma.canvas.edges.curve` in your console and tell me if a functions comes out? I remember a bug where the curver renderer would not exist.

**Comment by Tyrannas** [comment]
Nope undefined

**Comment by Yomguithereal** [comment]
Well, well, well. Can you load this file in your page and tell me whether this fixes it? https://github.com/jacomyal/sigma.js/blob/master/src/renderers/canvas/sigma.canvas.edgehovers.curve.js

**Comment by Tyrannas** [comment]
Huum nope, still not.

**Comment by Yomguithereal** [comment]
My bad. Should be this file: https://github.com/jacomyal/sigma.js/blob/master/src/renderers/canvas/sigma.canvas.edges.curve.js

**Comment by Tyrannas** [comment]
Oh yeah, now it's working great! Thanks!

**Comment by Yomguithereal** [comment]
Ok, I think I saw a PR about this particular problem somewhere which is the necessary file is not included in the build for a mysterious reason.

**Comment by gejigeji** [comment]
I also met this problem, and sovled it by add https://github.com/jacomyal/sigma.js/blob/master/src/renderers/canvas/sigma.canvas.edges.curve.js

but I do not think its a good way
