### ISSUE TITLE
Force Atlas not taking in account new Nodes after first run

### ISSUE THREAD

**Issue by Tyrannas** [jacomyal/sigma.js#870]
That's probably a mistake of mine, but just in case i'm posting this problem. 
I have a graph that I build step by step. When I first start force atlas, everything works great. But if i stop FA2, then add a Node with edges to the graph, and then run the FA again, the newly created node doesn't move at all.

**Comment by Yomguithereal** [comment]
Long story short, when you add a node, kill the layout and start it again:

```js
sigInst.killForceAtlas2();
sigInst.startForceAtlas2();
```

I hope this is the correct method names.

**Comment by Tyrannas** [comment]
oh okey, not stop it, kill it, great, it's working thanks!

**Comment by Yomguithereal** [comment]
Yes, once again this is a design problem. The fact is if you don't kill it, the layout won't regenerate the low-level byte arrays it's working on.
