### ISSUE TITLE
How to import plugins as module in Webpack ES6?

### ISSUE THREAD

**Issue by geekplux** [jacomyal/sigma.js#871]
I imported the sigma.js with Webpack and ES6 syntax:

```js
import { sigma as Sigma } from 'sigma';
```

but I can't import plugins like this:

```js
import 'sigma/build/plugins/sigma.parsers.json.require.js';
or
import 'sigma/build/plugins/sigma.parsers.json.min.js';
```

referenced: #799

**Comment by Yomguithereal** [comment]
Plugins need to access `sigma` through the global scope to work (that's old school but the library was developed quite a long time ago).

So you need something like this before loading the plugins:

```js
window.sigma = sigma;
```

**Comment by geekplux** [comment]
I use `resolve` in webpack:

```js
  module: {
    loaders: [{
      test: require.resolve('sigma'),
      loader: 'imports?this=>window'
    }]
  },
  resolve: {
    extensions: ['', '.js'],
    alias: {
      forceLayoutWorker: 'sigma/plugins/sigma.layout.forceAtlas2/worker.js',
      forceLayoutSupervisor: 'sigma/plugins/sigma.layout.forceAtlas2/supervisor.js'
    }
  }
```

and in my src file:

```js
import 'forceLayoutWorker';
import 'forceLayoutSupervisor'
```

but there is an error occur:

```
bundle.js:22717 Uncaught TypeError: _root.postMessage is not a function
    at Supervisor.sendByteArrayToWorker (bundle.js:22717)
    at Supervisor.start (bundle.js:22737)
    at sigma.startForceAtlas2 (bundle.js:22820)
    at Object.__instances (bundle.js:7884)
    at __webpack_require__ (bundle.js:20)
    at Object.<anonymous> (bundle.js:48)
    at __webpack_require__ (bundle.js:20)
    at bundle.js:40
    at bundle.js:43
```

referenced: https://github.com/jacomyal/sigma.js/pull/799#issuecomment-307030389

**Comment by Yomguithereal** [comment]
Both the supervisor & the worker need to be able to access the global scope through this if I remember correctly. Else they cannot send messages.

**Comment by geekplux** [comment]
can try to use webpack shimming(https://webpack.js.org/guides/shimming/):

```js
rules: [{
  test: require.resolve('sigma'),
  use: 'imports-loader?this=>window
}]

plugins: [
  new webpack.ProvidePlugin({
    sigma: 'sigma'
  })
]
```

**Comment by ktmud** [comment]
Just to commend on @geekplux 's solution. It seems `require.resolve('sigma')` must be replaced with a regex (`/sigma.*/`) in order to make the plugins also work.

**Comment by rmorrise** [comment]
I tried the solution provided by @geekplux in my Angular app (with ejected webpack config), but I got an error: 

`Error: Can't resolve 'imports-loader' in '...`

**Comment by YeechingTiger** [comment]
Hi everyone, in my angular5 projects, the code below works:
`const sigma = require('sigma'); (<any>window).sigma = sigma; require('../../../../node_modules/sigma/build/plugins/sigma.renderers.edgeLabels.min.js');`

**Comment by lmenus** [comment]
@rmorrise Did you add `import-loader` to your dependencies?

**Comment by lmenus** [comment]
For everyone struggling with this in 2018, merging solutions above works with `Webpack 4.1.0`.

`(yarn add | npm install --save) sigma`

```js
resolve: {
  modules: [
    'node_modules',
  ],
},
module: {
  rules: [
    {
      test: /sigma.*/,
      use: 'imports-loader?this=>window',
    },
  ],
}
```

And then in your modules (I am skipping `webpack.ProvidePlugin`).

```js
import Sigma from 'sigma';
/*
 * Plugins would be still undefined on sigmaInstance,
 * dive into build output and require them manually.
 */
import('sigma/build/plugins/sigma.layout.forceAtlas2.min');
```

**Comment by Sadin** [comment]
@lmenus so I need to create a webpack config and then add sigma to it?

**Comment by lmenus** [comment]
@Sadin Hi Zachary, in Webpack configuration which is the first snippet, we process all Sigma files with imports loader. You will also need to install Sigma as a dependency in your project (first command in my previous comment) and import it to your project as shown in the second snippet.

You can see it working here in a project's [Webpack file](https://github.com/lmenus/webpack-analyse/blob/master/webpack.config.js#L65L68) and in the [module](https://github.com/lmenus/webpack-analyse/blob/master/src/graphs/chunks.js#L1L5)

**Comment by Sadin** [comment]
@lmenus thank you so much for these examples and clarification!

**Comment by hiiwave** [comment]
@mrlubos Thanks! You save the day.

This solution works for vue too. 

```js
# vue.config.js
module.exports = {
  configureWebpack: {
    resolve: {
      modules: [
        'node_modules',
      ],
    },
    module: {
      rules: [
        {
          test: /sigma.*/,
          use: 'imports-loader?this=>window',
        },
      ],
    }
  }
}
```

```vue
# MyComponent.vue
<script>
import Sigma from 'sigma';
import('sigma/build/plugins/sigma.layout.forceAtlas2.min');

export default {
  mounted: function() {
    let s = new sigma(/*...*/)
    s.startForceAtlas2()
  }
}
</script>
```

This should hopefully solve #987 #981 #868.

**Comment by dunnock** [comment]
I had similar issue when creating [React wrapper](https://github.com/dunnock/react-sigma) and since v1 did not seem to actively maintained I had to apply some more fixes apart of above mentioned config to [forked version](https://github.com/dunnock/sigma.js), like https://github.com/dunnock/sigma.js/commit/64e7148c39b486eb594d034b1ce12fa33243af61,  https://github.com/dunnock/sigma.js/commit/52c9ab3e66c5fa00b7d914b037e348b9315d550b, https://github.com/dunnock/sigma.js/commit/134c780baeab4d2eae82f2ab813844a18142f7fc. In the end I got all plugins working from ES6 imports and published those changes + some bugfixes from hanging PRs and some plugins from other repos as separate [npm package @maxsparrow/sigma](https://www.npmjs.com/package/@maxsparrow/sigma) to be able to use it in react wrapper `react-sigma`, though it might be imported to any other ES6 lib just as easy...

**Comment by bornakke** [comment]
> ```
>     s.startForceAtlas2()
> ```

@hiiwave solution worked for us in Vue as well after installing imports-loader:
`npm install imports-loader`

**Comment by rk-zero** [comment]
for anyone struggling with this in symfony and yarn encore:


webpack.config.js
```
// fetch the config, then modify it!
var config = Encore.getWebpackConfig();

// sigma fixes
config.resolve.modules = ['node_modules'];

config.module.rules.push({
        test: /sigma.*/,
        use: 'imports-loader?this=>window',
    }
);

module.exports = config;
```

app.js
```
import Sigma from 'sigma';
import 'sigma/build/plugins/sigma.parsers.gexf.min.js';
import 'sigma/build/plugins/sigma.layout.forceAtlas2.min.js';
import 'sigma/build/plugins/sigma.plugins.filter.min'
```

**Comment by DominicSina** [comment]
The solution from @hiiwave worked for me. It shows the graph when I navigate to it's route but I can't refresh with F5 though. Somehow `Sigma.parsers` is undefined even though I use `import('sigma/build/plugins/sigma.parsers.json.min');` at the beginning of the script tag. Does refreshing work for anybody or is it just me?

**Comment by LinqLover** [comment]
Hi, I am having the same problem and none of the solutions above worked for me. For context: I am writing a custom visual for Power BI, which uses typescript and webpack as well.

[This solution](https://github.com/jacomyal/sigma.js/issues/871#issuecomment-370980446) brings up a ChunkLoadError (promise rejected) when loading the visual. (It's a very similar problem to [this one from StackOverflow](https://stackoverflow.com/questions/58979629/why-is-webpack-failing-to-load-chunks), in case it should matter. I did not find a solution there either.)  
I also tried to use `import '../node_modules/sigma/build/plugins/sigma.parsers.json.min.js'` or `const sigmaatlas = require('sigma/build/plugins/sigma.layout.forceAtlas2.min')` instead, but both give me the following error whne loading the visual: uncaught sigma is not declared.

I'm also confused that `Sigma` is imported as a function rather than as a module:
```ts
import Sigma from 'sigma';
console.log(Sigma);
```
Yields (in the chrome developer console)
```
ƒ sigma(conf) {
    // Local variables:
    // ****************
    var i, l, a, c, o, id;
```
etc. Is this expected behavior? If not, what could I be doing wrong?

I'm new to typescript and would highly appreciate any help! :-)

**Comment by Pheonix929** [comment]
@LinqLover did you manage to find a solution to this? Im having the same problem.

**Comment by rk-zero** [comment]
I solved the problem by switching to https://github.com/vasturiano/3d-force-graph - i know this is not the solution and the maintainer can ask me to remove this comment, but this plugin has way better integration support without hacks like above.

**Comment by dunnock** [comment]
Why? I starred 3d-force-graph instead. Unfortunately only few people like to join to help maintain opensource repositories

**Comment by LinqLover** [comment]
@Pheonix929 For my case, it was sufficient to use an older version (v0.1) of sigma and hard-copy it into my repository. Ugly, I know, but it works ...

---

If you're interested in using the hard copy, you can grab the files from https://textexture.com/js/sigma.min.js (there is also a `sigma.forceatlas2.js`). These are my type definitions:
```d.ts
// Reverse-engineered from https://github.com/jacomyal/sigma.js/tree/deprecated-v0.1/
export module SigmaV01 {
    interface Sigma {
        drawingProperties: Object;
        mouseProperties: Object;
        _core: any;
        addEdge(id: (string | number), sourceId: string, targetId: string, node: Edge): Sigma;
        addNode(id: (string | number), node: Node): Sigma;
        bind(event: string, callback: (e: any) => void): Sigma;
        draw(): void;
        getNodes(id: string): Node,
        iterEdges(callback: (edge: Edge) => void): Sigma;
        iterNodes(callback: (node: Node) => void): Sigma;
        
        /** Activates the fish eye effect on this sigma instance. */
        activateFishEye(): void;
        
        /** Starts or unpauses the layout. */
        startForceAtlas2(): void;
        /** Pauses the layout. */
        stopForceAtlas2(): void;
    }
    
    interface GraphComponent {
        attributes: [];
        hidden: boolean;
        id: (number | string);
    }
    
    interface Edge extends GraphComponent {
        source: string, target: string;
        weight: number;
    }
    
    interface Node extends GraphComponent {
        color: string;
        forceLabel: boolean;
        hidden: boolean;
        label: string;
        labelSize: number;
        size: number;
        x: number, y: number;
    }
}
```

**Comment by RoshanMali** [comment]
@hiiwave Solution didn't work for me, 
I'm still getting this error: `[Vue warn]: Error in mounted hook: "TypeError: s.startForceAtlas2 is not a function"`

```
<script>
import Sigma from 'sigma'
import('sigma/build/plugins/sigma.layout.forceAtlas2.min');
export default {
  name: 'sigma',
  data() {
    return {
      graph: {
        nodes: [
          {id: "n0", label: "A node", x: 0, y: 0, size: 3, color: '#008cc2'},
          {id: "n1", label: "Another node", x: 3, y: 1, size: 2, color: '#008cc2'},
        ],
        edges: [
          {id: "e0", source: "n0", target: "n1", color: '#282c34', type: 'line', size: 0.5},
        ]
      }
    }
  },
  mounted() {
    let s = new Sigma({
          renderer: {
            container: document.getElementById('sigma-container'),
            type: 'canvas'
          },
          settings: {
            minArrowSize: 10
          }
        }
    )
    s.startForceAtlas2()
  }
}
</script>
```

vue.config.js:
```
module.exports = {
  configureWebpack: {
    resolve: {
      modules: [
        'node_modules',
      ],
    },
    module: {
      rules: [
        {
          test: require.resolve('sigma'),
          use: 'imports-loader?wrapper=window',
        },
      ]
    }
  }
}
```

@hiiwave can you please provide solution link?
Thanks in advance
