### ISSUE TITLE
Can't make ForceAtlas2 work on 1.2.0

### ISSUE THREAD

**Issue by Javarome** [jacomyal/sigma.js#872]
Hi,

After multiple attemps (configuration changes, etc.) I still cannot make forceAtlas2 work on my sample (see [CodePen here](https://codepen.io/Javarome/pen/JJXEVP), just submit multiple inputs to create nodes). 

Basically what I'm doing is:

1. adding nodes (and edges from latest node) with random x and y
2. calling refresh + startForceAtlas2 each time I add a new node.

...but can't see any redraw (i.e. the nodes remain at the random x/y I initially set). However noOverlap seems to do something.

Could you help? The full code is included in the CodePen. Thanks.

**Comment by Yomguithereal** [comment]
You need to kill the layout and restart it when adding nodes else the underlying byte array is not refreshed (this is a design issue).

**Comment by Javarome** [comment]
Thanks for the reply. I'm new to sigma.js and so not sure about "killing the layout" means. To me the layout is forceAtlas2, about which I don't have a reference so far. Maybe you mean the graph (or the sigmajs instance) ? By "killing" do you mean graph.kill() or just graph.clear() as pointed in another issue? Does that mean that I should "save" all the nodes and edges before, then re-add them afterwards?
Thanks by advance for those clarifications!

**Comment by Yomguithereal** [comment]
I guess you start the layout using `sigInst.startForceAtlas2()`, so killing the layout would simply be `sigInst.killForceAtlas2()`.

**Comment by Javarome** [comment]
Okay, this works now, thanks a lot!
By the way, some node are giggling more on less, depending on the total number of nodes are present (odd total number seems to be a factor), but I assume this is another issue?

**Comment by Yomguithereal** [comment]
This layout is not really fitted for small networks and some of its optimizations can make specific structures giggle (stars notably). I don't remember the `autoStop` option. The layout is not deterministic and most of the heuristics we tried to stop it automatically tend to fail on some network typologies. Usually people use a timeout or let the user stop the layout.

**Comment by Yomguithereal** [comment]
I would advise you to scale the timeout time on the size of your network. But if 100ms works for you I guess you are working with relatively small graphs, no?

**Comment by Javarome** [comment]
Good advice indeed. Yes I was testing with less than 10 nodes only.
