### ISSUE TITLE
No Support for Alpha/Opacity in Webgl?

### ISSUE THREAD

**Issue by iankloo** [jacomyal/sigma.js#878]
I may be missing something, but I've spent a day looking for this with no success:

Is there a way to control edge opacity when using webgl?  I have some networks that are way too big for canvas, and I can't get anything to work for opacity.  I've tried:

1. Using rgba() in the data
2. Using rgba() to set the default edge color in the renderer settings

Is this just one of those things that will not be supported?  

Thanks!

-Ian

**Comment by Yomguithereal** [comment]
Hello @iankloo. For a reason I don't clearly remember I think we do not support alpha with the WebGL renderer. What are you trying to achieve UX-wise? Maybe we can find some workaround.

**Comment by iankloo** [comment]
Got it - thanks for the response.  I'm working with large (~90,000 edges and ~6,000 nodes) graphs and would benefit from being able to show fairly transparent links.  There's no doubt that graphs of this size typically just look like a hairball, but being able to see central nodes can give a good general idea of the network.  Without an alpha channel, it is hard to make sense of the nodes given all of the edges.  

I've had some success setting very small edges size attributes, so I'll probably just move ahead with that.

Thanks!

**Comment by nkint** [comment]
Is this related?
https://github.com/jacomyal/sigma.js/pull/573/files
