### ISSUE TITLE
How can I fix the node when I use  the sigma.plugins.dragNodes plugin

### ISSUE THREAD

**Issue by web1992** [jacomyal/sigma.js#885]
I use the [sigma.plugins.dragNodes](https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.plugins.dragNodes) . But I want some node is fixed ,and the node can't  drag, Please help me ,thanks!

**Comment by web1992** [comment]
@AVermeij

**Comment by AVermeij** [comment]
For the node which you do not want users to be able to drag, you can set a property ``fixed`` to ``true``. In ``sigma.plugins.dragNodes.js`` (line 156), you can then change the condition from

``if (_node && size > 1) {``

to 

``if (_node && !_node.fixed && size > 1) {``

to make sure that nodes which have their ``fixed`` property set to true can never be dragged.

**Comment by web1992** [comment]
@AVermeij  it works thanks.
