### ISSUE TITLE
Install Sigma.js on github pages and minimal mistakes

### ISSUE THREAD

**Issue by jaruizso** [jacomyal/sigma.js#888]
Hi there,

I am tryng to use sigma.js to use it on my website, but cant make it work. In theory it support js and its in html, so the basic stuff is there.

The process I followed is the next:
- I donwloaded the sigma.js folder and pasted on the general / of my repository: https://github.com/jaruizso/jaruizso.github.io
- I installed node.js and gjslint on my mac computer
- I run npm install in my terminal, and inside the sigma.js folder
- I run then npm run build inside as well sigma.js folder, and /build/sigma.min.js is created.

So far so good. So then I just try to run an example on the jaruizso.eu/teaching website with the following code. Notice that the route for sigma.min.js is the correct one:

![captura de pantalla 2017-07-28 a les 13 05 19](https://user-images.githubusercontent.com/12252768/28714821-79ff961c-7395-11e7-9384-5c0f572ff5de.png)

Am I missing something?

**Comment by AVermeij** [comment]
All looks good based on your code I guess, as long as the path to ``sigma.min.js`` is the correct relative reference. Is the global ``sigma`` object available in your console when loading up the page? Can you share a link to the ``basic.html`` example on your site?

**Comment by jaruizso** [comment]
Yep, the path seems correct, and sigma seems to load if npm start:

![captura de pantalla 2017-07-28 a les 13 31 36](https://user-images.githubusercontent.com/12252768/28715650-4c06df50-7399-11e7-993a-c3257b2081ae.png)

What you mean by basic.html? In theory all the files are in the repository https://github.com/jaruizso/jaruizso.github.io

**Comment by jaruizso** [comment]
Hi there. Sorry for the delay. I have tried to fix the issue. While what you said it is correct (if I take comments out it works). However if I try with another example does not work. For instance, I am trying to make work the examples provided on the sigma.js web as a starting point. In this case with Les Miserables gexf example.

![captura de pantalla 2017-08-01 a les 12 41 01](https://user-images.githubusercontent.com/12252768/28821735-e4f3625e-76b6-11e7-9113-938798182f8e.png)


Notice that the patch to the GEXF parser in the [examples](http://sigmajs.org) is:
`<script src="path/to/sigma.parsers.min.gexf.js"></script>`

While after installing sigma in my computer, it is:
`<script src="/sigma.js/build/plugins/sigma.parsers.gexf/sigma.parsers.gexf.min.js"></script>`

It a little difference with the name of the js, but that should not be a problem.

I attach the file in case you wanna have a look.
[codesigma.txt](https://github.com/jacomyal/sigma.js/files/1190291/codesigma.txt)

**Comment by AVermeij** [comment]
The paths to the scripts on your website are incorrect:

![image](https://user-images.githubusercontent.com/1857934/28822236-c5ef7f08-76b8-11e7-8b8f-c6a15313c2d7.png)

Should be ``<script src="sigma.js/build/sigma.min.js"></script>`` and ``<script src="sigma.js/build/plugins/sigma.parsers.gexf.min.js"></script>``

**Comment by jaruizso** [comment]
OPs! noob mistake. I fixed the path, but still nothing. Maybe a problem with identation?

![captura de pantalla 2017-08-01 a les 13 13 22](https://user-images.githubusercontent.com/12252768/28822883-57371ff0-76bb-11e7-9e7f-26b4ac432d4b.png)

**Comment by AVermeij** [comment]
Try to check your console every now and then for errors:

![image](https://user-images.githubusercontent.com/1857934/28824115-f0833e64-76c0-11e7-95af-9a43e1102b92.png)

This means the supplied GEXF file can't be found or has errors. Upon checking your file over at ``https://github.com/jaruizso/jaruizso.github.io/blob/master/sigma.js/plugins/sigma.parsers.gexf/les-miserables.gexf``, you'll see that this is actually not a GEXF but a copy of some HTML document. If you upload the correct file there, you should be good to go.

**Comment by jaruizso** [comment]
It works now. I still dont understand very well why works now, but it does. I think the problem was in container. I had different containers (container, sigma-container).

Thanks for your help!

**Comment by AVermeij** [comment]
Good! If you feel the issue has been resolved, please close it :-)
