### ISSUE TITLE
ForceAtlas moving nodes out of the canvas

### ISSUE THREAD

**Issue by Raibaz** [jacomyal/sigma.js#9]
When running forceAtlas with the "les miserables" gexf file from the examples, some nodes often get positioned outside of the canvas. 

Is there a way to instruct forceAtlas not to move nodes outside of the canvas, i.e. to limit the xy positions of the nodes?

**Comment by ZhaofengWu** [comment]
While this fix does take the node size into account, it doesn't consider the label. So sometimes labels around the border are only partially displayed.
