### ISSUE TITLE
[Feature Request] Add HTML support to node label

### ISSUE THREAD

**Issue by dcworldwide** [jacomyal/sigma.js#900]
When a node has multiple properties, a simple text label is insufficient. I'd like to be able to define a node label as HTML and have a full popup on hover.

**Comment by AVermeij** [comment]
This can be achieved pretty easily by using the `overNode` event and use the node's x and y coordinates to render a div at that location. For example:

``
s.bind('overNode', function(e) {
  var prefix = s.renderers[0].options.prefix;
  var node = e.data.node;
  var x = e.data.node[prefix + 'x'];
  var y = e.data.node[prefix + 'y'];
  
  // Now render some div based on these coordinates
});

Also see https://github.com/jacomyal/sigma.js/issues/752

**Comment by dcworldwide** [comment]
Brillaint, thankyou for you great work :+1: :taco:
