### ISSUE TITLE
Sigma Graph Issue With Angular-Material

### ISSUE THREAD

**Issue by walkercole** [jacomyal/sigma.js#901]
Hi,
I am having an issue with my Sigma Graph when I incorporate the Angular-Material framework,
when I use `<md-service>` all of my graph nodes concat into the same x-y position and don't expand into their random assigned positions until I manipulate the graph with either a click/zoom/drag function.
I was curious if anyone has faced a similar issue and if anyone had any tips or guidance.

**Comment by Yomguithereal** [comment]
This might be related to the size of your container computed dynamically. Sigma might have some trouble finding the correct width/height because of multiple measuring renders.

**Comment by walkercole** [comment]
@Yomguithereal You are exactly correct, sorry for getting back so late but yes, after noticing Angular-Material's flex was interfering with the canvas element that Sigma is based on I found a work around and everything is back to normal.

So if anyone else runs into the issue and are as clueless as I was, it has to do with Materials use of Flex and sigma's use of Canvas to render the graph.

**Comment by Yomguithereal** [comment]
Know also that sigma's renderer have a `.resize` method to which you can provide `width` & `height` if you need to.
