### ISSUE TITLE
Prevent default zoom on double click of node

### ISSUE THREAD

**Issue by sumeetpri** [jacomyal/sigma.js#910]
On double click of node , its doing default action and zooming canvas . Is it possible to stop default action because I have custom action  to do on double click .

```
s.bind('doubleClickNode', function(e) {				
	//e.preventDefault();  //  This does not work

      // Some custom action
});
```

**Comment by Optika17** [comment]
You can set sigma's ``doubleClickEnabled`` setting to ``false``, which will disable the standard zoom behaviour, while at the same time still allowing you to make use of the ``doubleClickNode`` event:

``s.settings('doubleClickEnabled', false);``

**Comment by AVermeij** [comment]
You can set sigma's ``doubleClickEnabled`` setting to false, which will disable the standard zoom behaviour, while at the same time still allowing you to make use of the ``doubleClickNode`` event:

``s.settings('doubleClickEnabled', false);``

**Comment by sumeetpri** [comment]
I want double click on canvas to zoom but not in node , will this will solve my problem ? @AVermeij

**Comment by AVermeij** [comment]
In that case, you'd be best off setting ``doubleClickEnabled`` to ``false`` each time a user enters a node, then to set it back again to its regular behavior when a user exits a node. You can do this using the ``overNode`` and ``outNode`` events:

```
s.bind('overNode', function(e) {
  s.settings('doubleClickEnabled', false);
});

s.bind('outNode', function(e) {
  s.settings('doubleClickEnabled', true);
});
```

**Comment by sumeetpri** [comment]
Brilliant it worked like charm !! Thanks @AVermeij

**Comment by deemeetree** [comment]
Just a little note that if your instance is already activated you will need to use 

`sigma.instances(0).settings({doubleClickEnabled: false});`

**Comment by vricosti** [comment]
It seems this answer does not work anymore ...

**Comment by sim51** [comment]
This answer is for sigma v1, not for the current version.

You can prevent the default behavior of the double click like that : 

```
sigma.on("doubleClick", (event) => event.preventSigmaDefault());
```

**Comment by agajdosi** [comment]
Any tips how to achieve this on v3? `sigma.on("doubleClick", (event) => event.preventSigmaDefault());` does not work for me 😿

**Comment by Picorims** [comment]
> Any tips how to achieve this on v3? `sigma.on("doubleClick", (event) => event.preventSigmaDefault());` does not work for me 😿

It worked for me through destructuring:
```js
function doubleClickNode({ node, event }) {
                event.preventSigmaDefault();
                //...
}
```
