### ISSUE TITLE
Running Forced layout on selected area only 

### ISSUE THREAD

**Issue by sumeetpri** [jacomyal/sigma.js#913]
On click of node I am trying to add dependent child and then running forced layout on entire graph .
Running forced layout happens in entire canvas , is it possible to apply forced layout to specified nodes and  area only . 

My question might sound novice , but is it possible ?

**Comment by Yomguithereal** [comment]
It could be possible but would need a lot of rewrite of the layout algorihtm code. The issue here is also conceptual since adding a node can potentially affect every other nodes' position and every other nodes' position can also alter your single node's one.

**Comment by sumeetpri** [comment]
On double click I am adding new nodes and then running forced layout , it
created distortion in entire graph . What could be best way to have smooth
transition . In d3 expand collapse example it looks smooth when parent node
expands it's child . Small hint will save my hours .

**Comment by Yomguithereal** [comment]
Position the new node at the barycenter of its neighbors and use a large `slowDown` on the layout setting. This should smooth things up.

**Comment by sumeetpri** [comment]
To barycenter i used sin and cos . Below is my code can you suggest how to make smooth transition .of opening 


```

	s.bind('doubleClickNode', function (e) {
	
	
		// Add Five new Node
		var radian = 360/10;
	    var theta = 0;
	    
		for (var i = Nx; i <= Nx+5; i++){
		  s.graph.addNode({
		    id: 'n' + i,
		    label: 'Node ' + i,
		    x: e.data.node.x+0.001*Math.cos(theta),
		    y: e.data.node.y+0.001*Math.sin(theta),
		    size: 10,
		    color: '#666'
		  });
		  theta +=radian;
		  }
		Nx = Nx+6;
		for (var i = Ey; i < Ey+5; i++)
		  s.graph.addEdge({
		    id: 'e' + i,
		    source: 'n' + i,
		    target: e.data.node.id,
		    size: 2,
		    color: '#ccc',
		    type:"curvedArrow"
		  });
		 Ey = Ey+6;
		 s.refresh();
		 s.startForceAtlas2({worker: true, barnesHutOptimize: true, scalingRatio:0.002 ,strongGravityMode : true,gravity : 0.1});
		
		setTimeout(function(){
			s.stopForceAtlas2();
			s.killForceAtlas2();
		},1000);		
});
```

**Comment by sumeetpri** [comment]
Is doing e.data.node.x + 0.001×Math.cos( theta ) is correct ?How to decide value of radius when scaled

**Comment by sumeetpri** [comment]
@Yomguithereal  Can you tell me how to decide r value at particular zoom /scale to place nodes in circular way  .  

`x: e.data.node.x+r*Math.cos(theta) 
`

This will help me to have similar edge distance in zoomed scale also
