### ISSUE TITLE
not being able to call angular2 component function on sigma.js bind event call

### ISSUE THREAD

**Issue by jasjeetkaur2211** [jacomyal/sigma.js#918]
I have a simple function in my angular2 component as follows:

    onSelectNode(label: String) {
    console.log(label)
    // do something based on label
      }

and have created a basic sigma.js graph in angular2 as follows:

    var s = new sigma({
      graph: sigmaJson,
      container: 'network-graph',
      settings: {
        defaultNodeColor: '#ec5148'
      }
    });
My graph is getting rendered successfully. Now I want to call the function onSelectNode when one of the node is clicked. So, I have used the `bind` functionality as follows:

    s.bind('clickNode', nodeClick)

The function nodeClick is defined as follows:

    nodeClick(event) {
    this.selectedLabel = event.data.node.label
    console.log(this.selectedLabel)   // this prints correctly
    this.onSelectNode(this.selectedLabel)  // getting error here}

But I am not able to call the component function from within the `nodeClick` function. I am getting the following error in javascript console:

    ERROR TypeError: this.onSelectNode is not a function
    
Can somebody please help me figure out what I am doing wrong here?

**Comment by Yomguithereal** [comment]
Hello @jasjeetkaur2211. Your problem is with JS `this` behavior. The `nodeClick` callback is called in its own scope, which is not the one of your angular component.

There is several ways to fix this:

1) Make `nodeClick` an arrow function.
2) Make a reference to the correct scope outside the `nodeClick` callback and use it `var self = this;` for instance.
3) Bind the component methods

**Comment by jasjeetkaur2211** [comment]
@Yomguithereal Thank you so much. I used the second option and it worked.
BTW, can you elaborate how to use the 1st and 3rd option?

**Comment by Yomguithereal** [comment]
* An arrow function compulsorily has the same scope as the calling scope:

```
function Animal(name) {
  this.name = name;

  ['one', 'two'].forEach(function(number) {
    console.log(number + ' ' + this.name);
  });
}

new Animal('kitty');
// Will log 'one undefined', 'two undefined' because scope of function is different

function Animal(name) {
  this.name = name;

  ['one', 'two'].forEach(number => {
    console.log(number + ' ' + this.name);
  });
}

new Animal('kitty');
// Will log 'one kitty', 'two kitty' because scope is the same thanks to arrow function
```

**Comment by Yomguithereal** [comment]
Concerning binding
```js
function Animal(name) {
  this.name = name;
  
  function callback(number {
    console.log(number + ' ' + this.name);
  }

  // Will bind the function to a precise context
  callback = callback.bind(this);

  ['one', 'two'].forEach(function(number) {
    console.log(number + ' ' + this.name);
  });
}
```

**Comment by Yomguithereal** [comment]
Basically, you have to understand that `this`, in JS, is an implicit argument given to every function, representing the scope (where it is called). When you use forEach, for instance, the callback given will be executed in another scope (not the local when where you gave the callback to forEach). So it might be a bit confusing. This is what arrow function was designed to "solve", in fact.

**Comment by jasjeetkaur2211** [comment]
@Yomguithereal Thanks alot for the short lesson. :+1:

**Comment by Sadin** [comment]
@jasjeetkaur2211 how did you get sigma properly working in angular 2? im having issues importing it into my components
