### ISSUE TITLE
CustomShape plugin not getting recogonised

### ISSUE THREAD

**Issue by jasjeetkaur2211** [jacomyal/sigma.js#920]
Hello, I want to create a graph with square shaped nodes. But I am having problem while calling `CustomShape.init(s)` function. Please find the code below:

In my angular component class, I have imported sigma and created a simple graph Json Object as follows:

```
`import {sigma} from "sigma"
  sigmaJson = {
    "nodes": [
      {
        "id": "n0",
        "label": "a node",
        "x": -265,
        "y": 30,
        "size": 8,
        "type": "square"
      },
      {
        "id": "n1",
        "label": "Another node",
        "x": -15,
        "y": 30,
        "size": 8,
        "type": "square"
      },
      {
        "id": "n2",
        "label": "And a last one",
        "x": -265,
        "y": 100,
        "size": 8,
        "type": "square"
      }
    ],
    "edges": [
      {
        "id": "e0",
        "source": "n0",
        "target": "n1",
        "type": "dotted"
      },
      {
        "id": "e1",
        "source": "n1",
        "target": "n2",
        "type": "dotted"
      },
      {
        "id": "e2",
        "source": "n2",
        "target": "n0",
        "type": "dotted"
      }
    ]
  };
`

```
Then I have rendered the graph as follows:
`drawGraph() {

    this.s = new sigma({
      graph: this.sigmaJson,
      renderer: {
        container: document.getElementById('network-graph'),
        type: 'canvas'
      },settings: {
        defaultNodeColor: '#ec5148',
        }
    });
    **CustomShapes.init(this.s);**
    this.s.refresh();
  }`

The graph is getting rendered, but I am getting an error in the  **CustomShapes.init(this.s);** The function is not getting recogonised. I have included all the JS files as indicated [here](https://github.com/jacomyal/sigma.js/blob/master/examples/plugin-customShapes.html) and verified that they are loading in the browser as well.  
Also, I am getting only default edge shapes, not the required "dotted" shape.
Can somebody point out my mistake here?

**Comment by Drake62610** [comment]
Hello, sorry to revive this old issue.

Did you find how to do It, I'm having the same issue two years later.

**Comment by Yomguithereal** [comment]
You need to import the customShapes plugins. To this extent, the sigma variable must be globally available.

**Comment by Drake62610** [comment]
> customShapes

This is what I tried to do by adding 
`import { CustomShapes, sigma } from 'sigma'` on the top of my file.
Is it how I'm supposed to import the plugin or am I missing something ?

With this method I'm having issue with an undefined value.

**Comment by Yomguithereal** [comment]
```js
import 'sigma';
import 'sigma/plugins/sigma.renderers.customShapes/sigma.renderers.customShapes
```

or something like this. This version of the lib was created way before package manager for JS became a thing unfortunately.

**Comment by Drake62610** [comment]
I think I'm almost there, I'm missing something.
```
ERROR Error: Uncaught (in promise): ShapeLibrary is not declared
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at 
```

Here is what I tried so far : 
```
import { sigma } from 'sigma';
import { ShapeLibrary } from 'sigma/plugins/sigma.renderers.customShapes/shape-library';
import 'sigma/plugins/sigma.renderers.customShapes/sigma.renderers.customShapes';
```

**Comment by Yomguithereal** [comment]
I think you need for ShapeLibrary to be in the global scope. Try something like:

```js
window.ShapeLibrary = ShapeLibrary;
```

before importing the plugin.

**Comment by Drake62610** [comment]
I've added 
```
"scripts": [
              "node_modules/sigma/build/sigma.min.js",
              "node_modules/sigma/plugins/sigma.renderers.customShapes/shape-library.js",
              "node_modules/sigma/plugins/sigma.renderers.customShapes/sigma.renderers.customShapes.js"
            ],
```
In my angular.json, now everything is compiling but I still have no Shape despite adding the type, for exemple : 

`{ id: 'n1', label: 'Helo i'm a square', x: 4, y: 8, size: 3, color: '#74d8c0', type: 'square' },`

No error is showing on the console.

**Comment by tommy-private** [comment]
https://github.com/jacomyal/sigma.js/issues/871
