### ISSUE TITLE
Is it possible to detect if the change of nodes?

### ISSUE THREAD

**Issue by emanodame** [jacomyal/sigma.js#934]
Is there a convenient way to check if there is a change of nodes? For example, node addition and deletion etc.

**Comment by AVermeij** [comment]
You could use the ``attach`` method to call an extra function after any call to ``addNode``, ``dropNode``, ``addEdge`` or ``dropEdge``. 

See https://github.com/jacomyal/sigma.js/blob/31cc1ee3baf321d355f5597ba4d7e9fc8e2c6ff2/src/classes/sigma.classes.graph.js#L209 for an explanation and example of how to use this.

**Comment by emanodame** [comment]
If i use the 'dropNode' version. Will 'sigma.grah.clear()' be detected too?

**Comment by AVermeij** [comment]
See here for how ``clear`` behaves:

https://github.com/jacomyal/sigma.js/blob/master/src/classes/sigma.classes.graph.js#L657

``dropNode`` is not called there, so a call to ``clear`` would not be detected. You could however simply use the ``attach`` method to call whatever you like after calling ``clear`` - it's a graph method as well after all :-)

**Comment by emanodame** [comment]
I'm quiet confused on how to execute this attach method.

    const s = new sigma({
        renderer: {
            container: document.getElementById('base'),
            type: 'canvas',
        },
        settings: {
            borderSize: 3,
        }
    });

Will it simply be: 

s.graph.attach('addNode', 'timesAddNodeCalledInc', function()timesAddNodeCalled++});

**Comment by AVermeij** [comment]
``attach`` is not available directly from the sigma instance, so you should call it using the global ``sigma`` object, for example:

``sigma.classes.graph.attach('addNode', 'addNodeLog', function() {console.log('added a node')})``

**Comment by emanodame** [comment]
Ahh got it. Thanks
