### ISSUE TITLE
automatic placement of nodes, with neat output

### ISSUE THREAD

**Issue by codenoid** [jacomyal/sigma.js#937]
I'm lazy to think

idea : 

`group_position: "admin_list"`

and y will be -5 (or custom) with x 0,1,2,3,4,5,6,7,8,9,10 (0..10 is admin_list)

cc @jacomyal @Yomguithereal @sheymann @sim51 @qinfchen @josemazo

**Comment by Yomguithereal** [comment]
Hello @codenoid. This can very easily be done on the user's end so I am not sure we would add this as a core feature.

**Comment by codenoid** [comment]
yeah, but this feature is very helpfully, just put `group:"some_buyer_of_product"` , and nodes neatly arranged automatically

**Comment by codenoid** [comment]
and in the backend, we just dealing with id, source and edge

**Comment by codenoid** [comment]
sorry, i move to VisJS
