### ISSUE TITLE
Sigma v2?

### ISSUE THREAD

**Issue by Sadin** [jacomyal/sigma.js#956]
Noticed the tags you're working on a v2 whats the roadmap for this?

**Comment by Yomguithereal** [comment]
We don't have a release date yet. However, if you feel adventurous, you can check the examples of the v2 branch and test it because it's already quite usable. It radically different from the current version though.

**Comment by Sadin** [comment]
@Yomguithereal I will for sure check it out, I would like to see how well it plays with frameworks like Vue and Angular 2+

**Comment by Yomguithereal** [comment]
It plays better, notably because it uses viable modules now and not the old web way of things. However, we cannot support the same one-way dataflow because of performance reasons but you can play around that the same way you interact with the DOM actually.

**Comment by Sadin** [comment]
Fantastic, that was what I was hoping for!
