### ISSUE TITLE
graph uses maxEdgeSize instead of specified edge size

### ISSUE THREAD

**Issue by s0md3v** [jacomyal/sigma.js#963]
Hi there,
I am a beginner in JavaScript & I am liking sigma.js so far.

**Goal**
Increasing the thickness of Edges.

**Problem**
I am using `size` attribute to set the size but the edge that are rendered in graph are using the size specified in `maxEdgeSize` somehow.
```javascript
trans = [["a", "b"], ["c", "d"]]
while(point = trans[num++])
  g.edges.push({
    id: 'e' + num,
    source: 'id=' + point[0],
    target: 'id=' + point[1],
    color: '#e74c3c',
    size: 1.2
  });
// sigma.renderers.def = sigma.renderers.canvas
// Instantiate sigma:
s = new sigma({
  graph: g,
  container: 'graph-container'
});

s.settings({
  scalingMode: 'outside',
  minEdgeSize: 0.5,
  maxEdgeSize: 10,
});

s.refresh();
```
**Screenshot**
![ss](https://preview.ibb.co/hYWCxJ/Screenshot_2018_07_03_15_47_55.png)
Any help will be appreciated.
Thanks in advance ^_^

**Comment by Yomguithereal** [comment]
min and max edge size will ensure the displayed size does not overcome it. Your edge's sizes are rescales to fit the min-max range.

**Comment by s0md3v** [comment]
How can I override this behavior?
I want the edges to be as thick as the `size` attribute's value.

**Comment by Yomguithereal** [comment]
Try to set the `autoRescale` setting to `['nodePosition', 'nodeSize']` so you can avoid rescaling the edge's sizes.

**Comment by s0md3v** [comment]
Thanks a lot, it worked.
