### ISSUE TITLE
How to implement sigma js in vue js application

### ISSUE THREAD

**Issue by Bilguunkhan** [jacomyal/sigma.js#981]
Hello,

Please excuse me for posting a request on issues thread. But I'm out of ideas and sincerely asking for your help.
I have been trying to implement sigma js in my vue js application, however I haven't been able to find any helpful resource on how to do it. Previously, I have been using vue js' component called vue-d3-network and tried to implement sigma js in a similar way, but after many tries Im still unsuccessful. Do you know any resources about sigma js + vue js integration?

**Comment by TAUFEEQ1** [comment]
import sigma from 'sigma'
Vue.prototype.$sigma = sigma

Add the lines above in your app.js file
when refering to sigma in your .vue files use:
this.$sigma()

**Comment by mjeffin** [comment]
@TAUFEEQ1 , thanks so much for the reply. I am able to get the graphs working. But not able to use any plugins. Getting the below error,
vue-router.esm.js?fe87:1905 Error: Failed to resolve async component default: ShapeLibrary is not declared

while trying to use the customShapes plugin. 
Thanks in advance for the help.

**Comment by wustdong** [comment]
@TAUFEEQ1 have you solved it ? any suggestions? Thanks.
same problem while import plugins in angular5:
```
sigma.renderers.customShapes.js:8 Uncaught ShapeLibrary is not declared
```

**Comment by wustdong** [comment]
> @mjeffin 
Have  you solved it? Or any suggestions? Thanks.
Encounter the same problem in angular5.
```
sigma.renderers.customShapes.js:8 Uncaught ShapeLibrary is not declared
```

**Comment by wustdong** [comment]
@mjeffin  
Have you solved it? Or any suggestions? Thanks.
Encounter the same problem in angular5.
```
sigma.renderers.customShapes.js:8 Uncaught ShapeLibrary is not declared
```

**Comment by TAUFEEQ1** [comment]
Not yet..

**Comment by hiiwave** [comment]
Please try this solution: https://github.com/jacomyal/sigma.js/issues/871#issuecomment-570036779
