### ISSUE TITLE
Use absolute node width/height

### ISSUE THREAD

**Issue by dennisschumann** [jacomyal/sigma.js#988]
Hello,

is there a way to force sigmajs to use a given node width/height for rendering instead of relative size? I'm using SigmaJs only for rendering - layout is done by another component, but this component needs node width/height for spacing and edge routing.

Best regards!

**Comment by englishisnotenglish** [comment]
Hi, the rescale middleware ajust the size. you can use settings to set autoRescale  false. 
Also you can get real pixels by node attribute renderer1:size.
